#!/usr/bin/perl -w

system("echo \"&control n = $ARGV[3], 
                events_in='$ARGV[0]',
                params_out='$ARGV[2]'
              /\" \| iis");

open IN, "$ARGV[2]";
open OUT, ">$ARGV[1]";

while (<IN>) {
  chomp;
  s/^\s*//;
  my ($f,$w) = split /\s+/;
  print OUT "weight($f,$w).\n"  if (defined $w);
}

unlink("$ARGV[0]");
unlink("$ARGV[2]");


close(IN);
close(OUT);
