sentence(1,train,[the,fountains,chased,the,telescope,with,the,cats,in,the,cat]).
sentence(2,train,[a,cat,with,a,cat,saw,a,man]).
sentence(3,train,[a,cat,puts,the,woman,with,a,dog,on,the,telescopes]).
sentence(4,train,[the,cats,chased,a,cat,on,a,book,in,the,cats]).
sentence(5,train,[a,fountain,put,a,fountain,on,the,woman,in,a,man]).
sentence(6,train,[the,telescopes,with,a,telescope,saw,a,man,with,a,person,in,a,woman]).
sentence(7,train,[the,person,barked,on,a,person]).
sentence(8,train,[the,telescope,on,the,parks,puts,a,cat,with,a,park,in,the,parks]).
sentence(9,train,[the,books,chased,a,park,with,a,fountain,in,a,person]).
sentence(10,train,[the,book,on,the,cat,saw,the,dog]).
sentence(11,train,[the,cats,in,a,fountain,chase,the,dogs,on,the,park,in,the,telescope]).
sentence(12,train,[a,park,barks,on,the,telescopes,in,the,dog]).
sentence(13,train,[the,telescope,barks,on,a,woman,in,the,fountains]).
sentence(14,train,[a,person,barked]).
sentence(15,train,[the,fountain,in,a,person,barked,on,a,man,in,a,man]).
sentence(16,train,[the,cats,saw,a,telescope]).
sentence(17,train,[the,books,saw,the,books,on,the,women,on,a,book]).
sentence(18,train,[a,woman,with,a,person,barks]).
sentence(19,train,[a,fountain,put,a,park,in,a,man,on,a,dog]).
sentence(20,train,[the,parks,bark]).
sentence(21,train,[a,dog,barks]).
sentence(22,train,[the,telescope,barks,on,a,book,in,a,woman]).
sentence(23,train,[the,parks,put,a,cat,on,the,dog,in,the,telescope]).
sentence(24,train,[the,telescope,puts,the,cat,with,a,cat]).
sentence(25,train,[the,woman,sees,a,woman,on,the,dog,in,a,park]).
sentence(26,train,[the,people,put,the,book,in,the,men,on,a,telescope]).
sentence(27,train,[the,fountains,see,the,cats,with,the,books,with,the,person]).
sentence(28,train,[a,man,with,a,telescope,puts,a,man,with,a,person,on,the,book]).
sentence(29,train,[a,cat,sees,a,dog,with,a,book,on,a,telescope]).
sentence(30,train,[the,women,see,a,cat,in,a,park]).
sentence(31,train,[the,park,on,the,cats,barks,on,a,fountain]).
sentence(32,train,[a,person,puts,the,telescopes,on,the,book,in,the,telescopes]).
sentence(33,train,[a,book,puts,the,books,on,the,fountain,with,the,book]).
sentence(34,train,[the,dog,barks,on,a,dog,in,the,books]).
sentence(35,train,[the,parks,put,the,person,with,the,park,in,the,dogs]).
sentence(36,train,[a,book,barked,in,the,fountains]).
sentence(37,train,[the,books,on,the,person,chased,the,park,on,the,fountain]).
sentence(38,train,[the,cats,on,a,woman,barked,on,a,person,with,the,fountains]).
sentence(39,train,[the,men,put,the,telescope,in,a,woman]).
sentence(40,train,[the,books,with,a,fountain,see,the,fountain,on,the,cat,in,a,dog]).
sentence(41,train,[a,book,chases,a,telescope]).
sentence(42,train,[the,people,bark,in,the,telescopes]).
sentence(43,train,[the,person,put,the,man,on,the,women]).
sentence(44,train,[a,woman,barks,with,the,people,with,the,dog]).
sentence(45,train,[the,woman,with,a,cat,saw,the,park]).
sentence(46,train,[the,book,chases,a,fountain,in,the,telescope,in,the,people]).
sentence(47,train,[a,person,put,the,telescope,on,the,person,in,a,park]).
sentence(48,train,[a,telescope,with,the,cats,barks,with,a,person,with,the,park]).
sentence(49,train,[a,book,saw,the,men,on,the,cats,in,a,person]).
sentence(50,train,[the,park,put,the,fountain,in,a,telescope,with,a,cat]).
sentence(51,train,[a,cat,barked,in,a,telescope,with,the,person]).
sentence(52,train,[a,fountain,chases,a,woman,in,a,cat,on,the,women]).
sentence(53,train,[a,telescope,sees,the,telescope,with,the,cats,with,a,man]).
sentence(54,train,[a,telescope,on,the,park,barked]).
sentence(55,train,[a,cat,saw,the,book,in,the,women,with,the,person]).
sentence(56,train,[the,fountain,on,the,person,puts,a,man,on,a,person,in,a,dog]).
sentence(57,train,[a,park,with,the,telescopes,barks,on,a,woman,with,the,park]).
sentence(58,train,[the,cats,see,a,cat,with,the,people]).
sentence(59,train,[the,books,bark,on,the,telescopes,in,a,telescope]).
sentence(60,train,[a,person,saw,a,telescope]).
sentence(61,train,[a,park,barks,in,the,men,in,the,people]).
sentence(62,train,[the,dogs,in,the,women,barked,in,the,people]).
sentence(63,train,[the,person,barked,with,the,dog]).
sentence(64,train,[a,fountain,on,a,woman,barks,on,the,fountains,with,the,people]).
sentence(65,train,[a,cat,chases,the,person,with,the,person,in,a,person]).
sentence(66,train,[a,dog,chases,the,dog,with,the,women,with,a,book]).
sentence(67,train,[a,dog,with,the,men,barked]).
sentence(68,train,[a,fountain,barked,on,the,people,on,the,men]).
sentence(69,train,[a,cat,on,the,dogs,sees,the,people,in,a,telescope,with,the,cats]).
sentence(70,train,[the,cat,put,the,fountains,on,a,book]).
sentence(71,train,[a,man,in,a,dog,chased,a,book]).
sentence(72,train,[a,person,put,the,dog,on,the,women]).
sentence(73,train,[the,cat,sees,the,cats,in,a,person,with,the,telescopes]).
sentence(74,train,[the,cats,put,the,person,on,the,books,in,the,fountains]).
sentence(75,train,[a,cat,put,the,books,with,a,fountain,with,a,book]).
sentence(76,train,[the,person,chases,the,cat,on,a,person]).
sentence(77,train,[the,cats,chased,the,telescope,in,the,fountains]).
sentence(78,train,[the,dogs,put,a,fountain,on,the,dog]).
sentence(79,train,[the,people,on,a,person,chased,the,cat,in,a,park,on,the,telescopes]).
sentence(80,train,[the,telescopes,on,the,telescope,saw,a,fountain,with,the,woman,in,the,people]).
sentence(81,train,[the,women,barked,on,the,cats,in,a,book]).
sentence(82,train,[the,person,puts,the,telescopes,in,a,man,in,a,cat]).
sentence(83,train,[the,telescopes,put,a,man,on,the,fountains,in,the,telescope]).
sentence(84,train,[a,park,in,a,person,barked,in,the,men]).
sentence(85,train,[a,person,barked]).
sentence(86,train,[the,telescopes,see,the,park,with,the,telescope,on,a,fountain]).
sentence(87,train,[a,woman,barks,in,the,people,in,the,woman]).
sentence(88,train,[a,book,put,a,man,with,the,dogs,in,a,book]).
sentence(89,train,[the,dogs,with,a,woman,bark]).
sentence(90,train,[the,dog,put,the,woman,with,the,telescopes,in,a,park]).
sentence(91,train,[a,woman,in,a,dog,chased,a,dog,on,the,women,in,a,person]).
sentence(92,train,[the,man,sees,the,dogs,in,the,women,with,the,man]).
sentence(93,train,[a,telescope,put,the,woman,with,the,people,on,a,telescope]).
sentence(94,train,[a,park,barked,in,the,parks,in,the,books]).
sentence(95,train,[the,fountains,chase,a,park,in,a,cat,in,a,woman]).
sentence(96,train,[the,woman,put,a,man,with,a,woman,in,the,dogs]).
sentence(97,train,[a,park,on,the,parks,sees,a,book,in,the,fountains,with,the,dog]).
sentence(98,train,[the,parks,on,the,books,barked,on,a,man,in,a,dog]).
sentence(99,train,[a,book,in,the,fountain,barked]).
sentence(100,train,[the,men,chased,a,dog,with,the,cats,in,a,person]).
sentence(101,train,[a,telescope,saw,a,woman,in,the,man]).
sentence(102,train,[the,park,on,a,fountain,puts,a,person,with,the,person,with,the,fountain]).
sentence(103,train,[a,fountain,puts,a,woman,in,the,telescopes,in,a,park]).
sentence(104,train,[a,park,on,a,man,chases,a,telescope]).
sentence(105,train,[a,dog,put,a,man,with,a,cat]).
sentence(106,train,[a,man,puts,the,cat,with,a,fountain]).
sentence(107,train,[the,woman,in,a,park,saw,a,dog,with,the,books,in,a,fountain]).
sentence(108,train,[a,telescope,saw,the,books,with,a,fountain]).
sentence(109,train,[a,telescope,puts,a,person,with,a,cat]).
sentence(110,train,[the,telescope,on,the,dogs,chased,a,dog,with,a,dog,with,the,men]).
sentence(111,train,[the,cats,see,a,man]).
sentence(112,train,[the,books,bark,in,a,man]).
sentence(113,train,[the,man,barks]).
sentence(114,train,[the,fountains,saw,a,book,with,the,women,in,a,park]).
sentence(115,train,[the,telescopes,bark,with,a,fountain,on,the,people]).
sentence(116,train,[a,fountain,saw,a,fountain,on,a,dog,in,the,dogs]).
sentence(117,train,[the,books,bark,in,the,book,on,a,cat]).
sentence(118,train,[a,cat,in,the,fountain,chases,a,dog,with,the,telescope,with,a,person]).
sentence(119,train,[the,man,in,a,cat,puts,the,book,with,a,dog,on,the,park]).
sentence(120,train,[the,fountains,bark,on,a,cat,in,the,women]).
sentence(121,train,[a,book,barks,on,a,fountain,with,a,person]).
sentence(122,train,[a,cat,saw,the,cat,on,the,telescope,with,the,parks]).
sentence(123,train,[the,man,saw,a,telescope,with,the,fountain,with,the,park]).
sentence(124,train,[the,woman,barked]).
sentence(125,train,[the,dogs,see,a,book,in,the,parks,in,a,book]).
sentence(126,train,[the,dogs,saw,the,people,with,a,dog,on,a,person]).
sentence(127,train,[a,book,with,a,book,saw,the,telescope,in,the,dog,in,a,cat]).
sentence(128,train,[a,cat,put,a,dog,on,the,people,with,the,women]).
sentence(129,train,[the,cats,saw,the,fountain,in,a,person,on,the,men]).
sentence(130,train,[a,dog,put,the,fountains,in,a,person,on,a,cat]).
sentence(131,train,[a,park,put,a,person,on,the,women]).
sentence(132,train,[the,people,saw,a,park,with,the,cats,on,a,man]).
sentence(133,train,[a,man,barked,in,a,dog]).
sentence(134,train,[the,park,puts,the,parks,in,the,dogs,on,the,books]).
sentence(135,train,[the,books,chase,the,park]).
sentence(136,train,[a,fountain,saw,a,cat]).
sentence(137,train,[a,person,chases,the,telescope,with,the,woman,in,the,fountain]).
sentence(138,train,[a,park,puts,the,telescopes,in,the,fountain]).
sentence(139,train,[a,man,in,the,people,chases,a,book]).
sentence(140,train,[the,cat,barks]).
sentence(141,train,[the,women,with,the,cats,put,the,parks,in,a,telescope]).
sentence(142,train,[a,telescope,puts,the,people,in,the,parks]).
sentence(143,train,[the,dog,puts,the,woman,with,a,person,with,the,park]).
sentence(144,train,[the,dog,puts,the,cats,on,the,telescopes]).
sentence(145,train,[the,dog,put,a,cat,on,a,fountain,with,a,book]).
sentence(146,train,[a,park,saw,a,woman,in,the,telescopes]).
sentence(147,train,[the,dog,barked,on,the,man]).
sentence(148,train,[the,book,chased,a,dog,on,the,woman,in,the,dog]).
sentence(149,train,[a,woman,barks,on,a,fountain,with,a,park]).
sentence(150,train,[the,cats,barked]).
sentence(151,train,[the,dogs,in,a,book,bark,in,a,man]).
sentence(152,train,[the,people,saw,a,telescope]).
sentence(153,train,[the,women,in,the,park,saw,a,dog,on,a,fountain,in,a,woman]).
sentence(154,train,[the,cats,barked,on,the,cat,on,the,telescope]).
sentence(155,train,[the,park,with,the,parks,chased,a,woman,on,the,cats,with,a,fountain]).
sentence(156,train,[the,telescopes,chased,the,person]).
sentence(157,train,[a,man,put,the,dog,in,the,parks,with,a,park]).
sentence(158,train,[a,book,in,a,telescope,chases,the,men,on,a,cat]).
sentence(159,train,[a,cat,on,the,dogs,barks,on,the,fountain,with,the,men]).
sentence(160,train,[the,fountains,chased,the,books,with,a,park,in,a,cat]).
sentence(161,train,[the,woman,chases,a,dog]).
sentence(162,train,[the,book,in,the,woman,chases,the,cat,with,the,cats,in,the,telescopes]).
sentence(163,train,[a,telescope,in,a,person,barks,on,a,dog,on,a,person]).
sentence(164,train,[the,parks,barked,in,a,fountain,on,a,woman]).
sentence(165,train,[a,dog,in,a,dog,saw,the,dog,with,the,books,with,a,person]).
sentence(166,train,[the,telescopes,put,a,telescope,with,the,book,with,a,fountain]).
sentence(167,train,[the,fountains,bark,on,the,fountain,with,the,dog]).
sentence(168,train,[the,parks,chase,the,dogs,in,a,woman,with,the,telescopes]).
sentence(169,train,[the,cat,puts,a,book,with,the,women]).
sentence(170,train,[the,telescopes,saw,the,telescopes]).
sentence(171,train,[a,dog,barks,with,a,telescope,with,a,fountain]).
sentence(172,train,[a,telescope,puts,a,man,on,the,telescope]).
sentence(173,train,[the,man,chases,the,parks]).
sentence(174,train,[the,woman,barked,with,a,person,in,the,telescope]).
sentence(175,train,[the,telescopes,with,the,parks,barked,in,the,book,in,a,dog]).
sentence(176,train,[the,dog,sees,a,person]).
sentence(177,train,[a,woman,with,a,man,sees,the,books]).
sentence(178,train,[the,fountains,on,the,person,saw,the,dog,in,a,dog,on,the,woman]).
sentence(179,train,[the,man,puts,a,woman,on,the,people,on,a,fountain]).
sentence(180,train,[the,man,barks,with,a,park]).
sentence(181,train,[the,person,sees,a,park,in,the,men,with,the,books]).
sentence(182,train,[a,fountain,on,a,park,barks,on,a,cat,with,the,cat]).
sentence(183,train,[the,people,put,the,cats,in,the,cat,in,a,dog]).
sentence(184,train,[a,park,barked]).
sentence(185,train,[a,woman,chased,the,book,on,a,fountain,in,a,man]).
sentence(186,train,[a,cat,with,the,fountains,puts,the,book,with,the,fountains,on,the,men]).
sentence(187,train,[a,book,with,a,cat,sees,the,cats]).
sentence(188,train,[a,book,put,a,man,with,a,telescope,with,the,parks]).
sentence(189,train,[a,person,in,a,person,barked,on,a,person,in,a,man]).
sentence(190,train,[a,person,barked,on,the,fountain,on,the,woman]).
sentence(191,train,[a,woman,on,a,fountain,barks,with,a,fountain]).
sentence(192,train,[the,woman,barks,with,a,woman]).
sentence(193,train,[the,dogs,see,the,cat]).
sentence(194,train,[the,book,chased,a,man,with,a,cat]).
sentence(195,train,[the,book,barks,on,a,man,on,the,book]).
sentence(196,train,[the,man,barked,with,a,book,in,the,park]).
sentence(197,train,[a,cat,chases,the,fountain,on,the,people,on,the,telescopes]).
sentence(198,train,[a,person,puts,the,cats,on,a,dog]).
sentence(199,train,[the,cats,barked]).
sentence(200,train,[the,man,chases,the,person,with,a,telescope,with,the,cat]).
sentence(201,test,[the,fountains,chased,the,telescope,with,the,cats,in,the,cat]).
sentence(202,test,[a,cat,with,a,cat,saw,a,man]).
sentence(203,test,[a,cat,puts,the,woman,with,a,dog,on,the,telescopes]).
sentence(204,test,[the,cats,chased,a,cat,on,a,book,in,the,cats]).
sentence(205,test,[a,fountain,put,a,fountain,on,the,woman,in,a,man]).
sentence(206,test,[the,telescopes,with,a,telescope,saw,a,man,with,a,person,in,a,woman]).
sentence(207,test,[the,person,barked,on,a,person]).
sentence(208,test,[the,telescope,on,the,parks,puts,a,cat,with,a,park,in,the,parks]).
sentence(209,test,[the,books,chased,a,park,with,a,fountain,in,a,person]).
sentence(210,test,[the,book,on,the,cat,saw,the,dog]).
sentence(211,test,[the,cats,in,a,fountain,chase,the,dogs,on,the,park,in,the,telescope]).
sentence(212,test,[a,park,barks,on,the,telescopes,in,the,dog]).
sentence(213,test,[the,telescope,barks,on,a,woman,in,the,fountains]).
sentence(214,test,[a,person,barked]).
sentence(215,test,[the,fountain,in,a,person,barked,on,a,man,in,a,man]).
sentence(216,test,[the,cats,saw,a,telescope]).
sentence(217,test,[the,books,saw,the,books,on,the,women,on,a,book]).
sentence(218,test,[a,woman,with,a,person,barks]).
sentence(219,test,[a,fountain,put,a,park,in,a,man,on,a,dog]).
sentence(220,test,[the,parks,bark]).
sentence(221,test,[a,dog,barks]).
sentence(222,test,[the,telescope,barks,on,a,book,in,a,woman]).
sentence(223,test,[the,parks,put,a,cat,on,the,dog,in,the,telescope]).
sentence(224,test,[the,telescope,puts,the,cat,with,a,cat]).
sentence(225,test,[the,woman,sees,a,woman,on,the,dog,in,a,park]).
sentence(226,test,[the,people,put,the,book,in,the,men,on,a,telescope]).
sentence(227,test,[the,fountains,see,the,cats,with,the,books,with,the,person]).
sentence(228,test,[a,man,with,a,telescope,puts,a,man,with,a,person,on,the,book]).
sentence(229,test,[a,cat,sees,a,dog,with,a,book,on,a,telescope]).
sentence(230,test,[the,women,see,a,cat,in,a,park]).
sentence(231,test,[the,park,on,the,cats,barks,on,a,fountain]).
sentence(232,test,[a,person,puts,the,telescopes,on,the,book,in,the,telescopes]).
sentence(233,test,[a,book,puts,the,books,on,the,fountain,with,the,book]).
sentence(234,test,[the,dog,barks,on,a,dog,in,the,books]).
sentence(235,test,[the,parks,put,the,person,with,the,park,in,the,dogs]).
sentence(236,test,[a,book,barked,in,the,fountains]).
sentence(237,test,[the,books,on,the,person,chased,the,park,on,the,fountain]).
sentence(238,test,[the,cats,on,a,woman,barked,on,a,person,with,the,fountains]).
sentence(239,test,[the,men,put,the,telescope,in,a,woman]).
sentence(240,test,[the,books,with,a,fountain,see,the,fountain,on,the,cat,in,a,dog]).
sentence(241,test,[a,book,chases,a,telescope]).
sentence(242,test,[the,people,bark,in,the,telescopes]).
sentence(243,test,[the,person,put,the,man,on,the,women]).
sentence(244,test,[a,woman,barks,with,the,people,with,the,dog]).
sentence(245,test,[the,woman,with,a,cat,saw,the,park]).
sentence(246,test,[the,book,chases,a,fountain,in,the,telescope,in,the,people]).
sentence(247,test,[a,person,put,the,telescope,on,the,person,in,a,park]).
sentence(248,test,[a,telescope,with,the,cats,barks,with,a,person,with,the,park]).
sentence(249,test,[a,book,saw,the,men,on,the,cats,in,a,person]).
sentence(250,test,[the,park,put,the,fountain,in,a,telescope,with,a,cat]).
