#!/bin/sh
if [ $# -lt 1 ]; then
    echo "Usage: Annotate <treebank> [.. options ..]" 1>&2
    exit 1
fi
suite="$1"
shift
if [ -r ./Suites/$suite.pl ]
    then mkdir -p ./Treebank/$suite
    Alpino debug=1 complex_parse_widget=on\
	-suite ./Suites/$suite\
	-flag treebank ./Treebank/$suite\
	-cmd load_suite\
        annotating=on\
	end_hook=undefined\
        xml_format_frame=off\
        -flag alpino_ds_version 1.3\
	interactive_lexical_analysis=off\
	-veryfast\
	use_guides=off\
	pos_tagger=off\
	$DEFAULT_ALPINO_ANNOTATE_OPTIONS "$@"
else
    echo "File ./Suites/$suite.pl does not exist!"
fi
    
