converse: $(target).data.dz $(target).index
	act -d /dev/shm -x $(target) 
	( cd /dev/shm/$(target) ; $(MAKE) -f $(ALPINO_HOME)/Makefile.xmlconverse conv )
	act -f -c /dev/shm/$(target)
	rm -rf /dev/shm/$(target)

conv: 
	dtlist . | xargs Alpino -u debug=0 -xml_converse


PAT=none
files=$(basename $(basename $(wildcard $(PAT)*.dz)))

all: 
	for file in $(files); do $(MAKE) -f $(ALPINO_HOME)/Makefile.xmlconverse converse target=$$file; done

