sentence(1,[what,rivers,are,there,?]).
sentence(2,[does,afghanistan,border,china,?]).
sentence(3,[what,is,the,capital,of,upper_volta,?]).
sentence(4,[where,is,the,largest,country,?]).
sentence(5,[which,countries,are,european,?]).
sentence(6,[which,country,'\'',s,capital,is,london,?]).
sentence(7,[which,is,the,largest,african,country,?]).
sentence(8,[how,large,is,the,smallest,american,country,?]).
sentence(9,[what,is,the,ocean,that,borders,african,countries,and,that,borders,asian,countries,?]).
sentence(10,[what,are,the,capitals,of,the,countries,bordering,the,baltic,?]).
sentence(11,[which,countries,are,bordered,by,two,seas,?]).
sentence(12,[how,many,countries,does,the,danube,flow,through,?]).
sentence(13,[what,is,the,total,area,of,countries,south,of,the,equator,and,not,in,australasia,?]).
sentence(14,[what,is,the,average,area,of,the,countries,in,each,continent,?]).
sentence(15,[is,there,more,than,one,country,in,each,continent,?]).
sentence(16,[is,there,some,ocean,that,does,not,border,any,country,?]).
sentence(17,[what,are,the,countries,from,which,a,river,flows,into,the,black_sea,?]).
sentence(18,[what,are,the,continents,no,country,in,which,contains,more,than,two,cities,whose,population,exceeds,1,million,?]).
sentence(19,[which,country,bordering,the,mediterranean,borders,a,country,that,is,bordered,by,a,country,whose,population,exceeds,the,population,of,india,?]).
sentence(20,[which,countries,have,a,population,exceeding,10,million,?]).
sentence(21,[which,countries,with,a,population,exceeding,10,million,border,the,atlantic,?]).
sentence(22,[what,percentage,of,countries,border,each,ocean,?]).
sentence(23,[what,countries,are,there,in,europe,?]).
