#!/usr/bin/perl -w

$opt_c="";
$opt_p="./";

use Getopt::Std;
use File::Basename;

getopts('s:c:p:');

print "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\">\n";
print "<HTML><HEAD><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n";
print "<TITLE>$opt_s</TITLE>\n";
print "<LINK rel=stylesheet href=\"$opt_c\" type=\"text/css\">\n";
print "<meta name=\"robots\" content=\"noindex,nofollow\">";
print "</HEAD><BODY><div class=\"box\">\n";
print "<H1>$opt_s</H1><p>\n";
## print "<H2>Last updated: ". `date +"%B %d, %Y"` . "</H2>\n";
print "
<p>The dependency structures are given in svg format. 
The svg format (packaged here in an xhtml file) is supported by decent browsers such 
as Firefox. It is not supported by Internet Explorer.
<p><table>
";

while (<>) {
  chomp;
  ($file,@words) = split;
  $sent = join(' ',@words);

  $base = basename($file);

  print "<tr><td style='white-space: nowrap'>$base</td><td><a href=/vannoord/bin/alpinods_act2svg?$opt_p/$file>svg</a></td><td><a href=/vannoord/bin/alpinods_act2xml?$opt_p/$file>xml</a></td><td >$sent</td></tr>\n";
 
}

print "</table></div></body></html>\n";
