accent(a,à).
accent('Abchazier','Abchaziër').
accent('Abchaziers','Abchaziërs').
accent(academien,academiën).
accent(actiecomite,actiecomité).
accent('actiecomite\'s','actiecomité\'s').
accent(actiecomites,actiecomités).
accent(actien,actiën).
accent(actiescene,actiescène).
accent(actiescenes,actiescènes).
accent(aerobe,aërobe).
accent(aeroob,aëroob).
accent(agrarier,agrariër).
accent(agrariers,agrariërs).
accent('aids-patient','aids-patiënt').
accent(aidspatient,aidspatiënt).
accent('aids-patiente','aids-patiënte').
accent(aidspatiente,aidspatiënte).
accent('aids-patienten','aids-patiënten').
accent(aidspatienten,aidspatiënten).
accent('aids-patientes','aids-patiëntes').
accent(aidspatientes,aidspatiëntes).
accent(aktien,aktiën).
accent(alleeen,alleeën).
accent(allegorieen,allegorieën).
accent(allergieen,allergieën).
accent(alpineskien,alpineskiën).
accent(altruist,altruïst).
accent(altruisten,altruïsten).
accent(alzheimerpatient,alzheimerpatiënt).
accent(alzheimerpatiente,alzheimerpatiënte).
accent(alzheimerpatienten,alzheimerpatiënten).
accent(alzheimerpatientes,alzheimerpatiëntes).
accent(ambieren,ambiëren).
accent(ambiguiteit,ambiguïteit).
accent(ambiguiteiten,ambiguïteiten).
accent(amfibieen,amfibieën).
accent(amnestieen,amnestieën).
accent(anaerobe,anaërobe).
accent(anaeroob,anaëroob).
accent(analogieen,analogieën).
accent(animatieserien,animatieseriën).
accent(antipathieen,antipathieën).
accent(antipatieen,antipatieën).
accent(appel,appèl).
accent(appels,appèls).
accent(apprecieren,appreciëren).
accent(arbeidsinspectien,arbeidsinspectiën).
accent(archaisch,archaïsch).
accent(archaische,archaïsche).
accent(aristocratieen,aristocratieën).
accent(aristokratieen,aristokratieën).
accent('Armenier','Armeniër').
accent('Armeniers','Armeniërs').
accent(artificiele,artificiële).
accent(artificieler,artificiëler).
accent(associeren,associëren).
accent(atheist,atheïst).
accent(atheisten,atheïsten).
accent('Atjeeer','Atjeeër').
accent('Atjeeers','Atjeeërs').
accent(attache,attaché).
accent('attache\'s','attaché\'s').
accent(attaches,attachés).
accent(audientie,audiëntie).
accent(audienties,audiënties).
accent(audientiezaal,audiëntiezaal).
accent(auspicien,auspiciën).
accent('Australier','Australiër').
accent('Australiers','Australiërs').
accent(autobiografieen,autobiografieën).
accent('auto-industrieen','auto-industrieën').
accent(autoindustrieen,autoindustrieën).
accent(automobielindustrieen,automobielindustrieën).
accent(bacterien,bacteriën).
accent(bandoneon,bandoneón).
accent(bandoneons,bandoneóns).
accent(barriere,barrière).
accent(barrieres,barrières).
accent(basisideeen,basisideeën).
accent(becommentarieren,becommentariëren).
accent(bediscussieren,bediscussiëren).
accent(bedoeien,bedoeïen).
accent(bedoeienen,bedoeïenen).
accent(beedig,beëdig).
accent(beedigd,beëdigd).
accent(beedigde,beëdigde).
accent(beedigden,beëdigden).
accent(beedigen,beëdigen).
accent(beediging,beëdiging).
accent(beedigingen,beëdigingen).
accent(beedigt,beëdigt).
accent(beeindig,beëindig).
accent(beeindigd,beëindigd).
accent(beeindigde,beëindigde).
accent(beeindigden,beëindigden).
accent(beeindigen,beëindigen).
accent(beeindiging,beëindiging).
accent(beeindigt,beëindigt).
accent(beerf,beërf).
accent(beerfd,beërfd).
accent(beerfde,beërfde).
accent(beerfden,beërfden).
accent(beerft,beërft).
accent(beerven,beërven).
accent(beinvloed,beïnvloed).
accent(beinvloedde,beïnvloedde).
accent(beinvloedden,beïnvloedden).
accent(beinvloede,beïnvloede).
accent(beinvloeden,beïnvloeden).
accent(beinvloeding,beïnvloeding).
accent(beinvloedingen,beïnvloedingen).
accent(beinvloedt,beïnvloedt).
accent(bemiddelingscomite,bemiddelingscomité).
accent('bemiddelingscomite\'s','bemiddelingscomité\'s').
accent(bemiddelingscomites,bemiddelingscomités).
accent(beta,bèta).
accent(betablokker,bètablokker).
accent(betablokkers,bètablokkers).
accent('beta\'s','bèta\'s').
accent(bete,bête).
accent(bezettingsactien,bezettingsactiën).
accent(bezettingsaktien,bezettingsaktiën).
accent(bibliografieen,bibliografieën).
accent(bijbelstudien,bijbelstudiën).
accent('Bijlmer-enquete','Bijlmer-enquête').
accent('Bijlmer-enquetes','Bijlmer-enquêtes').
accent(biografieen,biografieën).
accent('bio-industrieen','bio-industrieën').
accent(bioindustrieen,bioindustrieën).
accent(biotechnologieen,biotechnologieën).
accent(blase,blasé).
accent(bler,blèr).
accent(blerde,blèrde).
accent(blerden,blèrden).
accent(bleren,blèren).
accent(blert,blèrt).
accent(bobsleeen,bobsleeën).
accent('Bosnier','Bosniër').
accent('Bosniers','Bosniërs').
accent('Brentolien','Brentoliën').
accent(buhne,bühne).
accent('Burundier','Burundiër').
accent('Burundiers','Burundiërs').
accent(buurtcomite,buurtcomité).
accent('buurtcomite\'s','buurtcomité\'s').
accent(buurtcomites,buurtcomités).
accent(ca,ça).
accent(cafebaas,cafébaas).
accent(cafebaasje,cafébaasje).
accent(cafebaasjes,cafébaasjes).
accent(cafebazen,cafébazen).
accent(cafebezoeker,cafébezoeker).
accent(cafebezoekers,cafébezoekers).
accent(cafebrand,cafébrand).
accent(cafebranden,cafébranden).
accent(cafebrandje,cafébrandje).
accent(cafebrandjes,cafébrandjes).
accent(cafe,café).
accent(cafehouder,caféhouder).
accent(cafehouders,caféhouders).
accent('cafe\'s','café\'s').
accent(cafes,cafés).
accent(calorieen,calorieën).
accent(canape,canapé).
accent(canapes,canapés).
accent('Caraibisch','Caraïbisch').
accent('Caraibische','Caraïbische').
accent(caries,cariës).
accent(carre,carré).
accent(carres,carrés).
accent(carriere,carrière).
accent(carrieres,carrières).
accent(carrosserieen,carrosserieën).
accent(caseine,caseïne).
accent(categorieen,categorieën).
accent(ceremoniele,ceremoniële).
accent(ceremonien,ceremoniën).
accent(chemicalien,chemicaliën).
accent(chemotherapieen,chemotherapieën).
accent(chipindustrieen,chipindustrieën).
accent(choreografieen,choreografieën).
accent('christen-democratieen','christen-democratieën').
accent(chronologieen,chronologieën).
accent(clichebeeld,clichébeeld).
accent(clichebeelden,clichébeelden).
accent(clichebeeldje,clichébeeldje).
accent(clichebeeldjes,clichébeeldjes).
accent(cliche,cliché).
accent(clichematig,clichématig).
accent(clichematige,clichématige).
accent('cliche\'s','cliché\'s').
accent(cliches,clichés).
accent(client,cliënt).
accent(cliente,cliënte).
accent(clientele,clientèle).
accent(clientele,cliëntèle).
accent(clienten,cliënten).
accent(clientendossier,cliëntendossier).
accent(clientendossiers,cliëntendossiers).
accent(clientenraad,cliëntenraad).
accent(clientenraden,cliëntenraden).
accent(clientes,cliëntes).
accent(clubhistorien,clubhistoriën).
accent(cocaine,cocaïne).
accent(cocainehandel,cocaïnehandel).
accent(cocainehandels,cocaïnehandels).
accent(cocainehandeltje,cocaïnehandeltje).
accent(cocainehandeltjes,cocaïnehandeltjes).
accent(cocainesmokkelaar,cocaïnesmokkelaar).
accent(cocainesmokkelaars,cocaïnesmokkelaars).
accent(cocainesmokkel,cocaïnesmokkel).
accent(coefficient,coëfficiënt).
accent(coefficienten,coëfficiënten).
accent(coitus,coïtus).
accent(comedienne,comédienne).
accent(comediennes,comédiennes).
accent(comite,comité).
accent('comite\'s','comité\'s').
accent(comites,comités).
accent(commerciele,commerciële).
accent(commercieler,commerciëler).
accent(communien,communiën).
accent(communique,communiqué).
accent('communique\'s','communiqué\'s').
accent(communiques,communiqués).
accent(compagnieen,compagnieën).
accent(complottheorieen,complottheorieën).
accent(concierge,conciërge).
accent(concierges,conciërges).
accent(concilien,conciliën).
accent(concipieren,concipiëren).
accent(conditien,conditiën).
accent('conflict-situatien','conflict-situatiën').
accent(conflictsituatien,conflictsituatiën).
accent(congregatien,congregatiën).
accent(continuiteit,continuïteit).
accent(controversiele,controversiële).
accent(controversieler,controversiëler).
accent(controversielere,controversiëlere).
accent(cooperatie,coöperatie).
accent(cooperatief,coöperatief).
accent(cooperaties,coöperaties).
accent(cooperatieve,coöperatieve).
accent(coordinaat,coördinaat).
accent(coordinaten,coördinaten).
accent(coordinatie,coördinatie).
accent(coordinaties,coördinaties).
accent(coordinator,coördinator).
accent(coordinatoren,coördinatoren).
accent(coordineer,coördineer).
accent(coordineerde,coördineerde).
accent(coordineerden,coördineerden).
accent(coordineert,coördineert).
accent(coordineren,coördineren).
accent(copieen,copieën).
accent(copieren,copiëren).
accent(corticosteroide,corticosteroïde).
accent(corticosteroiden,corticosteroïden).
accent(coryfeeen,coryfeeën).
accent(coupe,coupé).
accent('coupe\'s','coupé\'s').
accent(coupes,coupés).
accent(coute,coûte).
accent(creche,crèche).
accent(creches,crèches).
accent(creeer,creëer).
accent(creeerde,creëerde).
accent(creeerden,creëerden).
accent(creeert,creëert).
accent(creeren,creëren).
accent(creme,crème).
accent(creme,crême).
accent(cremekleurig,crèmekleurig).
accent(cremekleurige,crèmekleurige).
accent(cremekleuriger,crèmekleuriger).
accent(cremekleurigere,crèmekleurigere).
accent(cremekleurigst,crèmekleurigst).
accent(cremekleurigste,crèmekleurigste).
accent(cremes,crèmes).
accent('crisis-situatien','crisis-situatiën').
accent(crisissituatien,crisissituatiën).
accent('Curacaos','Curaçaos').
accent('Curacaose','Curaçaose').
accent(cuvee,cuvée).
accent(debacle,debâcle).
accent(debacles,debâcles).
accent(decennien,decenniën).
accent(decollete,decolleté).
accent('decollete\'s','decolleté\'s').
accent(decolletes,decolletés).
accent(dedain,dédain).
accent('defensie-industrieen','defensie-industrieën').
accent(definieren,definiëren).
accent(deinstalleerde,deïnstalleerde).
accent(deinstalleer,deïnstalleer).
accent(deinstalleerden,deïnstalleerden).
accent(deinstalleert,deïnstalleert).
accent(deinstalleren,deïnstalleren).
accent(deja,déja).
accent(deja,déjà).
accent(democratieen,democratieën).
accent(dieselolien,dieseloliën).
accent(diete,diëte).
accent(dieten,diëten).
accent(differentiele,differentiële).
accent(differentieren,differentiëren).
accent(dinosaurier,dinosauriër).
accent(dinosauriers,dinosauriërs).
accent(diploid,diploïd).
accent(diploide,diploïde).
accent(directiecomite,directiecomité).
accent('directiecomite\'s','directiecomité\'s').
accent(directiecomites,directiecomités).
accent(discografieen,discografieën).
accent(discussieren,discussiëren).
accent(diskussieren,diskussiëren).
accent(distantieren,distantiëren).
accent(divisien,divisiën).
accent(documentaireserien,documentaireseriën).
accent(dona,doña).
accent('dona\'s','doña\'s').
accent(doodmoee,doodmoeë).
accent(doodmoeer,doodmoeër).
accent(doodmoeere,doodmoeëre).
accent(doorsneeen,doorsneeën).
accent(dramaserien,dramaseriën).
accent(drieeenheid,drieëenheid).
accent(drieen,drieën).
accent(dynastieen,dynastieën).
accent(echoen,echoën).
accent(economieen,economieën).
accent(een,één).
accent('een-honderdste','één-honderdste').
accent('een-op-een','één-op-één').
accent(eetcafe,eetcafé).
accent('eetcafe\'s','eetcafé\'s').
accent(eetcafes,eetcafés).
accent(efficiente,efficiënte).
accent(efficient,efficiënt).
accent(efficientere,efficiëntere).
accent(efficienter,efficiënter).
accent(efficientie,efficiëntie).
accent(efficientste,efficiëntste).
accent(efficientst,efficiëntst).
accent(egoisme,egoïsme).
accent(egoist,egoïst).
accent(egoisten,egoïsten).
accent(egoistische,egoïstische).
accent(egoistisch,egoïstisch).
accent(egoistischere,egoïstischere).
accent(egoistischer,egoïstischer).
accent(egoistischte,egoïstischte).
accent(egoistischt,egoïstischt).
accent(elegance,élégance).
accent(employe,employé).
accent('employe\'s','employé\'s').
accent(employes,employés).
accent(encyclopedieen,encyclopedieën).
accent(energieen,energieën).
accent(enquetecommissie,enquêtecommissie).
accent(enquetecommissies,enquêtecommissies).
accent(enquete,enquête).
accent(enquetekommissie,enquêtekommissie).
accent(enquetekommissies,enquêtekommissies).
accent(enquetes,enquêtes).
accent(epidemieen,epidemieën).
accent(essentiele,essentiële).
accent('Ethiopier','Ethiopiër').
accent('Ethiopiers','Ethiopiërs').
accent(europarlementarier,europarlementariër).
accent('Europarlementarier','Europarlementariër').
accent(europarlementariers,europarlementariërs).
accent('Europarlementariers','Europarlementariërs').
accent(evacuee,evacuée).
accent(evacuees,evacuées).
accent(evacue,evacué).
accent(evacues,evacués).
accent(evangelien,evangeliën).
accent(evolutietheorieen,evolutietheorieën).
accent(existentiele,existentiële).
accent(facade,façade).
accent(facaden,façaden).
accent(facades,façades).
accent(facadetje,façadetje).
accent(facadetjes,façadetjes).
accent(factien,factiën).
accent(fantasieen,fantasieën).
accent(fantazieen,fantazieën).
accent(fascistoide,fascistoïde).
accent(fascistoidere,fascistoïdere).
accent(fascistoider,fascistoïder).
accent(fascistoid,fascistoïd).
accent(feeen,feeën).
accent(filmindustrieen,filmindustrieën).
accent(filosofieen,filosofieën).
accent(financiele,financiële).
accent(financien,financiën).
accent(fobieen,fobieën).
accent(fohnde,föhnde).
accent(fohnden,föhnden).
accent(fohnen,föhnen).
accent(fohn,föhn).
accent(fohns,föhns).
accent(fohnt,föhnt).
accent(fotocopieen,fotocopieën).
accent(fotogalerieen,fotogalerieën).
accent(fotografieen,fotografieën).
accent(fotokopieen,fotokopieën).
accent(fotoserien,fotoseriën).
accent('Francaise','Française').
accent('Francaises','Françaises').
accent(frele,frêle).
accent(frobelde,fröbelde).
accent(frobelden,fröbelden).
accent(frobelen,fröbelen).
accent(frobel,fröbel).
accent(frobelt,fröbelt).
accent(furien,furiën).
accent(fysiotherapieen,fysiotherapieën).
accent(galerieen,galerieën).
accent(geblerd,geblèrd).
accent(gecoordineerde,gecoördineerde).
accent(gecoordineerd,gecoördineerd).
accent(gecreeerde,gecreëerde).
accent(gecreeerd,gecreëerd).
accent(gedeinstalleerd,gedeïnstalleerd).
accent(gedesorienteerde,gedesoriënteerde).
accent(gedesorienteerd,gedesoriënteerd).
accent(gedragsterapieen,gedragsterapieën).
accent(gedragstherapieen,gedragstherapieën).
accent(gedrieen,gedrieën).
accent(gedweee,gedweeë).
accent(gedweeere,gedweeëre).
accent(gedweeer,gedweeër).
accent(geebd,geëbd).
accent(geechode,geëchode).
accent(geechood,geëchood).
accent(geedit,geëdit).
accent(geeerbiedigde,geëerbiedigde).
accent(geeerbiedigd,geëerbiedigd).
accent(geeerde,geëerde).
accent(geeerdere,geëerdere).
accent(geeerder,geëerder).
accent(geeerd,geëerd).
accent(geeerdste,geëerdste).
accent(geeerdst,geëerdst).
accent(geeffectueerde,geëffectueerde).
accent(geeffectueerd,geëffectueerd).
accent(geeffektueerde,geëffektueerde).
accent(geeffektueerd,geëffektueerd).
accent(geeffende,geëffende).
accent(geeffend,geëffend).
accent(geegaliseerd,geëgaliseerd).
accent(geeigende,geëigende).
accent(geeigendere,geëigendere).
accent(geeigender,geëigender).
accent(geeigend,geëigend).
accent(geeigendste,geëigendste).
accent(geeigendst,geëigendst).
accent(geeindigde,geëindigde).
accent(geeindigd,geëindigd).
accent(geeiste,geëiste).
accent(geeist,geëist).
accent(geekskuseerde,geëkskuseerde).
accent(geekskuseerd,geëkskuseerd).
accent(geelimineerde,geëlimineerde).
accent(geelimineerd,geëlimineerd).
accent(geemaild,geëmaild).
accent(geemancipeerde,geëmancipeerde).
accent(geemancipeerdere,geëmancipeerdere).
accent(geemancipeerder,geëmancipeerder).
accent(geemancipeerd,geëmancipeerd).
accent(geemancipeerdste,geëmancipeerdste).
accent(geemancipeerdst,geëmancipeerdst).
accent(geemigreerde,geëmigreerde).
accent(geemigreerd,geëmigreerd).
accent(geemmerd,geëmmerd).
accent(geemotioneerde,geëmotioneerde).
accent(geemotioneerdere,geëmotioneerdere).
accent(geemotioneerder,geëmotioneerder).
accent(geemotioneerd,geëmotioneerd).
accent(geemotioneerdste,geëmotioneerdste).
accent(geemotioneerdst,geëmotioneerdst).
accent(geeneen,geenéén).
accent(geengageerde,geëngageerde).
accent(geengageerd,geëngageerd).
accent(geensceneerde,geënsceneerde).
accent(geensceneerd,geënsceneerd).
accent(geente,geënte).
accent(geenterde,geënterde).
accent(geenterd,geënterd).
accent(geentertaind,geëntertaind).
accent(geent,geënt).
accent(geenthousiasmeerd,geënthousiasmeerd).
accent(geerfde,geërfde).
accent(geerfd,geërfd).
accent(geergerde,geërgerde).
accent(geergerd,geërgerd).
accent(geescaleerd,geëscaleerd).
accent(geescorteerde,geëscorteerde).
accent(geescorteerd,geëscorteerd).
accent(geetaleerde,geëtaleerde).
accent(geetaleerd,geëtaleerd).
accent(geetiketteerde,geëtiketteerde).
accent(geetiketteerd,geëtiketteerd).
accent(geetste,geëtste).
accent(geetst,geëtst).
accent(geetterd,geëtterd).
accent(geevacueerde,geëvacueerde).
accent(geevacueerd,geëvacueerd).
accent(geevalueerde,geëvalueerde).
accent(geevalueerd,geëvalueerd).
accent(geevangeliseerd,geëvangeliseerd).
accent(geevenaarde,geëvenaarde).
accent(geevenaard,geëvenaard).
accent(geevolueerde,geëvolueerde).
accent(geevolueerd,geëvolueerd).
accent(geexamineerd,geëxamineerd).
accent(geexcelleerd,geëxcelleerd).
accent(geexcuseerde,geëxcuseerde).
accent(geexcuseerd,geëxcuseerd).
accent(geexecuteerde,geëxecuteerde).
accent(geexecuteerd,geëxecuteerd).
accent(geexpandeerde,geëxpandeerde).
accent(geexpandeerd,geëxpandeerd).
accent(geexperimenteerd,geëxperimenteerd).
accent(geexpliciteerde,geëxpliciteerde).
accent(geexpliciteerd,geëxpliciteerd).
accent(geexplodeerde,geëxplodeerde).
accent(geexplodeerd,geëxplodeerd).
accent(geexploiteerde,geëxploiteerde).
accent(geexploiteerd,geëxploiteerd).
accent(geexploreerde,geëxploreerde).
accent(geexploreerd,geëxploreerd).
accent(geexporteerde,geëxporteerde).
accent(geexporteerd,geëxporteerd).
accent(geexposeerde,geëxposeerde).
accent(geexposeerd,geëxposeerd).
accent(geextraheerd,geëxtraheerd).
accent(geextrapoleerde,geëxtrapoleerde).
accent(geextrapoleerd,geëxtrapoleerd).
accent(gefohnde,geföhnde).
accent(gefohnd,geföhnd).
accent(gefrobeld,gefröbeld).
accent(geidealiseerde,geïdealiseerde).
accent(geidealiseerd,geïdealiseerd).
accent(geidealizeerde,geïdealizeerde).
accent(geidealizeerd,geïdealizeerd).
accent(geidentificeerde,geïdentificeerde).
accent(geidentificeerd,geïdentificeerd).
accent(geillustreerde,geïllustreerde).
accent(geillustreerd,geïllustreerd).
accent(geimiteerde,geïmiteerde).
accent(geimiteerd,geïmiteerd).
accent(geimmuniseerd,geïmmuniseerd).
accent(geimplanteerd,geïmplanteerd).
accent(geimplementeerde,geïmplementeerde).
accent(geimplementeerd,geïmplementeerd).
accent(geimpliceerde,geïmpliceerde).
accent(geimpliceerd,geïmpliceerd).
accent(geimponeerde,geïmponeerde).
accent(geimponeerd,geïmponeerd).
accent(geimporteerde,geïmporteerde).
accent(geimporteerd,geïmporteerd).
accent(geimproviseerde,geïmproviseerde).
accent(geimproviseerd,geïmproviseerd).
accent(geimprovizeerde,geïmprovizeerde).
accent(geimprovizeerd,geïmprovizeerd).
accent(geincasseerde,geïncasseerde).
accent(geincasseerd,geïncasseerd).
accent(geincorporeerd,geïncorporeerd).
accent(geinde,geïnde).
accent(geind,geïnd).
accent(geindiceerde,geïndiceerde).
accent(geindiceerd,geïndiceerd).
accent(geindividualiseerde,geïndividualiseerde).
accent(geindividualiseerd,geïndividualiseerd).
accent(geindividualizeerde,geïndividualizeerde).
accent(geindividualizeerd,geïndividualizeerd).
accent(geindoctrineerd,geïndoctrineerd).
accent(geinduceerde,geïnduceerde).
accent(geinduceerd,geïnduceerd).
accent(geindustrialiseerde,geïndustrialiseerde).
accent(geindustrialiseerd,geïndustrialiseerd).
accent(geindustrializeerde,geïndustrializeerde).
accent(geindustrializeerd,geïndustrializeerd).
accent(geinfecteerde,geïnfecteerde).
accent(geinfecteerd,geïnfecteerd).
accent(geinfekteerde,geïnfekteerde).
accent(geinfekteerd,geïnfekteerd).
accent(geinfiltreerde,geïnfiltreerde).
accent(geinfiltreerd,geïnfiltreerd).
accent(geinformeerde,geïnformeerde).
accent(geinformeerd,geïnformeerd).
accent(geinhaleerde,geïnhaleerde).
accent(geinhaleerd,geïnhaleerd).
accent(geinitieerde,geïnitieerde).
accent(geinitieerd,geïnitieerd).
accent(geinjecteerd,geïnjecteerd).
accent(geinkasseerde,geïnkasseerde).
accent(geinkasseerd,geïnkasseerd).
accent(geinkt,geïnkt).
accent(geinnoveerd,geïnnoveerd).
accent(geinsinueerde,geïnsinueerde).
accent(geinsinueerd,geïnsinueerd).
accent(geinspecteerde,geïnspecteerde).
accent(geinspecteerd,geïnspecteerd).
accent(geinspekteerde,geïnspekteerde).
accent(geinspekteerd,geïnspekteerd).
accent(geinspireerde,geïnspireerde).
accent(geinspireerdere,geïnspireerdere).
accent(geinspireerder,geïnspireerder).
accent(geinspireerd,geïnspireerd).
accent(geinspireerdste,geïnspireerdste).
accent(geinspireerdst,geïnspireerdst).
accent(geinstalleerde,geïnstalleerde).
accent(geinstalleerd,geïnstalleerd).
accent(geinstitutionaliseerde,geïnstitutionaliseerde).
accent(geinstitutionaliseerd,geïnstitutionaliseerd).
accent(geinstitutionalizeerde,geïnstitutionalizeerde).
accent(geinstitutionalizeerd,geïnstitutionalizeerd).
accent(geinstrueerde,geïnstrueerde).
accent(geinstrueerd,geïnstrueerd).
accent(geintegreerde,geïntegreerde).
accent(geintegreerd,geïntegreerd).
accent(geintensiveerde,geïntensiveerde).
accent(geintensiveerd,geïntensiveerd).
accent(geinteresseerde,geïnteresseerde).
accent(geinteresseerden,geïnteresseerden).
accent(geinteresseerdere,geïnteresseerdere).
accent(geinteresseerder,geïnteresseerder).
accent(geinteresseerd,geïnteresseerd).
accent(geinteresseerdste,geïnteresseerdste).
accent(geinteresseerdst,geïnteresseerdst).
accent(geinterneerde,geïnterneerde).
accent(geinterneerd,geïnterneerd).
accent(geinternet,geïnternet).
accent(geinterpreteerde,geïnterpreteerde).
accent(geinterpreteerd,geïnterpreteerd).
accent(geinterrumpeerd,geïnterrumpeerd).
accent(geintervenieerd,geïntervenieerd).
accent(geinterviewde,geïnterviewde).
accent(geinterviewd,geïnterviewd).
accent(geintimideerde,geïntimideerde).
accent(geintimideerd,geïntimideerd).
accent(geintrigeerde,geïntrigeerde).
accent(geintrigeerd,geïntrigeerd).
accent(geintroduceerde,geïntroduceerde).
accent(geintroduceerd,geïntroduceerd).
accent(geinventariseerde,geïnventariseerde).
accent(geinventariseerd,geïnventariseerd).
accent(geinventarizeerde,geïnventarizeerde).
accent(geinventarizeerd,geïnventarizeerd).
accent(geinvesteerde,geïnvesteerde).
accent(geinvesteerd,geïnvesteerd).
accent(geinviteerde,geïnviteerde).
accent(geinviteerd,geïnviteerd).
accent(geioniseerde,geïoniseerde).
accent(geioniseerd,geïoniseerd).
accent(geirriteerde,geïrriteerde).
accent(geirriteerdere,geïrriteerdere).
accent(geirriteerder,geïrriteerder).
accent(geirriteerd,geïrriteerd).
accent(geirriteerdste,geïrriteerdste).
accent(geirriteerdst,geïrriteerdst).
accent(geisoleerde,geïsoleerde).
accent(geisoleerd,geïsoleerd).
accent(gekoordineerde,gekoördineerde).
accent(gekoordineerd,gekoördineerd).
accent(genante,gênante).
accent(genantere,gênantere).
accent(genanter,gênanter).
accent(genant,gênant).
accent(genantste,gênantste).
accent(genantst,gênantst).
accent(genealogieen,genealogieën).
accent(gene,gêne).
accent(genieen,genieën).
accent(gentechnologieen,gentechnologieën).
accent(gentherapieen,gentherapieën).
accent(geonweerd,geönweerd).
accent('Georgier','Georgiër').
accent('Georgiers','Georgiërs').
accent(georienteerde,georiënteerde).
accent(georienteerd,georiënteerd).
accent(gerecreeerd,gerecreëerd).
accent(gereintegreerd,gereïntegreerd).
accent(geruineerde,geruïneerde).
accent(geruineerd,geruïneerd).
accent(getatoeeerde,getatoeëerde).
accent(getatoeeerd,getatoeëerd).
accent(getweeen,getweeën).
accent(geuniformeerde,geüniformeerde).
accent(geuniformeerd,geüniformeerd).
accent(geupdate,geüpdate).
accent(geupdatet,geüpdatet).
accent(geupgraad,geüpgraad).
accent(geuploade,geüploade).
accent(geupload,geüpload).
accent(geurineerd,geürineerd).
accent(gevreeen,gevreeën).
accent(gezinstherapieen,gezinstherapieën).
accent(gijzelingsactien,gijzelingsactiën).
accent(gijzelingsaktien,gijzelingsaktiën).
accent(glorien,gloriën).
accent(googleen,googleën).
accent(gratien,gratiën).
accent(griepepidemieen,griepepidemieën).
accent(groepstherapieen,groepstherapieën).
accent(haalbaarheidsstudien,haalbaarheidsstudiën).
accent(haarlemmerolien,haarlemmeroliën).
accent('Haitiaan','Haïtiaan').
accent('Haitiaanse','Haïtiaanse').
accent('Haitiaans','Haïtiaans').
accent('Haitianen','Haïtianen').
accent(handelsmissien,handelsmissiën).
accent(handtekeningenactien,handtekeningenactiën).
accent(handtekeningenaktien,handtekeningenaktiën).
accent(haploide,haploïde).
accent(haploid,haploïd).
accent(harmonieen,harmonieën).
accent(harmonieren,harmoniëren).
accent(hartpatiente,hartpatiënte).
accent(hartpatienten,hartpatiënten).
accent(hartpatientes,hartpatiëntes).
accent(hartpatient,hartpatiënt).
accent(he,hé).
accent(he,hè).
accent(hehe,hèhè).
accent(hemelcoordinaat,hemelcoördinaat).
accent(hemelcoordinaten,hemelcoördinaten).
accent(hemofiliepatiente,hemofiliepatiënte).
accent(hemofiliepatienten,hemofiliepatiënten).
accent(hemofiliepatientes,hemofiliepatiëntes).
accent(hemofiliepatient,hemofiliepatiënt).
accent('Hengeloer','Hengeloër').
accent('Hengeloers','Hengeloërs').
accent(heroine,heroïne).
accent(heroische,heroïsche).
accent(heroischere,heroïschere).
accent(heroischer,heroïscher).
accent(heroisch,heroïsch).
accent(heroischte,heroïschte).
accent(heroischt,heroïscht).
accent(herorientatie,heroriëntatie).
accent(herorientaties,heroriëntaties).
accent(het,hét).
accent(hierarchieen,hiërarchieën).
accent(hierarchie,hiërarchie).
accent(hierarchische,hiërarchische).
accent(hierarchischere,hiërarchischere).
accent(hierarchischer,hiërarchischer).
accent(hierarchisch,hiërarchisch).
accent(hierarchischte,hiërarchischte).
accent(hierarchischt,hiërarchischt).
accent(hindoeisme,hindoeïsme).
accent(historien,historiën).
accent(hitserien,hitseriën).
accent(hoofdideeen,hoofdideeën).
accent(hostien,hostiën).
accent(hulpactien,hulpactiën).
accent(hulpaktien,hulpaktiën).
accent(hygiene,hygiëne).
accent(hygienische,hygiënische).
accent(hygienischere,hygiënischere).
accent(hygienischer,hygiënischer).
accent(hygienisch,hygiënisch).
accent(hygienischte,hygiënischte).
accent(hygienischt,hygiënischt).
accent(ideeel,ideëel).
accent(ideeelste,ideëelste).
accent(ideeelst,ideëelst).
accent(ideeen,ideeën).
accent(ideele,ideële).
accent(ideelere,ideëlere).
accent(ideeler,ideëler).
accent(ideologieen,ideologieën).
accent(ijstheeen,ijstheeën).
accent(immateriele,immateriële).
accent(immaterieler,immateriëler).
accent(incompatibilite,incompatibilité).
accent(inconvenienten,inconveniënten).
accent(inconvenient,inconveniënt).
accent('Indier','Indiër').
accent('Indiers','Indiërs').
accent('Indonesier','Indonesiër').
accent('Indonesiers','Indonesiërs').
accent(industrialisatien,industrialisatiën).
accent(industrializatien,industrializatiën).
accent(industrieen,industrieën).
accent(industriele,industriële).
accent(industrielen,industriëlen).
accent(inefficiente,inefficiënte).
accent(inefficientere,inefficiëntere).
accent(inefficienter,inefficiënter).
accent(inefficient,inefficiënt).
accent(inefficientste,inefficiëntste).
accent(inefficientst,inefficiëntst).
accent(informatietechnologieen,informatietechnologieën).
accent(ingeente,ingeënte).
accent(ingeent,ingeënt).
accent(ingredienten,ingrediënten).
accent(ingredient,ingrediënt).
accent(initieren,initiëren).
accent(inkonvenienten,inkonveniënten).
accent(inkonvenient,inkonveniënt).
accent(inspectien,inspectiën).
accent(interlandcarriere,interlandcarrière).
accent(interlandcarrieres,interlandcarrières).
accent(internetcafe,internetcafé).
accent('internetcafe\'s','internetcafé\'s').
accent(internetcafes,internetcafés).
accent(intervenieren,interveniëren).
accent(intuitief,intuïtief).
accent(intuitiefste,intuïtiefste).
accent(intuitiefst,intuïtiefst).
accent(intuitie,intuïtie).
accent(intuities,intuïties).
accent(intuitieve,intuïtieve).
accent(intuitievere,intuïtievere).
accent(intuitiever,intuïtiever).
accent(inzamelingsactien,inzamelingsactiën).
accent(inzamelingsaktien,inzamelingsaktiën).
accent('Iranier','Iraniër').
accent('Iraniers','Iraniërs').
accent(ironieen,ironieën).
accent(irreeel,irreëel).
accent(irreeelste,irreëelste).
accent(irreeelst,irreëelst).
accent(irreele,irreële).
accent(irreelere,irreëlere).
accent(irreeler,irreëler).
accent('Israelier','Israeliër').
accent('Israelier','Israëliër').
accent('Israeliers','Israeliërs').
accent('Israeliers','Israëliërs').
accent('Israeli','Israëli').
accent('Israelische','Israëlische').
accent('Israelisch','Israëlisch').
accent('Israelisch-Palestijnse','Israëlisch-Palestijnse').
accent('Israelisch-Palestijns','Israëlisch-Palestijns').
accent('Israeli\'s','Israëli\'s').
accent(jaloezieen,jaloezieën).
accent(je,jé).
accent(jezuieten,jezuïeten).
accent(jezuiet,jezuïet).
accent(jojoen,jojoën).
accent(jongerencafe,jongerencafé).
accent('jongerencafe\'s','jongerencafé\'s').
accent(jongerencafes,jongerencafés).
accent('Jordanier','Jordaniër').
accent('Jordaniers','Jordaniërs').
accent(judoen,judoën).
accent(jurisdictien,jurisdictiën).
accent(justitiele,justitiële).
accent(kalorieen,kalorieën).
accent(kandidaatcomite,kandidaatcomité).
accent('kandidaatcomite\'s','kandidaatcomité\'s').
accent(kandidaatcomites,kandidaatcomités).
accent(kankerpatiente,kankerpatiënte).
accent(kankerpatienten,kankerpatiënten).
accent(kankerpatientes,kankerpatiëntes).
accent(kankerpatient,kankerpatiënt).
accent(kanoen,kanoën).
accent(kenniseconomieen,kenniseconomieën).
accent(kerkprovincien,kerkprovinciën).
accent(kernenergieen,kernenergieën).
accent(kernonderzeeer,kernonderzeeër).
accent(kernonderzeeers,kernonderzeeërs).
accent(keukendivisien,keukendivisiën).
accent(kleinodien,kleinodiën).
accent(kliente,kliënte).
accent(klienten,kliënten).
accent(klient,kliënt).
accent(knieen,knieën).
accent(kolonien,koloniën).
accent(kooperatief,koöperatief).
accent(kooperatieve,koöperatieve).
accent(koordineerde,koördineerde).
accent(koordineerden,koördineerden).
accent(koordineer,koördineer).
accent(koordineert,koördineert).
accent(koordineren,koördineren).
accent(kopieen,kopieën).
accent(kopieren,kopiëren).
accent(kroonkolonien,kroonkoloniën).
accent(kunsthistorien,kunsthistoriën).
accent(kur,kür).
accent(kustprovincien,kustprovinciën).
accent(lance,lancé).
accent(leefsituatien,leefsituatiën).
accent(leeftijdscategorieen,leeftijdscategorieën).
accent(leemindustrieen,leemindustrieën).
accent(legionellabacterien,legionellabacteriën).
accent(lelien,leliën).
accent(levensbeeindigingen,levensbeëindigingen).
accent(levensbeeindiging,levensbeëindiging).
accent(levenssituatien,levenssituatiën).
accent('Libier','Libiër').
accent('Libiers','Libiërs').
accent(lieren,liëren).
accent(linkerknieen,linkerknieën).
accent(litanieen,litanieën).
accent(liturgieen,liturgieën).
accent(lobbieen,lobbieën).
accent(loss,löss).
accent(luchtactien,luchtactiën).
accent(luchtaktien,luchtaktiën).
accent(luchtvaartindustrieen,luchtvaartindustrieën).
accent('Macedonier','Macedoniër').
accent('Macedoniers','Macedoniërs').
accent(machinerieen,machinerieën).
accent(machtsvacuum,machtsvacuüm).
accent(magier,magiër).
accent(magiers,magiërs).
accent(mais,maïs).
accent(maitresse,maîtresse).
accent(maitressen,maîtressen).
accent(maitresses,maîtresses).
accent(maizena,maïzena).
accent(manicheeer,manicheeër).
accent(manicheeers,manicheeërs).
accent(manieen,manieën).
accent(maoistische,maoïstische).
accent(maoistisch,maoïstisch).
accent(markteconomieen,markteconomieën).
accent(materiele,materiële).
accent(materieler,materiëler).
accent(materien,materiën).
accent(meditatien,meditatiën).
accent(meediscussieren,meediscussiëren).
accent(megamoskeeen,megamoskeeën).
accent(melodieen,melodieën).
accent(menage,ménage).
accent(mensenrechtensituatien,mensenrechtensituatiën).
accent(metaalindustrieen,metaalindustrieën).
accent(milieuhygiene,milieuhygiëne).
accent(milieuhygienische,milieuhygiënische).
accent(milieuhygienisch,milieuhygiënisch).
accent(miltvuurbacterien,miltvuurbacteriën).
accent(ministeriele,ministeriële).
accent(misere,misère).
accent(miseres,misères).
accent(missien,missiën).
accent(modefotografieen,modefotografieën).
accent(moee,moeë).
accent(moeere,moeëre).
accent(moeer,moeër).
accent(monarchieen,monarchieën).
accent(mongoloide,mongoloïde).
accent(mongoloid,mongoloïd).
accent(monografieen,monografieën).
accent(monopolien,monopoliën).
accent(moskeeen,moskeeën).
accent(mozaieken,mozaïeken).
accent(mozaiek,mozaïek).
accent(mummien,mummiën).
accent(muziekcafe,muziekcafé).
accent('muziekcafe\'s','muziekcafé\'s').
accent(muziekcafes,muziekcafés).
accent(muziekindustrieen,muziekindustrieën).
accent(muziektherapieen,muziektherapieën).
accent(myeloide,myeloïde).
accent(mysterien,mysteriën).
accent(mythologieen,mythologieën).
accent(naief,naïef).
accent(naiefste,naïefste).
accent(naiefst,naïefst).
accent(naieve,naïeve).
accent(naievere,naïevere).
accent(naiever,naïever).
accent(naiviteiten,naïviteiten).
accent(naiviteit,naïviteit).
accent(natien,natiën).
accent('Navo-actien','Navo-actiën').
accent('Navoactien','Navoactiën').
accent('NAVO-actien','NAVO-actiën').
accent('NAVOactien','NAVOactiën').
accent('Navo-aktien','Navo-aktiën').
accent('Navoaktien','Navoaktiën').
accent('NAVO-aktien','NAVO-aktiën').
accent('NAVOaktien','NAVOaktiën').
accent(naweeen,naweeën).
accent(netcoordinaat,netcoördinaat).
accent(netcoordinaten,netcoördinaten).
accent(neurieen,neurieën).
accent(neurien,neuriën).
accent('niet-essentiele','niet-essentiële').
accent(nieuwjaarsreceptien,nieuwjaarsreceptiën).
accent(noodsituatien,noodsituatiën).
accent(notariele,notariële).
accent('Oekraiense','Oekraïense').
accent('Oekraiens','Oekraïens').
accent('Oekrainer','Oekraïner').
accent('Oekrainers','Oekraïners').
accent(officiele,officiële).
accent(officieler,officiëler).
accent(oke,oké).
accent('olie-industrieen','olie-industrieën').
accent(olien,oliën).
accent(onderwijsinspectien,onderwijsinspectiën).
accent(onderzeeer,onderzeeër).
accent(onderzeeers,onderzeeërs).
accent(ongeevenaarde,ongeëvenaarde).
accent(ongeevenaard,ongeëvenaard).
accent(ongeinteresseerde,ongeïnteresseerde).
accent(ongeinteresseerdere,ongeïnteresseerdere).
accent(ongeinteresseerder,ongeïnteresseerder).
accent(ongeinteresseerd,ongeïnteresseerd).
accent(ongeinteresseerdste,ongeïnteresseerdste).
accent(ongeinteresseerdst,ongeïnteresseerdst).
accent(oorlogssituatien,oorlogssituatiën).
accent(openingsceremonien,openingsceremoniën).
accent(opgeeiste,opgeëiste).
accent(opgeeist,opgeëist).
accent(oranjerieen,oranjerieën).
accent(orchideeen,orchideeën).
accent(ordonnantien,ordonnantiën).
accent(ore,öre).
accent(organisatiecomite,organisatiecomité).
accent('organisatiecomite\'s','organisatiecomité\'s').
accent(organisatiecomites,organisatiecomités).
accent(orgieen,orgieën).
accent(orgien,orgiën).
accent(orientaalse,oriëntaalse).
accent('Orientaalse','Oriëntaalse').
accent(orientaals,oriëntaals).
accent('Orientaals','Oriëntaals').
accent(orientatie,oriëntatie).
accent(orientaties,oriëntaties).
accent(orienteerden,oriënteerden).
accent(orienteerde,oriënteerde).
accent(orienteer,oriënteer).
accent(orienteert,oriënteert).
accent(orienteren,oriënteren).
accent(overgeerfde,overgeërfde).
accent(overgeerfd,overgeërfd).
accent(overheidsfinancien,overheidsfinanciën).
accent(overlegeconomieen,overlegeconomieën).
accent(pacificatien,pacificatiën).
accent(pacifikatien,pacifikatiën).
accent(paranoide,paranoïde).
accent(parlementarier,parlementariër).
accent(parlementariers,parlementariërs).
accent(parochien,parochiën).
accent(parodieen,parodieën).
accent(partiele,partiële).
accent(partieler,partiëler).
accent(passe,passé).
accent(pastorieen,pastorieën).
accent(pate,pâté).
accent('pate\'s','pâté\'s').
accent(pates,pâtés).
accent(patienten,patiënten).
accent(patientenservice,patiëntenservice).
accent(patientenzorg,patiëntenzorg).
accent(patiente,patiënte).
accent(patientes,patiëntes).
accent(patient,patiënt).
accent(peeen,peeën).
accent(pere,père).
accent(periferieen,periferieën).
accent(persfotografieen,persfotografieën).
accent(personifieren,personifiëren).
accent(petitien,petitiën).
accent(piece,pièce).
accent(planetoiden,planetoïden).
accent(planetoide,planetoïde).
accent(platenindustrieen,platenindustrieën).
accent(poeet,poëet).
accent(poesie,poésie).
accent(poeten,poëten).
accent(poetische,poëtische).
accent(poetischere,poëtischere).
accent(poetischer,poëtischer).
accent(poetisch,poëtisch).
accent(poetischte,poëtischte).
accent(poetischt,poëtischt).
accent(poezie,poëzie).
accent(politieactien,politieactiën).
accent(politieaktien,politieaktiën).
accent(politieserien,politieseriën).
accent(poolcoordinaat,poolcoördinaat).
accent(poolcoordinaten,poolcoördinaten).
accent(porien,poriën).
accent(potentielen,potentiëlen).
accent(potentiele,potentiële).
accent('pousse-cafe','pousse-café').
accent(poussecafe,poussecafé).
accent(prairien,prairiën).
accent(praktijktheorieen,praktijktheorieën).
accent(preferentiele,preferentiële).
accent(prehistorien,prehistoriën).
accent(premiere,première).
accent(premieres,premières).
accent(pre,pré).
accent(presidentiele,presidentiële).
accent(prielen,priëlen).
accent(principiele,principiële).
accent(principieler,principiëler).
accent(privebezit,privébezit).
accent(privedetective,privédetective).
accent(privedetectives,privédetectives).
accent('prive-klinieken','privé-klinieken').
accent(priveklinieken,privéklinieken).
accent('prive-kliniek','privé-kliniek').
accent(privekliniek,privékliniek).
accent('prive-leven','privé-leven').
accent(priveleven,privéleven).
accent('prive-levens','privé-levens').
accent(privelevens,privélevens).
accent(prive,privé).
accent(probleemsituatien,probleemsituatiën).
accent(procede,procédé).
accent('procede\'s','procédé\'s').
accent(procedes,procédés).
accent(profetieen,profetieën).
accent(proletarier,proletariër).
accent(proletariers,proletariërs).
accent(prostituee,prostituée).
accent(prostituees,prostituées).
accent(protestactien,protestactiën).
accent(protestaktien,protestaktiën).
accent(provincien,provinciën).
accent(prozaische,prozaïsche).
accent(prozaisch,prozaïsch).
accent(psychotherapieen,psychotherapieën).
accent(rabies,rabiës).
accent(rais,raïs).
accent(realityserien,realityseriën).
accent(rebellieen,rebellieën).
accent(receptien,receptiën).
accent(rechterknieen,rechterknieën).
accent(recreeerden,recreëerden).
accent(recreeerde,recreëerde).
accent(recreeer,recreëer).
accent(recreeert,recreëert).
accent(recreeren,recreëren).
accent(reddingsactien,reddingsactiën).
accent(reddingsaktien,reddingsaktiën).
accent(reeel,reëel).
accent(reeelste,reëelste).
accent(reeelst,reëelst).
accent(reeen,reeën).
accent(reele,reële).
accent(reelere,reëlere).
accent(reeler,reëler).
accent(referendumcomite,referendumcomité).
accent('referendumcomite\'s','referendumcomité\'s').
accent(referendumcomites,referendumcomités).
accent(referentien,referentiën).
accent('regeringen-Schroder','regeringen-Schröder').
accent('regering-Schroder','regering-Schröder').
accent(regiocoordinatoren,regiocoördinatoren).
accent(regiocoordinator,regiocoördinator).
accent(reincarnatie,reïncarnatie).
accent(reincarnaties,reïncarnaties).
accent(reintegratiebedrijfje,reïntegratiebedrijfje).
accent(reintegratiebedrijfjes,reïntegratiebedrijfjes).
accent(reintegratiebedrijf,reïntegratiebedrijf).
accent(reintegratiebedrijven,reïntegratiebedrijven).
accent(reintegratie,reïntegratie).
accent(reintegreerden,reïntegreerden).
accent(reintegreerde,reïntegreerde).
accent(reintegreer,reïntegreer).
accent(reintegreert,reïntegreert).
accent(reintegreren,reïntegreren).
accent(relativiteitstheorieen,relativiteitstheorieën).
accent(relief,reliëf).
accent(reliefs,reliëfs).
accent(religien,religiën).
accent(relikwieen,relikwieën).
accent(repatrieren,repatriëren).
accent(repatriering,repatriëring).
accent(resume,resumé).
accent(resumes,resumés).
accent(reumapatienten,reumapatiënten).
accent(reumapatiente,reumapatiënte).
accent(reumapatientes,reumapatiëntes).
accent(reumapatient,reumapatiënt).
accent(reunieen,reünieën).
accent(reunie,reünie).
accent(rijksinspectien,rijksinspectiën).
accent(rontgenfoto,röntgenfoto).
accent('rontgenfoto\'s','röntgenfoto\'s').
accent(rontgenstraling,röntgenstraling).
accent(rose,rosé).
accent('rose\'s','rosé\'s').
accent(roses,rosés).
accent(rotsituatien,rotsituatiën).
accent('rsi-patienten','rsi-patiënten').
accent('RSI-patienten','RSI-patiënten').
accent('rsi-patient','rsi-patiënt').
accent('RSI-patient','RSI-patiënt').
accent(rucksichtlose,rücksichtlose).
accent(rucksichtlos,rücksichtlos).
accent(rucksichtslose,rücksichtslose).
accent(rucksichtslos,rücksichtslos).
accent(ruineerden,ruïneerden).
accent(ruineerde,ruïneerde).
accent(ruineer,ruïneer).
accent(ruineert,ruïneert).
accent(ruinen,ruïnen).
accent(ruineren,ruïneren).
accent(ruine,ruïne).
accent(ruines,ruïnes).
accent(ruzieen,ruzieën).
accent(ruzien,ruziën).
accent(sacristieen,sacristieën).
accent(sakristieen,sakristieën).
accent(salariering,salariëring).
accent('Saoedier','Saoediër').
accent('Saoediers','Saoediërs').
accent('Sars-epidemieen','Sars-epidemieën').
accent('Scandinavier','Scandinaviër').
accent('Scandinaviers','Scandinaviërs').
accent(scene,scène).
accent(scenes,scènes).
accent(schizoide,schizoïde).
accent(sectien,sectiën).
accent(sektien,sektiën).
accent(senor,señor).
accent(serien,seriën).
accent('Servier','Serviër').
accent('Serviers','Serviërs').
accent(sierra,siërra).
accent('sierra\'s','siërra\'s').
accent(siesta,siësta).
accent('siesta\'s','siësta\'s').
accent(situatien,situatiën).
accent(skien,skiën).
accent(skier,skiër).
accent(skiers,skiërs).
accent(sleeen,sleeën).
accent(slotscene,slotscène).
accent(slotscenes,slotscènes).
accent(sluitingsceremonien,sluitingsceremoniën).
accent(smeuige,smeuïge).
accent(smeuig,smeuïg).
accent(sneeen,sneeën).
accent(soapserien,soapseriën).
accent(societeiten,sociëteiten).
accent(societeit,sociëteit).
accent(solocarriere,solocarrière).
accent(solocarrieres,solocarrières).
accent('Somalier','Somaliër').
accent('Somaliers','Somaliërs').
accent(specificatien,specificatiën).
accent(specifikatien,specifikatiën).
accent(spraaktechnologieen,spraaktechnologieën).
accent(staalindustrieen,staalindustrieën).
accent(steeen,steeën).
accent(stoicijnsere,stoïcijnsere).
accent(stoicijnser,stoïcijnser).
accent(stoicijnse,stoïcijnse).
accent(stoicijns,stoïcijns).
accent(stoicijnste,stoïcijnste).
accent(stoicijnst,stoïcijnst).
accent(stookolien,stookoliën).
accent(strategieen,strategieën).
accent(studien,studiën).
accent(subsidieren,subsidiëren).
accent(subsidiering,subsidiëring).
accent(substantiele,substantiële).
accent(suede,suède).
accent(surseance,surséance).
accent(symfonieen,symfonieën).
accent(sympathieen,sympathieën).
accent(sympatieen,sympatieën).
accent(symphatieen,symphatieën).
accent('Syriers','Syriërs').
accent('Syrier','Syriër').
accent(systeemtheorieen,systeemtheorieën).
accent(taaltechnologieen,taaltechnologieën).
accent(tabaksindustrieen,tabaksindustrieën).
accent(tatoeeerden,tatoeëerden).
accent(tatoeeerde,tatoeëerde).
accent(tatoeeer,tatoeëer).
accent(tatoeeert,tatoeëert).
accent(tatoeeren,tatoeëren).
accent(taxatien,taxatiën).
accent(taxien,taxiën).
accent(taxonomieen,taxonomieën).
accent(technologieen,technologieën).
accent(teeen,teeën).
accent(tekenfilmserien,tekenfilmseriën).
accent(televisieactien,televisieactiën).
accent(televisieaktien,televisieaktiën).
accent(televisieserien,televisieseriën).
accent(terminologieen,terminologieën).
accent(te,té).
accent(te,tè).
accent(textielindustrieen,textielindustrieën).
accent(theeen,theeën).
accent(theorieen,theorieën).
accent(therapieen,therapieën).
accent(tirannieen,tirannieën).
accent(toegeeigende,toegeëigende).
accent(toegeeigend,toegeëigend).
accent(toeristenindustrieen,toeristenindustrieën).
accent('trace\'s','tracé\'s').
accent(trace,tracé).
accent(tragedien,tragediën).
accent(trainerscarrieres,trainerscarrières).
accent(trainerscarriere,trainerscarrière).
accent(tralien,traliën).
accent(transactien,transactiën).
accent(transaktien,transaktiën).
accent(treeen,treeën).
accent(trilogieen,trilogieën).
accent(trofeeen,trofeeën).
accent('Tunesiers','Tunesiërs').
accent('Tunesier','Tunesiër').
accent('tv-actien','tv-actiën').
accent(tvactien,tvactiën).
accent('TV-actien','TV-actiën').
accent('tv-aktien','tv-aktiën').
accent(tvaktien,tvaktiën).
accent('TV-aktien','TV-aktiën').
accent('tv-serien','tv-seriën').
accent(tvserien,tvseriën).
accent('TV-serien','TV-seriën').
accent(tweeen,tweeën).
accent(tweeerlei,tweeërlei).
accent(uberhaupt,überhaupt).
accent(uitgangssituatien,uitgangssituatiën).
accent(utopieen,utopieën).
accent(vacuum,vacuüm).
accent(varieren,variëren).
accent(varieteiten,variëteiten).
accent(varieteit,variëteit).
accent(vegetariers,vegetariërs).
accent(vegetarier,vegetariër).
accent(veiligheidsmissien,veiligheidsmissiën).
accent(veiligheidssituatien,veiligheidssituatiën).
accent(verbruikerscooperaties,verbruikerscoöperaties).
accent(verbruikerscooperatie,verbruikerscoöperatie).
accent(vergeldingsactien,vergeldingsactiën).
accent(vergeldingsaktien,vergeldingsaktiën).
accent(verifieren,verifiëren).
accent(verkeerssituatien,verkeerssituatiën).
accent(vetoen,vetoën).
accent(vliegtuigindustrieen,vliegtuigindustrieën).
accent(voedingsindustrieen,voedingsindustrieën).
accent(voila,voilà).
accent(volieres,volières).
accent(voliere,volière).
accent(voor,vóór).
accent(vredesmissien,vredesmissiën).
accent(vreeen,vreeën).
accent(vuurzeeen,vuurzeeën).
accent(wapeninspectien,wapeninspectiën).
accent(waterlelien,waterleliën).
accent(waterpoloers,waterpoloërs).
accent(waterpoloer,waterpoloër).
accent(weeen,weeën).
accent(weee,weeë).
accent(weeige,weeïge).
accent(weeig,weeïg).
accent(weggeebde,weggeëbde).
accent(weggeebd,weggeëbd).
accent(wereldeconomieen,wereldeconomieën).
accent(wereldpremieres,wereldpremières).
accent(wereldpremiere,wereldpremière).
accent(werksituatien,werksituatiën).
accent(windenergieen,windenergieën).
accent(wraakactien,wraakactiën).
accent(wraakaktien,wraakaktiën).
accent('Zairees','Zaïrees').
accent('Zairese','Zaïrese').
accent('Zairezen','Zaïrezen').
accent(zeeen,zeeën).
accent(zelfmoordactien,zelfmoordactiën).
accent(zelfmoordaktien,zelfmoordaktiën).
accent(zelfstudien,zelfstudiën).
accent(zoekactien,zoekactiën).
accent(zoekaktien,zoekaktiën).
accent(zoeven,zoëven).
accent('zonne-energieen','zonne-energieën').
