with_dt_all('00',['2500',de,de,en,tussen]).
with_dt_all('0,1',['0,3',de,en,tussen]).
with_dt_all('0',['15',en,tussen]).
with_dt_all('0',['1',en,tussen]).
with_dt_all('0,2',['0,3',de,en,tussen]).
with_dt_all('0,26',['1,8',de,en,tussen]).
with_dt_all('0,49',['1,49',de,en,tussen]).
with_dt_all('\'04',['\'99']).
with_dt_all('0,5',['1',de,en,tussen]).
with_dt_all('0,5',['1',en,tussen]).
with_dt_all('0',['5',en,tussen]).
with_dt_all('100.000',['150.000',de,en,tussen]).
with_dt_all('100.000',['200.000',de,en,tussen]).
with_dt_all('100.000',['200.000',en,tussen]).
with_dt_all('100.000',['500.000',en,tussen]).
with_dt_all('100.000',['50.000',de,en,tussen]).
with_dt_all('100.000',['50.000',en,tussen]).
with_dt_all('100.000',['60.000',de,en,tussen]).
with_dt_all('100.000',['80.000',de,en,tussen]).
with_dt_all('10.000',['15.000',de,en,tussen]).
with_dt_all('10.000',['15.000',en,tussen]).
with_dt_all('10.000',['20.000',de,en,tussen]).
with_dt_all('10.000',['30.000',de,en,tussen]).
with_dt_all('10.000',['5000',de,de,en,tussen]).
with_dt_all('10.000',['5.000',de,en,tussen]).
with_dt_all('10.000',['5000',de,en,tussen]).
with_dt_all('10.000',['7.000',de,en,tussen]).
with_dt_all('10.000',['8.000',de,en,tussen]).
with_dt_all('1000',['1200',de,en,tussen]).
with_dt_all('1000',['1500',de,en,tussen]).
with_dt_all('1000',['2000',de,en,tussen]).
with_dt_all('1000',['3000',de,en,tussen]).
with_dt_all('1000',['500',bij]).
with_dt_all('1000',['500',de,en,tussen]).
with_dt_all('1000',['500',en,tussen]).
with_dt_all('1000',['600',de,en,tussen]).
with_dt_all('1000',['700',de,en,tussen]).
with_dt_all('1000',['800',de,en,tussen]).
with_dt_all('100',['1000',de,en,tussen]).
with_dt_all('100',['100',bij]).
with_dt_all('100',['115',de,en,tussen]).
with_dt_all('100',['120',de,en,tussen]).
with_dt_all('100',['150',de,en,tussen]).
with_dt_all('100',['150',en,tussen]).
with_dt_all('100',['170',de,en,tussen]).
with_dt_all('100',['200',de,en,tussen]).
with_dt_all('100',['250',de,en,tussen]).
with_dt_all('100',['300',de,en,tussen]).
with_dt_all('100',['40',de,en,tussen]).
with_dt_all('100',['500',de,en,tussen]).
with_dt_all('100',['50',de,en,tussen]).
with_dt_all('100',['50',en,tussen]).
with_dt_all('100',['60',de,en,tussen]).
with_dt_all('100',['70',de,en,tussen]).
with_dt_all('100',['75',de,en,tussen]).
with_dt_all('100',['80',de,en,tussen]).
with_dt_all('100',['80',en,tussen]).
with_dt_all('10',['10',bij]).
with_dt_all('10',['11',de,en,tussen]).
with_dt_all('10',['12',de,de,en,tussen]).
with_dt_all('10',['12',de,en,tussen]).
with_dt_all('10',['12',en,tussen]).
with_dt_all('10',['13',de,en,tussen]).
with_dt_all('10',['13',en,tussen]).
with_dt_all('10',['14',de,en,tussen]).
with_dt_all('10',['14',en,tussen]).
with_dt_all('10',['15',bij]).
with_dt_all('10',['15',de,en,tussen]).
with_dt_all('10',['15',en,tussen]).
with_dt_all('10',['20',bij]).
with_dt_all('10',['20',de,de,en,tussen]).
with_dt_all('10',['20',de,en,tussen]).
with_dt_all('10',['20',en,tussen]).
with_dt_all('10',['25',bij]).
with_dt_all('10',['25',en,tussen]).
with_dt_all('10',['2',de,en,tussen]).
with_dt_all('10',['3',bij]).
with_dt_all('10',['40',en,tussen]).
with_dt_all('10',['50',de,en,tussen]).
with_dt_all('10',['50',en,tussen]).
with_dt_all('105',['68',bij]).
with_dt_all('10',['5',de,de,en,tussen]).
with_dt_all('10',['5',de,en,tussen]).
with_dt_all('10',['5',en,tussen]).
with_dt_all('10',['60',de,en,tussen]).
with_dt_all('10',['6',de,en,tussen]).
with_dt_all('10',['6',en,tussen]).
with_dt_all('10',['7',de,en,tussen]).
with_dt_all('10',['7',en,tussen]).
with_dt_all('10',['8',de,en,tussen]).
with_dt_all('10',['9',de,en,tussen]).
with_dt_all('1100',['1400',de,en,tussen]).
with_dt_all('1',['100',en,tussen]).
with_dt_all('110',['80',de,en,tussen]).
with_dt_all('1',['10',en,tussen]).
with_dt_all('11',['11',bij]).
with_dt_all('11',['12',de,en,tussen]).
with_dt_all('11',['12',en,tussen]).
with_dt_all('11',['13',de,en,tussen]).
with_dt_all('11',['13',en,tussen]).
with_dt_all('11',['14',de,en,tussen]).
with_dt_all('11',['14',en,tussen]).
with_dt_all('11',['15',de,en,tussen]).
with_dt_all('11',['15',en,tussen]).
with_dt_all('11',['16',en,tussen]).
with_dt_all('11',['18',de,en,tussen]).
with_dt_all('1',['12',de,en,tussen]).
with_dt_all('11',['2',en,tussen]).
with_dt_all('1',['1,5',bij]).
with_dt_all('1',['1,5',de,en,tussen]).
with_dt_all('1',['1,5',en,tussen]).
with_dt_all('11',['6',en,tussen]).
with_dt_all('11',['8',de,en,tussen]).
with_dt_all('11',['8',en,tussen]).
with_dt_all('11',['9',de,en,tussen]).
with_dt_all('11',['9',en,tussen]).
with_dt_all('1',['1',bij]).
with_dt_all('12.000',['15.000',de,en,tussen]).
with_dt_all('12.000',['5000',en,tussen]).
with_dt_all('12.000',['6000',de,en,tussen]).
with_dt_all('1200',['1300',de,en,tussen]).
with_dt_all('1200',['1400',de,en,tussen]).
with_dt_all('1200',['1600',bij]).
with_dt_all('1200',['600',de,en,tussen]).
with_dt_all('1200',['900',de,en,tussen]).
with_dt_all('1200',[de,duizend,en,tussen]).
with_dt_all('120',['130',en,tussen]).
with_dt_all('120',['150',de,en,tussen]).
with_dt_all('120',['80',de,en,tussen]).
with_dt_all('120',['80',en,tussen]).
with_dt_all('120',['90',de,en,tussen]).
with_dt_all('12',['12',bij]).
with_dt_all('12',['13',de,en,tussen]).
with_dt_all('12',['14',de,en,tussen]).
with_dt_all('1,2',['1,5',de,en,tussen]).
with_dt_all('12',['15',de,en,tussen]).
with_dt_all('12',['15',en,tussen]).
with_dt_all('12',['16',de,en,tussen]).
with_dt_all('12',['16',en,tussen]).
with_dt_all('12',['16°',en,tussen]).
with_dt_all('12',['17',de,en,tussen]).
with_dt_all('12',['18',de,en,tussen]).
with_dt_all('12',['20',de,en,tussen]).
with_dt_all('12',['20',en,tussen]).
with_dt_all('12',['24',de,en,tussen]).
with_dt_all('12',['25',de,en,tussen]).
with_dt_all('12',['30',de,en,tussen]).
with_dt_all('125',['150',de,en,tussen]).
with_dt_all('125',['75',de,en,tussen]).
with_dt_all('12',['6',de,en,tussen]).
with_dt_all('12',['6',en,tussen]).
with_dt_all('12',['7',de,en,tussen]).
with_dt_all('12',['7',en,tussen]).
with_dt_all('12',['8',bij]).
with_dt_all('12',['8',de,en,tussen]).
with_dt_all('12',['8',en,tussen]).
with_dt_all('12',['9',de,en,tussen]).
with_dt_all('12',['9',en,tussen]).
with_dt_all('1',['2',bij]).
with_dt_all('1',['2',de,en,tussen]).
with_dt_all('1',['2',en,tussen]).
with_dt_all('130',['140',de,en,tussen]).
with_dt_all('130',['160',de,en,tussen]).
with_dt_all('13',['14',de,en,tussen]).
with_dt_all('13',['15',de,en,tussen]).
with_dt_all('13',['15',en,tussen]).
with_dt_all('13',['16',de,en,tussen]).
with_dt_all('13',['17',de,en,tussen]).
with_dt_all('13',['17',en,tussen]).
with_dt_all('13',['18',de,en,tussen]).
with_dt_all('13',['18',en,tussen]).
with_dt_all('13',['19',en,tussen]).
with_dt_all('136',[bij,vier]).
with_dt_all('13',['8',de,en,tussen]).
with_dt_all('1',['3',de,en,tussen]).
with_dt_all('1',['3',en,tussen]).
with_dt_all('140',['180',de,en,tussen]).
with_dt_all('14',['15',de,en,tussen]).
with_dt_all('14',['16',de,en,tussen]).
with_dt_all('14',['16',en,tussen]).
with_dt_all('14',['17',de,en,tussen]).
with_dt_all('14',['17',en,tussen]).
with_dt_all('\'14',['\'18']).
with_dt_all('14',['18',de,en,tussen]).
with_dt_all('14',['19',de,en,tussen]).
with_dt_all('14',['20',de,en,tussen]).
with_dt_all('14',['20',en,tussen]).
with_dt_all('14',['21',de,en,tussen]).
with_dt_all('14',['4',bij]).
with_dt_all('14',['5',en,tussen]).
with_dt_all('14',['6',en,tussen]).
with_dt_all('14',['8',de,en,tussen]).
with_dt_all('14',['9',de,en,tussen]).
with_dt_all('14',['9',en,tussen]).
with_dt_all('1',['4',de,en,tussen]).
with_dt_all('1',['4',en,tussen]).
with_dt_all('150.000',['200.000',de,en,tussen]).
with_dt_all('150.000',['200.000',en,tussen]).
with_dt_all('15.000',['20.000',de,en,tussen]).
with_dt_all('15.000',['20.000',en,tussen]).
with_dt_all('15.000',['50.000',en,tussen]).
with_dt_all('1500',['2000',de,en,tussen]).
with_dt_all('1500',[de,duizend,en,tussen]).
with_dt_all('150',['170',de,en,tussen]).
with_dt_all('150',['200',de,en,tussen]).
with_dt_all('150',['200',en,tussen]).
with_dt_all('150',['250',de,en,tussen]).
with_dt_all('150',['250',en,tussen]).
with_dt_all('150',['300',en,tussen]).
with_dt_all('150',['60',de,en,tussen]).
with_dt_all('150',[de,en,honderd,tussen]).
with_dt_all('15',['15',bij]).
with_dt_all('1,5',['1,6',de,en,tussen]).
with_dt_all('15',['16',de,en,tussen]).
with_dt_all('15',['17',de,en,tussen]).
with_dt_all('15',['17',en,tussen]).
with_dt_all('15',['18',de,en,tussen]).
with_dt_all('15',['19',de,en,tussen]).
with_dt_all('15',['20',bij]).
with_dt_all('15',['20',de,de,en,tussen]).
with_dt_all('15',['20',de,en,tussen]).
with_dt_all('15',['20',en,tussen]).
with_dt_all('15',['21',de,en,tussen]).
with_dt_all('15',['22',de,en,tussen]).
with_dt_all('15',['24',de,en,tussen]).
with_dt_all('15',['24',en,tussen]).
with_dt_all('1,5',['2,5',bij]).
with_dt_all('15',['25',bij]).
with_dt_all('15',['25',de,en,tussen]).
with_dt_all('1,5',['2,5',en,tussen]).
with_dt_all('15',['25',en,tussen]).
with_dt_all('1,5',['2',bij]).
with_dt_all('1,5',['2',de,en,tussen]).
with_dt_all('15',['30',de,en,tussen]).
with_dt_all('15',['30',en,tussen]).
with_dt_all('15',['35',en,tussen]).
with_dt_all('15',['40',de,en,tussen]).
with_dt_all('15',['40',en,tussen]).
with_dt_all('15',['49',en,tussen]).
with_dt_all('15',['5',de,en,tussen]).
with_dt_all('15',['5',en,tussen]).
with_dt_all('15',['64',de,de,en,tussen]).
with_dt_all('15',['65',en,tussen]).
with_dt_all('15',['70',de,en,tussen]).
with_dt_all('15',['8',de,en,tussen]).
with_dt_all('1',['5',de,en,tussen]).
with_dt_all('1',['5',en,tussen]).
with_dt_all('16',['17',de,en,tussen]).
with_dt_all('16',['18',de,en,tussen]).
with_dt_all('16',['18',en,tussen]).
with_dt_all('1,6',['1,9',de,en,tussen]).
with_dt_all('16',['19',de,en,tussen]).
with_dt_all('16',['20',de,en,tussen]).
with_dt_all('16',['20',en,tussen]).
with_dt_all('16',['21',de,en,tussen]).
with_dt_all('16',['22',de,en,tussen]).
with_dt_all('16',['22',en,tussen]).
with_dt_all('16',['23',de,en,tussen]).
with_dt_all('16',['24',de,en,tussen]).
with_dt_all('16',['24',en,tussen]).
with_dt_all('16',['25',de,en,tussen]).
with_dt_all('16',['25',en,tussen]).
with_dt_all('16',['26',en,tussen]).
with_dt_all('16',['8',de,en,tussen]).
with_dt_all('16',['9',bij]).
with_dt_all('16',['9',de,en,tussen]).
with_dt_all('1700',['2200',de,en,tussen]).
with_dt_all('17',['18',de,en,tussen]).
with_dt_all('17',['19',de,en,tussen]).
with_dt_all('17',['20',de,en,tussen]).
with_dt_all('17',['21',de,en,tussen]).
with_dt_all('17',['22',de,en,tussen]).
with_dt_all('17',['22',en,tussen]).
with_dt_all('17',['23',de,en,tussen]).
with_dt_all('17',['23',en,tussen]).
with_dt_all('18',['19',de,en,tussen]).
with_dt_all('18',['20',de,en,tussen]).
with_dt_all('18',['20',en,tussen]).
with_dt_all('18',['21',de,en,tussen]).
with_dt_all('18',['21',en,tussen]).
with_dt_all('18',['22',de,en,tussen]).
with_dt_all('18',['22',en,tussen]).
with_dt_all('18',['23',de,en,tussen]).
with_dt_all('18',['24',de,en,tussen]).
with_dt_all('18',['24',en,tussen]).
with_dt_all('18',['25',de,en,tussen]).
with_dt_all('18',['25',en,tussen]).
with_dt_all('18',['30',de,en,tussen]).
with_dt_all('18',['30',en,tussen]).
with_dt_all('18',['34',de,en,tussen]).
with_dt_all('18',['35',de,en,tussen]).
with_dt_all('18',['35',en,tussen]).
with_dt_all('1880',['1890']).
with_dt_all('1880',['1914']).
with_dt_all('1889',['1936']).
with_dt_all('1890',['1950']).
with_dt_all('1900',['1939']).
with_dt_all('1900',['1940']).
with_dt_all('1903',['2003']).
with_dt_all('1914',['1918']).
with_dt_all('1919',['1999']).
with_dt_all('1920',['1930']).
with_dt_all('1920',['1945']).
with_dt_all('19',['22',de,en,tussen]).
with_dt_all('19',['23',de,en,tussen]).
with_dt_all('19',['23',en,tussen]).
with_dt_all('19',['24',de,en,tussen]).
with_dt_all('19',['24',en,tussen]).
with_dt_all('19',['25',de,en,tussen]).
with_dt_all('19',['28',de,en,tussen]).
with_dt_all('1936',['1939']).
with_dt_all('1936',['1956']).
with_dt_all('1940',['1945']).
with_dt_all('1941',['1945']).
with_dt_all('1944',['1945']).
with_dt_all('1945',['1965']).
with_dt_all('1945',['2000']).
with_dt_all('1948',['1952']).
with_dt_all('1950',['1973']).
with_dt_all('1950',['1980']).
with_dt_all('1950',['2000']).
with_dt_all('1955',['1995']).
with_dt_all('1957',['1968']).
with_dt_all('1960',['1961']).
with_dt_all('1960',['1989']).
with_dt_all('1965',['1967']).
with_dt_all('1965',['1975']).
with_dt_all('1966',['2003']).
with_dt_all('1970',['1980']).
with_dt_all('1970',['1995']).
with_dt_all('1977',['1978']).
with_dt_all('1977',['1981']).
with_dt_all('1979',['1980']).
with_dt_all('1980',['1988']).
with_dt_all('1980',['1990']).
with_dt_all('1980',['1993']).
with_dt_all('1980',['2000']).
with_dt_all('1985',['1986']).
with_dt_all('1985',['1989']).
with_dt_all('1985',['1995']).
with_dt_all('1989',['1991']).
with_dt_all('1989',['1995']).
with_dt_all('1990',['1991']).
with_dt_all('1990',['1993']).
with_dt_all('1990',['1995']).
with_dt_all('1990',['1996']).
with_dt_all('1990',['2002']).
with_dt_all('1991',['1992']).
with_dt_all('1991',['1993']).
with_dt_all('1991',['1995']).
with_dt_all('1991',['1996']).
with_dt_all('1991',['2003']).
with_dt_all('1992',['1993']).
with_dt_all('1992',['1994']).
with_dt_all('1992',['1995']).
with_dt_all('1992',['1996']).
with_dt_all('1992',['2002']).
with_dt_all('1993',['1994']).
with_dt_all('1993',['2003']).
with_dt_all('1994',['1995']).
with_dt_all('1994',['1996']).
with_dt_all('1994',['1998']).
with_dt_all('1994',['1999']).
with_dt_all('1995',['1996']).
with_dt_all('1995',['2000']).
with_dt_all('1995',['2001']).
with_dt_all('1995',['2005']).
with_dt_all('1996',['1997']).
with_dt_all('1996',['2000']).
with_dt_all('1996',['2001']).
with_dt_all('1996',['2002']).
with_dt_all('1996',['2003']).
with_dt_all('1996',['2009']).
with_dt_all('1997',['1998']).
with_dt_all('1997',['2000']).
with_dt_all('1997',['2001']).
with_dt_all('1997',['2002']).
with_dt_all('1998',['1999']).
with_dt_all('1998',['2000']).
with_dt_all('1998',['2001']).
with_dt_all('1998',['2002']).
with_dt_all('1998',['2003']).
with_dt_all('1999',['2000']).
with_dt_all('1999',['2001']).
with_dt_all('1999',['2002']).
with_dt_all('1999',['2003']).
with_dt_all('1e',[klas]).
with_dt_all('1e',[klasse]).
with_dt_all('200.000',['300.000',de,en,tussen]).
with_dt_all('200.000',['400.000',de,en,tussen]).
with_dt_all('20.000',['25.000',de,en,tussen]).
with_dt_all('20.000',['30.000',de,en,tussen]).
with_dt_all('20.000',['40.000',de,en,tussen]).
with_dt_all('20.000',['50.000',de,en,tussen]).
with_dt_all('2000',['2001']).
with_dt_all('2000',['2002']).
with_dt_all('2000',['2003']).
with_dt_all('2000',['2004']).
with_dt_all('2000',['2005']).
with_dt_all('2000',['2006']).
with_dt_all('2000',['2007']).
with_dt_all('2000',['2009']).
with_dt_all('2000',['2010']).
with_dt_all('2000',['2500',de,en,tussen]).
with_dt_all('2.000',['3.000',de,en,tussen]).
with_dt_all('2000',['3000',de,en,tussen]).
with_dt_all('2.000',['4.000',de,en,tussen]).
with_dt_all('2000',['4000',de,en,tussen]).
with_dt_all('2000',[en,nu,tussen]).
with_dt_all('2001',['2002']).
with_dt_all('2001',['2003']).
with_dt_all('2001',['2004']).
with_dt_all('2001',['2006']).
with_dt_all('2002',['2003']).
with_dt_all('2002',['2006']).
with_dt_all('200',['220',de,en,tussen]).
with_dt_all('200',['250',de,en,tussen]).
with_dt_all('200',['250',en,tussen]).
with_dt_all('2002',[en,nu,tussen]).
with_dt_all('200',['300',de,de,en,tussen]).
with_dt_all('200',['300',de,en,tussen]).
with_dt_all('200',['300',en,tussen]).
with_dt_all('2003',['2004']).
with_dt_all('2003',[en,nu,tussen]).
with_dt_all('200',['400',de,en,tussen]).
with_dt_all('200',['400',en,tussen]).
with_dt_all('2004',['2005']).
with_dt_all('2004',['2006']).
with_dt_all('2004',[en,nu,tussen]).
with_dt_all('200',['500',de,en,tussen]).
with_dt_all('200',['500',en,tussen]).
with_dt_all('200',['50',de,en,tussen]).
with_dt_all('2005',['2006']).
with_dt_all('2005',['2007']).
with_dt_all('2005',['2008']).
with_dt_all('2005',['2009']).
with_dt_all('2005',['2010']).
with_dt_all('2005',[en,nu,tussen]).
with_dt_all('2006',['2007']).
with_dt_all('2006',['2009']).
with_dt_all('2007',['2008']).
with_dt_all('2007',['2009']).
with_dt_all('200',['75',de,en,tussen]).
with_dt_all('2007',[en,nu,tussen]).
with_dt_all('2008',['2009']).
with_dt_all('2008',['2012']).
with_dt_all('2008',[en,nu,tussen]).
with_dt_all('2009',['2010']).
with_dt_all('2010',['2011']).
with_dt_all('2010',['2030']).
with_dt_all('2010',[en,nu,tussen]).
with_dt_all('2011',['2012']).
with_dt_all('2012',['2013']).
with_dt_all('2013',['2014']).
with_dt_all('2014',['2015']).
with_dt_all('2014',['2018']).
with_dt_all('2015',['2016']).
with_dt_all('20',['20',bij]).
with_dt_all('2020',[en,nu,tussen]).
with_dt_all('20',['21',de,en,tussen]).
with_dt_all('20',['22',de,en,tussen]).
with_dt_all('20',['23',de,en,tussen]).
with_dt_all('20',['24',de,en,tussen]).
with_dt_all('20',['24',en,tussen]).
with_dt_all('20',['25',bij]).
with_dt_all('20',['25',de,de,en,tussen]).
with_dt_all('20',['25',de,en,tussen]).
with_dt_all('20',['25',en,tussen]).
with_dt_all('20',['26',de,en,tussen]).
with_dt_all('20',['28',de,en,tussen]).
with_dt_all('20',['30',bij]).
with_dt_all('20',['30',de,de,en,tussen]).
with_dt_all('20',['30',de,en,tussen]).
with_dt_all('20',['30',en,tussen]).
with_dt_all('20',['35',de,de,en,tussen]).
with_dt_all('20',['35',de,en,tussen]).
with_dt_all('20',['35',en,tussen]).
with_dt_all('20',['40',bij]).
with_dt_all('20',['40',de,de,en,tussen]).
with_dt_all('20',['40',de,en,tussen]).
with_dt_all('20',['40',en,tussen]).
with_dt_all('20',['49',en,tussen]).
with_dt_all('20',['50',bij]).
with_dt_all('20',['50',de,en,tussen]).
with_dt_all('2050',[en,nu,tussen]).
with_dt_all('20',['5',de,en,tussen]).
with_dt_all('20',['5',en,tussen]).
with_dt_all('20',['60',de,en,tussen]).
with_dt_all('20',['60',en,tussen]).
with_dt_all('21/2',['41/2',bij]).
with_dt_all('21',['25',de,en,tussen]).
with_dt_all('21',['28',de,en,tussen]).
with_dt_all('21',['30',en,tussen]).
with_dt_all('220',['40',bij]).
with_dt_all('22',['24',de,en,tussen]).
with_dt_all('22',['25',de,en,tussen]).
with_dt_all('22',['25',en,tussen]).
with_dt_all('22',['26',de,en,tussen]).
with_dt_all('22',['27',de,en,tussen]).
with_dt_all('22',['27',en,tussen]).
with_dt_all('22',['28',de,en,tussen]).
with_dt_all('22',['28',en,tussen]).
with_dt_all('22',['29',de,en,tussen]).
with_dt_all('22',['33',de,en,tussen]).
with_dt_all('22',['35',de,en,tussen]).
with_dt_all('2250',['500',en,tussen]).
with_dt_all('2',['2,5',de,en,tussen]).
with_dt_all('2',['2,5',en,tussen]).
with_dt_all('22',['6',en,tussen]).
with_dt_all('22',['8',bij]).
with_dt_all('2',['2',bij]).
with_dt_all('23',['26',de,en,tussen]).
with_dt_all('23',['27',en,tussen]).
with_dt_all('23',['28',en,tussen]).
with_dt_all('23',['29',en,tussen]).
with_dt_all('2',['3',bij]).
with_dt_all('2',['3',de,de,en,tussen]).
with_dt_all('2',['3',de,en,tussen]).
with_dt_all('2',['3',en,tussen]).
with_dt_all('24',['27',de,en,tussen]).
with_dt_all('24',['28',de,en,tussen]).
with_dt_all('24',['29',de,en,tussen]).
with_dt_all('24',['30',de,en,tussen]).
with_dt_all('24',['8',de,en,tussen]).
with_dt_all('24',[achttien,de,en,tussen]).
with_dt_all('2',['4',de,en,tussen]).
with_dt_all('2',['4',en,tussen]).
with_dt_all('250.000',['300.000',de,en,tussen]).
with_dt_all('250.000',['500.000',de,en,tussen]).
with_dt_all('25.000',['30.000',de,en,tussen]).
with_dt_all('25000',['30000',de,en,tussen]).
with_dt_all('25.000',['40.000',de,en,tussen]).
with_dt_all('2.500',['3.000',de,en,tussen]).
with_dt_all('2500',['3000',de,en,tussen]).
with_dt_all('2500',['3000',en,tussen]).
with_dt_all('2500',['5000',de,en,tussen]).
with_dt_all('250',['300',de,en,tussen]).
with_dt_all('250',['400',de,en,tussen]).
with_dt_all('250',['40',bij]).
with_dt_all('250',['50',de,en,tussen]).
with_dt_all('2,5',['2,5',bij]).
with_dt_all('25',['25',bij]).
with_dt_all('25',['27',en,tussen]).
with_dt_all('25',['30',de,de,en,tussen]).
with_dt_all('25',['30',de,en,tussen]).
with_dt_all('25',['30',en,tussen]).
with_dt_all('25',['33',de,en,tussen]).
with_dt_all('25',['34',en,tussen]).
with_dt_all('25',['35',de,de,en,tussen]).
with_dt_all('25',['35',de,en,tussen]).
with_dt_all('25',['35',en,tussen]).
with_dt_all('2,5',['3',bij]).
with_dt_all('2,5',['3',de,en,tussen]).
with_dt_all('2,5',['3',en,tussen]).
with_dt_all('25',['40',bij]).
with_dt_all('25',['40',de,en,tussen]).
with_dt_all('25',['40',en,tussen]).
with_dt_all('2,5',['4,5',bij]).
with_dt_all('25',['45',en,tussen]).
with_dt_all('2,5',['4',bij]).
with_dt_all('25',['50',de,en,tussen]).
with_dt_all('25',['50',en,tussen]).
with_dt_all('2',['5',bij]).
with_dt_all('2',['5',de,en,tussen]).
with_dt_all('25',[de,en,tussen,twintig]).
with_dt_all('25',[de,en,tussen,vijftien]).
with_dt_all('2',['5',en,tussen]).
with_dt_all('26',['33',de,en,tussen]).
with_dt_all('2',['6',bij]).
with_dt_all('2',['6',de,en,tussen]).
with_dt_all('270',['300',de,en,tussen]).
with_dt_all('27',['32',de,en,tussen]).
with_dt_all('28',['30',de,en,tussen]).
with_dt_all('28',['32',de,en,tussen]).
with_dt_all('28',['35',de,en,tussen]).
with_dt_all('2',['9',en,tussen]).
with_dt_all('2e',[klas]).
with_dt_all('2e',[klasse]).
with_dt_all('300.000',['400.000',de,en,tussen]).
with_dt_all('300.000',['500.000',de,en,tussen]).
with_dt_all('30.000',['40.000',de,en,tussen]).
with_dt_all('30.000',['50.000',en,tussen]).
with_dt_all('3000',['3500',de,en,tussen]).
with_dt_all('3000',['4000',de,en,tussen]).
with_dt_all('3000',['4000',en,tussen]).
with_dt_all('3.000',['5.000',de,en,tussen]).
with_dt_all('3000',['5000',de,en,tussen]).
with_dt_all('300',['350',de,en,tussen]).
with_dt_all('300',['400',de,en,tussen]).
with_dt_all('300',['400',en,tussen]).
with_dt_all('300',['500',de,en,tussen]).
with_dt_all('300',['600',de,en,tussen]).
with_dt_all('30',['30',bij]).
with_dt_all('30',['34',de,en,tussen]).
with_dt_all('30',['35',de,en,tussen]).
with_dt_all('30',['35',en,tussen]).
with_dt_all('30',['36',de,en,tussen]).
with_dt_all('30',['38',de,en,tussen]).
with_dt_all('30',['40',bij]).
with_dt_all('30',['40',de,de,en,tussen]).
with_dt_all('30',['40',de,en,tussen]).
with_dt_all('30',['40',en,tussen]).
with_dt_all('30',['45',de,en,tussen]).
with_dt_all('30',['50',de,de,en,tussen]).
with_dt_all('30',['50',de,en,tussen]).
with_dt_all('30',['50',en,tussen]).
with_dt_all('30',['60',bij]).
with_dt_all('30',['60',de,en,tussen]).
with_dt_all('30',['60',en,tussen]).
with_dt_all('30',['70',de,en,tussen]).
with_dt_all('30',['80',en,tussen]).
with_dt_all('30',['90',de,en,tussen]).
with_dt_all('31',['42',de,en,tussen]).
with_dt_all('320',['480',bij]).
with_dt_all('33',['37',de,en,tussen]).
with_dt_all('3',['3,5',en,tussen]).
with_dt_all('3',['3',bij]).
with_dt_all('34',['42',de,en,tussen]).
with_dt_all('3',['4',bij]).
with_dt_all('3',['4',de,en,tussen]).
with_dt_all('3',['4',en,tussen]).
with_dt_all('35.000',['40.000',de,en,tussen]).
with_dt_all('35.000',['50.000',de,en,tussen]).
with_dt_all('3.500',['4.000',de,en,tussen]).
with_dt_all('350',['400',de,en,tussen]).
with_dt_all('350',['500',de,en,tussen]).
with_dt_all('350',['500',en,tussen]).
with_dt_all('35',['35',bij]).
with_dt_all('35',['39',de,en,tussen]).
with_dt_all('35',['40',de,en,tussen]).
with_dt_all('35',['45',de,en,tussen]).
with_dt_all('35',['45',en,tussen]).
with_dt_all('35',['49',en,tussen]).
with_dt_all('3,5',['4',de,en,tussen]).
with_dt_all('35',['50',de,en,tussen]).
with_dt_all('35',['50',en,tussen]).
with_dt_all('35',['55',de,en,tussen]).
with_dt_all('35',['55',en,tussen]).
with_dt_all('35',['60',de,en,tussen]).
with_dt_all('3',['5',bij]).
with_dt_all('3',['5',de,de,en,tussen]).
with_dt_all('3',['5',de,en,tussen]).
with_dt_all('3',['5',en,tussen]).
with_dt_all('36',['39',de,en,tussen]).
with_dt_all('3',['6,5',bij]).
with_dt_all('3',['6',bij]).
with_dt_all('3',['6',de,en,tussen]).
with_dt_all('3',['6',en,tussen]).
with_dt_all('37',['38,8',de,en,tussen]).
with_dt_all('37',['38,8',en,tussen]).
with_dt_all('3',['7',en,tussen]).
with_dt_all('3',['8',en,tussen]).
with_dt_all('3e',[klas]).
with_dt_all('3e',[klasse]).
with_dt_all('400.000',['500.000',de,en,tussen]).
with_dt_all('400.000',['500.000',en,tussen]).
with_dt_all('40.000',['50.000',de,en,tussen]).
with_dt_all('40.000',['60.000',de,en,tussen]).
with_dt_all('40.000',['70.000',de,en,tussen]).
with_dt_all('4000',['5000',de,en,tussen]).
with_dt_all('4000',['6000',de,en,tussen]).
with_dt_all('4000',['6000',en,tussen]).
with_dt_all('400',['400',bij]).
with_dt_all('400',['500',de,en,tussen]).
with_dt_all('400',['600',de,en,tussen]).
with_dt_all('400',['800',en,tussen]).
with_dt_all('40',['40',bij]).
with_dt_all('\'40',['\'45']).
with_dt_all('40',['45',de,en,tussen]).
with_dt_all('40',['45',en,tussen]).
with_dt_all('40',['50',bij]).
with_dt_all('40',['50',de,de,en,tussen]).
with_dt_all('40',['50',de,en,tussen]).
with_dt_all('40',['50',en,tussen]).
with_dt_all('40',['5',de,en,tussen]).
with_dt_all('40',['60',bij]).
with_dt_all('40',['60',de,en,tussen]).
with_dt_all('40',['60',en,tussen]).
with_dt_all('40',['80',bij]).
with_dt_all('4',['4',bij]).
with_dt_all('45.000',['50.000',de,en,tussen]).
with_dt_all('450',['500',de,en,tussen]).
with_dt_all('45',['50',de,en,tussen]).
with_dt_all('45',['50',en,tussen]).
with_dt_all('45',['55',de,en,tussen]).
with_dt_all('45',['55',en,tussen]).
with_dt_all('45',['60',de,en,tussen]).
with_dt_all('4',['5',bij]).
with_dt_all('4',['5',de,en,tussen]).
with_dt_all('4',['5',en,tussen]).
with_dt_all('4',['6',bij]).
with_dt_all('4',['6',de,en,tussen]).
with_dt_all('4',['6',en,tussen]).
with_dt_all('4',['7',en,tussen]).
with_dt_all('480',['640',bij]).
with_dt_all('480',['800',bij]).
with_dt_all('480',['854',bij]).
with_dt_all('4',['8',bij]).
with_dt_all('4',['8',de,de,en,tussen]).
with_dt_all('4',['8',en,tussen]).
with_dt_all('4e',[klas]).
with_dt_all('4e',[klasse]).
with_dt_all('500.000',['600.000',de,en,tussen]).
with_dt_all('500.000',['700.000',de,en,tussen]).
with_dt_all('500.000',['800.000',de,en,tussen]).
with_dt_all('50.000',['60.000',de,en,tussen]).
with_dt_all('50.000',['80.000',de,en,tussen]).
with_dt_all('5000',['6000',de,en,tussen]).
with_dt_all('5000',['7000',de,en,tussen]).
with_dt_all('5000',['8000',de,en,tussen]).
with_dt_all('500',['550',de,en,tussen]).
with_dt_all('500',['550',en,tussen]).
with_dt_all('500',['600',de,en,tussen]).
with_dt_all('500',['700',de,en,tussen]).
with_dt_all('500',['750',de,en,tussen]).
with_dt_all('500',['800',de,en,tussen]).
with_dt_all('50',['500',de,en,tussen]).
with_dt_all('50',['50',bij]).
with_dt_all('50',['55',de,en,tussen]).
with_dt_all('50',['60',bij]).
with_dt_all('50',['60',de,en,tussen]).
with_dt_all('50',['60',en,tussen]).
with_dt_all('50',['70',de,en,tussen]).
with_dt_all('50',['70',en,tussen]).
with_dt_all('50',['75',de,en,tussen]).
with_dt_all('50',['75',en,tussen]).
with_dt_all('50',['80',de,en,tussen]).
with_dt_all('50',['80',en,tussen]).
with_dt_all('5,2',['5,8',en,tussen]).
with_dt_all('540',['960',bij]).
with_dt_all('\'54',['\'58']).
with_dt_all('5,5',['5,5',bij]).
with_dt_all('55',['55',bij]).
with_dt_all('55',['60',de,en,tussen]).
with_dt_all('55',['64',en,tussen]).
with_dt_all('55',['65',de,en,tussen]).
with_dt_all('55',['65',en,tussen]).
with_dt_all('5',['5',bij]).
with_dt_all('\'56',['\'58']).
with_dt_all('5',['6',de,en,tussen]).
with_dt_all('5',['6',en,tussen]).
with_dt_all('5',['7',de,en,tussen]).
with_dt_all('5',['7',en,tussen]).
with_dt_all('5',['8',de,en,tussen]).
with_dt_all('5',['9',de,en,tussen]).
with_dt_all('5',['9',en,tussen]).
with_dt_all('60.000',['70.000',de,en,tussen]).
with_dt_all('6000',['8000',de,en,tussen]).
with_dt_all('600',['700',de,en,tussen]).
with_dt_all('600',['700',en,tussen]).
with_dt_all('600',['800',bij]).
with_dt_all('600',['800',de,en,tussen]).
with_dt_all('60',['60',bij]).
with_dt_all('\'60',['\'61']).
with_dt_all('60',['64',en,tussen]).
with_dt_all('60',['65',de,de,en,tussen]).
with_dt_all('60',['65',de,en,tussen]).
with_dt_all('\'60',['\'70']).
with_dt_all('60',['70',bij]).
with_dt_all('60',['70',de,en,tussen]).
with_dt_all('60',['80',de,en,tussen]).
with_dt_all('60',['80',en,tussen]).
with_dt_all('60',['90',de,en,tussen]).
with_dt_all('60',['90',en,tussen]).
with_dt_all('65',['70',de,en,tussen]).
with_dt_all('65',['75',de,en,tussen]).
with_dt_all('65',['75',en,tussen]).
with_dt_all('65',['80',de,en,tussen]).
with_dt_all('6',['6',bij]).
with_dt_all('6',['7',de,en,tussen]).
with_dt_all('6',['7',en,tussen]).
with_dt_all('6',['8',bij]).
with_dt_all('6',['8',de,en,tussen]).
with_dt_all('6',['9',bij]).
with_dt_all('6',['9',de,en,tussen]).
with_dt_all('6',['9',en,tussen]).
with_dt_all('7000',['8000',de,en,tussen]).
with_dt_all('700',['800',de,en,tussen]).
with_dt_all('70',['75',en,tussen]).
with_dt_all('70',['80',de,en,tussen]).
with_dt_all('70',['80',en,tussen]).
with_dt_all('70',['90',de,en,tussen]).
with_dt_all('70',['90',en,tussen]).
with_dt_all('75',['95',de,en,tussen]).
with_dt_all('7',['7',bij]).
with_dt_all('7',['8',de,en,tussen]).
with_dt_all('7',['9',de,en,tussen]).
with_dt_all('7',['9',en,tussen]).
with_dt_all('800.000',['900.000',de,en,tussen]).
with_dt_all('8000',['9000',de,en,tussen]).
with_dt_all('800',['900',de,en,tussen]).
with_dt_all('80',['85',de,en,tussen]).
with_dt_all('80',['90',de,en,tussen]).
with_dt_all('8',['8',bij]).
with_dt_all('\'89',['\'90']).
with_dt_all('8',['9',de,en,tussen]).
with_dt_all('8',['9',en,tussen]).
with_dt_all('90',['90',bij]).
with_dt_all('\'90',['\'91']).
with_dt_all('\'90',['\'99']).
with_dt_all('\'92',['1991']).
with_dt_all('\'92',['\'93']).
with_dt_all('\'93',['\'94']).
with_dt_all('\'93',['\'98']).
with_dt_all('\'94',['1992']).
with_dt_all('\'94',['1993']).
with_dt_all('\'94',['\'95']).
with_dt_all('95',['95',bij]).
with_dt_all('\'95',['\'96']).
with_dt_all('\'95',['\'98']).
with_dt_all('\'96',['1995']).
with_dt_all('\'96',['\'97']).
with_dt_all('\'97',['1996']).
with_dt_all('\'97',['\'98']).
with_dt_all('97',['98',en,tussen]).
with_dt_all('\'98',['\'99']).
with_dt_all('9',['9',bij]).
with_dt_all('aan af',[jongs,van]).
with_dt_all('aan af',[jongs,vanaf]).
with_dt_all(aan,[denk,geen]).
with_dt_all(aan,[goed]).
with_dt_all(aan,[ik,neem_aan]).
with_dt_all(aan,[jongsaf,sinds]).
with_dt_all(aan,[jongsaf,van]).
with_dt_all(aan,[jongsaf,vanaf]).
with_dt_all(aan,[jongs,van]).
with_dt_all(aan,[jongs,vanaf]).
with_dt_all(aan,[kindsaf,sinds]).
with_dt_all(aan,[kindsaf,van]).
with_dt_all(aan,[kindsaf,vanaf]).
with_dt_all(aan,[kleinsaf,sinds]).
with_dt_all(aan,[kleinsaf,van]).
with_dt_all(aan,[kleinsaf,vanaf]).
with_dt_all(aanschijn,[de]).
with_dt_all(aantal,[beperkt,een]).
with_dt_all(aantal,[een]).
with_dt_all(aantal,[een,enorm]).
with_dt_all(aantal,[een,flink]).
with_dt_all(aantal,[een,groot]).
with_dt_all(aantal,[een,klein]).
with_dt_all(aantal,[een,respectabel]).
with_dt_all(aan,[van,vooraf]).
with_dt_all(aanverwant,[deze,en]).
with_dt_all(aan,[vroeger]).
with_dt_all(aanzien,[dien,te]).
with_dt_all(aanzien,[haren,te]).
with_dt_all(aanzien,[mijnen,te]).
with_dt_all(aanzien,[te,uwen]).
with_dt_all(aanzien,[te,zijnen]).
with_dt_all(aard,[dat,een,heb,het]).
with_dt_all(aarde,[moeder]).
with_dt_all(absoluut,[altijd,niet]).
with_dt_all(absoluut,[niemand]).
with_dt_all(absoluut,[niet]).
with_dt_all(absoluut,[niet,overal]).
with_dt_all(acht,[bij,drie]).
with_dt_all(acht,[bij,vijf]).
with_dt_all(acht,[bij,zes]).
with_dt_all(acht,[de,de,en,tussen,vier]).
with_dt_all(acht,[de,drie,en,tussen]).
with_dt_all(acht,[de,en,tien,tussen]).
with_dt_all(acht,[de,en,tussen,twaalf]).
with_dt_all(acht,[de,en,tussen,twee]).
with_dt_all(acht,[de,en,tussen,vijf]).
with_dt_all(acht,[de,en,tussen,zes]).
with_dt_all(acht,[en,tien,tussen]).
with_dt_all(acht,[en,tussen,twaalf]).
with_dt_all(acht,[en,tussen,vier]).
with_dt_all(acht,[en,tussen,zes]).
with_dt_all(acht,[en,tussen,zeven]).
with_dt_all(acht,[gij]).
with_dt_all(acht,[hen]).
with_dt_all(acht,[hun]).
with_dt_all(acht,[hun,met]).
with_dt_all(acht,[jullie]).
with_dt_all(acht,[jullie,met]).
with_dt_all(acht,[met,ons]).
with_dt_all(acht,[met,zijn]).
with_dt_all(acht,[met,'z\'n']).
with_dt_all(acht,[ons]).
with_dt_all(achttien,[de,de,en,tussen,vijftien]).
with_dt_all(achttien,[de,en,tussen,twaalf]).
with_dt_all(achttien,[gij]).
with_dt_all(achttien,[hen]).
with_dt_all(achttien,[hun]).
with_dt_all(achttien,[hun,met]).
with_dt_all(achttien,[jullie]).
with_dt_all(achttien,[jullie,met]).
with_dt_all(achttien,[met,ons]).
with_dt_all(achttien,[met,zijn]).
with_dt_all(achttien,[met,'z\'n']).
with_dt_all(achttien,[ons]).
with_dt_all(achttien,[u]).
with_dt_all(achttien,[wij]).
with_dt_all(achttien,[zij]).
with_dt_all(acht,[u]).
with_dt_all(acht,[wij]).
with_dt_all(acht,[zij]).
with_dt_all('af aan',[jongs,sinds]).
with_dt_all('af aan',[jongs,van]).
with_dt_all('af aan',[jongs,vanaf]).
with_dt_all('af aan',[kindsbeen,sinds]).
with_dt_all('af aan',[kindsbeen,van]).
with_dt_all('af aan',[kindsbeen,vanaf]).
with_dt_all('af aan',[kinds,sinds]).
with_dt_all('af aan',[kinds,van]).
with_dt_all('af aan',[kinds,vanaf]).
with_dt_all('af aan',[kleins,sinds]).
with_dt_all('af aan',[kleins,van]).
with_dt_all('af aan',[kleins,vanaf]).
with_dt_all('af aan',[nu,van]).
with_dt_all('af aan',[van,voor]).
with_dt_all('af aan',[van,voren]).
with_dt_all(af,[bij]).
with_dt_all(af,[fabriek]).
with_dt_all(af,[jongs,sinds]).
with_dt_all(af,[jongs,van]).
with_dt_all(af,[jongs,vanaf]).
with_dt_all(af,[kindsbeen,sinds]).
with_dt_all(af,[kindsbeen,van]).
with_dt_all(af,[kindsbeen,vanaf]).
with_dt_all(af,[kinds,sinds]).
with_dt_all(af,[kinds,van]).
with_dt_all(af,[kinds,vanaf]).
with_dt_all(af,[kleins,sinds]).
with_dt_all(af,[kleins,van]).
with_dt_all(af,[kleins,vanaf]).
with_dt_all(af,[naar]).
with_dt_all(afstand,[lang]).
with_dt_all(al,[dat]).
with_dt_all(al,[degeen]).
with_dt_all(al,[dit]).
with_dt_all(al,[gij]).
with_dt_all(al,[hen]).
with_dt_all(al,[het]).
with_dt_all(al,[hun]).
with_dt_all(al,[hun,met]).
with_dt_all(al,[jullie]).
with_dt_all(al,[jullie,met]).
with_dt_all(al,[lang,niet]).
with_dt_all(allebei,[gij]).
with_dt_all(allebei,[hen]).
with_dt_all(allebei,[hun]).
with_dt_all(allebei,[hun,met]).
with_dt_all(allebei,[jullie]).
with_dt_all(allebei,[jullie,met]).
with_dt_all(allebei,[met,ons]).
with_dt_all(allebei,[met,zijn]).
with_dt_all(allebei,[met,'z\'n']).
with_dt_all(allebei,[of]).
with_dt_all(allebei,[ons]).
with_dt_all(allebei,[u]).
with_dt_all(allebei,[van]).
with_dt_all(allebei,[wij]).
with_dt_all(allebei,[zij]).
with_dt_all(alle,[best]).
with_dt_all(alledag,[van]).
with_dt_all(alleen,[alleen,ben,maar]).
with_dt_all(alleen,[jammer]).
with_dt_all(alleen,[maar]).
with_dt_all(alleen,[niet]).
with_dt_all(allemaal,[best]).
with_dt_all(allemaal,[bijna]).
with_dt_all(allemaal,[gij]).
with_dt_all(allemaal,[haast]).
with_dt_all(allemaal,[hen]).
with_dt_all(allemaal,[hun]).
with_dt_all(allemaal,[hun,met]).
with_dt_all(allemaal,[jullie]).
with_dt_all(allemaal,[jullie,met]).
with_dt_all(allemaal,[lang,niet]).
with_dt_all(allemaal,[lief]).
with_dt_all(allemaal,[met,ons]).
with_dt_all(allemaal,[met,zijn]).
with_dt_all(allemaal,[met,'z\'n']).
with_dt_all(allemaal,[niet]).
with_dt_all(allemaal,[ons]).
with_dt_all(allemaal,[u]).
with_dt_all(allemaal,[vrijwel]).
with_dt_all(allemaal,[wij]).
with_dt_all(allemaal,[zij]).
with_dt_all(allemaal,[zowat]).
with_dt_all(allen,[prijze,te]).
with_dt_all(allen,[prijze,ten]).
with_dt_all(alles,[lang,niet]).
with_dt_all(alles,[niet]).
with_dt_all(alles,[samen]).
with_dt_all(alles,[tesamen]).
with_dt_all(alles,[tezamen]).
with_dt_all(allicht,[daarom]).
with_dt_all(allicht,[vandaar]).
with_dt_all(al,[maar,te]).
with_dt_all(al,[met,ons]).
with_dt_all(al,[met,zijn]).
with_dt_all(al,[met,'z\'n']).
with_dt_all(al,[niet]).
with_dt_all(al,[ons]).
with_dt_all(al,[ook]).
with_dt_all(als,[echt,onecht,zowel]).
with_dt_all(als,[groen,rijp,zowel]).
with_dt_all(als,[groot,klein,zowel]).
with_dt_all(als,[hard,zacht,zowel]).
with_dt_all(als,[hoog,laag,zowel]).
with_dt_all(als,[jong,oud,zowel]).
with_dt_all(als,[nieuw,oud,zowel]).
with_dt_all(als,[volg]).
with_dt_all(al,[te]).
with_dt_all(al,[te,zeer]).
with_dt_all(altijd,[ben,mis,niet,schiet]).
with_dt_all(altijd,[bepaald,niet]).
with_dt_all(altijd,[beslist,niet]).
with_dt_all(altijd,[dan,toch,vanwaar]).
with_dt_all(altijd,[dan,toch,waarom]).
with_dt_all(altijd,[echt,niet]).
with_dt_all(altijd,[heus,niet]).
with_dt_all(altijd,[hoegenaamd,niet]).
with_dt_all(altijd,[lang,niet]).
with_dt_all(altijd,[mooi,niet]).
with_dt_all(altijd,[natuurlijk,niet]).
with_dt_all(altijd,[niet]).
with_dt_all(altijd,[niet,toch]).
with_dt_all(altijd,[niet,vast]).
with_dt_all(altijd,[niet,volstrekt]).
with_dt_all(altijd,[niet,waarachtig]).
with_dt_all(altijd,[niet,waarschijnlijk]).
with_dt_all(altijd,[niet,wellicht]).
with_dt_all(altijd,[niet,werkelijk]).
with_dt_all(altijd,[niet,zeker]).
with_dt_all(altijd,[nog]).
with_dt_all(altijd,[toch,vanwaar]).
with_dt_all(altijd,[toch,waarom]).
with_dt_all(altijd,[voor]).
with_dt_all(altijd,[weer]).
with_dt_all(al,[u]).
with_dt_all(al,[wie]).
with_dt_all(al,[wij]).
with_dt_all(al,[zij]).
with_dt_all(ander,[ben,leuk]).
with_dt_all(ander,[ben,makkelijk]).
with_dt_all(ander,[ben,mooi]).
with_dt_all(ander,[ben,plezant]).
with_dt_all(ander,[ben,prettig]).
with_dt_all(ander,[deze,en]).
with_dt_all(ander,[deze,en,nog]).
with_dt_all(ander,[en,niet]).
with_dt_all(ander,[ik]).
with_dt_all(andermans,[eigen,en]).
with_dt_all(andermans,[eigen,of]).
with_dt_all(andersom,[en]).
with_dt_all(andersom,[en,niet]).
with_dt_all(andersom,[of]).
with_dt_all(anderszins,[of]).
with_dt_all(anno,[nu]).
with_dt_all(arm,[ik]).
with_dt_all(arm,[jij]).
with_dt_all(artistiek,[leider]).
with_dt_all(baan,[lang]).
with_dt_all(bedde,[te]).
with_dt_all(bedoel,[ik]).
with_dt_all(bed,[te]).
with_dt_all(beginne,[den,in]).
with_dt_all(begrijp,[me,niet,verkeerd]).
with_dt_all(beide,[de]).
with_dt_all(beide_DIM,[gij]).
with_dt_all(beide_DIM,[hen]).
with_dt_all(beide_DIM,[hun]).
with_dt_all(beide_DIM,[hun,met]).
with_dt_all(beide_DIM,[jullie]).
with_dt_all(beide_DIM,[jullie,met]).
with_dt_all(beide_DIM,[met,ons]).
with_dt_all(beide_DIM,[met,zijn]).
with_dt_all(beide_DIM,[met,'z\'n']).
with_dt_all(beide_DIM,[ons]).
with_dt_all(beide_DIM,[u]).
with_dt_all(beide_DIM,[wij]).
with_dt_all(beide_DIM,[zij]).
with_dt_all(beide,[gij]).
with_dt_all(beide,[hen]).
with_dt_all(beide,[hun]).
with_dt_all(beide,[hun,met]).
with_dt_all(beide,[jullie]).
with_dt_all(beide,[jullie,met]).
with_dt_all(beide,[met,ons]).
with_dt_all(beide,[met,zijn]).
with_dt_all(beide,[met,'z\'n']).
with_dt_all(beide,[ons]).
with_dt_all(beide,[u]).
with_dt_all(beide,[wij]).
with_dt_all(beide,[zij]).
with_dt_all(bekend,[bemind,maak]).
with_dt_all(beloofd,[beloofd,ben]).
with_dt_all(ben,[binnen,binnen]).
with_dt_all(ben,[dat,een,het,lief,lust]).
with_dt_all(ben,[doe,jong,leer,oud]).
with_dt_all(ben,[eerlijk,eerlijk]).
with_dt_all(ben,[gebeur,gebeur]).
with_dt_all(ben,[krom,krom]).
with_dt_all(ben,[op,op]).
with_dt_all(ben,[recht,recht]).
with_dt_all(ben,[vol,vol]).
with_dt_all(bepaald,[niet]).
with_dt_all(bepaald,[niet,overal]).
with_dt_all(beslist,[niet]).
with_dt_all(beslist,[niet,overal]).
with_dt_all(best,[iedereen]).
with_dt_all(biecht,[te]).
with_dt_all(bij,[dertien,zeven]).
with_dt_all(bij,[dertig,dertig]).
with_dt_all(bij,[dertig,veertig]).
with_dt_all(bij,[dertig,vijftig]).
with_dt_all(bij,[drie,drie]).
with_dt_all(bij,[drie,twee]).
with_dt_all(bij,[drie,vier]).
with_dt_all(bij,[drie,vijf]).
with_dt_all(bij,[drie,zes]).
with_dt_all(bij,[drie,zeven]).
with_dt_all(bij,[elf,vier]).
with_dt_all(bijna,[direct]).
with_dt_all(bijna,[direkt]).
with_dt_all(bij,[name]).
with_dt_all(bijna,[meteen]).
with_dt_all(bijna,[onmiddellijk]).
with_dt_all(bijna,[uitsluitend]).
with_dt_all(bij,[negen,negen]).
with_dt_all(bij,[tien,tien]).
with_dt_all(bij,[tien,twintig]).
with_dt_all(bij,[tien,vier]).
with_dt_all(bij,[tien,vijf]).
with_dt_all(bij,[tien,vijftien]).
with_dt_all(bij,[twaalf,twaalf]).
with_dt_all(bij,[twee,twee]).
with_dt_all(bij,[twee,vier]).
with_dt_all(bij,[twee,vijf]).
with_dt_all(bij,[twintig,twintig]).
with_dt_all(bij,[veertig,veertig]).
with_dt_all(bij,[vier,vier]).
with_dt_all(bij,[vier,vijf]).
with_dt_all(bij,[vier,zes]).
with_dt_all(bij,[vier,zeven]).
with_dt_all(bij,[vijftien,vijftien]).
with_dt_all(bij,[vijftig,vijftig]).
with_dt_all(bij,[vijf,vijf]).
with_dt_all(bij,[vijf,zes]).
with_dt_all(bij,[vijf,zeven]).
with_dt_all(bij,[zestig,zestig]).
with_dt_all(bij,[zes,zes]).
with_dt_all(bijzonder,[heel,het,in]).
with_dt_all(bijzonder,[het,in]).
with_dt_all('bij zoverre',[zelfs]).
with_dt_all(biljoen,[de,paar]).
with_dt_all(biljoen,[deze,paar]).
with_dt_all(biljoen,[die,paar]).
with_dt_all(biljoen,[een,paar]).
with_dt_all(binnenkort,[zeer]).
with_dt_all(binnenland,[buitenland,en]).
with_dt_all(blij,[verrast]).
with_dt_all(blik,[bloos,of,zonder]).
with_dt_all(blind,[liefde,maak]).
with_dt_all(bloede,[in,koelen]).
with_dt_all(boel,[een]).
with_dt_all(bovengenoemd,[deze,en]).
with_dt_all(breed,[het,in]).
with_dt_all(brode,[den,om]).
with_dt_all(broeder,[de]).
with_dt_all(broeder,[haar]).
with_dt_all(broeder,[hun]).
with_dt_all(broeder,[je]).
with_dt_all(broeder,[jou]).
with_dt_all(broeder,[jullie]).
with_dt_all(broeder,[mijn]).
with_dt_all(broeder,[u]).
with_dt_all(broeder,[zijn]).
with_dt_all(broer,[de]).
with_dt_all(broer,[haar]).
with_dt_all(broer,[hun]).
with_dt_all(broer,[je]).
with_dt_all(broer,[jou]).
with_dt_all(broer,[jullie]).
with_dt_all(broer,[mijn]).
with_dt_all(broer,[u]).
with_dt_all(broer,[zijn]).
with_dt_all(buiten,[dat]).
with_dt_all(buiten,[de]).
with_dt_all(communie,[te]).
with_dt_all(daaraan,[vooraf]).
with_dt_all(daarmee,[en,uit]).
with_dt_all(daarom,[misschien]).
with_dt_all(daarom,[ook]).
with_dt_all(daaromtrent,[of]).
with_dt_all(daarom,[wellicht]).
with_dt_all(dag,[deze]).
with_dt_all(dage,[dien,te]).
with_dt_all(dame,[en,goedenavond,heer]).
with_dt_all(dan,[dwaal,goed,keer,'ten halve','ten hele']).
with_dt_all(dan,[eerst,geloof,zie]).
with_dt_all(dan,[en]).
with_dt_all(dan,[ineens]).
with_dt_all(dan,[lief,morgen,vandaag]).
with_dt_all(dan,[ook,vandaar]).
with_dt_all(dan,[toch,vanwaar]).
with_dt_all(dan,[toch,waarom]).
with_dt_all(dan,[vanwaar]).
with_dt_all(dan,[waarom]).
with_dt_all(dan,[welaan]).
with_dt_all(dat,[giet,het]).
with_dt_all(dat,[het,kraak]).
with_dt_all(dat,[ondanks]).
with_dt_all(dat,[soort]).
with_dt_all(dat,[van]).
with_dt_all(dat,[van,veel]).
with_dt_all(dat,[zonder]).
with_dt_all(decennium,[dit,en,het,kom]).
with_dt_all(decennium,[dit,en,het,volg]).
with_dt_all(de,[de,dertig,en,tussen,twintig]).
with_dt_all(de,[de,dertig,en,tussen,veertig]).
with_dt_all(de,[de,dertig,en,tussen,vijf]).
with_dt_all(de,[de,dertig,en,tussen,vijftig]).
with_dt_all(de,[de,drie,en,tussen,vier]).
with_dt_all(de,[de,drie,en,tussen,vijf]).
with_dt_all(de,[de,en,tien,tussen,twintig]).
with_dt_all(de,[de,en,tien,tussen,vijf]).
with_dt_all(de,[de,en,tien,tussen,vijftien]).
with_dt_all(de,[de,en,tussen,twee,zes]).
with_dt_all(de,[de,en,tussen,twintig,veertig]).
with_dt_all(de,[de,en,tussen,veertig,vijftig]).
with_dt_all(de,[de,en,tussen,vier,vijf]).
with_dt_all(de,[de,en,tussen,vijftig,zestig]).
with_dt_all(de,[dertien,en,tien,tussen]).
with_dt_all(de,[dertig,en,tien,tussen]).
with_dt_all(de,[dertig,en,tussen,twintig]).
with_dt_all(de,[dertig,en,tussen,veertig]).
with_dt_all(de,[dertig,en,tussen,vijftien]).
with_dt_all(de,[dertig,en,tussen,vijftig]).
with_dt_all(de,[dertig,en,tussen,zestig]).
with_dt_all(de,[dichter]).
with_dt_all(de,[dood]).
with_dt_all(de,[drie,en,tien,tussen]).
with_dt_all(de,[drie,en,tussen,twee]).
with_dt_all(de,[drie,en,tussen,vier]).
with_dt_all(de,[drie,en,tussen,vijf]).
with_dt_all(de,[drie,en,tussen,zes]).
with_dt_all(de,[drie,en,tussen,zeven]).
with_dt_all(de,[driehonderd,en,honderd,tussen]).
with_dt_all(de,[driehonderd,en,tussen,tweehonderd]).
with_dt_all(de,[duizend,en,tussen,twaalfhonderd]).
with_dt_all(de,[duizend,en,tussen,tweeduizend]).
with_dt_all(de,[duizend,en,tussen,vijfhonderd]).
with_dt_all(de,[duizend,en,tussen,zeshonderd]).
with_dt_all(de,[duizend,paar]).
with_dt_all(de,[een]).
with_dt_all(de,[één]).
with_dt_all(deel,[geen]).
with_dt_all(de,[en,honderd,honderdvijftig,tussen]).
with_dt_all(de,[en,honderd,tachtig,tussen]).
with_dt_all(de,[en,honderd,tussen,tweehonderd]).
with_dt_all(de,[en,honderd,tussen,veertig]).
with_dt_all(de,[en,honderd,tussen,vijfhonderd]).
with_dt_all(de,[en,honderd,tussen,vijftig]).
with_dt_all(de,[en,honderd,tussen,zeventig]).
with_dt_all(de,[en,negentien,tussen,zeven]).
with_dt_all(de,[en,negen,tussen,twaalf]).
with_dt_all(de,[en,negen,tussen,vijf]).
with_dt_all(de,[en,negen,tussen,zes]).
with_dt_all(de,[en,tachtig,tussen,vijftig]).
with_dt_all(de,[en,tachtig,tussen,zestig]).
with_dt_all(de,[en,tachtig,tussen,zeventig]).
with_dt_all(de,[en,tien,tussen,twaalf]).
with_dt_all(de,[en,tien,tussen,twee]).
with_dt_all(de,[en,tien,tussen,twintig]).
with_dt_all(de,[en,tien,tussen,veertien]).
with_dt_all(de,[en,tien,tussen,vijf]).
with_dt_all(de,[en,tien,tussen,vijftien]).
with_dt_all(de,[en,tien,tussen,zes]).
with_dt_all(de,[en,tien,tussen,zeven]).
with_dt_all(de,[en,tussen,twaalf,twintig]).
with_dt_all(de,[en,tussen,twaalf,vier]).
with_dt_all(de,[en,tussen,twaalf,zes]).
with_dt_all(de,[en,tussen,twaalf,zestien]).
with_dt_all(de,[en,tussen,twee,vier]).
with_dt_all(de,[en,tussen,twee,vijf]).
with_dt_all(de,[en,tussen,twintig,veertig]).
with_dt_all(de,[en,tussen,twintig,vijfentwintig]).
with_dt_all(de,[en,tussen,twintig,vijftien]).
with_dt_all(de,[en,tussen,twintig,zestien]).
with_dt_all(de,[en,tussen,veertig,vijftig]).
with_dt_all(de,[en,tussen,vier,vijf]).
with_dt_all(de,[en,tussen,vier,zes]).
with_dt_all(de,[en,tussen,vijfentwintig,vijftien]).
with_dt_all(de,[en,tussen,vijftig,zestig]).
with_dt_all(de,[en,tussen,vijftig,zeventig]).
with_dt_all(de,[en,tussen,vijf,vijftien]).
with_dt_all(de,[en,tussen,vijf,zes]).
with_dt_all(de,[en,tussen,vijf,zeven]).
with_dt_all(de,[en,tussen,zestig,zeventig]).
with_dt_all(de,[en,tussen,zes,zeven]).
with_dt_all(degelijk,[wel]).
with_dt_all(de,[god,vader]).
with_dt_all(de,[grootmoeder]).
with_dt_all(de,[grootvader]).
with_dt_all(de,[haar,koningin,majesteit]).
with_dt_all(de,[heb]).
with_dt_all(de,[heelal]).
with_dt_all(de,[hemel]).
with_dt_all(de,[hij]).
with_dt_all(de,[honderdduizend,paar]).
with_dt_all(de,[honderd,paar]).
with_dt_all(de,[huize]).
with_dt_all(de,[ik]).
with_dt_all(de,[in,laatst,niet,plaats]).
with_dt_all(de,[keizer]).
with_dt_all(de,[klok,rond]).
with_dt_all(de,[koning]).
with_dt_all(de,[kwaad]).
with_dt_all(de,[land]).
with_dt_all(de,[leven]).
with_dt_all(de,[man]).
with_dt_all(de,[miljard,paar]).
with_dt_all(de,[miljoen,paar]).
with_dt_all(de,[minnaar]).
with_dt_all(de,[moeder]).
with_dt_all(de,[moeder,vrouw]).
with_dt_all(den,[in,lande]).
with_dt_all(den,[in,vreemde]).
with_dt_all(denk,[ik]).
with_dt_all(denk,[je]).
with_dt_all(de,[oma]).
with_dt_all(de,[onderscheid]).
with_dt_all(de,[onheil]).
with_dt_all(de,[oordeel]).
with_dt_all(de,[opa]).
with_dt_all(de,[overvloed]).
with_dt_all(de,[persoon]).
with_dt_all(derde,[klas]).
with_dt_all(derde,[klasse]).
with_dt_all(dergelijks,[iets,of]).
with_dt_all(dergelijk,[zelfs]).
with_dt_all(de,[rijk]).
with_dt_all(dermate,[zelfs]).
with_dt_all(dertien,[gij]).
with_dt_all(dertien,[hen]).
with_dt_all(dertien,[hun]).
with_dt_all(dertien,[hun,met]).
with_dt_all(dertien,[jullie]).
with_dt_all(dertien,[jullie,met]).
with_dt_all(dertien,[met,ons]).
with_dt_all(dertien,[met,zijn]).
with_dt_all(dertien,[met,'z\'n']).
with_dt_all(dertien,[ons]).
with_dt_all(dertien,[u]).
with_dt_all(dertien,[wij]).
with_dt_all(dertien,[zij]).
with_dt_all(dertig,[en,tussen,twintig]).
with_dt_all(dertig,[en,tussen,veertig]).
with_dt_all('des te',[veel]).
with_dt_all(de,[stief_moeder]).
with_dt_all(de,[stief_vader]).
with_dt_all(de,[tante]).
with_dt_all(de,[tijd]).
with_dt_all(de,[vader]).
with_dt_all(de,[vaderland]).
with_dt_all(de,[veld]).
with_dt_all(de,[volk]).
with_dt_all(de,[vriend]).
with_dt_all(de,[vriendin]).
with_dt_all(de,[woord]).
with_dt_all(deze,[duizend,paar]).
with_dt_all(deze,[één]).
with_dt_all(deze,[en,soortgelijk]).
with_dt_all(deze,[en,volg]).
with_dt_all(deze,[en,vorig]).
with_dt_all(deze,[honderdduizend,paar]).
with_dt_all(deze,[honderd,paar]).
with_dt_all(deze,[miljard,paar]).
with_dt_all(deze,[miljoen,paar]).
with_dt_all(deze,[van]).
with_dt_all(de,[zuster]).
with_dt_all(die,[duizend,paar]).
with_dt_all(die,[honderdduizend,paar]).
with_dt_all(die,[honderd,paar]).
with_dt_all(die,[miljard,paar]).
with_dt_all(die,[miljoen,paar]).
with_dt_all(dien,[einde,te]).
with_dt_all(dien,[opzichte,te]).
with_dt_all(dien,[te,tijde]).
with_dt_all(die,[paar]).
with_dt_all(diep,[ik]).
with_dt_all(die,[van]).
with_dt_all(dikwijls,[niet]).
with_dt_all(dikwijls,[nogal]).
with_dt_all(dikwijls,[te]).
with_dt_all(dikwijls,[zeer]).
with_dt_all(direct,[haast]).
with_dt_all(direct,[per]).
with_dt_all(direct,[vrijwel]).
with_dt_all(direkt,[haast]).
with_dt_all(direkt,[per]).
with_dt_all(direkt,[vrijwel]).
with_dt_all(dit,[en,het,jaar,kom]).
with_dt_all(dit,[en,het,jaar,volg]).
with_dt_all(dit,[en,het,kom,millenium]).
with_dt_all(dit,[en,het,kom,seizoen]).
with_dt_all(dit,[en,het,millenium,volg]).
with_dt_all(dit,[en,het,seizoen,volg]).
with_dt_all(dit,[en,volg]).
with_dt_all(dit,[en,vorig]).
with_dt_all(dit,[keer]).
with_dt_all(dit,[maal]).
with_dt_all(dit,[soort]).
with_dt_all(dit,[terzijde]).
with_dt_all(dit,[van]).
with_dt_all(doe,[ik,zeg]).
with_dt_all(doen,[goede,in]).
with_dt_all(doen,[goeden,heel,in]).
with_dt_all(doen,[goeden,in]).
with_dt_all(draai,[u,vraag,wij]).
with_dt_all(drie_DIM,[gij]).
with_dt_all(drie_DIM,[hen]).
with_dt_all(drie_DIM,[hun]).
with_dt_all(drie_DIM,[hun,met]).
with_dt_all(drie_DIM,[jullie]).
with_dt_all(drie_DIM,[jullie,met]).
with_dt_all(drie_DIM,[met,ons]).
with_dt_all(drie_DIM,[met,zijn]).
with_dt_all(drie_DIM,[met,'z\'n']).
with_dt_all(drie_DIM,[ons]).
with_dt_all(drie_DIM,[u]).
with_dt_all(drie_DIM,[wij]).
with_dt_all(drie_DIM,[zij]).
with_dt_all(drie,[en,tien,tussen]).
with_dt_all(drie,[en,tussen,vier]).
with_dt_all(drie,[en,tussen,vijf]).
with_dt_all(drie,[en,tussen,zes]).
with_dt_all(drie,[gij]).
with_dt_all(drie,[hen]).
with_dt_all(drie,[hun]).
with_dt_all(drie,[hun,met]).
with_dt_all(drie,[jullie]).
with_dt_all(drie,[jullie,met]).
with_dt_all(drie,[met,ons]).
with_dt_all(drie,[met,zijn]).
with_dt_all(drie,[met,'z\'n']).
with_dt_all(drie,[ons]).
with_dt_all(drie,[u]).
with_dt_all(drie,[wij]).
with_dt_all(drie,[zij]).
with_dt_all(duizend,[een,paar]).
with_dt_all(dunk,[me]).
with_dt_all(dunk,[mij]).
with_dt_all(dusdanig,[zelfs]).
with_dt_all(dus,[mooi,niet]).
with_dt_all(dus,[niet]).
with_dt_all(dus,['op grond van']).
with_dt_all(dus,[vandaar]).
with_dt_all(duur,[eerlijk,lang]).
with_dt_all(echt,[en,onecht]).
with_dt_all(echter,['op grond van']).
with_dt_all(echt,[het,in]).
with_dt_all(echt,[ik]).
with_dt_all(echt,[niet]).
with_dt_all(echt,[niet,overal]).
with_dt_all(ede,[onder]).
with_dt_all(een,[een,een,een,man,man,woord,woord]).
with_dt_all(een,[handvol]).
with_dt_all(een,[heleboel]).
with_dt_all(een,[hele,hoop]).
with_dt_all(een,[het]).
with_dt_all(een,[hij]).
with_dt_all(een,[honderdduizend,paar]).
with_dt_all(een,[honderd,paar]).
with_dt_all(een,[hoop]).
with_dt_all(een,[ik]).
with_dt_all(een,[maar]).
with_dt_all(een,[miljard,paar]).
with_dt_all(een,[miljoen]).
with_dt_all(een,[miljoen,paar]).
with_dt_all(een,[mits]).
with_dt_all(een,[na]).
with_dt_all(een,[paar]).
with_dt_all(een,[pak]).
with_dt_all(een,[reeks]).
with_dt_all(eens,[niet]).
with_dt_all(een,[soort]).
with_dt_all(een,[stel]).
with_dt_all(een,[stelletje]).
with_dt_all(eens,[temeer]).
with_dt_all(eens,['te veel']).
with_dt_all(eens,[zo]).
with_dt_all(eentje,[zo]).
with_dt_all(een,[welk]).
with_dt_all(eerder,[gisteravond]).
with_dt_all(eerder,[gisteren]).
with_dt_all(eerder,[gisterenavond]).
with_dt_all(eerder,[gisterenmiddag]).
with_dt_all(eerder,[gisterenmorgen]).
with_dt_all(eerder,[gisterennacht]).
with_dt_all(eerder,[gisterenochtend]).
with_dt_all(eerder,[gistermiddag]).
with_dt_all(eerder,[gistermorgen]).
with_dt_all(eerder,[gisternacht]).
with_dt_all(eerder,[gisterochtend]).
with_dt_all(eerder,[vanavond]).
with_dt_all(eerder,[vandaag]).
with_dt_all(eerder,[vanmiddag]).
with_dt_all(eerder,[vanmorgen]).
with_dt_all(eerder,[vannacht]).
with_dt_all(eerder,[vanochtend]).
with_dt_all(eerste,[klas]).
with_dt_all(eerste,[klasse]).
with_dt_all(eeuwig,[voor]).
with_dt_all(eigen,[elkaar,en]).
with_dt_all(eigen,[elkaar,of]).
with_dt_all(eigen,[ik]).
with_dt_all(eigen,[kunnen]).
with_dt_all(eigenlijk,[niet,waarom]).
with_dt_all(eigen,[zeggen]).
with_dt_all(elf,[en,tien,tussen]).
with_dt_all(elf,[en,tussen,twaalf]).
with_dt_all(elf,[gij]).
with_dt_all(elf,[hen]).
with_dt_all(elf,[hun]).
with_dt_all(elf,[hun,met]).
with_dt_all(elf,[jullie]).
with_dt_all(elf,[jullie,met]).
with_dt_all(elf,[met,ons]).
with_dt_all(elf,[met,zijn]).
with_dt_all(elf,[met,'z\'n']).
with_dt_all(elf,[ons]).
with_dt_all(elf,[u]).
with_dt_all(elf,[wij]).
with_dt_all(elf,[zij]).
with_dt_all(elke,[paar]).
with_dt_all(en,[groen,rijp]).
with_dt_all(en,[groot,klein]).
with_dt_all(en,[hang,met,wurg]).
with_dt_all(en,['hard drugs',soft]).
with_dt_all(en,[hard,'soft drugs']).
with_dt_all(en,[hard,zacht]).
with_dt_all(en,[heen,terug]).
with_dt_all(en,[het,het,hier,nu]).
with_dt_all(en,[het,het,laag,middelbaar,onderwijs]).
with_dt_all(en,[het,het,laag,onderwijs,secundair]).
with_dt_all(en,[het,hier,nu]).
with_dt_all(en,[het,hoe,wat]).
with_dt_all(en,[honderd,tussen,zestig]).
with_dt_all(en,[hoog,laag]).
with_dt_all(en,[in,vlam,vuur]).
with_dt_all(en,[je,jij]).
with_dt_all(en,[jij,jou]).
with_dt_all(en,[jong,oud]).
with_dt_all(en,[klaar]).
with_dt_all(en,[met,sta_op,val]).
with_dt_all(en,[met,succes]).
with_dt_all(en,[negen,tussen,twaalf]).
with_dt_all(en,[negen,tussen,vijf]).
with_dt_all(en,[negen,tussen,zes]).
with_dt_all(en,[negen,tussen,zeven]).
with_dt_all(en,['niet zo\'n beetje ook']).
with_dt_all(en,[nieuw,oud]).
with_dt_all(en,[omgekeerd]).
with_dt_all(en,[onder,ons,zeg,zwijg]).
with_dt_all(en,[terecht]).
with_dt_all(en,[tien,tussen,twintig]).
with_dt_all(en,[tien,tussen,vijf]).
with_dt_all(en,[tien,tussen,vijftien]).
with_dt_all(en,[tien,tussen,zes]).
with_dt_all(en,[tien,tussen,zeven]).
with_dt_all(en,[tussen,twaalf,twee]).
with_dt_all(en,[tussen,twaalf,veertien]).
with_dt_all(en,[tussen,twaalf,vijftien]).
with_dt_all(en,[tussen,twaalf,zes]).
with_dt_all(en,[tussen,twee,vier]).
with_dt_all(en,[tussen,twee,vijf]).
with_dt_all(en,[tussen,twee,zes]).
with_dt_all(en,[tussen,twintig,veertig]).
with_dt_all(en,[tussen,veertig,vijftig]).
with_dt_all(en,[tussen,vier,zes]).
with_dt_all(en,[tussen,vier,zeven]).
with_dt_all(en,[tussen,vijf,vijftien]).
with_dt_all(en,[tussen,vijf,zes]).
with_dt_all(en,[tussen,vijf,zeven]).
with_dt_all(en,[tussen,zes,zeven]).
with_dt_all(en,[ver]).
with_dt_all(en,['vice versa']).
with_dt_all(en,[wat,wie]).
with_dt_all(en,[zo]).
with_dt_all(eraan,[vooraf]).
with_dt_all(ere,[ere,kom_toe,toe,wie]).
with_dt_all(ere,[ere,kom_toe,wie]).
with_dt_all(erg,[veel,zonder]).
with_dt_all(erg,[zonder]).
with_dt_all(fiets,[te]).
with_dt_all(ga,[moeilijk,ook]).
with_dt_all(ga,[slaap]).
with_dt_all(geef_toe,[ik,toe]).
with_dt_all(geen,[nauwelijks,of]).
with_dt_all(geen,[stand]).
with_dt_all(gelijk,[gelijk,kap,monnik]).
with_dt_all(gelijk,[zijn]).
with_dt_all(geloof,[het,niet,of]).
with_dt_all(geloof,[ik]).
with_dt_all(geloof,[niet,te]).
with_dt_all(gemeentewege,[van]).
with_dt_all(genoeg,[jammer]).
with_dt_all(geval,[ieder,in]).
with_dt_all(gij,[negen]).
with_dt_all(gij,[negentien]).
with_dt_all(gij,[tien]).
with_dt_all(gij,[twaalf]).
with_dt_all(gij,[twee]).
with_dt_all(gij,[twee_DIM]).
with_dt_all(gij,[twintig]).
with_dt_all(gij,[veertien]).
with_dt_all(gij,[vier]).
with_dt_all(gij,[vier_DIM]).
with_dt_all(gij,[vijf]).
with_dt_all(gij,[vijf_DIM]).
with_dt_all(gij,[vijftien]).
with_dt_all(gij,[zes]).
with_dt_all(gij,[zes_DIM]).
with_dt_all(gij,[zestien]).
with_dt_all(gij,[zeven]).
with_dt_all(gij,[zeventien]).
with_dt_all(ginder,[langs]).
with_dt_all(gisteravond,[later]).
with_dt_all(gisterenavond,[later]).
with_dt_all(gisteren,[later]).
with_dt_all(gisterenmiddag,[later]).
with_dt_all(gisterenmorgen,[later]).
with_dt_all(gisterennacht,[later]).
with_dt_all(gisterenochtend,[later]).
with_dt_all(gistermiddag,[later]).
with_dt_all(gistermorgen,[later]).
with_dt_all(gisternacht,[later]).
with_dt_all(gisterochtend,[later]).
with_dt_all(goeden,[heel,huize,van]).
with_dt_all(goeden,[huizen,van]).
with_dt_all(goeden,[huize,van]).
with_dt_all(goed,[ik]).
with_dt_all(goed,[mij]).
with_dt_all(graag,[niet]).
with_dt_all(graag,[niet,of]).
with_dt_all(grabbel,[te]).
with_dt_all(groot,[het,in]).
with_dt_all(grootmoeder,[haar]).
with_dt_all(grootmoeder,[hun]).
with_dt_all(grootmoeder,[je]).
with_dt_all(grootmoeder,[jou]).
with_dt_all(grootmoeder,[jullie]).
with_dt_all(grootmoeder,[mijn]).
with_dt_all(grootmoeder,[u]).
with_dt_all(grootmoeder,[zijn]).
with_dt_all(grootvader,[haar]).
with_dt_all(grootvader,[hun]).
with_dt_all(grootvader,[je]).
with_dt_all(grootvader,[jou]).
with_dt_all(grootvader,[jullie]).
with_dt_all(grootvader,[mijn]).
with_dt_all(grootvader,[u]).
with_dt_all(grootvader,[zijn]).
with_dt_all(gunste,[haren,te]).
with_dt_all(gunste,[mijnen,te]).
with_dt_all(gunste,[te,uwen]).
with_dt_all(gunste,[te,zijnen]).
with_dt_all(haar,[majesteit]).
with_dt_all(haar,[man]).
with_dt_all(haar,[minnaar]).
with_dt_all(haar,[moeder]).
with_dt_all(haar,[oma]).
with_dt_all(haar,[opa]).
with_dt_all(haar,[stief_moeder]).
with_dt_all(haar,[stief_vader]).
with_dt_all(haar,[tante]).
with_dt_all(haar,[vader]).
with_dt_all(haar,[vriend]).
with_dt_all(haar,[vriendin]).
with_dt_all(haar,[zuster]).
with_dt_all(haast,[meteen]).
with_dt_all(haast,[onmiddellijk]).
with_dt_all(haast,[uitsluitend]).
with_dt_all(hard,[om]).
with_dt_all(haren,[huize,te]).
with_dt_all(haren,[laste,te]).
with_dt_all(haren,[nadele,te]).
with_dt_all(heel,[in,tijden,vroeger]).
with_dt_all(heel,[wat]).
with_dt_all(helemaal,[niemand]).
with_dt_all(helemaal,[niet]).
with_dt_all(helemaal,[niets]).
with_dt_all(helemaal,[niks]).
with_dt_all(helemaal,[ongelijk]).
with_dt_all(hen,[negen]).
with_dt_all(hen,[negentien]).
with_dt_all(hen,[tien]).
with_dt_all(hen,[twaalf]).
with_dt_all(hen,[twee]).
with_dt_all(hen,[twee_DIM]).
with_dt_all(hen,[twintig]).
with_dt_all(hen,[veertien]).
with_dt_all(hen,[vier]).
with_dt_all(hen,[vier_DIM]).
with_dt_all(hen,[vijf]).
with_dt_all(hen,[vijf_DIM]).
with_dt_all(hen,[vijftien]).
with_dt_all(hen,[zes]).
with_dt_all(hen,[zes_DIM]).
with_dt_all(hen,[zestien]).
with_dt_all(hen,[zeven]).
with_dt_all(hen,[zeventien]).
with_dt_all(het,[één]).
with_dt_all(het,[ik]).
with_dt_all(het,[ik,weet]).
with_dt_all(het,[in,klein]).
with_dt_all(het,[in,kort]).
with_dt_all(het,[in,lang]).
with_dt_all(het,[laatst,toe,tot]).
with_dt_all(het,[laatst,tot]).
with_dt_all(het,[nu]).
with_dt_all(het,[zelf]).
with_dt_all(heus,[niet]).
with_dt_all(heus,[niet,overal]).
with_dt_all(hieraan,[vooraf]).
with_dt_all(hoegenaamd,[niet]).
with_dt_all(hoegenaamd,[niet,overal]).
with_dt_all(hoelaat,[tot]).
with_dt_all(hoelang,[ik,niet,weet]).
with_dt_all(hoelang,[voor]).
with_dt_all(hoeveel,[hun,met]).
with_dt_all(hoeveel,[ik,niet,weet]).
with_dt_all(hoeveel,[jullie,met]).
with_dt_all(hoeveel,[met,ons]).
with_dt_all(hoeveel,[met,zijn]).
with_dt_all(hoeveel,[met,'z\'n']).
with_dt_all(hoever,[in]).
with_dt_all(hoeverre,[in]).
with_dt_all(hoever,[tot]).
with_dt_all(hoever,[voor]).
with_dt_all(hoog,[of]).
with_dt_all(hoor,[voor,wat,wat]).
with_dt_all(huize,[mijnen,te]).
with_dt_all(huize,[te,uwen]).
with_dt_all(huize,[te,zijnen]).
with_dt_all(hun,[man]).
with_dt_all(hun,[met,negen]).
with_dt_all(hun,[met,negentien]).
with_dt_all(hun,[met,tien]).
with_dt_all(hun,[met,twaalf]).
with_dt_all(hun,[met,twee]).
with_dt_all(hun,[met,twee_DIM]).
with_dt_all(hun,[met,twintig]).
with_dt_all(hun,[met,veertien]).
with_dt_all(hun,[met,vier]).
with_dt_all(hun,[met,vier_DIM]).
with_dt_all(hun,[met,vijf]).
with_dt_all(hun,[met,vijf_DIM]).
with_dt_all(hun,[met,vijftien]).
with_dt_all(hun,[met,zes]).
with_dt_all(hun,[met,zes_DIM]).
with_dt_all(hun,[met,zestien]).
with_dt_all(hun,[met,zeven]).
with_dt_all(hun,[met,zeventien]).
with_dt_all(hun,[minnaar]).
with_dt_all(hun,[moeder]).
with_dt_all(hun,[negen]).
with_dt_all(hun,[negentien]).
with_dt_all(hun,[oma]).
with_dt_all(hun,[opa]).
with_dt_all(hun,[stief_moeder]).
with_dt_all(hun,[stief_vader]).
with_dt_all(hun,[tante]).
with_dt_all(hun,[tien]).
with_dt_all(hun,[twaalf]).
with_dt_all(hun,[twee]).
with_dt_all(hun,[twee_DIM]).
with_dt_all(hun,[twintig]).
with_dt_all(hun,[vader]).
with_dt_all(hun,[veertien]).
with_dt_all(hun,[vier]).
with_dt_all(hun,[vier_DIM]).
with_dt_all(hun,[vijf]).
with_dt_all(hun,[vijf_DIM]).
with_dt_all(hun,[vijftien]).
with_dt_all(hun,[vriend]).
with_dt_all(hun,[vriendin]).
with_dt_all(hun,[zes]).
with_dt_all(hun,[zes_DIM]).
with_dt_all(hun,[zestien]).
with_dt_all(hun,[zeven]).
with_dt_all(hun,[zeventien]).
with_dt_all(hun,[zuster]).
with_dt_all(iedereen,[lang,niet]).
with_dt_all(iedereen,[niet]).
with_dt_all(iedere,[paar]).
with_dt_all(iemand,[zo]).
with_dt_all(iets,[of,soortgelijks]).
with_dt_all(ik,[lyrisch]).
with_dt_all(ik,[moet,zeg]).
with_dt_all(ik,[niet,waar,weet]).
with_dt_all(ik,[niet,weet,welk]).
with_dt_all(ik,[nieuw]).
with_dt_all(ik,[oud]).
with_dt_all(ik,[vermoed]).
with_dt_all(ik,[vind]).
with_dt_all(ik,[vrees]).
with_dt_all(ik,[waar]).
with_dt_all(ik,[weet]).
with_dt_all(ik,[zal,zeg]).
with_dt_all(ik,[zeg]).
with_dt_all('in die mate',[zelfs]).
with_dt_all('in dier voege',[zelfs]).
with_dt_all(in,[levende,lijve]).
with_dt_all(in,[levenden,lijve]).
with_dt_all(in,[punt]).
with_dt_all(in,[ruste]).
with_dt_all('in tegenstelling tot',[vroeg]).
with_dt_all(in,[tijden,vroeger]).
with_dt_all(in,[totaal]).
with_dt_all(inzoverre,[zelfs]).
with_dt_all(ja,[nee,of]).
with_dt_all(je,[man]).
with_dt_all(je,[minnaar]).
with_dt_all(je,[moeder]).
with_dt_all(je,[noem,wat]).
with_dt_all(je,[oma]).
with_dt_all(je,[opa]).
with_dt_all(je,[stief_moeder]).
with_dt_all(je,[stief_vader]).
with_dt_all(je,[tante]).
with_dt_all(je,[vader]).
with_dt_all(je,[vriend]).
with_dt_all(je,[vriendin]).
with_dt_all(je,[weet]).
with_dt_all(je,[zuster]).
with_dt_all(jongsaf,[sinds]).
with_dt_all(jongsaf,[van]).
with_dt_all(jou,[man]).
with_dt_all(jou,[minnaar]).
with_dt_all(jou,[moeder]).
with_dt_all(jou,[oma]).
with_dt_all(jou,[opa]).
with_dt_all(jou,[stief_moeder]).
with_dt_all(jou,[stief_vader]).
with_dt_all(jou,[tante]).
with_dt_all(jou,[vader]).
with_dt_all(jou,[vriend]).
with_dt_all(jou,[vriendin]).
with_dt_all(jou,[zuster]).
with_dt_all(jullie,[man]).
with_dt_all(jullie,[met,negen]).
with_dt_all(jullie,[met,negentien]).
with_dt_all(jullie,[met,tien]).
with_dt_all(jullie,[met,twaalf]).
with_dt_all(jullie,[met,twee]).
with_dt_all(jullie,[met,twee_DIM]).
with_dt_all(jullie,[met,twintig]).
with_dt_all(jullie,[met,veertien]).
with_dt_all(jullie,[met,vier]).
with_dt_all(jullie,[met,vier_DIM]).
with_dt_all(jullie,[met,vijf]).
with_dt_all(jullie,[met,vijf_DIM]).
with_dt_all(jullie,[met,vijftien]).
with_dt_all(jullie,[met,zes]).
with_dt_all(jullie,[met,zes_DIM]).
with_dt_all(jullie,[met,zestien]).
with_dt_all(jullie,[met,zeven]).
with_dt_all(jullie,[met,zeventien]).
with_dt_all(jullie,[minnaar]).
with_dt_all(jullie,[moeder]).
with_dt_all(jullie,[negen]).
with_dt_all(jullie,[negentien]).
with_dt_all(jullie,[oma]).
with_dt_all(jullie,[opa]).
with_dt_all(jullie,[stief_moeder]).
with_dt_all(jullie,[stief_vader]).
with_dt_all(jullie,[tante]).
with_dt_all(jullie,[tien]).
with_dt_all(jullie,[twaalf]).
with_dt_all(jullie,[twee]).
with_dt_all(jullie,[twee_DIM]).
with_dt_all(jullie,[twintig]).
with_dt_all(jullie,[vader]).
with_dt_all(jullie,[veertien]).
with_dt_all(jullie,[vier]).
with_dt_all(jullie,[vier_DIM]).
with_dt_all(jullie,[vijf]).
with_dt_all(jullie,[vijf_DIM]).
with_dt_all(jullie,[vijftien]).
with_dt_all(jullie,[vriend]).
with_dt_all(jullie,[vriendin]).
with_dt_all(jullie,[zes]).
with_dt_all(jullie,[zes_DIM]).
with_dt_all(jullie,[zestien]).
with_dt_all(jullie,[zeven]).
with_dt_all(jullie,[zeventien]).
with_dt_all(jullie,[zuster]).
with_dt_all(ken,[ons,ons]).
with_dt_all(kindsaf,[sinds]).
with_dt_all(kindsaf,[van]).
with_dt_all(klasse,[tweede]).
with_dt_all(klasse,[vierde]).
with_dt_all(klas,[tweede]).
with_dt_all(klas,[vierde]).
with_dt_all(kleinsaf,[sinds]).
with_dt_all(kleinsaf,[van]).
with_dt_all(koets,[te]).
with_dt_all(kooi,[te]).
with_dt_all(laat,[we,zeg]).
with_dt_all(lande,[te]).
with_dt_all(lande,[ten]).
with_dt_all(land,[te]).
with_dt_all(lang,[niet]).
with_dt_all(lang,[niet,overal]).
with_dt_all(laste,[mijnen,te]).
with_dt_all(laste,[ten]).
with_dt_all(laste,[te,uwen]).
with_dt_all(laste,[te,zijnen]).
with_dt_all(later,[vanavond]).
with_dt_all(later,[vandaag]).
with_dt_all(later,[vanmiddag]).
with_dt_all(later,[vanmorgen]).
with_dt_all(later,[vannacht]).
with_dt_all(later,[vanochtend]).
with_dt_all(leider,[politiek]).
with_dt_all(lief,[niet]).
with_dt_all(lijf,[te]).
with_dt_all(lijk,[me]).
with_dt_all(lijk,[mij]).
with_dt_all(linkerzijde,[te]).
with_dt_all(maak,[onbekend,onbemind]).
with_dt_all(majesteit,[zijn]).
with_dt_all(mam,[ons]).
with_dt_all(man,[mijn]).
with_dt_all(man,[u]).
with_dt_all(man,[zijn]).
with_dt_all(ma,[ons]).
with_dt_all(meerdere,[of,één]).
with_dt_all(men,[zie]).
with_dt_all(meteen,[vrijwel]).
with_dt_all(met,[negen,ons]).
with_dt_all(met,[negentien,ons]).
with_dt_all(met,[negentien,zijn]).
with_dt_all(met,[negentien,'z\'n']).
with_dt_all(met,[negen,zijn]).
with_dt_all(met,[negen,'z\'n']).
with_dt_all(met,[ons,tien]).
with_dt_all(met,[ons,twaalf]).
with_dt_all(met,[ons,twee]).
with_dt_all(met,[ons,twee_DIM]).
with_dt_all(met,[ons,twintig]).
with_dt_all(met,[ons,veertien]).
with_dt_all(met,[ons,vier]).
with_dt_all(met,[ons,vier_DIM]).
with_dt_all(met,[ons,vijf]).
with_dt_all(met,[ons,vijf_DIM]).
with_dt_all(met,[ons,vijftien]).
with_dt_all(met,[ons,zes]).
with_dt_all(met,[ons,zes_DIM]).
with_dt_all(met,[ons,zestien]).
with_dt_all(met,[ons,zeven]).
with_dt_all(met,[ons,zeventien]).
with_dt_all(met,[tien,zijn]).
with_dt_all(met,[tien,'z\'n']).
with_dt_all(met,[toen]).
with_dt_all(met,[twaalf,zijn]).
with_dt_all(met,[twaalf,'z\'n']).
with_dt_all(met,[twee_DIM,zijn]).
with_dt_all(met,[twee_DIM,'z\'n']).
with_dt_all(met,[twee,zijn]).
with_dt_all(met,[twee,'z\'n']).
with_dt_all(met,[twintig,zijn]).
with_dt_all(met,[twintig,'z\'n']).
with_dt_all(met,[veertien,zijn]).
with_dt_all(met,[veertien,'z\'n']).
with_dt_all(met,[vier_DIM,zijn]).
with_dt_all(met,[vier_DIM,'z\'n']).
with_dt_all(met,[vier,zijn]).
with_dt_all(met,[vier,'z\'n']).
with_dt_all(met,[vijf_DIM,zijn]).
with_dt_all(met,[vijf_DIM,'z\'n']).
with_dt_all(met,[vijftien,zijn]).
with_dt_all(met,[vijftien,'z\'n']).
with_dt_all(met,[vijf,zijn]).
with_dt_all(met,[vijf,'z\'n']).
with_dt_all(met,[vroeger]).
with_dt_all(met,[zes_DIM,zijn]).
with_dt_all(met,[zestien,zijn]).
with_dt_all(met,[zes,zijn]).
with_dt_all(met,[zeventien,zijn]).
with_dt_all(met,[zeven,zijn]).
with_dt_all(met,['z\'n',zes]).
with_dt_all(met,['z\'n',zes_DIM]).
with_dt_all(met,['z\'n',zestien]).
with_dt_all(met,['z\'n',zeven]).
with_dt_all(met,['z\'n',zeventien]).
with_dt_all(mijnen,[nadele,te]).
with_dt_all(mijn,[minnaar]).
with_dt_all(mijn,[moeder]).
with_dt_all(mijn,[oma]).
with_dt_all(mijn,[opa]).
with_dt_all(mijn,[stief_moeder]).
with_dt_all(mijn,[stief_vader]).
with_dt_all(mijn,[tante]).
with_dt_all(mijn,[vader]).
with_dt_all(mijn,[vriend]).
with_dt_all(mijn,[vriendin]).
with_dt_all(mijn,[zuster]).
with_dt_all(miljoen,[één]).
with_dt_all(min,[mogelijk,zo]).
with_dt_all(minnaar,[u]).
with_dt_all(minnaar,[zijn]).
with_dt_all(misschien,[vandaar]).
with_dt_all(misschien,[wel]).
with_dt_all(misschien,[zelfs]).
with_dt_all(moeder_DIM,[natuur]).
with_dt_all(moeder,[natuur]).
with_dt_all(moeder,[ons]).
with_dt_all(moeder,[u]).
with_dt_all(moeder,[zijn]).
with_dt_all(mogelijk,[zo]).
with_dt_all(mogelijk,[zogauw]).
with_dt_all(mogelijk,[zolang]).
with_dt_all(mogelijk,[zomin]).
with_dt_all(mogelijk,[zoveel]).
with_dt_all(mooi,[niet]).
with_dt_all(mooi,[niet,overal]).
with_dt_all('\'n',[aantal]).
with_dt_all('\'n',[aantal,beperkt]).
with_dt_all('\'n',[aantal,enorm]).
with_dt_all('\'n',[aantal,flink]).
with_dt_all('\'n',[aantal,groot]).
with_dt_all('\'n',[aantal,klein]).
with_dt_all('\'n',[aantal,respectabel]).
with_dt_all(naar,[verwachting]).
with_dt_all(nadele,[te,uwen]).
with_dt_all(nadele,[te,zijnen]).
with_dt_all(nature,[van]).
with_dt_all(natuurlijk,[niet]).
with_dt_all(natuurlijk,[niet,overal]).
with_dt_all(natuurlijk,[vandaar]).
with_dt_all(na,[twee]).
with_dt_all(na,[vier]).
with_dt_all(na,[vijf]).
with_dt_all(na,[zes]).
with_dt_all('\'n',[biljoen,paar]).
with_dt_all('\'n',[boel]).
with_dt_all('\'n',[duizend,paar]).
with_dt_all(negen,[ons]).
with_dt_all(negentien,[ons]).
with_dt_all(negentien,[u]).
with_dt_all(negentien,[wij]).
with_dt_all(negentien,[zij]).
with_dt_all(negen,[u]).
with_dt_all(negen,[wij]).
with_dt_all(negen,[zij]).
with_dt_all('\'n',[handvol]).
with_dt_all('\'n',[heleboel]).
with_dt_all('\'n',[hele,hoop]).
with_dt_all('\'n',[honderdduizend,paar]).
with_dt_all('\'n',[honderd,paar]).
with_dt_all('\'n',[hoop]).
with_dt_all(niet,[één]).
with_dt_all(niet,[nog]).
with_dt_all(niet,[of]).
with_dt_all(niet,[of,toch]).
with_dt_all(niet,[overal]).
with_dt_all(niet,[overal,toch]).
with_dt_all(niet,[overal,vast]).
with_dt_all(niet,[overal,volstrekt]).
with_dt_all(niet,[overal,waarachtig]).
with_dt_all(niet,[overal,waarschijnlijk]).
with_dt_all(niet,[overal,wellicht]).
with_dt_all(niet,[overal,werkelijk]).
with_dt_all(niet,[overal,zeker]).
with_dt_all(niet,[reden,zonder]).
with_dt_all(niets,[voor]).
with_dt_all(niet,[temeer]).
with_dt_all(niet,['te veel']).
with_dt_all(niet,[te,vergeet]).
with_dt_all(niet,[toch]).
with_dt_all(niet,[vaak]).
with_dt_all(niet,[vast]).
with_dt_all(niet,[veel]).
with_dt_all(niet,[ver]).
with_dt_all(niet,[volstrekt]).
with_dt_all(niet,[vooral]).
with_dt_all(niet,[waarachtig]).
with_dt_all(niet,[waarom]).
with_dt_all(niet,[waarschijnlijk]).
with_dt_all(niet,[wellicht]).
with_dt_all(niet,[werkelijk]).
with_dt_all(niet,[zeker]).
with_dt_all(niet,[zelden]).
with_dt_all(niet,[zonder]).
with_dt_all(niet,[zozeer]).
with_dt_all(nieuw,[stijl]).
with_dt_all('\'n',[miljard,paar]).
with_dt_all('\'n',[miljoen]).
with_dt_all('\'n',[miljoen,paar]).
with_dt_all(nodig,[zo]).
with_dt_all(nogal,[vaak]).
with_dt_all(nog,[toe,tot]).
with_dt_all(nooit,[of,zelden]).
with_dt_all(nooit,[voorheen]).
with_dt_all('\'n',[paar]).
with_dt_all('\'n',[pak]).
with_dt_all('\'n',[reeks]).
with_dt_all('\'n',[soort]).
with_dt_all('\'n',[stel]).
with_dt_all('\'n',[stelletje]).
with_dt_all(nummer,[positie,één]).
with_dt_all(nu,[waarom,weer]).
with_dt_all(of,[omgekeerd]).
with_dt_all(of,[veel,één]).
with_dt_all(of,['vice versa']).
with_dt_all(of,[wat,wie]).
with_dt_all(of,[wel]).
with_dt_all(of,[zo]).
with_dt_all(of,['zo iets']).
with_dt_all(of,[zoiets]).
with_dt_all(oma,[u]).
with_dt_all(oma,[zijn]).
with_dt_all(onderweg,[voor]).
with_dt_all(oneindig,[op]).
with_dt_all(ongeveer,[zo]).
with_dt_all(onlangs,[zeer]).
with_dt_all(onmiddellijk,[per]).
with_dt_all(onmiddellijk,[vrijwel]).
with_dt_all(ons,[pa]).
with_dt_all(ons,[pap]).
with_dt_all(ons,[tien]).
with_dt_all(ons,[twaalf]).
with_dt_all(ons,[twee]).
with_dt_all(ons,[twee_DIM]).
with_dt_all(ons,[twintig]).
with_dt_all(ons,[vader]).
with_dt_all(ons,[veertien]).
with_dt_all(ons,[vier]).
with_dt_all(ons,[vier_DIM]).
with_dt_all(ons,[vijf]).
with_dt_all(ons,[vijf_DIM]).
with_dt_all(ons,[vijftien]).
with_dt_all(ons,[zes]).
with_dt_all(ons,[zes_DIM]).
with_dt_all(ons,[zestien]).
with_dt_all(ons,[zeven]).
with_dt_all(ons,[zeventien]).
with_dt_all(onzent,[te]).
with_dt_all(onzent,[ten]).
with_dt_all(ook,[vandaar]).
with_dt_all(ook,[vooral]).
with_dt_all(ook,[vooral,weer]).
with_dt_all(ook,[zelf]).
with_dt_all(opa,[u]).
with_dt_all(opa,[zijn]).
with_dt_all(opnieuw,[steeds]).
with_dt_all(opnieuw,[telkens]).
with_dt_all(op,[vandaag]).
with_dt_all(op,[zich]).
with_dt_all(oudsher,[van]).
with_dt_all(oud,[stijl]).
with_dt_all(overheidswege,[van]).
with_dt_all(over,[vroeger]).
with_dt_all(paard,[te]).
with_dt_all(plekke,[ter]).
with_dt_all(pronk,[te]).
with_dt_all(raad,[voorbedacht]).
with_dt_all(rade,[te]).
with_dt_all(rechterzijde,[te]).
with_dt_all(rechtswege,[van]).
with_dt_all(regeringswege,[van]).
with_dt_all(rijkswege,[van]).
with_dt_all(ruste,[te]).
with_dt_all(samen,[samen,thuis,uit]).
with_dt_all(soort,[zulk]).
with_dt_all(staatswege,[van]).
with_dt_all(stede,[ter]).
with_dt_all(steeds,[waarom,weer]).
with_dt_all(steeds,[weer]).
with_dt_all(stief_moeder,[u]).
with_dt_all(stief_moeder,[zijn]).
with_dt_all(stief_vader,[u]).
with_dt_all(stief_vader,[zijn]).
with_dt_all(stijl,[vrij]).
with_dt_all(strijde,[ten]).
with_dt_all(tante,[u]).
with_dt_all(tante,[zijn]).
with_dt_all(telkens,[weer]).
with_dt_all('ten overvloede',[wellicht]).
with_dt_all(te,[veel]).
with_dt_all(te,[velde]).
with_dt_all(te,[voet]).
with_dt_all(te,[water]).
with_dt_all(te,[wereld]).
with_dt_all(te,[zeer]).
with_dt_all(tien,[u]).
with_dt_all(tien,[wij]).
with_dt_all(tien,[zij]).
with_dt_all(toch,[vanwaar]).
with_dt_all(toch,[waarom]).
with_dt_all(tot,[zo]).
with_dt_all(twaalf,[u]).
with_dt_all(twaalf,[wij]).
with_dt_all(twaalf,[zij]).
with_dt_all(twee_DIM,[u]).
with_dt_all(twee_DIM,[wij]).
with_dt_all(twee_DIM,[zij]).
with_dt_all(twee,[u]).
with_dt_all(twee,[wij]).
with_dt_all(twee,[zij]).
with_dt_all(twintig,[u]).
with_dt_all(twintig,[wij]).
with_dt_all(twintig,[zij]).
with_dt_all(uitsluitend,[vrijwel]).
with_dt_all(u,[vader]).
with_dt_all(u,[veertien]).
with_dt_all(u,[vier]).
with_dt_all(u,[vier_DIM]).
with_dt_all(u,[vijf]).
with_dt_all(u,[vijf_DIM]).
with_dt_all(u,[vijftien]).
with_dt_all(u,[vriend]).
with_dt_all(u,[vriendin]).
with_dt_all(u,[zes]).
with_dt_all(u,[zes_DIM]).
with_dt_all(u,[zestien]).
with_dt_all(u,[zeven]).
with_dt_all(u,[zeventien]).
with_dt_all(u,[zuster]).
with_dt_all(vaak,[zeer]).
with_dt_all(vader,[zijn]).
with_dt_all(vandaar,[waarschijnlijk]).
with_dt_all(vandaar,[wellicht]).
with_dt_all('van dien aard',[zelfs]).
with_dt_all(van,[weggeweest]).
with_dt_all(van,[zulk]).
with_dt_all(veertien,[wij]).
with_dt_all(veertien,[zij]).
with_dt_all(vier_DIM,[wij]).
with_dt_all(vier_DIM,[zij]).
with_dt_all(vier,[wij]).
with_dt_all(vier,[zij]).
with_dt_all(vijf_DIM,[wij]).
with_dt_all(vijf_DIM,[zij]).
with_dt_all(vijftien,[wij]).
with_dt_all(vijftien,[zij]).
with_dt_all(vijf,[wij]).
with_dt_all(vijf,[zij]).
with_dt_all(vooraf,[waaraan]).
with_dt_all(vriendin,[zijn]).
with_dt_all(vriend,[zijn]).
with_dt_all(wel,[zeer]).
with_dt_all(wij,[zes]).
with_dt_all(wij,[zes_DIM]).
with_dt_all(wij,[zestien]).
with_dt_all(wij,[zeven]).
with_dt_all(wij,[zeventien]).
with_dt_all(zelfs,[zo]).
with_dt_all(zelfs,[zodanig]).
with_dt_all(zelfs,[zolang]).
with_dt_all(zelfs,[zoveel]).
with_dt_all(zelfs,[zover]).
with_dt_all(zelfs,[zozeer]).
with_dt_all(zes_DIM,[zij]).
with_dt_all(zestien,[zij]).
with_dt_all(zes,[zij]).
with_dt_all(zeventien,[zij]).
with_dt_all(zeven,[zij]).
with_dt_all(zijn,[zuster]).
with_dt_all('zo\'n',[zorg]).
with_dt_root('0').
with_dt_root('00').
with_dt_root('0,1').
with_dt_root('0,2').
with_dt_root('0,26').
with_dt_root('0,3').
with_dt_root('\'04').
with_dt_root('0,49').
with_dt_root('0,5').
with_dt_root('1').
with_dt_root('10').
with_dt_root('100').
with_dt_root('1000').
with_dt_root('10.000').
with_dt_root('100.000').
with_dt_root('105').
with_dt_root('11').
with_dt_root('110').
with_dt_root('1100').
with_dt_root('115').
with_dt_root('1,2').
with_dt_root('12').
with_dt_root('120').
with_dt_root('1200').
with_dt_root('12.000').
with_dt_root('125').
with_dt_root('13').
with_dt_root('130').
with_dt_root('1300').
with_dt_root('136').
with_dt_root('\'14').
with_dt_root('14').
with_dt_root('140').
with_dt_root('1400').
with_dt_root('1,49').
with_dt_root('1,5').
with_dt_root('15').
with_dt_root('150').
with_dt_root('1500').
with_dt_root('15.000').
with_dt_root('150.000').
with_dt_root('1,6').
with_dt_root('16').
with_dt_root('16°').
with_dt_root('160').
with_dt_root('1600').
with_dt_root('17').
with_dt_root('170').
with_dt_root('1700').
with_dt_root('\'18').
with_dt_root('1,8').
with_dt_root('18').
with_dt_root('180').
with_dt_root('1880').
with_dt_root('1889').
with_dt_root('1890').
with_dt_root('1,9').
with_dt_root('19').
with_dt_root('1900').
with_dt_root('1903').
with_dt_root('1914').
with_dt_root('1918').
with_dt_root('1919').
with_dt_root('1920').
with_dt_root('1930').
with_dt_root('1936').
with_dt_root('1939').
with_dt_root('1940').
with_dt_root('1941').
with_dt_root('1944').
with_dt_root('1945').
with_dt_root('1948').
with_dt_root('1950').
with_dt_root('1952').
with_dt_root('1955').
with_dt_root('1956').
with_dt_root('1957').
with_dt_root('1960').
with_dt_root('1961').
with_dt_root('1965').
with_dt_root('1966').
with_dt_root('1967').
with_dt_root('1968').
with_dt_root('1970').
with_dt_root('1973').
with_dt_root('1975').
with_dt_root('1977').
with_dt_root('1978').
with_dt_root('1979').
with_dt_root('1980').
with_dt_root('1981').
with_dt_root('1985').
with_dt_root('1986').
with_dt_root('1988').
with_dt_root('1989').
with_dt_root('1990').
with_dt_root('1991').
with_dt_root('1992').
with_dt_root('1993').
with_dt_root('1994').
with_dt_root('1995').
with_dt_root('1996').
with_dt_root('1997').
with_dt_root('1998').
with_dt_root('1999').
with_dt_root('1e').
with_dt_root('2').
with_dt_root('20').
with_dt_root('200').
with_dt_root('2.000').
with_dt_root('2000').
with_dt_root('20.000').
with_dt_root('200.000').
with_dt_root('2001').
with_dt_root('2002').
with_dt_root('2003').
with_dt_root('2004').
with_dt_root('2005').
with_dt_root('2006').
with_dt_root('2007').
with_dt_root('2008').
with_dt_root('2009').
with_dt_root('2010').
with_dt_root('2011').
with_dt_root('2012').
with_dt_root('2013').
with_dt_root('2014').
with_dt_root('2015').
with_dt_root('2016').
with_dt_root('2018').
with_dt_root('2020').
with_dt_root('2030').
with_dt_root('2050').
with_dt_root('21').
with_dt_root('21/2').
with_dt_root('22').
with_dt_root('220').
with_dt_root('2200').
with_dt_root('2250').
with_dt_root('23').
with_dt_root('24').
with_dt_root('2,5').
with_dt_root('25').
with_dt_root('250').
with_dt_root('2.500').
with_dt_root('2500').
with_dt_root('25.000').
with_dt_root('25000').
with_dt_root('250.000').
with_dt_root('26').
with_dt_root('27').
with_dt_root('270').
with_dt_root('28').
with_dt_root('29').
with_dt_root('2e').
with_dt_root('3').
with_dt_root('30').
with_dt_root('300').
with_dt_root('3.000').
with_dt_root('3000').
with_dt_root('30.000').
with_dt_root('30000').
with_dt_root('300.000').
with_dt_root('31').
with_dt_root('32').
with_dt_root('320').
with_dt_root('33').
with_dt_root('34').
with_dt_root('3,5').
with_dt_root('35').
with_dt_root('350').
with_dt_root('3.500').
with_dt_root('3500').
with_dt_root('35.000').
with_dt_root('36').
with_dt_root('37').
with_dt_root('38').
with_dt_root('38,8').
with_dt_root('39').
with_dt_root('3e').
with_dt_root('4').
with_dt_root('\'40').
with_dt_root('40').
with_dt_root('400').
with_dt_root('4.000').
with_dt_root('4000').
with_dt_root('40.000').
with_dt_root('400.000').
with_dt_root('41/2').
with_dt_root('42').
with_dt_root('\'45').
with_dt_root('4,5').
with_dt_root('45').
with_dt_root('450').
with_dt_root('45.000').
with_dt_root('480').
with_dt_root('49').
with_dt_root('4e').
with_dt_root('5').
with_dt_root('50').
with_dt_root('500').
with_dt_root('5.000').
with_dt_root('5000').
with_dt_root('50.000').
with_dt_root('500.000').
with_dt_root('5,2').
with_dt_root('\'54').
with_dt_root('540').
with_dt_root('5,5').
with_dt_root('55').
with_dt_root('550').
with_dt_root('\'56').
with_dt_root('\'58').
with_dt_root('5,8').
with_dt_root('6').
with_dt_root('\'60').
with_dt_root('60').
with_dt_root('600').
with_dt_root('6000').
with_dt_root('60.000').
with_dt_root('600.000').
with_dt_root('\'61').
with_dt_root('64').
with_dt_root('640').
with_dt_root('6,5').
with_dt_root('65').
with_dt_root('68').
with_dt_root('7').
with_dt_root('\'70').
with_dt_root('70').
with_dt_root('700').
with_dt_root('7.000').
with_dt_root('7000').
with_dt_root('70.000').
with_dt_root('700.000').
with_dt_root('75').
with_dt_root('750').
with_dt_root('8').
with_dt_root('80').
with_dt_root('800').
with_dt_root('8.000').
with_dt_root('8000').
with_dt_root('80.000').
with_dt_root('800.000').
with_dt_root('85').
with_dt_root('854').
with_dt_root('\'89').
with_dt_root('9').
with_dt_root('\'90').
with_dt_root('90').
with_dt_root('900').
with_dt_root('9000').
with_dt_root('900.000').
with_dt_root('\'91').
with_dt_root('\'92').
with_dt_root('\'93').
with_dt_root('\'94').
with_dt_root('\'95').
with_dt_root('95').
with_dt_root('\'96').
with_dt_root('960').
with_dt_root('\'97').
with_dt_root('97').
with_dt_root('\'98').
with_dt_root('98').
with_dt_root('\'99').
with_dt_root(aan).
with_dt_root('aan af').
with_dt_root(aanschijn).
with_dt_root(aantal).
with_dt_root(aanverwant).
with_dt_root(aanzien).
with_dt_root(aard).
with_dt_root(aarde).
with_dt_root(absoluut).
with_dt_root(acht).
with_dt_root(achttien).
with_dt_root(af).
with_dt_root('af aan').
with_dt_root(afstand).
with_dt_root(al).
with_dt_root(alle).
with_dt_root(allebei).
with_dt_root(alledag).
with_dt_root(alleen).
with_dt_root(allemaal).
with_dt_root(allen).
with_dt_root(alles).
with_dt_root(allicht).
with_dt_root(als).
with_dt_root(altijd).
with_dt_root(ander).
with_dt_root(andermans).
with_dt_root(andersom).
with_dt_root(anderszins).
with_dt_root(anno).
with_dt_root(arm).
with_dt_root(artistiek).
with_dt_root(baan).
with_dt_root(bed).
with_dt_root(bedde).
with_dt_root(bedoel).
with_dt_root(beginne).
with_dt_root(begrijp).
with_dt_root(beide).
with_dt_root(beide_DIM).
with_dt_root(bekend).
with_dt_root(beloofd).
with_dt_root(bemind).
with_dt_root(ben).
with_dt_root(bepaald).
with_dt_root(beperkt).
with_dt_root(beslist).
with_dt_root(best).
with_dt_root(biecht).
with_dt_root(bij).
with_dt_root(bijna).
with_dt_root(bijzonder).
with_dt_root('bij zoverre').
with_dt_root(biljoen).
with_dt_root(binnen).
with_dt_root(binnenkort).
with_dt_root(binnenland).
with_dt_root(blij).
with_dt_root(blik).
with_dt_root(blind).
with_dt_root(bloede).
with_dt_root(bloos).
with_dt_root(boel).
with_dt_root(bovengenoemd).
with_dt_root(breed).
with_dt_root(brode).
with_dt_root(broeder).
with_dt_root(broer).
with_dt_root(buiten).
with_dt_root(buitenland).
with_dt_root(communie).
with_dt_root(daaraan).
with_dt_root(daarmee).
with_dt_root(daarom).
with_dt_root(daaromtrent).
with_dt_root(dag).
with_dt_root(dage).
with_dt_root(dame).
with_dt_root(dan).
with_dt_root(dat).
with_dt_root(de).
with_dt_root(decennium).
with_dt_root(deel).
with_dt_root(degeen).
with_dt_root(degelijk).
with_dt_root(den).
with_dt_root(denk).
with_dt_root(derde).
with_dt_root(dergelijk).
with_dt_root(dergelijks).
with_dt_root(dermate).
with_dt_root(dertien).
with_dt_root(dertig).
with_dt_root('des te').
with_dt_root(deze).
with_dt_root(dichter).
with_dt_root(die).
with_dt_root(dien).
with_dt_root(diep).
with_dt_root(dikwijls).
with_dt_root(direct).
with_dt_root(direkt).
with_dt_root(dit).
with_dt_root(doe).
with_dt_root(doen).
with_dt_root(dood).
with_dt_root(draai).
with_dt_root(drie).
with_dt_root(drie_DIM).
with_dt_root(driehonderd).
with_dt_root(duizend).
with_dt_root(dunk).
with_dt_root(dus).
with_dt_root(dusdanig).
with_dt_root(duur).
with_dt_root(dwaal).
with_dt_root(echt).
with_dt_root(echter).
with_dt_root(ede).
with_dt_root(een).
with_dt_root(één).
with_dt_root(eens).
with_dt_root(eentje).
with_dt_root(eerder).
with_dt_root(eerlijk).
with_dt_root(eerst).
with_dt_root(eerste).
with_dt_root(eeuwig).
with_dt_root(eigen).
with_dt_root(eigenlijk).
with_dt_root(einde).
with_dt_root(elf).
with_dt_root(elkaar).
with_dt_root(elke).
with_dt_root(en).
with_dt_root(enorm).
with_dt_root(eraan).
with_dt_root(ere).
with_dt_root(erg).
with_dt_root(fabriek).
with_dt_root(fiets).
with_dt_root(flink).
with_dt_root(ga).
with_dt_root(gebeur).
with_dt_root(geef_toe).
with_dt_root(geen).
with_dt_root(gelijk).
with_dt_root(geloof).
with_dt_root(gemeentewege).
with_dt_root(genoeg).
with_dt_root(geval).
with_dt_root(giet).
with_dt_root(gij).
with_dt_root(ginder).
with_dt_root(gisteravond).
with_dt_root(gisteren).
with_dt_root(gisterenavond).
with_dt_root(gisterenmiddag).
with_dt_root(gisterenmorgen).
with_dt_root(gisterennacht).
with_dt_root(gisterenochtend).
with_dt_root(gistermiddag).
with_dt_root(gistermorgen).
with_dt_root(gisternacht).
with_dt_root(gisterochtend).
with_dt_root(god).
with_dt_root(goed).
with_dt_root(goede).
with_dt_root(goeden).
with_dt_root(goedenavond).
with_dt_root(graag).
with_dt_root(grabbel).
with_dt_root(groen).
with_dt_root(groot).
with_dt_root(grootmoeder).
with_dt_root(grootvader).
with_dt_root(gunste).
with_dt_root(haar).
with_dt_root(haast).
with_dt_root(handvol).
with_dt_root(hang).
with_dt_root(hard).
with_dt_root('hard drugs').
with_dt_root(haren).
with_dt_root(heb).
with_dt_root(heel).
with_dt_root(heelal).
with_dt_root(heen).
with_dt_root(heer).
with_dt_root(hele).
with_dt_root(heleboel).
with_dt_root(helemaal).
with_dt_root(hemel).
with_dt_root(hen).
with_dt_root(het).
with_dt_root(heus).
with_dt_root(hier).
with_dt_root(hieraan).
with_dt_root(hij).
with_dt_root(hoe).
with_dt_root(hoegenaamd).
with_dt_root(hoelaat).
with_dt_root(hoelang).
with_dt_root(hoeveel).
with_dt_root(hoever).
with_dt_root(hoeverre).
with_dt_root(honderd).
with_dt_root(honderdduizend).
with_dt_root(honderdvijftig).
with_dt_root(hoog).
with_dt_root(hoop).
with_dt_root(hoor).
with_dt_root(huize).
with_dt_root(huizen).
with_dt_root(hun).
with_dt_root(ieder).
with_dt_root(iedere).
with_dt_root(iedereen).
with_dt_root(iemand).
with_dt_root(iets).
with_dt_root(ik).
with_dt_root(in).
with_dt_root('in die mate').
with_dt_root('in dier voege').
with_dt_root(ineens).
with_dt_root('in tegenstelling tot').
with_dt_root(inzoverre).
with_dt_root(ja).
with_dt_root(jaar).
with_dt_root(jammer).
with_dt_root(je).
with_dt_root(jij).
with_dt_root(jong).
with_dt_root(jongs).
with_dt_root(jongsaf).
with_dt_root(jou).
with_dt_root(jullie).
with_dt_root(kap).
with_dt_root(keer).
with_dt_root(keizer).
with_dt_root(ken).
with_dt_root(kinds).
with_dt_root(kindsaf).
with_dt_root(kindsbeen).
with_dt_root(klaar).
with_dt_root(klas).
with_dt_root(klasse).
with_dt_root(klein).
with_dt_root(kleins).
with_dt_root(kleinsaf).
with_dt_root(klok).
with_dt_root(koelen).
with_dt_root(koets).
with_dt_root(kom).
with_dt_root(kom_toe).
with_dt_root(koning).
with_dt_root(koningin).
with_dt_root(kooi).
with_dt_root(kort).
with_dt_root(kraak).
with_dt_root(krom).
with_dt_root(kunnen).
with_dt_root(kwaad).
with_dt_root(laag).
with_dt_root(laat).
with_dt_root(laatst).
with_dt_root(land).
with_dt_root(lande).
with_dt_root(lang).
with_dt_root(langs).
with_dt_root(laste).
with_dt_root(later).
with_dt_root(leer).
with_dt_root(leider).
with_dt_root(leuk).
with_dt_root(leven).
with_dt_root(levende).
with_dt_root(levenden).
with_dt_root(lief).
with_dt_root(liefde).
with_dt_root(lijf).
with_dt_root(lijk).
with_dt_root(lijve).
with_dt_root(linkerzijde).
with_dt_root(lust).
with_dt_root(lyrisch).
with_dt_root(ma).
with_dt_root(maak).
with_dt_root(maal).
with_dt_root(maar).
with_dt_root(majesteit).
with_dt_root(makkelijk).
with_dt_root(mam).
with_dt_root(man).
with_dt_root(me).
with_dt_root(meerdere).
with_dt_root(men).
with_dt_root(met).
with_dt_root(meteen).
with_dt_root(middelbaar).
with_dt_root(mij).
with_dt_root(mijn).
with_dt_root(mijnen).
with_dt_root(miljard).
with_dt_root(miljoen).
with_dt_root(millenium).
with_dt_root(min).
with_dt_root(minnaar).
with_dt_root(mis).
with_dt_root(misschien).
with_dt_root(mits).
with_dt_root(moeder).
with_dt_root(moeder_DIM).
with_dt_root(moeilijk).
with_dt_root(moet).
with_dt_root(mogelijk).
with_dt_root(monnik).
with_dt_root(mooi).
with_dt_root(morgen).
with_dt_root('\'n').
with_dt_root(na).
with_dt_root(naar).
with_dt_root(nadele).
with_dt_root(name).
with_dt_root(nature).
with_dt_root(natuur).
with_dt_root(natuurlijk).
with_dt_root(nauwelijks).
with_dt_root(nee).
with_dt_root(neem_aan).
with_dt_root(negen).
with_dt_root(negentien).
with_dt_root(niemand).
with_dt_root(niet).
with_dt_root(niets).
with_dt_root('niet zo\'n beetje ook').
with_dt_root(nieuw).
with_dt_root(niks).
with_dt_root(nodig).
with_dt_root(noem).
with_dt_root(nog).
with_dt_root(nogal).
with_dt_root(nooit).
with_dt_root(nu).
with_dt_root(nummer).
with_dt_root(of).
with_dt_root(om).
with_dt_root(oma).
with_dt_root(omgekeerd).
with_dt_root(onbekend).
with_dt_root(onbemind).
with_dt_root(ondanks).
with_dt_root(onder).
with_dt_root(onderscheid).
with_dt_root(onderweg).
with_dt_root(onderwijs).
with_dt_root(onecht).
with_dt_root(oneindig).
with_dt_root(ongelijk).
with_dt_root(ongeveer).
with_dt_root(onheil).
with_dt_root(onlangs).
with_dt_root(onmiddellijk).
with_dt_root(ons).
with_dt_root(onzent).
with_dt_root(ook).
with_dt_root(oordeel).
with_dt_root(op).
with_dt_root(opa).
with_dt_root('op grond van').
with_dt_root(opnieuw).
with_dt_root(opzichte).
with_dt_root(oud).
with_dt_root(oudsher).
with_dt_root(over).
with_dt_root(overal).
with_dt_root(overheidswege).
with_dt_root(overvloed).
with_dt_root(pa).
with_dt_root(paar).
with_dt_root(paard).
with_dt_root(pak).
with_dt_root(pap).
with_dt_root(per).
with_dt_root(persoon).
with_dt_root(plaats).
with_dt_root(plekke).
with_dt_root(plezant).
with_dt_root(politiek).
with_dt_root(positie).
with_dt_root(prettig).
with_dt_root(prijze).
with_dt_root(pronk).
with_dt_root(punt).
with_dt_root(raad).
with_dt_root(rade).
with_dt_root(recht).
with_dt_root(rechterzijde).
with_dt_root(rechtswege).
with_dt_root(reden).
with_dt_root(reeks).
with_dt_root(regeringswege).
with_dt_root(respectabel).
with_dt_root(rijk).
with_dt_root(rijkswege).
with_dt_root(rijp).
with_dt_root(rond).
with_dt_root(ruste).
with_dt_root(samen).
with_dt_root(schiet).
with_dt_root(secundair).
with_dt_root(seizoen).
with_dt_root(sinds).
with_dt_root(slaap).
with_dt_root(soft).
with_dt_root('soft drugs').
with_dt_root(soort).
with_dt_root(soortgelijk).
with_dt_root(soortgelijks).
with_dt_root(staatswege).
with_dt_root(stand).
with_dt_root(sta_op).
with_dt_root(stede).
with_dt_root(steeds).
with_dt_root(stel).
with_dt_root(stelletje).
with_dt_root(stief_moeder).
with_dt_root(stief_vader).
with_dt_root(stijl).
with_dt_root(strijde).
with_dt_root(succes).
with_dt_root(tachtig).
with_dt_root(tante).
with_dt_root(te).
with_dt_root(telkens).
with_dt_root(temeer).
with_dt_root(ten).
with_dt_root('ten halve').
with_dt_root('ten hele').
with_dt_root('ten overvloede').
with_dt_root(ter).
with_dt_root(terecht).
with_dt_root(terug).
with_dt_root(terzijde).
with_dt_root(tesamen).
with_dt_root('te veel').
with_dt_root(tezamen).
with_dt_root(thuis).
with_dt_root(tien).
with_dt_root(tijd).
with_dt_root(tijde).
with_dt_root(tijden).
with_dt_root(toch).
with_dt_root(toe).
with_dt_root(toen).
with_dt_root(tot).
with_dt_root(totaal).
with_dt_root(tussen).
with_dt_root(twaalf).
with_dt_root(twaalfhonderd).
with_dt_root(twee).
with_dt_root(tweede).
with_dt_root(twee_DIM).
with_dt_root(tweeduizend).
with_dt_root(tweehonderd).
with_dt_root(twintig).
with_dt_root(u).
with_dt_root(uit).
with_dt_root(uitsluitend).
with_dt_root(uwen).
with_dt_root(vaak).
with_dt_root(vader).
with_dt_root(vaderland).
with_dt_root(val).
with_dt_root(van).
with_dt_root(vanaf).
with_dt_root(vanavond).
with_dt_root(vandaag).
with_dt_root(vandaar).
with_dt_root('van dien aard').
with_dt_root(vanmiddag).
with_dt_root(vanmorgen).
with_dt_root(vannacht).
with_dt_root(vanochtend).
with_dt_root(vanwaar).
with_dt_root(vast).
with_dt_root(veel).
with_dt_root(veertien).
with_dt_root(veertig).
with_dt_root(veld).
with_dt_root(velde).
with_dt_root(ver).
with_dt_root(vergeet).
with_dt_root(verkeerd).
with_dt_root(vermoed).
with_dt_root(verrast).
with_dt_root(verwachting).
with_dt_root('vice versa').
with_dt_root(vier).
with_dt_root(vierde).
with_dt_root(vier_DIM).
with_dt_root(vijf).
with_dt_root(vijf_DIM).
with_dt_root(vijfentwintig).
with_dt_root(vijfhonderd).
with_dt_root(vijftien).
with_dt_root(vijftig).
with_dt_root(vind).
with_dt_root(vlam).
with_dt_root(voet).
with_dt_root(vol).
with_dt_root(volg).
with_dt_root(volk).
with_dt_root(volstrekt).
with_dt_root(voor).
with_dt_root(vooraf).
with_dt_root(vooral).
with_dt_root(voorbedacht).
with_dt_root(voorheen).
with_dt_root(voren).
with_dt_root(vorig).
with_dt_root(vraag).
with_dt_root(vreemde).
with_dt_root(vrees).
with_dt_root(vriend).
with_dt_root(vriendin).
with_dt_root(vrij).
with_dt_root(vrijwel).
with_dt_root(vroeg).
with_dt_root(vroeger).
with_dt_root(vrouw).
with_dt_root(vuur).
with_dt_root(waar).
with_dt_root(waaraan).
with_dt_root(waarachtig).
with_dt_root(waarom).
with_dt_root(waarschijnlijk).
with_dt_root(wat).
with_dt_root(water).
with_dt_root(we).
with_dt_root(weer).
with_dt_root(weet).
with_dt_root(weggeweest).
with_dt_root(wel).
with_dt_root(welaan).
with_dt_root(welk).
with_dt_root(wellicht).
with_dt_root(wereld).
with_dt_root(werkelijk).
with_dt_root(wie).
with_dt_root(wij).
with_dt_root(woord).
with_dt_root(wurg).
with_dt_root(zacht).
with_dt_root(zal).
with_dt_root(zeer).
with_dt_root(zeg).
with_dt_root(zeggen).
with_dt_root(zeker).
with_dt_root(zelden).
with_dt_root(zelf).
with_dt_root(zelfs).
with_dt_root(zes).
with_dt_root(zes_DIM).
with_dt_root(zeshonderd).
with_dt_root(zestien).
with_dt_root(zestig).
with_dt_root(zeven).
with_dt_root(zeventien).
with_dt_root(zeventig).
with_dt_root(zich).
with_dt_root(zie).
with_dt_root(zij).
with_dt_root(zijn).
with_dt_root(zijnen).
with_dt_root('z\'n').
with_dt_root(zo).
with_dt_root(zodanig).
with_dt_root(zogauw).
with_dt_root('zo iets').
with_dt_root(zoiets).
with_dt_root(zolang).
with_dt_root(zomin).
with_dt_root('zo\'n').
with_dt_root(zonder).
with_dt_root(zorg).
with_dt_root(zoveel).
with_dt_root(zover).
with_dt_root(zowat).
with_dt_root(zowel).
with_dt_root(zozeer).
with_dt_root(zulk).
with_dt_root(zuster).
with_dt_root(zwijg).
