#!/bin/bash

export ALPINO_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

. $ALPINO_HOME/create_bin/env.sh

echo ALPINO_HOME=$ALPINO_HOME
echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
echo TK_LIBRARY=$TK_LIBRARY
echo TCL_LIBRARY=$TCL_LIBRARY

$ALPINO_HOME/create_bin/Alpino.bin\
   debug=undefined\
   -flag tcl_dir $ALPINO_HOME/src\
   -flag hdrug_library $ALPINO_HOME/Hdrug/Tcl\
   -flag tex_library $ALPINO_HOME/Hdrug/Tex\
   -flag suite $ALPINO_HOME/Suites/cdb\
   end_hook=triples\
   display_quality=on\
   display_main_parts=on\
   -veryfast\
   penalties=undefined\
   syntax_features=undefined\
   suite=undefined\
   fluency_feature_weights=undefined\
   generation_suite=undefined\
   demo=on\
   -cmd "asserta(library_directory('$ALPINO_HOME/hdrug'))" "$@"
