#!/usr/bin/env python3

"""Example of using estimate to build MaxEnt classifiers."""

__author__ = "Rob Malouf <rmalouf@mail.sdsu.edu>"
__date__ = "12 February 2004"
__version__ = "$Revision: 1.2 $"

import sys
import argparse
from maxent import *
import pickle

try:
    import psyco
    psyco.full()
except:
    pass

# process options

parser = argparse.ArgumentParser()
parser.add_argument("-p", "--prior", type=float, default=0,
                  help="use Gaussion prior with variance VAR",
                  metavar="VAR")
parser.add_argument("-l", "--lasso", type=float, default=0,
                  help="use least absolute smoothing with variance VAR",
                  metavar="VAR")
parser.add_argument("-a", "--algorithm", choices=['MaxEnt','NaiveBayes'],
                  default='MaxEnt',
                  help="use learning algoritm ALG (MaxEnt (def), NaiveBayes)",
                  metavar="ALG")
parser.add_argument("-d", "--data-format", choices=['C45','Sparse','Rainbow'],
                  default='C45',
                  help="use data format FORM (C45 (def), Sparse, Rainbow)",
                  metavar="FORM")
parser.add_argument("-s", "--smooth", type=float, default=0,
                  help="add EPS to all counts",
                  metavar="EPS")
parser.add_argument("-m", "--model", action="store", default='',
                  help="use model FILE",
                  metavar="FILE")
parser.add_argument("-f", "--train", action="store", default='',
                  help="read training data from FILE",
                  metavar="FILE")
parser.add_argument("-t", "--test", action="store", default='',
                  help="read test data from FILE",
                  metavar="FILE")
parser.add_argument("-q", "--quiet", action="store_true", default=False,
                  help="be quiet")
parser.add_argument("-b", "--no-baseline", action="store_true", default=False,
                  help="don't use a baseline category")
parser.add_argument("-c", "--confusion", action="store_true", default=False,
                  help="print confusion matrix")
parser.add_argument("-w", "--write", action="store_true", default=False,
                  help="write each class")
parser.add_argument("-y", "--display-parameters", action="store_true", default=False,
                  help="display all parameters")


options = parser.parse_args()

if not options.quiet:
    print(file=sys.stderr)
    print('Bayesian classifier', file=sys.stderr)
    print(file=sys.stderr)

# Construct model

if options.train == '':
    # no training file, so check model file
    if options.model != '':
        if not options.quiet:
            print('Reading model from',options.model, file=sys.stderr)
        with open(options.model,'rb') as file:
            cat = pickle.load(file)
    else:
        raise Exception
else:
    if options.data_format == 'Rainbow':
        if not options.quiet:
            print('Reading Rainbow training data from', \
                  options.train, file=sys.stderr)
        source = RainbowSource(options.train,binary=True)
    elif options.data_format == 'C45':
        if not options.quiet:
            print('Reading C4.5 training data from', \
                  options.train, file=sys.stderr)
        source = C4_5Source(options.train)
    elif options.data_format == 'Sparse':
        if not options.quiet:
            print('Reading Sparse Binary training data from', \
                  options.train, file=sys.stderr)
        source = SparseSource(options.train)
    else:
        raise Exception

    if options.algorithm == 'MaxEnt':
        print('Building MaxEnt model', file=sys.stderr)
        cat = MaxEntInducer().train(source, \
                                    quiet=options.quiet, \
                                    eps=options.smooth, \
                                    var=options.prior, \
                                    lasso=options.lasso, \
                                    use_baseline=not options.no_baseline)
    elif options.algorithm == 'NaiveBayes':
        print('Building naive Bayes model', file=sys.stderr)
        cat =  NaiveBayesInducer().train(source, \
                                         quiet=options.quiet, \
                                         eps=options.smooth)

# write model (if desired)

if (options.train != '') and (options.model != ''):
    if not options.quiet:
        print('Writing model to',options.model, file=sys.stderr)
    file = open(options.model,'wb')
    pickle.dump(cat,file,True)
    file.close()

# evaluate model

if options.test != '':
    if options.data_format == 'Rainbow':
        if not options.quiet:
            print('Reading Rainbow test data from', \
                  options.test, file=sys.stderr)
        source = RainbowSource(options.test,binary=True)
    elif options.data_format == 'C45':
        if not options.quiet:
            print('Reading C4.5 test data from', \
                  options.test, file=sys.stderr)
        source = C4_5Source(options.test)
    elif options.data_format == 'Sparse':
        if not options.quiet:
            print('Reading Sparse Binary test data from', \
                  options.test, file=sys.stderr)
        source = SparseSource(options.test)
    else:
        raise Exception

    acc = AccuracySink()
    cat.apply(source,acc,options.write)

    if not options.write:
        print('Accuracy =', acc.score() * 100.0)

    if options.confusion:
        acc.confusion()

if options.display_parameters:
    cat.dump()
