#!/usr/bin/perl -w
$line="";
$outside=1;
while (<>) {
    chomp;
    next if /-DOCSTART-/;
    if (/^$/) {
	if (!$outside) {
	    $line=$line."]";
	    $outside=1;
	}
	line();
	$line="";
	next;
    }
    ($word,undef,$tag) = split;
    if ($tag eq "O") {
	if (!$outside) {
	    $line=$line."] ";
	    $outside=1;
	}
	$line=$line."$word ";
    } else {
	($bi,$class) = split /-/,$tag;
	if ($bi eq "B") {
	    if (!$outside) {
		$line=$line."] [ $class ";
	    } else {
		$line=$line."[ $class ";
	    }
	    $line=$line."$word ";

	} else {
	    $line=$line."$word ";
	}
	$outside=0;
    }
}

sub line {

    while ($line =~ /[\[] ([^]]*) [\]]/g) {
        $lcont=$`;
	$match=$1;
        $rcont=$';  ###$'
	$match =~ s/ /|/;
        $lcont=~ s/[\[] [A-Z]* //g;
	$lcont=~ s/ [\]]//g;
        $rcont=~ s/[\[] [A-Z]* //g;
	$rcont=~ s/ [\]]//g;
	@lwords=split(' ',$lcont);
	$lword1 = pop @lwords;
	$lword2 = pop @lwords;
	@rwords=split(' ',$rcont);
	$rword1 = shift @rwords;
	$rword2 = shift @rwords;
	$lword1 ||="";
	$rword1 ||="";
	$lword2 ||="";
	$rword2 ||="";
        print "$match|$lword2|$lword1|$rword1|$rword2\n";
    }

}
