#!/usr/bin/perl -w

while(<>) {
    chomp;
    ($string,$result) = split '\|' ;
    ($label,undef) = split ' ',$result;
    @words = split ' ',$string;
    $word = shift @words;
    print "$word na B-$label\n";
    foreach $word (@words) {
	print "$word na I-$label\n";
    }
}
