#!/usr/bin/perl -w

use Getopt::Std;
getopts('f:');

$opt_f ||= "features";

%fsindex=();

open(FEATURES,"$opt_f") or die "Can't find features file $opt_f: $!\n";
while (<FEATURES>) {
  next if /^[%\#]/;
  chomp;
  ($ind,$feat) = split/\|/;
  $fsindex{$feat}=$ind;
}
close FEATURES;
print STDERR "reading features file $opt_f done\n";

while(<>) {
  next if /^[%\#]/;
  next if !/\|/;
  chomp;
  if ($. % 25000==0) 
    { print STDERR "read $. lines\n";}


  ($key,$len,$triple,$pairs) = split/\#/;

  print $key;

  @pairs = split/\|/,$pairs;
  @npairs = ();
  foreach $pair (@pairs) {
    ($count,$feat) = split/\@/,$pair;
    if (exists $fsindex{$feat}) {
      push(@npairs,$count . "@" . $fsindex{$feat})
    }
  }
  print "$key#$len#$triple#";
  print join("|",@npairs);
  print "\n";
}
