treebank(4,r(r1,s,[r(r3,nps,[r(l2,ds,[w(a)]),r(l4,ns,[w(dog)])]),r(l8,vs,[w(barks)])])).
treebank(3,r(r1,s,[r(r3,nps,[r(l2,ds,[w(a)]),r(l5,ns,[w(cat)])]),r(l8,vs,[w(barks)])])).
treebank(1,r(r1,s,[r(r3,nps,[r(l2,ds,[w(a)]),r(l4,ns,[w(dog)])]),r(l9,vs,[w(barked)])])).
treebank(6,r(r1,s,[r(r3,nps,[r(l2,ds,[w(a)]),r(l5,ns,[w(cat)])]),r(l9,vs,[w(barked)])])).
treebank(2,r(r1,s,[r(r3,nps,[r(l1,ds,[w(the)]),r(l4,ns,[w(dog)])]),r(l8,vs,[w(barks)])])).
treebank(5,r(r1,s,[r(r3,nps,[r(l1,ds,[w(the)]),r(l5,ns,[w(cat)])]),r(l8,vs,[w(barks)])])).
treebank(7,r(r1,s,[r(r3,nps,[r(l1,ds,[w(the)]),r(l4,ns,[w(dog)])]),r(l9,vs,[w(barked)])])).
treebank(1,r(r1,s,[r(r3,nps,[r(l1,ds,[w(the)]),r(l5,ns,[w(cat)])]),r(l9,vs,[w(barked)])])).
treebank(6,r(r2,s,[r(r4,npp,[r(l3,dp,[w(the)]),r(l6,np,[w(dogs)])]),r(l10,vp,[w(bark)])])).
treebank(1,r(r2,s,[r(r4,npp,[r(l3,dp,[w(the)]),r(l7,np,[w(cats)])]),r(l10,vp,[w(bark)])])).
treebank(8,r(r2,s,[r(r4,npp,[r(l3,dp,[w(the)]),r(l6,np,[w(dogs)])]),r(l11,vp,[w(barked)])])).
treebank(6,r(r2,s,[r(r4,npp,[r(l3,dp,[w(the)]),r(l7,np,[w(cats)])]),r(l11,vp,[w(barked)])])).
