#!/usr/bin/perl -w
while (<>) {
    if (   s/(\s)1[.](?=\s.*\W2[.])/${1}1\#/
        || s/^1[.](?=\s.*\W2[.])/1\#/  ) {
	$next=2;
	$next2=3;
	while (s/(\s)${next}[.](?=\s.*\W${next2}[.])/${1}${next}\#/) {
	    $next++;
	    $next2++;
	}
	s/(\s)${next}[.]/${1}${next}\#/;
    }

    if (/\s([0-9][0-9]*)[.]\s/) {
	$cur=$1;
	$next=$cur++;
	if ($' =~ /\s(${cur})[.]\s/) {
	    s/(\s)([0-9]*)[.](\s)/$1$2\#$3/g;
	}
    }

    print;
}

