:- module(alpino_suite,[ sentence/2 ]).

:- hdrug_util:set_flag(application_type,qa).

sentence(451,['In',welk,jaar,werd,de,'Nobelprijs',toegekend,aan,'Thomas','Mann',?]).
sentence(452,['Wie',is,de,bestuursvoorzitter,van,'Fiat',?]).
sentence(453,['In',welke,stad,is,de,'San','Vittore',gevangenis,?]).
sentence(454,['Wat',is,de,eenheid,voor,frequentie,?]).
sentence(455,['Met',hoeveel,groeit,de,wereldbevolking,elk,jaar,?]).
sentence(456,['Wat',is,de,voornaam,van,rechter,'Borsellino',?]).
sentence(457,['Hoeveel',lijfwachten,werden,er,gedood,bij,de,moord,op,rechter,'Falcone',?]).
sentence(458,['Wie',is,'Shimon','Peres',?]).
sentence(459,['Welke',functie,heeft,'Ariel','Sharon',?]).
sentence(460,['Wanneer',ontving,'Yasir','Arafat',de,'Nobelprijs',voor,de,'Vrede',?]).
sentence(461,['Wat',is,de,heilige,stad,voor,de,'Joden',?]).
sentence(462,['Hoeveel','Palestijnse',vluchtelingen,zijn,er,in,'Libanon',?]).
sentence(463,['In',welk,jaar,begon,de,'Intifada',?]).
sentence(464,['Hoe',worden,'Japanse',zelfmoordpiloten,genoemd,?]).
sentence(465,['Welk',land,is,de,grootste,wapenleverancier,voor,'Derde','Wereldlanden',?]).
sentence(466,['In',welk,jaar,viel,de,atoombom,op,'Hiroshima',?]).
sentence(467,['Tot',welke,partij,behoorde,'Hitler',?]).
sentence(468,['Welke',taal,spreekt,men,in,'Duitsland',?]).
sentence(469,['Hoeveel',miljoen,'Joden',kwamen,er,om,in,de,'Tweede','Wereldoorlog',?]).
sentence(470,['Waar',is,het,vernietigingskamp,'Auschwitz',?]).
sentence(471,['Hoe',heet,de,grootste,aanbieder,van,mobiele,telefonie,in,de,wereld,?]).
sentence(472,['In',welk,jaar,eindigde,de,'Tweede','Wereldoorlog',?]).
sentence(473,['Wat',was,'Hitlers',voornaam,?]).
sentence(474,['Wat',is,de,'Duitse',munteenheid,?]).
sentence(475,['Wie',schreef,'"','Mein','Kampf','"',?]).
sentence(476,['Wat',is,de,hoofdstad,van,'Rusland',?]).
sentence(477,['Welke',autoproducent,maakt,de,'"','Kever','"',?]).
sentence(478,['Hoe',heet,de,film,van,'Stephen','Frears',met,in,de,hoofdrol,'Glenn','Close',',','John','Malkovich',en,'Michelle','Pfeiffer',?]).
sentence(479,['Welk',land,grenst,in,het,noorden,aan,'Canada',?]).
sentence(480,['Wie',was,de,eerste,president,van,de,'Verenigde','Staten',?]).
sentence(481,['Welk',beroep,heeft,'James','Bond',?]).
sentence(482,['Wie',speelde,'James','Bond',in,de,eerste,afleveringen,van,de,'007',serie,?]).
sentence(483,['Wie',speelt,'James','Bond',in,de,laatste,film,uit,de,serie,van,de,'007',?]).
sentence(484,['Waar',vindt,de,'Motorshow',plaats,?]).
sentence(485,['Wie',vraag,je,om,een,hypotheek,?]).
sentence(486,['Naar',welke,school,ging,'William',',',de,oudste,zoon,van,'Prins','Charles',?]).
sentence(487,['In',welke,band,zat,'Michael','Jackson',toen,hij,jong,was,?]).
sentence(488,['Hoe',stierf,'Jimi','Hendrix',?]).
sentence(489,['Wie',was,de,vader,van,'Lisa','Marie','Presley',?]).
sentence(490,['Met',wie,is,'Michael','Jackson',getrouwd,?]).
sentence(491,['Op',welke,leeftijd,begon,'Michael','Jackson',te,zingen,in,de,'"','Jackson','Five','"',?]).
sentence(492,['In',welk,genre,blinkt,'Michael','Jackson',uit,?]).
sentence(493,['Hoe',heet,'Michael','Jackson\'s',platenmaatschappij,?]).
sentence(494,['Wie',is,de,uitvinder,van,de,televisie,?]).
sentence(495,['Hoeveel',onderbrekingen,staat,de,'EEG',toe,voor,reclame,tijdens,een,film,?]).
sentence(496,['Wat',is,de,'Mossad',?]).
sentence(497,['Wat',is,de,'INCB',?]).
sentence(498,['Welke',straf,kreeg,'Pietro','Pacciani',voor,de,moorden,van,het,'"','Monster',van,'Florence','"',?]).
sentence(499,['Hoeveel',moorden,werden,toegeschreven,aan,het,'Monster',van,'Florence',?]).
sentence(500,['Wat',is,het,meestgelezen,'Italiaanse',dagblad,?]).
sentence(501,['Hoeveel',mensen,lijden,aan,overgewicht,in,de,'Verenigde','Staten',?]).
sentence(502,['Noem',een,basisingrediënt,van,de,'Japanse',keuken,'.']).
sentence(503,['In',welk,jaar,werd,'Greenpeace',opgericht,?]).
sentence(504,['Waar',vond,een,milieuramp,plaats,?]).
sentence(505,['Welke',nationaliteit,hadden,de,twee,olietankers,die,de,milieuramp,veroorzaakten,in,de,buurt,van,'Trinidad',en,'Tobago',in,'1979',?]).
sentence(506,['Waar',verblijft,'Arafat',?]).
sentence(507,['Wanneer',werd,het,'Cyrillisch',alfabet,ingevoerd,?]).
sentence(508,['Hoeveel',werklozen,zijn,er,in,'Europa',?]).
sentence(509,['Hoe',heet,de,vooorzitter,van,'Greenpeace','International',?]).
sentence(510,['Wat',is,de,hoofdstad,van,'Japan',?]).
sentence(511,['Welke',levende,wezens,absorberen,kooldioxide,?]).
sentence(512,['Waarmee',is,'Antarctica',bedekt,?]).
sentence(513,['Wat',veroorzaakt,het,ozongat,?]).
sentence(514,['Wat',kan,longkanker,veroorzaken,?]).
sentence(515,['Boven',welk,gebied,is,het,'"',ozongat,'"',waargenomen,?]).
sentence(516,['Hoe',oud,is,de,'Paus',?]).
sentence(517,['Hoeveel',monotheistische,religies,zijn,er,?]).
sentence(518,['Hoeveel',katholieken,zijn,er,op,de,wereld,?]).
sentence(519,['Hoeveel','Joden',zijn,er,in,de,wereld,?]).
sentence(520,['In',welke,stad,is,de,'St','Pieter','Kathedraal',?]).
sentence(521,['In',hoeveel,'Amerikaanse',staten,wordt,de,doodstraf,toegepast,?]).
sentence(522,['Hoeveel',executies,werden,er,in,'1993',in,de,'Verenigde','Staten',uitgevoerd,?]).
sentence(523,['In',welk,jaar,werd,de,apartheid,afgeschaft,in,'Zuid-Afrika',?]).
sentence(524,['Hoeveel',mensen,wonen,in,de,'VS',?]).
sentence(525,['Hoeveel',jaar,heeft,'Nelson','Mandela',in,de,gevangenis,doorgebracht,?]).
sentence(526,['Hoe',heet,de,'Koerdische',partij,die,naar,afscheiding,streeft,?]).
sentence(527,['Hoeveel',gevangenen,wachten,in,'Californië',op,de,doodstraf,?]).
sentence(528,['Wat',is,'UNICEF',?]).
sentence(529,['Tot',welke,leeftijd,zijn,kinderen,leerplichtig,in,'Italië',?]).
sentence(530,['Wanneer',werd,het,'Verdrag',inzake,de,'Rechten',van,het,'Kind',aangenomen,?]).
sentence(531,['Noem',iemand,die,van,pedofilie,wordt,beschuldigd,'.']).
sentence(532,['Op',welke,leeftijd,worden,jongeren,opgeroepen,voor,de,militaire,keuring,?]).
sentence(533,['Hoeveel',analfabeten,zijn,er,in,de,wereld,?]).
sentence(534,['Wie',is,de,'Franse',minister,voor,'Gezondheidszorg',?]).
sentence(535,['Hoe',gaat,het,met,de,'Paus',?]).
sentence(536,['Welk',bedrijf,wordt,beschuldigd,van,het,gebruik,van,kinderarbeid,?]).
sentence(537,['Welke','Amerikaanse',president,meldde,zich,niet,voor,de,militaire,dienst,?]).
sentence(538,['Wie',ontdekten,radioactiviteit,?]).
sentence(539,['Waar',is,'Greenpeace',opgericht,?]).
sentence(540,['Hoeveel',jaar,voert,'Greenpeace',al,campagne,?]).
sentence(541,['Waartegen',was,de,eerste,actie,van,'Greenpeace',gericht,?]).
sentence(542,['Hoeveel',oorlogen,worden,er,gevochten,?]).
sentence(543,['Hoeveel',landmijnen,zijn,er,in,de,wereld,?]).
sentence(544,['Wat',is,de,risicofactor,bij,'hart-',en,vaatziekten,?]).
sentence(545,['Welke',beroepsgroepen,lopen,een,verhoogd,risico,op,longkanker,?]).
sentence(546,['Noem',een,lichaamsdeel,dat,wordt,aangetast,door,het,'Ebola',virus,'.']).
sentence(547,['Wanneer',dook,het,'Ebola-virus',voor,het,eerst,op,?]).
sentence(548,['Geef',een,symptoom,van,het,'Ebola-virus','.']).
sentence(549,['Wat',is,het,'Internationale','Rode','Kruis',?]).
sentence(550,['Hoe',wordt,het,'Ebola-virus',overgedragen,?]).
sentence(551,['Noem',een,pesticide,'.']).
sentence(552,['Op',welke,dag,valt,het,'Chinese','Nieuwjaar',?]).
sentence(553,['Wie',is,'Jean-Bertrand','Aristide',?]).
sentence(554,['Waar',treedt,'El','Nino',op,?]).
sentence(555,['Wanneer',trad,'Nixon',af,?]).
sentence(556,['Door',wie,was,het,embargo,tegen,'Irak',ingesteld,?]).
sentence(557,['Noem',een,walvisachtige,'.']).
sentence(558,['Naar',wie,zijn,de,'Zapatistas',vernoemd,?]).
sentence(559,['Hoeveel',menselijke,genen,zijn,er,?]).
sentence(560,['Wie',zijn,de,'Amish',?]).
sentence(561,['Wie',is,de,keizer,van,'Japan',?]).
sentence(562,['Hoeveel',mensen,spreken,er,'Gaelic',in,'Schotland',?]).
sentence(563,['Wanneer',werd,'Letland',onafhankelijk,?]).
sentence(564,['Waar',is,de,'Al','Aqsa',moskee,?]).
sentence(565,['Noem',een,dier,dat,licht,geeft,'.']).
sentence(566,['Hoe',ontstaat,ozon,?]).
sentence(567,['Wie',schreef,'"','Ulysses','"',?]).
sentence(568,['Waar',is,de,'Vallei',der,'Koningen',?]).
sentence(569,['Hoe',heet,de,officiële,'Duitse',luchtvaartmaatschappij,?]).
sentence(570,['Wanneer',trouwden,'Prins','Charles',en,'Diana',?]).
sentence(571,['Waar',is,'CERN',?]).
sentence(572,['Hoeveel',kostte,de,'Kanaaltunnel',?]).
sentence(573,['Waar',is,het,'Cedars-Sinai','Medical','Center',?]).
sentence(574,['In',welk,jaar,sloeg,de,orkaan,'Andrew',toe,?]).
sentence(575,['Wat',is,de,'UEFA',?]).
sentence(576,['Wat',is,de,eenheid,van,radioactiviteit,?]).
sentence(577,['In',welk,'Europees',land,ligt,'Galway',?]).
sentence(578,['In',welk,jaar,vonden,de,'Olympische','Spelen',plaats,in,'Barcelona',?]).
sentence(579,['Waarvan',worden,borstimplantaten,gemaakt,?]).
sentence(580,['Wie',is,de,regisseur,van,'"','Braveheart','"',?]).
sentence(581,['Wie',is,'Yves','Saint','Laurent',?]).
sentence(582,['Wanneer',scheidde,'Bosnië',zich,af,van,'Joegoslavië',?]).
sentence(583,['Noem',een,'Frans',dagblad,'.']).
sentence(584,['Wanneer',vond,de,bomaanslag,op,het,'World','Trade','Center',plaats,?]).
sentence(585,['Wanneer',werd,'John','Lennon',gedood,?]).
sentence(586,['Wat',doen,antioxodanten,?]).
sentence(587,['Hoe',stierf,'River','Phoenix',?]).
sentence(588,['In',welk,jaar,was,de,komeet,van,'Halley',zichtbaar,?]).
sentence(589,['Op',welke,dag,valt,de,zommer,zonnewende,?]).
sentence(590,['Waaruit',wordt,salicylzuur,gewonnen,?]).
sentence(591,['Waar',staat,de,'Scheve','Toren',?]).
sentence(592,['Hoe',wordt,de,snelheid,van,een,chip,gemeten,?]).
sentence(593,['Wie',is,'Paul','Simon',?]).
sentence(594,['Wat',zijn,de,carabinieri,?]).
sentence(595,['Waar',ligt,'Heathrow','Airport',?]).
sentence(596,['Wie',speelt,de,hoofdrol,in,'"','Sleepless',in,'Seattle','"',?]).
sentence(597,['Wat',is,de,'Yakuza',?]).
sentence(598,['Hoe',kan,een,allergie,worden,behandeld,?]).
sentence(599,['Welke',kleur,heeft,koolomonoxide,?]).
sentence(600,['Wie',is,de,burgemeester,van,'New','York',?]).
sentence(601,['Wat',is,de,'FDA',?]).
sentence(602,['Hoe',zetten,planten,licht,om,in,voedsel,?]).
sentence(603,['Waar',is,het,'Hermitage','Museum',?]).
sentence(604,['Hoeveel',kardinalen,hebbe,het,recht,om,de,'Paus',te,kiezen,?]).
sentence(605,['Wat',is,de,voornaam,van,'Armani',?]).
sentence(606,['Hoe',werkt,'MRI',?]).
sentence(607,['Welke',nationaliteit,had,'Aristotle','Onassis',?]).
sentence(608,['Tot',welk,zonnestelsel,behoort,de,aarde,?]).
sentence(609,['In',welk,jaar,werd,het,'Vrijdheidsbeeld',gebouwd,?]).
sentence(610,['Waarvan',worden,'fiber-optic',kabels,gemaakt,?]).
sentence(611,['Wie',schilderde,de,'Guernica',?]).
sentence(612,['Hoeveel',mensen,wonen,in,'Tsjetsjenië',?]).
sentence(613,['Wat',voor,soort,regering,heeft,'Frankrijk',?]).
sentence(614,['Hoeveel',continenten,zijn,er,?]).
sentence(615,['Hoe',heet,de,vrouw,van,'Kurt','Cobain',?]).
sentence(616,['Noem',een,bordspel,'.']).
sentence(617,['In',welk,jaar,was,de,'Yom','Kippoeroorlog',?]).
sentence(618,['Hoeveel',mensen,worden,er,jaarlijks,door,landmijnen,gedood,?]).
sentence(619,['Wat',is,de,hoogste,actieve,vulkaan,in,'Europa',?]).
sentence(620,['Welke',rivier,stroomt,door,'Dublin',?]).
sentence(621,['Hoeveel',inwoners,van,'Beieren',zijn,katholiek,?]).
sentence(622,['Wat',is,'Amnesty','International',?]).
sentence(623,['Wie',is,'Silvio','Berlusconi',?]).
sentence(624,['Wat',betekent,'"','Forza','Italia','"',?]).
sentence(625,['Wat',heeft,de,artiest,'Christo',ingepakt,?]).
sentence(626,['Wat',bouwt,een,luthier,?]).
sentence(627,['Noem',een,reden,voor,zelfmoord,onder,tieners,'.']).
sentence(628,['Wanneer',werd,'Ulysses',',',het,ruimtevaartuig,',',gelanceerd,?]).
sentence(629,['Wie',zijn,de,'Simpsons',?]).
sentence(630,['Wat',is,vrijmetselarij,?]).
sentence(631,['Waarvan',werd,'Aldrich','H.','Ames',beschuldigd,?]).
sentence(632,['Waar',is,het,'Rode','Plein',?]).
sentence(633,['Welke',groep,droeg,bij,aan,de,muziek,van,de,film,'"','Zabriskie','Point','"',?]).
sentence(634,['Noem',een,beroemde,persoon,die,'Man','Ray',is,gefotografeerd,'.']).
sentence(635,['In',welk,jaar,werd,'Paus','Johannes','Paulus','II',pontifex,?]).
sentence(636,['Wie',bevrijdde,de,stad,'Sainte-Mere-Eglise',op,'D-Day',?]).
sentence(637,['Wie',is,'Alan','Turing',?]).
sentence(638,['Hoe',oud,is,'Beck','Hansen',?]).
sentence(639,['Wie',is,'Harlequin',?]).
sentence(640,['In',welke,oorlog,vochten,de,'Internationale','Brigades',?]).
sentence(641,['Wie',was,de,laatste,'Russische',tsaar,?]).
sentence(642,['Geef',de,naam,van,een,robot,'.']).
sentence(643,['Hoe',kun,je,energie,besparen,?]).
sentence(644,['Welk',dier,koert,?]).
sentence(645,['Hoeveel','panda\'s',leven,er,in,'China',in,het,wild,?]).
sentence(646,['Wie',speelt,het,hoertje,in,'"','Taxi','Driver','"',?]).
sentence(647,['Hoe',werkt,accupunctuur,?]).
sentence(648,['Waarvoor',wordt,acetic,anhydride,gebruikt,?]).
sentence(649,['Van',wie,is,de,uitspraak,'"',close,encounters,of,the,third,kind,'"',?]).
sentence(650,['Uit',welk,land,komt,de,tango,?]).
sentence(651,['Welke',nationaliteit,heeft,de,'Mitsubishi','Bank',?]).
sentence(652,['Wat',is,de,afkorting,voor,'Amnesty','International',?]).
sentence(653,['Noem',een,land,waar,het,'Boeddhisme',wordt,bedreven,'.']).
sentence(654,['Noem',een,land,dat,rijst,exporteert,'.']).
sentence(655,['Welk',land,is,de,belangrijkste,producent,van,diamanten,?]).
sentence(656,['Welk',ambt,bekleedde,'Silvio','Berlusconi',?]).
sentence(657,['Waarop',had,het,'"','Tequila','Effect','"',invloed,?]).
sentence(658,['Wat',veroorzaakte,het,'"','Tequila','Effect','"',?]).
sentence(659,['In',welk,land,keerde,'UNESCO',terug,na,een,afwezigheid,van,'38',jaar,?]).
sentence(660,['Welke',prijs,deelden,'Yasser','Arafat',',','Shimon','Peres',en,'Yitzhak','Rabin',?]).
sentence(661,['Welk',percentage,van,de,wereldhandel,in,diamanten,was,geconcentreerd,in,'Antwerpen',?]).
sentence(662,['Hoeveel',mensen,stierven,er,in,'Nederland',en,'Duitsland',tijdens,de,overstromingen,van,'1995',?]).
sentence(663,['Hoeveel',mensen,zijn,praktiserend,'Boeddhist',in,'Spanje',?]).
sentence(664,['Welke',afstand,legt,de,'Granada-Dakar',rally,af,?]).
sentence(665,['Hoe',groot,is,het,'Lacandona-bos',?]).
sentence(666,['Hoe',lang,deed,'Christo',erover,om,de,'Duitse','Rijksdag',in,'Berlijn',in,te,pakken,?]).
sentence(667,['Hoeveel',mensen,werden,er,vermist,in,de,'Filipijnen',na,de,tyfoon,'Angela',?]).
sentence(668,['Hoeveel',astronauten,waren,er,aan,boord,van,de,spaceshuttle,'Atlantis',?]).
sentence(669,['Hoeveel',mensen,stierven,er,door,verstikking,in,de,metro,van,'Bakoe',?]).
sentence(670,['Hoeveel',kilometers,betrof,het,grenssconflict,tussen,'Argentinië',en,'Chili',?]).
sentence(671,['Hoe',heet,de,binnenkant,van,een,schip,?]).
sentence(672,['Welke',olietanker,had,een,ongeluk,na,de,'"','Mar','Ego','"',?]).
sentence(673,['Noem',een,reukloze,en,smaakloze,vloeistof,'.']).
sentence(674,['Wat',kun,je,vinden,in,de,'"','Chester','Beatty','"',?]).
sentence(675,['Waar',is,de,'Rijksdag',?]).
sentence(676,['Welke',tyfoon,had,meer,dan,'1000',doden,en,vermisten,tot,gevolg,in,de,'Filipijnen',?]).
sentence(677,['Door',het,inhaleren,van,welke,substantie,werd,de,dood,van,'Joseph','Bryan','Thomson',veroorzaakt,?]).
sentence(678,['Wat',heeft,'Baron','Marcel','Bich',uitgevonden,?]).
sentence(679,['Welk',sportcomplex,werd,in,december,'1993',in,'Buenos','Aires',in,gebruik,genomen,?]).
sentence(680,['Welke','Amerikaanse',space,shuttle,nam,voor,het,eerst,een,'Russische',astronaut,mee,aan,boord,?]).
sentence(681,['In',welk,land,ligt,'Essen',?]).
sentence(682,['Waar',worden,de,'Oscars',uitgereikt,?]).
sentence(683,['Waar',vonden,de,'Olympische','Spelen',plaats,in,'1992',?]).
sentence(684,['Boven',welk,continent,is,het,ozongat,?]).
sentence(685,['Op',welke,hoogte,is,de,ozonlaag,?]).
sentence(686,['Waar',ligt,eiland,'Svalbard',?]).
sentence(687,['Waar',ligt,'Rio',de,'Janeiro',?]).
sentence(238,['Waar',vond,het,'Wereldvrouwencongres',plaats,?]).
sentence(689,['Waar',ligt,'Tarbes',?]).
sentence(690,['In',welke,stad,explodeerde,een,bombrief,?]).
sentence(691,['Welke','Italiaanse',regisseur,heeft,een,'Oscar',ontvangen,?]).
sentence(692,['Wie',is,directeur,van,het,'International','Monetary','Fund',?]).
sentence(693,['Wie',regisseerde,de,'Spaanse',film,'"','Los',peores,años,de,nuestra,vida,'"',?]).
sentence(694,['Wie',was,het,hoofd,van,het,twaalfde,kabinet,van,'Israel',?]).
sentence(695,['Wie',schreef,'"','Leonardo\'s','Fiets','"',?]).
sentence(696,['Wie',ontving,de,'Prins',van,'Asturias','Prijs',voor,'Technisch',en,'Wetenschappelijk',onderzoek,voor,zijn,onderzoek,voor,de,ontdekking,van,het,eerste,synthetische,vaccin,tegen,malaria,?]).
sentence(697,['Wie',besloot,de,'"','Luis','Donaldo','Colosio','"',beurs,in,het,leven,te,roepen,?]).
sentence(698,['Wie',sloot,het,zesde,'Rode','Kruis-Rode','Maan','Mediterraan','Congres',af,?]).
sentence(699,['Wie',leidde,de,heropening,van,het,'Sefardisch','Museum',in,'Toledo',?]).
sentence(700,['Wie',won,het,'Vierde','Internationale','Schaaktoernooi','"','Ciudad',de,'Pamplona','"',?]).
sentence(701,['Wanneer',kwam,de,eerste,'Cubaanse',president,aan,de,macht,?]).
sentence(702,['In',welk,jaar,was,de,'Iraakse',invasie,in,'Koeweit',?]).
sentence(703,['Wanneer',werd,'José','Rizal',geëxecuteerd,?]).
sentence(704,['Op',welke,dag,is,de,verjaardag,van,de,ontdekking,van,'Amerika',?]).
sentence(705,['Wanneer',begint,de,'21ste',eeuw,?]).
sentence(706,['Wanneer',was,de,'Chaco-oorlog',?]).
sentence(707,['Op',welke,dag,in,juni,'1995',explodeerde,een,bombrief,?]).
sentence(708,['Wanneer',was,de,'Mantsjoerijnse',invasie,van,'China',?]).
sentence(709,['Wanneer',ging,de,'NAFTA',van,start,?]).
sentence(710,['Wanneer',ging,'José','Celestino','Mutis',naar,'Colombia',?]).
sentence(711,['Noem',een,oliemaatschappij,'.']).
sentence(712,['Noem',een,'fastfood-keten','.']).
sentence(713,['Voor',welk,televisiekanaal,is,'Arabella','Kiesbauer',presentatrice,?]).
sentence(714,['Met',welke,'Palestijnse',organisatie,heeft,het,'Vaticaan',officiële,relaties,aangeknoopt,?]).
sentence(715,['Welk',leger,bezette,'Haïti',?]).
sentence(716,['Welke',organisatie,is,door,'Andrés','Townsend','Ezcurra',opgericht,?]).
sentence(717,['Welke',partij,won,de,eerste,'multi-raciale',verkiezingen,in,'Zuid-Afrika',?]).
sentence(718,['Welke',internationale,commissie,heeft,voor,het,eerst,formeel,'anti-semitisme',en,xenofobie,veroordeeld,?]).
sentence(719,['Welke',kerk,keurde,nieuwe,regels,goed,voor,de,wijding,van,vrouwen,?]).
sentence(720,['Welk',orgaan,werd,door,'Brazilië',',','Portugal',',','Angola',',','Mozambique',',','Sao','Tomé',en,'Principe',',','Guinee-Bissau',en,'Kaapverdië',opgericht,?]).
sentence(721,['Wat',is,de,'NAFTA',?]).
sentence(722,['Wat',is,de,'"','Mercosur','"',?]).
sentence(723,['Wie',was,'Rosa','Chacel',?]).
sentence(724,['Wie',is,'Arabella','Kiesbauer',?]).
sentence(725,['Wie',is,'Christo',?]).
sentence(726,['Wie',is,'Bill','Clinton',?]).
sentence(727,['Wie',is,'Leo','Reting',?]).
sentence(728,['Wat',is,de,'FIOV',?]).
sentence(729,['Wie',is,'Johannes','Paulus','II',?]).
sentence(730,['Wat',is,het,'Europese','Parlement',?]).
sentence(731,['Wie',was,president,van,de,'Verenigde','Staten',in,'1994',?]).
sentence(732,['In',welk,land,werden,operaties,van,de,'Verenigde','Naties',uitgesteld,tot,'31',maart,'1995',?]).
sentence(733,['Wie',was,president,van,'Noord-Korea',voor,'1994',?]).
sentence(734,['Wie',was,president,van,'Noord-Korea',na,'1994',?]).
sentence(735,['Welke',energiebedrijven,gingen,samen,in,'1995',?]).
sentence(736,['In',welk,jaar,',',voor,'1995',',',vond,het,'Wereldvrouwencongres',plaats,?]).
sentence(737,['Wie',won,de,'Nobelprijs',voor,'Literatuur',in,'1994',?]).
sentence(738,['Welke',ploeg,won,de,'Spaanse',voetbalcompetitie,in,'1994-1995',?]).
sentence(739,['Welk','Europees',land,kocht,twee,'"','CASA','C-212-300','Aviocar','"',toestellen,in,'1994',?]).
sentence(740,['Wat',is,het,begrote,'FIOV',budget,voor,de,periode,'1994-1991',voor,het,saneren,van,de,'Spaanse',vloot,?]).
sentence(741,['Wat',is,de,beste,manier,om,allergiën,te,bestrijden,?]).
sentence(742,['Hoe',kan,de,hoeveelheid,deuterium,in,wijn,bepaald,worden,?]).
sentence(743,['Hoe',kan,het,innen,van,sancties,worden,gegarandeerd,?]).
sentence(744,['Hoe',wil,men,aan,geboortebeperking,gaan,doen,in,'Peru',?]).
sentence(745,['Hoe',begint,',',volgens,de,'Hamer',methode,',',kanker,?]).
sentence(746,['Hoe',wordt,indocyanine,angiografie,uitgevoerd,?]).
sentence(747,['Hoe',wordt,de,'"','Japan','Premium','"',geëlimineerd,?]).
sentence(748,['Hoe',kunnen,afstootreacties,door,het,immuunsysteem,worden,uitgeschakeld,?]).
sentence(749,['Hoe',wordt,de,'Hamer',methode,toegepast,?]).
sentence(750,['Hoe',werkt,het,groeihormoon,?]).
sentence(751,['Wie',is,'Alain','Juppé',?]).
sentence(752,['Wie',is,'Shoko','Asahara',?]).
sentence(753,['Wie',is,'Franz','Schönhuber',?]).
sentence(754,['Waar',ligt,'Indiana',?]).
sentence(755,['Wie',is,'Bruce','Morrison',?]).
sentence(756,['Wat',is,'FARC',?]).
sentence(757,['Waar',ligt,'Caltanissetta',?]).
sentence(758,['Wat',is,de,afkorting,voor,het,'Soedanees','Volksbevrijdingsleger',?]).
sentence(759,['Wat',is,de,hoofdstad,van,'Venezuela',?]).
sentence(760,['Wat',is,de,'UNHCR',?]).
sentence(761,['De','Beierse',premier,',',wie,is,dat,?]).
sentence(762,['In',welk,jaar,nam,het,'Amerikaanse',congres,de,'"','War','Powers','Act','"',aan,?]).
sentence(763,['Izmir',ligt,in,welk,land,?]).
sentence(764,['Wie',is,de,'Duitse',minister,van,economische,zaken,?]).
sentence(765,['Van',welk,bedrijf,is,'Christian','Blanc',president,?]).
sentence(766,['Noem',een,'Finse',stad,'.']).
sentence(767,['Waar',ligt,'Tipaza',?]).
sentence(768,['Hoeveel',mensen,wonen,in,'Bombay',?]).
sentence(769,['Wie',is,directeur,van,het,'IAEA',?]).
sentence(770,['Wat',is,het,'IAEA',?]).
sentence(771,['Waar',is,het,'IAEA',gevestigd,?]).
sentence(772,['Hoeveel',mensen,wonen,in,'Brazilë',?]).
sentence(773,['In',welke,'Italiaanse',stad,is,de,'Trevi-fontein',?]).
sentence(774,['Wie',was,de,oprichter,van,'Motown',?]).
sentence(775,['Wat',is,de,voornaam,van,de,'Turkse',leider,'Atatürk',?]).
sentence(776,['In',welke,stad,is,het,'Van','Gogh','Museum',?]).
sentence(777,['Hoe',heet,de,dochter,van,de,'Chinese',leider,'Deng','Xiaopeng',?]).
sentence(778,['Noem',een,vulkaan,in,'Japan','.']).
sentence(779,['Wat',is,'GM',?]).
sentence(780,['Wat',is,de,'FSK',?]).
sentence(781,['In',welk,land,ligt,'Vukovar',?]).
sentence(782,['In',welke,'Amerikaanse',stad,is,het,'Warhol','Museum',?]).
sentence(783,['Wie',is,'Andy','Warhol',?]).
sentence(784,['Wie',is,'Keith','Richards',?]).
sentence(785,['Wie',is,ontdekker,van,het,'aids-virus',?]).
sentence(786,['Wat',is,'Yves','Saint-Laurent',?]).
sentence(787,['Wie',is,de,'Duitse',minister,van,milieu,?]).
sentence(788,['Noem',een,poppenspeler,'.']).
sentence(789,['Wie',is,voorzitter,van,de,'UEFA',?]).
sentence(790,['Wie',is,de,'Republikeinse',leider,in,de,'Amerikaanse',senaat,?]).
sentence(791,['Wie',is,de,oprichter,van,de,nieuwszender,'CNN',?]).
sentence(792,['In',welk,land,ligt,'East-London',?]).
sentence(793,['Wat',is,'MTV',?]).
sentence(794,['Wanneer',vond,er,een,staatsgreep,plaats,in,'Cyprus',?]).
sentence(795,['Wanneer',is,'Alberto','Giacometti',geboren,?]).
sentence(796,['Hoe',heet,de,leider,van,de,'Turks-Cyprioten',?]).
sentence(797,['Hoe',heet,de,zoon,van,de,schrijver,en,'Nobelprijswinnaar','Thomas','Mann',?]).
sentence(798,['Wie',is,de,president,van,'Zuid-Jemen',?]).
sentence(799,['Wie',is,de,leider,van,'KwaZulu',?]).
sentence(800,['Van',welke,'Franse',voetbalclub,was,'Bernard','Tapie',voorzitter,?]).
sentence(801,['Wie',is,'Andrew','Morton',?]).
sentence(802,['Hoeveel',inwoners,telt,'Zuid-Afrika',?]).
sentence(803,['Wat',is,'NASA',?]).
sentence(804,['Wie',ontwierp,het,'San','Jordi','Sportpaleis',in,'Barcelona',?]).
sentence(805,['Hoe',heet,de,koningin,van,'Denemarken',?]).
sentence(806,['Hoe',heet,de,vrouw,van,de,'Peruaanse',president,'Alberto','Fujimori',?]).
sentence(807,['In',welk,land,ligt,'Silver','Star',?]).
sentence(808,['Hoe',heet,de,premier,van,'Rwanda',?]).
sentence(809,['Wie',is,de,koning,van,'Bulgarije',?]).
sentence(810,['Bij',welke,basketballploeg,speelt,'Shaquille','O\'Neal',?]).
sentence(811,['Welke','ANC-leider',werd,president,van,'Zuid-Afrika',?]).
sentence(812,['Wie',is,de,voorzitter,van,het,'Amerikaanse',huis,van,afgevaardigden,?]).
sentence(813,['Noem',een,provincie,in,'Spanje','.']).
sentence(814,['In',welk,jaar,werd,de,'Chileens',president,'Allende',vermoord,?]).
sentence(815,['Wie',is,'Marvin','Minsky',?]).
sentence(816,['In',welk,jaar,werd,'Nelson','Mandela',geboren,?]).
sentence(817,['Hoe',heet,de,autobiografie,van,'Nelson','Mandela',?]).
sentence(818,['Hoe',heet,de,weduwe,van,de,overleden,'Mozambiquaanse',president,'Samora','Machel',?]).
sentence(819,['Wanneer',werd,het,bedrijf,'Netscape','Communications',opgericht,?]).
sentence(820,['Wie',is,'Juan','Antonio','Samaranch',?]).
sentence(821,['Wanneer',kwam,'Pinochet',aan,de,macht,in,'Chili',?]).
sentence(822,['Waar',is,het,'CERN',gevestigd,?]).
sentence(823,['Wie',is,leider,van,de,'Likud',partij,?]).
sentence(824,['Wat',is,'Goldman','Sachs',?]).
sentence(825,['In',welk,land,ligt,de,provincie,'Antioquia',?]).
sentence(826,['Hoe',heet,de,voorzitter,van,de,'Federal','Reserve','Board',?]).
sentence(827,['Noem',een,van,de,oprichters,van,'Greenpeace','.']).
sentence(828,['In',welk,jaar,werd,de,'NAVO',opgericht,?]).
sentence(829,['Wat',is,'Nick','Leesons',geboorteplaats,?]).
sentence(830,['Wie',is,'Joao','Havelange',?]).
sentence(831,['Wat',is,de,vorige,'Argentijnse',munt,?]).
sentence(832,['Wat',is,de,munteenheid,van,'Mexico',?]).
sentence(833,['Waar',staat,de,afkorting,'OAU',voor,?]).
sentence(834,['Waar',ligt,'Hyde','Park',?]).
sentence(835,['Door',wie,werd,'Yitzak','Rabin',vermoord,?]).
sentence(836,['Wat',is,de,voornaam,van,de,zakenman,'Soros',?]).
sentence(837,['Van',welke,politieke,partij,is,'Ian','Paisley',leider,?]).
sentence(838,['Hoe',oud,is,de,'Russische',premier,'Viktor','Tsjernomyrdin',?]).
sentence(839,['Wie',is,voorzitter,van,de,'Palestijnse','Nationale','Autoriteit',?]).
sentence(840,['Hoe',verdedigde,'Vladimir','Zjirinovski',zich,tegen,demonstranten,in,'Straatsburg',?]).
sentence(841,['Wie',is,'Ruben','Acosta',?]).
sentence(842,['Waar',staat,de,afkorting,'"','AWACS','"',in,'AWACS-toestellen',voor,?]).
sentence(843,['Voor',welk,team,komt,'Michael','Schumacher',uit,?]).
sentence(844,['Wie',ontwierp,de,nieuwe,luchthaven,van,het,'Japanse','Osaka',?]).
sentence(845,['Welke',organisatie,strijdt,voor,de,bevrijding,van,'Tamil','Eelam',?]).
sentence(846,['Noem',een,broeikasgas,'.']).
sentence(847,['Hoe',heet,de,'Belgische',luchtvaartmaatschappij,?]).
sentence(848,['Wat',is,de,grootste,planeet,in,ons,zonnestelsel,?]).
sentence(849,['Wat',betekent,'MBA',?]).
sentence(850,['Welke',schrijver,was,de,laatste,echtgenoot,van,'Marilyn','Monroe',?]).
sentence(851,['Wat',is,het,grootste,softwarebedrijf,ter,wereld,?]).
sentence(852,['Wat',is,'MSNBC',?]).
sentence(853,['Wie',is,'Andrew','Lack',?]).
sentence(854,['Wie',produceert,'Invirase',?]).
sentence(855,['Wat',is,'IUPAC',?]).
sentence(856,['Waar',zit,'Hugo','Lacour',in,de,gevangenis,?]).
sentence(857,['Wat',is,de,waarde,van,'Kunstprijs',van,'Darmstadt',?]).
sentence(858,['Wanneer',is,'Marie-Jo','Lafontaine',geboren]).
sentence(859,['Waar',werd,'Marie-Jo','Lafontaine',geboren,?]).
sentence(860,['Waar',vindt,de,documenta,plaats,?]).
sentence(861,['Wat',is,'ALDI',?]).
sentence(862,['Wie',is,de,president,van,de,associatie,van,handelsorganisaties,in,'Hesssen',?]).
sentence(863,['Hoeveel',handwerkbedrijven,zijn,er,in,'Hessen',?]).
sentence(864,['Hoeveel',abbonees,heeft,'MSN',?]).
sentence(865,['Waarvoor',neemt,'Microsoft',een,licentie,van,'SUN',?]).
sentence(866,['Wanneer',werd,'Butzbach',een,garnizoensstad,?]).
sentence(867,['Wie',is,de,voorzitter,van,het,stadsarchief,van,'Butzbach',?]).
sentence(868,['Wanneer',bezocht,'Raymund','Peraudi','Butzbach',?]).
sentence(869,['Waar',is,de,zetel,van,het,'Europees','Monetair','Instituut',?]).
sentence(870,['Wie',is,'Marvin','Minsky',?]).
sentence(871,['Wat',is,'FTP',?]).
sentence(872,['Hoeveel',heeft,'IBM',voor,'Lotus',betaald,?]).
sentence(873,['Welk',bedrijf,heeft,haar,hoofdkantoor,in,'Armonk',?]).
sentence(874,['Wanneer',werd,'Hugo','Lacour',gearresteerd,?]).
sentence(875,['Wat',roept,'Saab',terug,?]).
sentence(876,['Wie',is,de,eigenaar,van,'Saab',?]).
sentence(877,['Wat',is,'UNICE',?]).
sentence(878,['Wie',is,de,president,van,'UNICE',?]).
sentence(879,['Wie',is,de,'secretaris-generaal',van,de,'Duitse',afdeling,van,'Amnesty','International',?]).
sentence(880,['Wie',moest,in,'1991',terugtreden,als,premier,van,'Karintië',?]).
sentence(881,['Wanneer',werd,'Dreamworks','SKG',opgericht,?]).
sentence(882,['Wie',heeeft,'Dreamworks','SKG',opgericht,?]).
sentence(883,['Welk',bedrijf,zal,in,'Dreamworks','SKG',investeren,?]).
sentence(884,['Wie',is,'Christoph','Ransmayr',?]).
sentence(885,['Wie',ontving,in,'1995',de,'Kafka-literatuurprijs',?]).
sentence(886,['Wie',is,'Jorma','Ollila']).
sentence(887,['Wie',is,bestuursvoorzitter,van,'Nokia',?]).
sentence(888,['Wat',is,'Finlands',grootste,industriële,bedrijf,?]).
sentence(889,['Hoe',hoog,was,de,winst,van,het,'Finse','electronica-',en,telecommunicatieconcern,'Nokia',in,'1994',?]).
sentence(890,['Wanneer',introduceerde,'IBM',de,eerste,'PC',?]).
sentence(891,['Waar',werd,'Hewlett','Packard','(','HP',')',opgericht,?]).
sentence(892,['Hoeveel',personen,werkten,bij,'HP',aan,het,slot,van,'1994',?]).
sentence(893,['Welk',deel,van,zijn,omzet,behaalt,'HP',in,'Europa',?]).
sentence(894,['Waar',is,'Kasteel','Esterhazy',?]).
sentence(895,['Wat',is,'CERN',?]).
sentence(896,['Waar',is,'CERN',gevestigd,?]).
sentence(897,['Hoeveel',lidstaten,heeft,'CERN',?]).
sentence(898,['Wie',slaagde,erin,om,'20000',nummers,te,stelen,door,in,te,breken,in,de,computer,van,'internet-bedrijf','Netcom',in,'New','York',?]).
sentence(899,['Wie',is,'Kevin','Mitnick',?]).
sentence(900,['Waar',is,het,hoofdkantoor,van,'Lindt',&,'Sprüngli',?]).
sentence(901,['Wanneer',is,'CERN',opgericht,?]).
sentence(902,['Wie',is,de,directeur,van,'CERN',?]).
sentence(903,['Hoeveel',mensen,werken,er,bij,'CERN',?]).
sentence(904,['Hoe',heet,de,provinciehoofdstad,van,'Saarland',?]).
sentence(905,['Hoeveel',inwoners,heeft,'Slowenië',?]).
sentence(906,['Wie',is,'Peeter','Tulviste',?]).
sentence(907,['Wanneer',rolden,de,tanks,van,het,'Joegoslavische',leger,'Slowenië',binnen,?]).
sentence(908,['Welk',bedrijf,verkocht,'Studer','Revox','AG']).
sentence(909,['Welk',bedrijf,kocht,'Studer','Revox','AG',?]).
sentence(910,['Wanneer',werd,'Studer','Revox',opgericht,?]).
sentence(911,['Waar',is,het,hoofdkantoor,van,'Harman','International','Industries',',','Inc',?]).
sentence(912,['Wat',is,de,munteenheid,van,'Georgië',?]).
sentence(913,['Wie',is,'Nodar','Dschawachischwili',?]).
sentence(914,['Op',welk,terrein,verhoogde,'HP',zijn,omzet,in,'1994',?]).
sentence(915,['Wie',is,'Thomas','Klante',?]).
sentence(916,['Wat',zal,vervoerd,worden,naar,'Endlager','Konrad',?]).
sentence(917,['Wat',is,'Mayr-Melnhof',?]).
sentence(918,['Wanneer',zal,'Weimar',cultureel,hoofdstad,van,'Europa',zijn,?]).
sentence(919,['Wie',is,'Götz','Friedrich',?]).
sentence(920,['Waar',is,de,'Chaos','Computer','CLub','(','CCC',')',gevestigd,?]).
sentence(921,['Wat',is,de,'BMFT',?]).
sentence(922,['Hoe',heet,de,'Europese',standaard,voor,digitale,mobiele,communicatie,?]).
sentence(923,['Wat',is,'Ericsson',?]).
sentence(924,['Wat',is,'ETSI',?]).
sentence(925,['Wie',produceert,de,'Smart',auto,?]).
sentence(926,['Wanneer',komt,de,compacte,auto,'Smart',op,de,markt,?]).
sentence(927,['Welk',bedrijf,werd,door,'Mercedes',and,'SMH',opgezet,?]).
sentence(928,['Wat',is,'Micro','Compact','Car','(','MCC',')',?]).
sentence(929,['Wat',maakt,het,bedrijf,'Victorinox',?]).
sentence(930,['Wat',produceert,'MCC',?]).
sentence(931,['Waar',is,'Ubilab',onder,een,eigen,adres,bekend,?]).
sentence(932,['Wat',is,de,hoogste,berg,ter,wereld,?]).
sentence(933,['Wat',is,de,hoogste,berg,van,'Japan',?]).
sentence(934,['Wat',is,het,symbool,van,'Parijs',?]).
sentence(935,['Waardoor',werd,het,'Colosseum',ernstig,beschadigd,in,'851',?]).
sentence(936,['Wat',werd,er,in,'438',verboden,in,het,'Colosseum',?]).
sentence(937,['Hoeveel',zal,'"','Internet','Explorer','"',van,'Microsoft',kosten,?]).
sentence(938,['Waaraan',stierven,'232',mensen,in,'Rajasthan',?]).
sentence(939,['Welke',epidemie,breidde,zich,uit,in,'Albanië',?]).
sentence(940,['Waar',worden,de,'Milka',chocoladerepen,gemaakt,?]).
sentence(941,['Wat',wordt,er,opgericht,in,'Seibertenrod',in,'Vogelsberg',?]).
sentence(942,['Wie',is,benoemd,tot,voorzitter,van,de,'Leica','Camera-groep',?]).
sentence(943,['Wat',maakt,het,technologiebedrijf,'Leica',?]).
sentence(944,['Wat',verkoopt,'Oracle',?]).
sentence(945,['Hoe',raakten,'22',mensen,in,het,'Empire','State','Building',gewond,?]).
sentence(946,['Wanneer',wordt,het,'Guggenheimmuseum',in,'Bilbao',geopend,?]).
sentence(947,['Wie',is,de,architect,van,het,'Guggenheimmuseum',in,'Bilbao',?]).
sentence(948,['Wat',bouwt,'Frank','Gehry',in,'Bilbao',?]).
sentence(949,['Welke',meubelmaker,heeft,een,museum,in,'Weil',am,'Rhein',?]).
sentence(950,['Wat',wordt,er,tentoongesteld,in,het,'Vitra','Design','Museum',?]).
sentence(951,['Wie',is,'Alberto','Fujimori',?]).
sentence(952,['Wat',is,'WTO',?]).
sentence(953,['Hoe',heet,de,minister,van,binnenlandse,zaken,van,'Senegal',?]).
sentence(954,['Waar',is,'Halifax',?]).
sentence(955,['Wie',is,de,'Russische',minister,van,financiën,?]).
sentence(956,['Wanneer',was,de,aanval,op,het,'Saint-Michel',metrostation,in,'Parijs',?]).
sentence(957,['Wie',is,'Umberto','Bosssi',?]).
sentence(958,['Waar',is,'La','Scala',?]).
sentence(959,['Hoeveel',mensen,stierven,er,als,gevolg,van,de,hittegolf,in,'India',?]).
sentence(960,['Wat',is,de,'Orde',van,de,'Zonnetempel',?]).
sentence(961,['Wanneer',stierf,'Lenin',?]).
sentence(962,['Wanneer',was,de,islamitische,revolutie,in,'Iran',?]).
sentence(963,['Hoe',heet,het,schip,dat,in,'1994',in,'Zweden',verging,?]).
sentence(964,['Wie',pleegde,de,terroristische,aanslag,op,de,metro,van,'Tokyo',?]).
sentence(965,['Waar',vond,de,'Wereld','Klimaat','Conferentie',plaats,in,'1995',?]).
sentence(966,['Waar',is,het,hoofdkantoor,van,de,'UNESCO',?]).
sentence(967,['Sinds',wanneer,doet,'Oostenrijk',mee,aan,'Schengen',?]).
sentence(968,['Hoe',heet,'Silvio','Berlusconi\'s',partij,?]).
sentence(969,['Hoeveel',katholieken,leven,er,in,'Afrika',?]).
sentence(970,['Wie',is,'Philippe','Biberson',?]).
sentence(971,['Wat',is,'Eurotunnel',?]).
sentence(972,['Wanneer',vond,de,aanval,op,'Pearl','Harbor',plaats,?]).
sentence(973,['Wie',is,de,regisseur,van,'"','Nikita','"',?]).
sentence(974,['Hoe',heet,de,'Nederlandse',koningin,?]).
sentence(975,['Wie',is,'Montxo','Armendariz',?]).
sentence(976,['Wie',won,het,'Cannes','Film','Festival',in,'1995',?]).
sentence(977,['Wie',is,'Paul','Feyerabend',?]).
sentence(978,['Hoeveel',mensen,wonen,in,'Irak',?]).
sentence(979,['Hoeveel',jaar,dient,men,in,'Zwitserland',gewoond,te,hebben,om,de,'Zwitserse',nationaliteit,te,krijgen,?]).
sentence(980,['Wie',is,'Butros','Butros','Ghali',?]).
sentence(981,['Wat',is,de,'IRA',?]).
sentence(982,['Waar',wordt,het,'Chopin','Concours',gehouden,?]).
sentence(983,['Wat',is,'GIA',?]).
sentence(984,['Hoe',heet,de,president,van,'Burundi',?]).
sentence(985,['Wanneer',in,'1994',vonden,de,eerste,parlementaire,verkiezingen,plaats,in,'Hongarije',?]).
sentence(986,['Welke',positie,had,'Redha','Malek',in,'1994',?]).
sentence(987,['Wanneer',werd,het,herstructureringsplan,voor,'Euro','Disney',gepresenteerd,?]).
sentence(988,['Waar',vond,de,'9de',editie,van,'Videoformes',plaats,?]).
sentence(989,['Wie',is,verkozen,tot,president,van,de,'Algemene','Raad',van,'Frans-Guyana',?]).
sentence(990,['Van',welk,land,was,'Egor','Gadar',premier,?]).
sentence(991,['Hoe',heet,de,premier,van,'Oekraïne',die,in,juni,'1994',werd,benoemd,?]).
sentence(992,['Vanaf',wanneer,werd,cannabis,gedoogd,in,'Duitsland',?]).
sentence(993,['Wat',is,de,politieke,partij,van,'Charles','Millon',?]).
sentence(994,['Wie',is,de,nieuwe,president,van,'Rwanda',?]).
sentence(995,['Waar',vond,de,'Internationale','Conferentie',over,'Bevolking',en,'Ontwikkeling',plaats,?]).
sentence(996,['Wanneer',was,het,'48ste','Festival',van,'Avignon',?]).
sentence(997,['Wat',is,de,hoofdstad,van,'Togo',?]).
sentence(998,['Hoeveel',geld,wil,'FC','Sevilla',zien,van,'Diego','Maradona',?]).
sentence(999,['Hoe',heet,de,'Poolse',minister,van,financiën,?]).
sentence(1000,['Waar',ligt,'Kishinev',?]).
sentence(1001,['Hoeveel',mensen,wonen,in,de,'Verenigde','Arabische','Emiraten',?]).
sentence(1002,['Wie',is,de,president,van,de,'Europese','Commissie',in,'1995',?]).
sentence(1003,['Hoe',stierf,'Juvénal','Habyarimana',?]).
sentence(1004,['Waar',staat,'"','VAE','"',voor,?]).
sentence(1005,['Wie',won,the,parlementsverkiezingen,in,'Hongarije',?]).
sentence(1006,['Welk',toernooi,heeft,'Andrei','Medvedev',gewonnen,?]).
sentence(1007,['Wie',versloeg,'Andrei','Medvedev',in,de,finale,van,het,'Monte','Carlo',tennistoernooi,?]).
sentence(1008,['Welek',nationaliteit,heeft,de,tennisspeler,'Sergi','Bruguera',?]).
sentence(1009,['Wie',heeft,de,'Super-G',in,'Lillehammer',gewonnen,?]).
sentence(1010,['Wanneer',is,'Claude','Lévi-Strauss',geboren,?]).
sentence(1011,['Waar',is,'Alexander','Vassilievitch','Korjakov',geboren,?]).
sentence(1012,['Hoe',heet,het,enige,onafhankelijke,dagblad,van,'Joegoslavië',?]).
sentence(1013,['Wat',is,de,'Kabylische',hoofdstad,?]).
sentence(1014,['Kaboe',is,de,hoofdstad,van,welk,land,?]).
sentence(1015,['Wat',was,de,levensverwachting,in,'Frankrijk',in,'1991',?]).
sentence(1016,['Wat',is,de,oppervlakte,van,'Tsjetsjenië',?]).
sentence(1017,['Hoeveel',inwoners,heeft,'Tsjetsjenië',?]).
sentence(1018,['Waar',vond,de,'7de',top,van,de,'Organisatie',van,de,'Islamitsche','Conferentie',plaats,?]).
sentence(1019,['Van',welke,organisatie,was,'Pierre-Paul','Schweitzer',directeur,?]).
sentence(1020,['Welk',team,won,het,'Vijf','Landen','Toernooi',in,'1994',?]).
sentence(1021,['Wanneer',was,de,officiële,opening,van,de,'Kanaaltunnel',?]).
sentence(1022,['Welke',beroemdheid,stond,naast,'François','Mitterand',bij,de,opening,van,de,'Kanaaltunnel',?]).
sentence(1023,['Waar',ligt,'Lesotho',?]).
sentence(1024,['Waar',vond,de,'International','Air','Show',plaats,?]).
sentence(1025,['Hoeveel',mensen,wonen,in,'Lesotho',?]).
sentence(1026,['Wat',is,de,politieke,partij,van,'Ntsu','Mokhele',',',premier,van,'Lesotho',?]).
sentence(1027,['Hoeveel',films,werden,er,gepresenteerd,tijdens,het,'Montreal','World','Film',festival,?]).
sentence(1028,['Welke',film,won,de,speciale,prijs,van,de,'Grand','Jury',tijdens,het,'Montreal','World','Film','Festival',?]).
sentence(1029,['Wie',is,de,regisseur,van,'"','Cancion',de,'Cuna','"',?]).
sentence(1030,['Wie',won,de,prijs,voor,de,beste,acteur,tijdens,het,'Montreal','World','Film','Festival',?]).
sentence(1031,['Hoe',heet,de,premier,van,'Rwanda',?]).
sentence(1032,['Uit',welk,land,komt,de,schrijver,'Taslima','Nasreen',?]).
sentence(1033,['Wie',was,de,laatste,koning,van,'Roemenië',?]).
sentence(1034,['Wanneer',werd,'Babacar','Seye',vermoord,?]).
sentence(1035,['Welke',politieke,functie,bekleedt,'Albert','Reynolds',in,'Ierland',?]).
sentence(1036,['Hoeveel',banen,wil,'Air','France',schrappen,in,'1995',?]).
sentence(1037,['Waar',landde,de,airbus,van,'Air','France',die,eerder,in,'Algerije',gekaapt,was,?]).
sentence(1038,['Hoeveel',mensen,werken,voor,de,'Warburg',groep,?]).
sentence(1039,['Wanneer',trouwden,'Federico','Fellini',en,'Giulietta','Masina',?]).
sentence(1040,['Wat',was,het,beroep,van,'Danny','Barker',?]).
sentence(1041,['Welk',percentage,van,de,'Amerikaanse',bevolking,was,eind,'1994',werkloos,?]).
sentence(1042,['Wat',is,het,oudste,bioscoopbedrijf,ter,wereld,?]).
sentence(1043,['Van',welke,raceploeg,is,'Flavio','Briatore',manager,?]).
sentence(1044,['Wanneer',vonden,de,'Europese',verkiezingen,plaats,in,'1994',?]).
sentence(1045,['Wat',is,de,officiële,taal,in,'Jemen',?]).
sentence(1046,['Op',welke,leeftijd,stierf,'Fernando','Rey',?]).
sentence(1047,['Hoe',stierf,'Jack','Unterweger',?]).
sentence(1048,['Waar',ligt,'Luxor',?]).
sentence(1049,['Sinds',wanneer,is,er,een,embargo,tegen,'Irak',van,kracht,?]).
sentence(1050,['Wat',was,de,bijnaam,van,'Ho','Chi','Mihn',?]).
sentence(1051,['Waar',is,de,'Gizah','Sfinx',?]).
sentence(1052,['Waar',ligt,'Izhevsk',?]).
sentence(1053,['Waar',ligt,het,'José','Alvalade','Stadium',?]).
sentence(1054,['Waar',woont,'José','Saramago',?]).
sentence(1055,['Waar',is,'Nelson','Mandela',geboren,?]).
sentence(1056,['Wat',is,de,grootste,maan,van,'Jupiter',?]).
sentence(1057,['Waar',ligt,'Turku',?]).
sentence(1058,['Wat',is,de,voormalige,hoofdstad,van,'Polen',?]).
sentence(1059,['In',welk,district,ligt,'Paredes',de,'Coura',?]).
sentence(1060,['Waar',ligt,'Sosnvyj','Bor',?]).
sentence(1061,['Op',welk,eiland,ligt,'Ponta','Delgada',?]).
sentence(1062,['Waar',is,'Álvaro','Cunhal',geboren,?]).
sentence(1063,['Waar',ligt,het,'Júlio',de,'Matos',ziekenhuis,?]).
sentence(1064,['Wat',is,het,kleinste,land,binnen,de,'Europese','Unie',?]).
sentence(1065,['Waar',ligt,'Gabrovo',?]).
sentence(1066,['Wat',is,meest,noordelijke,'Amerikaanse',staat,?]).
sentence(1067,['Wat',is,de,hoofdstad,van,'Wit-Rusland',?]).
sentence(1068,['Waar',stroomt,de,'Cubango',rivier,doorheen,?]).
sentence(1069,['In',welke,stad,stroomt,de,'Moezel',in,de,'Rijn',?]).
sentence(1070,['In',welke,'Braziliaanse',staat,ligt,'Campo','Grande',?]).
sentence(1071,['Waar',ligt,'Tianjin',?]).
sentence(1072,['Waar',ligt,'Duivelseiland',?]).
sentence(1073,['Wie',is,de,uitvinder,van,de,saxofoon,?]).
sentence(1074,['Wie',schreef,'"','De','Kleine','Prins','"',?]).
sentence(1075,['Wie',houdt,het,wereldrecord,polsstokhoogspringen,?]).
sentence(1076,['Wie',is,de,'"','Barefoot','Lady','"',?]).
sentence(1077,['Wie',is,de,'secretaris-general',van,de,'Portugese','Communistische','Partij',?]).
sentence(1078,['Wiens',dochter,is,'Martine','Aubry',?]).
sentence(1079,['Wie',is,de,burgemeester,van,'Lissabon',?]).
sentence(1080,['Wie',is,de,burgemeester,van,'Lamego',?]).
sentence(1081,['Wie',is,de,'Portugese',ambassadeur,in,'Frankrijk',?]).
sentence(1082,['Met',wie,is,'Whoopi','Goldberg',getrouwd,?]).
sentence(1083,['Wie',was,de,eerste,president,van,de,'Verenigde','Staten',?]).
sentence(1084,['Wie',is,'minister-president',van,'Rheinland-Pfalz',?]).
sentence(1085,['Wie',was,de,laatste,gouverneur,van,'Oost-Timor',?]).
sentence(1086,['Wie',was,de,echtgenoot,van,'Vieira',da,'Silva',?]).
sentence(1087,['Wie',is,de,aanvoerder,van,'FC','Porto',?]).
sentence(1088,['Wie',is,de,imam,van,de,moskee,in,'Lissabon',?]).
sentence(1089,['Wie',regiseerde,de,film,'"','Lisbon','Story','"',?]).
sentence(1090,['Wie',is,de,'Zweedse',minister,voor,het,milieu,?]).
sentence(1091,['Hoe',heet,de,'Koningin',van,'Denemarken',?]).
sentence(1092,['Wie',is,de,beschermheilige,van,'Penafiel',?]).
sentence(1093,['Welke',groep,vermoordde,'Aldo','Moro',?]).
sentence(1094,['Van',welke,band,is,'Teresa','Salgueiro',de,zangeres,?]).
sentence(1095,['Welke',ploeg,won,de,'CERS','Cup',voor,rolschaatshockey,?]).
sentence(1096,['Bij',welk,team,is,'Bobby','Robson',coach,?]).
sentence(1097,['Welk',bedrijf,heeft,een,raffinaderij,in,'Leça',da,'Palmeira',?]).
sentence(1098,['Tot',welke,partij,behoort,'Duarte','Lima',?]).
sentence(1099,['Wie',financiert,de,'IPSS','(','privé-instellingen',voor,sociale,solidariteit,')',?]).
sentence(1100,['Hoeveel',onderzeeërs,heeft,de,'Portugese',marine,?]).
sentence(1101,['Hoeveel',gemeenten,zijn,er,in,'Portugal',?]).
sentence(1102,['Hoelang',is,de,'Freixo','Brug',?]).
sentence(1103,['Hoe',oud,is,'Inês',de,'Medeiros',?]).
sentence(1104,['Hoever',is,het,van,'Braga',naar,'Guimarães',?]).
sentence(1105,['Hoe',hoog,is,de,'K2',?]).
sentence(1106,['Hoeveel',bedraagt,de,schuld,van,'Eurotunnel',?]).
sentence(1107,['Wat',is,de,oppervlakte,van,'Nedersaksen',?]).
sentence(1108,['Hoeveel',inwoners,heeft,de,'Dominicaanse','Republiek',?]).
sentence(1109,['Hoeveel',doelpunten,heeft,'Eusébio',gescoord,tijdens,zijn,loopbaan,?]).
sentence(1110,['Wat',is,de,snelheid,van,het,licht,?]).
sentence(1111,['Wanneer',werd,de,'FPLM',opgericht,?]).
sentence(1112,['Wanneer',werd,'Kaapverdië',onafhankelijk,?]).
sentence(1113,['Wanneer',komt,de,film,'"','Lisbon','Story','"',uit,?]).
sentence(1114,['Wanneer',werd,'Universele','Verklaring',van,de,'Rechten',van,de,'Mens',goedgekeurd,?]).
sentence(1115,['Wanneer',stierf,'Salvador','Allende',?]).
sentence(1116,['Wanneer',stierf,'Simon','Bolivar',?]).
sentence(1117,['Op',welke,dag,wordt,'Onafhankelijkheidsdag',in,'Brazilië',gevierd,?]).
sentence(1118,['Wanneer',werd,'"','A','Portuguesa','"',het,volkslied,?]).
sentence(1119,['In',welk,jaar,gebeurde,de,'"','25ste',april,'"',?]).
sentence(1120,['Waardoor',werd,de,'Titanic',geraakt,?]).
sentence(1121,['Wat',is,het,symbool,van,de,leider,van,de,'Giro','d\'Italia',?]).
sentence(1122,['Wat',werd,op,'13',augustus,'1961',opgericht,?]).
sentence(1123,['Waarvoor',was,'Mel','Blanc',allergisch,?]).
sentence(1124,['Welk',land,is,wereldkampioen,voetbal,?]).
sentence(1125,['Hoe',stierf,'Pasolini',?]).
sentence(1126,['Hoe',werd,'Brazilië',voor,de,vierde,keer,wereldkampioen,voetbal,?]).
sentence(1127,['Wat',was,de,eerste,'Portugese',geluidsfilm,?]).
sentence(1128,['Wat',verkoopt,'Faust',aan,de,duivel,?]).
sentence(1129,['Welk',dier,is,het,symbool,van,'Namibië',?]).
sentence(1130,['Onder',welke,naam,schrijft,'Álvaro','Cunhal',?]).
sentence(1131,['Welke',nationaliteit,heeft,'Yordan','Letchkov',?]).
sentence(1132,['Welke',nationaliteit,heeft,'Hercule','Poirot',?]).
sentence(1133,['Wat',was,'Napoleon','III',van,'Napoleon','Bonapart',?]).
sentence(1134,['Van',welk,materiaal,zijn,de,friezen,van,het,'Parthenon',gemaakt,?]).
sentence(1135,['Welke',militaire,rang,had,'Alfred','Dreyfus',?]).
sentence(1136,['Welke',kleur,heeft,sneeuw,?]).
sentence(1137,['Wat',is,de,'Iraakse',munteenheid,?]).
sentence(1138,['Wat',is,het,adres,van,de,'Barata',boekhandel,?]).
sentence(1139,['Wie',is,'Leonor','Beleza',?]).
sentence(1140,['Wie',is,'Arnold','Ruutel',?]).
sentence(1141,['Wie',is,'Wim','Duisenberg',?]).
sentence(1142,['Wie',is,'Rocha','Vieira']).
sentence(1143,['Wie',is,'Guilherme',da,'Fonseca',?]).
sentence(1144,['Wie',is,'Fernando','Gomes',?]).
sentence(1145,['Wie',is,'Valentina','Terechkova',?]).
sentence(1146,['Wie',is,'Jorge','Amado',?]).
sentence(1147,['Wat',is,de,'"','PC',do,'B','"',?]).
sentence(1148,['Wat',is,de,'PSN',?]).
sentence(1149,['Wat',is,de,'CSKA',?]).
sentence(1150,['Wat',is,'Vigor',?]).
