:- module(alpino_suite,[ sentence/2 ]).

:- hdrug_util:set_flag(application_type,qa).

sentence('0001',['Wat',is,'Atlantis',?]).
sentence('0002',['Wat',is,'Hubble',?]).
sentence('0003',['Wat',is,'Lusa',?]).
sentence('0004',['Waarheen',verhuisde,'Freud',in,'1939',?]).
sentence('0005',['Waar',is,de,'olie-tanker','Prestige',gezonken,?]).
sentence('0006',['Waar',vindt,de,uitreiking,van,de,'Oscars',plaats,?]).
sentence('0007',['Hoeveel',ruimtevaartuigen,werden,er,gelanceerd,in,'1977',?]).
sentence('0008',['Hoe',lang,duurt,de,ruimtemissie,'Voyager',?]).
sentence('0009',['Hoeveel',illegale,immigranten,zijn,er,nu,in,de,'EU',landen,?]).
sentence('0010',['Welke',partij,heeft,'Karadzic',opgericht,?]).
sentence('0011',['Welke',verklaring,werd,in,'1948',door,de,'VN',aangenomen,?]).
sentence('0012',['Welke',film,heeft,de,'Oscar',voor,de,beste,buitenlandse,film,gekregen,?]).
sentence('0013',['Noem',een,film,met,'Kirk','Douglas',uit,de,periode,'1946-1960','.']).
sentence('0014',['Welke',voetballer,heeft,in,'1994',de,'Gouden','Bal',gewonnen,?]).
sentence('0015',['Wie',was,de,kanselier,van,'Duitsland',van,'1974',tot,'1982',?]).
sentence('0016',['Welke',landen,hebben,kerncentrales,?]).
sentence('0017',['Wie',schreef,de,trilogie,'"','In',de,ban,van,de,ring,'"',?]).
sentence('0018',['In',welk,jaar,is,'Martin','Luther','King',vermoord,?]).
sentence('0019',['In',welke,stad,is,'Wolfgang','Amadeus','Mozart',geboren,?]).
sentence('0020',['In',welke,stad,werd,'Karl','Marx',geboren,?]).
sentence('0021',['Wat',is,de,diameter,van,de,'Maan',?]).
sentence('0022',['Waarvan',werd,'O.J.','Simpson',beschuldigd,?]).
sentence('0023',['Wie',was,'Alfred','Nobel',?]).
sentence('0024',['Wat',is,de,'Fokker','F100',?]).
sentence('0025',['Wat',zijn,de,symptomen,van,de,ziekte,van,'Parkinson',?]).
sentence('0026',['Welke',milieuorganisatie,werd,in,'1971',opgericht,?]).
sentence('0027',['Wat',was,'Churchill',tussen,'1951',en,'1955',?]).
sentence('0028',['In',welke,stad,vonden,voor,'Salt','Lake','City',de,'Olympische','Winterspelen',plaats,?]).
sentence('0029',['Welk',land,werd,onafhankelijk,na,een,'30-jarige',burgeroorlog,?]).
sentence('0030',['Hoe',hoog,is,de,'Eiffeltoren',?]).
sentence('0031',['Wat',zijn,de,drie,fundamentele,deeltjes,in,het,'Standaardmodel',uit,de,deeltjesfysica,?]).
sentence('0032',['Hoeveel',onderzoekers,waren,er,betrokken,bij,de,'17-jarige',zoektocht,naar,het,topquark,?]).
sentence('0033',['Hoeveel',deelstaten,heeft,'Duitsland',?]).
sentence('0034',['Noem',monumenten,die,op,de,'Werelderfgoedlijst',staan,'.']).
sentence('0035',['Welke',planeet,heeft,de,'Shoemaker-Levy',komeet,geraakt,?]).
sentence('0036',['Welke',landen,zijn,nucleaire,grootmachten,?]).
sentence('0037',['Wie',was,'Vermeer',?]).
sentence('0038',['Bij',welke,partij,hoort,'Helmut','Kohl',?]).
sentence('0039',['Noem',een,'Brits',bedrijf,dat,radioactief,afval,vervoert,'.']).
sentence('0040',['Wat',is,de,nieuwe,naam,van,'Nicosia',volgens,de,spellingswijzigingen,in,'Cyprus',?]).
sentence('0041',['Waar',ligt,het,'Jet','Propulsion','Laboratory',van,'NASA',?]).
sentence('0042',['Wie',heeft,de,opera,'"','Het','Meisje',van,'Pskov','"',gecomponeerd,?]).
sentence('0043',['Wie',is,de,premier,van,'Litouwen',?]).
sentence('0044',['Wat',is,nintendo,?]).
sentence('0045',['Waar',heeft,de,'"',killer,smog,'"',van,'1952','4000',sterfgevallen,veroorzaakt,?]).
sentence('0046',['In',welk,jaar,werd,'Graeme','Obree',benoemd,tot,'Scotland\'s','Sports','Personality',?]).
sentence('0047',['Wat',is,'Medicus','Mundi',?]).
sentence('0048',['Wie',heeft,een,prijs,van,het,'Goethe','Instituut',gekregen,maar,niet,geaccepteerd,?]).
sentence('0049',['Hoe',heet,de,'secretaris-generaal',van,'Interpol',?]).
sentence('0050',['In',welk,jaar,overleed,'Bernard','Montgomery',?]).
sentence('0051',['Wanneer',werd,'Hubble','Space','Telescope',gelanceerd,?]).
sentence('0052',['In',welk,jaar,kreeg,'Einstein',de,'Nobelprijs',natuurkunde,?]).
sentence('0053',['Bij',welke,groep,hoort,'Aviaco',?]).
sentence('0054',['Hoeveel',categorieën,hebben,de,'Grammy','Awards',?]).
sentence('0055',['In',welke,gevangenis,werd,'Mario','Conde',vastgehouden,?]).
sentence('0056',['Wat',heeft,'Yogi','Bear',gestolen,?]).
sentence('0057',['Welke','Russische',tsaar,overleed,in,'1584',?]).
sentence('0058',['Wie',nam,deel,aan,de,'Conferentie',van,'Jalta',?]).
sentence('0059',['Noem',drie,'Baltische',landen,'.']).
sentence('0060',['Wat',is,de,hoofdstad,van,'Tsjetsjenië',?]).
sentence('0061',['Welk',land,heeft,het,'WK',voetbal,in,'1994',gewonnen,?]).
sentence('0062',['Wie',is,'Boris','Becker',?]).
sentence('0063',['Wat',is,de,'RKA',?]).
sentence('0064',['Welke',astronaut,is,het,langst,in,de,ruimte,gebleven,'.']).
sentence('0065',['Welke',beroemde,gebeurtenis,vieren,de,'Fransen',op,'11',november,?]).
sentence('0066',['Bij',welke,partij,hoort,'Mahfoudh','Nahnah',?]).
sentence('0067',['Wat',is,de,'Nasdaq',?]).
sentence('0068',['Waar',wordt,het,tennistoernooi,van,'Wimbledon',gehouden,?]).
sentence('0069',['Wat',is,het,beroep,van,'Franz','Fischler',?]).
sentence('0070',['Hoeveel',journalisten,verwondde,'Diego','Maradona',met,een,luchtbuks,?]).
sentence('0071',['Waar',debuteerde,'Elisabeth','Schwarzkopf',als,zangeres,?]).
sentence('0072',['Wanneer',werd,'Dalai','Lama',genomineerd,voor,de,'Nobelprijs',voor,de,'Vrede',?]).
sentence('0073',['Welk','Frans',bedrijf,dat,gespecialiseerd,is,in,platte,beeldbuizen,',',is,aan,de,'NASDAQ',genoteerd,?]).
sentence('0074',['Wat',is,de,bevolking,van,'Libanon',?]).
sentence('0075',['Wat',is,'Nauru',?]).
sentence('0076',['Wat',produceert,'Frudesa',?]).
sentence('0077',['Hoeveel',leden,heeft,'Amnesty','International',?]).
sentence('0078',['Wanneer',werd,het,referendum,over,onafhankelijkheid,in,'Moldavië',gehouden,?]).
sentence('0079',['Wat',is,'Transnistrië',?]).
sentence('0080',['Wat',is,'Dianetics',?]).
sentence('0081',['Wie',is,'Benazir','Bhutto',?]).
sentence('0082',['Hoeveel',oorlogen,voerden,'India',en,'Pakistan',om,'Kashmir',?]).
sentence('0083',['Welke',partij,heeft,in,augustus,'1994',de,parlementsverkiezingen,in,'Sri','Lanka',gewonnen,?]).
sentence('0084',['Hoeveel',keren,werd,'Jackie','Stewart',wereldkampioen,?]).
sentence('0085',['Wie',schreef,het,boek,'"','Jurassic','Park','"',?]).
sentence('0086',['Wie',heeft,de,animatiefilm,'"','Toy','Story','"',geproduceerd,?]).
sentence('0087',['Wat',is,'MTV',?]).
sentence('0088',['Noem',een,roman,van,'Geert',van,'Oorschot','.']).
sentence('0089',['Hoeveel',beschermde,natuurgebieden,heeft,'Costa','Rica',?]).
sentence('0090',['Hoe',heet,de,oprichter,van,'Black','Sparrow','Press',?]).
sentence('0091',['Hoe',heet,'Charles','Bukowskis',alter,ego,?]).
sentence('0092',['Wie',was,de,'Japanse',ambassadeur,in,'Nederland',in,'1994',?]).
sentence('0093',['Wanneer',werd,de,manga,populair,in,'Japan',?]).
sentence('0094',['Welke',voorzitter,van,het,'ANC',was,ook,'Nobelprijswinnaar',?]).
sentence('0095',['Wat',is,de,'APEC',?]).
sentence('0096',['Wat',zou,'65',miljoen,jaar,geleden,een,eind,hebben,gemaakt,aan,het,tijdperk,van,de,dinosaurus,?]).
sentence('0097',['Wanneer',werd,'Suriname',onafhankelijk,?]).
sentence('0098',['Wie',ontving,in,'1995',de,'Anna','Bijns','Prijs',?]).
sentence('0099',['Waaruit',bestaat,de,'Anna','Bijns','Prijs',?]).
sentence('0100',['Wat',was,de,bijnaam,van,'Eddy','Merckx',?]).
sentence('0101',['Waarover',gaat,'Herman','Brusselmans\'',roman,'"','Vrouwen',met,een,'IQ','"',?]).
sentence('0102',['Uit',wiens,handen,ontving,'Gerard','Reve',in,'1969',de,'P.C.','Hooftprijs',?]).
sentence('0103',['Wat',zijn,deadheads,?]).
sentence('0104',['Waar',ligt,'James','Ensor',begraven,?]).
sentence('0105',['Waar',is,de,'Hermitage',?]).
sentence('0106',['Waar',ligt,'Ystad',?]).
sentence('0107',['Wat',zijn,'Koi',?]).
sentence('0108',['Noem',een,van,de,'613',goede,daden,die,een,mens,volgens,de,'Torah',',',de,'Talmoed',en,andere,joodse,wetten,kan,verrichten,'.']).
sentence('0109',['Wie',was,'Ajax-aanvoerder',in,'1994',?]).
sentence('0110',['Waar',is,'Danny','Blind',geboren,?]).
sentence('0111',['Waar',ligt,de,langste,spoortunnel,ter,wereld,?]).
sentence('0112',['Wie',was,de,burgemeester,van,'Hiroshima',in,'1995',?]).
sentence('0113',['Van',wie,is,het,besturingsysteem,'OS/2',?]).
sentence('0114',['Wat',zijn,'otaku\'s',?]).
sentence('0115',['In',welk,land,slapen,volgens,'Pippi','Langkous',alle,mensen,met,hun,voeten,op,het,hoofdkussen,?]).
sentence('0116',['Wie',bestuurden,in,'1899',samen,'Soedan',?]).
sentence('0117',['Wat',is,een,høker,?]).
sentence('0118',['Hoe',heet,de,klassieke,kreeftensoep,?]).
sentence('0119',['Wat',is,'CBGB',?]).
sentence('0120',['Wat',is,'ERMES',?]).
sentence('0121',['Hoe',oud,was,'Romano','Prodi',in,'1995',?]).
sentence('0122',['Wat',is,een,cincinnato,?]).
sentence('0123',['Wat',is,'CD-i',?]).
sentence('0124',['Wat',is,een,'SD-schijf',?]).
sentence('0125',['Noem',bonden,in,het,boksen,'.']).
sentence('0126',['Wat',is,apron,plus,?]).
sentence('0127',['Wie',regisseerde,'Leaving','Las','Vegas',?]).
sentence('0128',['Wie',zei,'"','Dieren',zijn,niet,goed,om,te,eten,',',maar,goed,om,mee,te,denken,'"',?]).
sentence('0129',['Noem',indianenstammen,uit,het,'Braziliaanse',binnenland,'.']).
sentence('0130',['In',welke,stad,schreef,'Nietzsche',zijn,'\'','Ecce','Homo','\'',?]).
sentence('0131',['Wanneer',leefde,'Friedrich','Nietzsche',?]).
sentence('0132',['Wanneer',leefde,'Ludwig','Wittgenstein',?]).
sentence('0133',['Wanneer',leefde,'Gottlob','Frege',?]).
sentence('0134',['Noem','Friese',terpen,'.']).
sentence('0135',['Wat',bestudeert,men,aan,het,'P.J.','Meertens-Instituut',in,'Amsterdam',?]).
sentence('0136',['Wat',voor,muziek,speelt,'Offspring',?]).
sentence('0137',['Wie',is,'Jack','Soden',?]).
sentence('0138',['Wie',was,in,'1995',voetballer,van,het,jaar,in,'België',?]).
sentence('0139',['Noem',dagattracties,in,'Noord-Nederland','.']).
sentence('0140',['Wat',is,'Villa','Achterwerk',?]).
sentence('0141',['Wie',zong,'"','Like','A','Virgin','"',?]).
sentence('0142',['In',welk,jaar,overleed,'Glenn','Gould',?]).
sentence('0143',['Hoeveel','Goldbergvariaties',zijn,er,?]).
sentence('0144',['Wie',is,'Jan','Tinbergen',?]).
sentence('0145',['Waar',is,het,nieuwe,kantoor,van,de,'Nederlandse','Gasunie',?]).
sentence('0146',['Wie',is,'Chad','Rowan',?]).
sentence('0147',['Noem','sumo-worstelaars','.']).
sentence('0148',['Wie',was,de,'Luxemburgse',voetbalbondscoach,tussen,'1995',en,'2000',?]).
sentence('0149',['Welke',stad,heeft,een,bioscoop,met,de,naam,'"','Filmtheater','De','Fabriek','"',?]).
sentence('0150',['Wie',is,'Klaas','Bruinsma',?]).
sentence('0151',['Wat',zijn,de,hobbies,van,'Jim','Courier',?]).
sentence('0152',['Hoe',heet,'Corneille',eigenlijk,?]).
sentence('0153',['Wat',is,crème,de,menthe,?]).
sentence('0154',['Wie',is,'Johan','Maasbach',?]).
sentence('0155',['Noem',een,evolutiebioloog,'.']).
sentence('0156',['Wat',is,het,'\'',principe,van,'Gause','\'',?]).
sentence('0157',['Wat',is,'Roppongi',?]).
sentence('0158',['Hoeveel',verdienen,statenleden,in,'1995',?]).
sentence('0159',['Uit',welk,land,stammen,de,tabla,en,kathakdans,?]).
sentence('0160',['In',welk,museum,werd,in,'1994',een,overzichtstentoonstelling,over,'Mondriaan',gehouden,?]).
sentence('0161',['In',welk,'Zeeuws',stadje,bracht,'Jan','Toorop',van,'1903',tot,'1924',elk,jaar,een,paar,weken,of,maanden,door,?]).
sentence('0162',['Hoeveel',werken,heeft,'Piet','Mondriaan',in,zijn,'Amsterdamse',jaren,gemaakt,?]).
sentence('0163',['In',welke,stad,is,het,'Frans','Halsmuseum',?]).
sentence('0164',['Wat',is,de,letterlijke,vertaling,van,'Ukiyo-e',?]).
sentence('0165',['In',welke,periode,zijn,de,tulpen,in,het,'Tulpenboek',van,'Marel',geschilderd,?]).
sentence('0166',['Wanneer',werd,'Józef','Oleksy',verkozen,tot,voorzitter,van,het,'Poolse',parlement,?]).
sentence('0167',['Geef',een,andere,naam,voor,'\'',chronisch,moeheidssyndroom,'\'']).
sentence('0168',['Wat',is,het,effect,van,de,griepprik,bij,ouderen,?]).
sentence('0169',['Wanneer',kregen,de,'Antillen',een,gelijkwaardige,positie,ten,opzichte,van,'Nederland',?]).
sentence('0170',['Op',welk,onderdeel,won,'Pernette','Osinga',de,wereldbekerwedstrijd,schermen,in,'Havana',?]).
sentence('0171',['Wat',bestudeert,de,neurologie,?]).
sentence('0172',['Wat',zijn,de,rebètika,?]).
sentence('0173',['Wie',was,de,president,van,'Eritrea',in,'1995']).
sentence('0174',['Waar',speelt,het,verhaal,van,'Reinaert',de,'Vos',zich,af,?]).
sentence('0175',['Welk',verschijnsel,wordt,wel,'"',sitcom,cinema,'"',genoemd,?]).
sentence('0176',['Waar',speelt,de,'animatie-film','Akira',zich,af,?]).
sentence('0177',['Met',wie,maakte,de,'Franse',jazzpianist,'Gérard','Gusti',platen,?]).
sentence('0178',['Wie',was,de,voorzitter,van,de,vaste,'Kamercommissie',voor,financiën,in,'1995',?]).
sentence('0179',['Wie',was,de,eerste,die,het,'Kanaal',zwemmend,overstak,?]).
sentence('0180',['Hoe',oud,was,het,attractiepark,'Duinrell',in,'1995',?]).
sentence('0181',['Welk',dier,spoelde,in,januari,'1995',op,'Texel',aan,?]).
sentence('0182',['In',welke,kleur,shirt,is,het,'Nederlandse',voetbalteam,succesvol,',',oranje,of,wit,?]).
sentence('0183',['In',welk,jaar,studeerde,'Karin','Bloemen',af,aan,de,'Academie',voor,kleinkunst,te,'Amsterdam']).
sentence('0184',['Hoe',hoog,kan,bamboe,worden,?]).
sentence('0185',['Voor',welk,percentage,van,de,wereldbevolking,is,uitgebreide,tandheelkundige,zorg,beschikbaar,?]).
sentence('0186',['Welk',land,is,'Nederlands',belangrijkste,handelspartner,?]).
sentence('0187',['Welk','WK',was,in,'München',in,'2001',gehouden,?]).
sentence('0188',['Wat',is,kabuki,?]).
sentence('0189',['Wie',was,'Qin','Shi','Huang',?]).
sentence('0190',['Waar',is,'Beslan',?]).
sentence('0191',['Waar',is,'Banat',?]).
sentence('0192',['Waar',heeft,'ABBA',het,'Eurovisiesongfestival',gewonnen,?]).
sentence('0193',['Waar',is,de,'Atatürk-dam',?]).
sentence('0194',['Hoe',groot,is,de,'Stille','Oceaan',?]).
sentence('0195',['Wat',is,het,wereldrecord,hoogspringen,?]).
sentence('0196',['Hoeveel','Beatles',waren,er,?]).
sentence('0197',['Bij',welke,dynastie,hoorde,'Dzjengis','Khan',?]).
sentence('0198',['Wat',was,de,eindstand,van,de,wedstrijd,'Italië-Nigeria',op,het,'WK',van,'1994',?]).
sentence('0199',['Wat',is,de,taal,van,de,koran,?]).
sentence('0200',['Wanneer',was,de,eruptie,van,de,'Vesuvius',?]).
