:- module(alpino_suite,[ sentence/2 ]).

:- hdrug_util:set_flag(application_type,qa).

sentence('0001',['Wat',is,'BMW',?]).
sentence('0002',['Wat',is,de,'ESA',?]).
sentence('0003',['Wie',is,'Javier','Solana',?]).
sentence('0004',['Wie',is,'Giulio','Andreotti',?]).
sentence('0005',['Noem',een,stad,waar,'Giulio','Andreotti',terecht,heeft,gestaan,'.']).
sentence('0006',['Hoeveel',wiet,mag,men,op,zak,hebben,?]).
sentence('0007',['Welke',voetballer,ontving,'"','De','Gouden','Bal','"',in,'1995',?]).
sentence('0008',['Wie',speelde,de,rol,van,'Superman',voordat,hij,verlamd,werd,?]).
sentence('0009',['Wie',is,de,leider,van,de,'Democratische','Unie',van,'Kosovo',?]).
sentence('0010',['Wie',heeft,de,'Colombiaanse','Partido','Verde','Oxigeno',opgericht,?]).
sentence('0011',['In',welk,jaar,brak,de,islamitische,revolutie,uit,in,'Iran',?]).
sentence('0012',['Wanneer',is,'Christopher','Reeve',geboren,?]).
sentence('0013',['Wie',heeft,de,'Rijksdag',in,'Berlijn',gebouwd,?]).
sentence('0014',['Wanneer',is,'Luc','Jouret',geboren,?]).
sentence('0015',['Wanneer',besloot,'Diwisa',een,machine,te,bouwen,voor,het,afvalwater,van,een,branderij,?]).
sentence('0016',['Waar',is,de,hoofdzetel,van,de,'WTO',?]).
sentence('0017',['In',welke,'Amerikaanse',staat,ligt,'Iron','Mountain',?]).
sentence('0018',['Wie',is,'Goodwill','Zwelithini',?]).
sentence('0019',['Wie',is,'Bettino','Craxi',?]).
sentence('0020',['Wie',is,'Diego','Armando','Maradona',?]).
sentence('0021',['Wie',is,'Silvio','Berlusconi',?]).
sentence('0022',['Wat',is,'Sabena',?]).
sentence('0023',['Wat',is,de,'NAFTA',?]).
sentence('0024',['Welke',ziekte,kregen,veel,'Amerikaanse',soldaten,na,de,'Golfoorlog',?]).
sentence('0025',['Wanneer',is,'Donatella','Della','Corte',geboren,?]).
sentence('0026',['Wie',is,'Romano','Prodi',?]).
sentence('0027',['Wat',is,'Eurostat',?]).
sentence('0028',['Welke',taak,krijgt,een,gewetensbezwaarde,in,'Frankrijk',?]).
sentence('0029',['Welke',sport,beoefent,'Adrian','Mutu',?]).
sentence('0030',['Wie',was,'Charles','Bukowski',?]).
sentence('0031',['Wie',is,'Rolf','Ekeus',?]).
sentence('0032',['Wie',is,'Dzjochar','Doedajev',?]).
sentence('0033',['Wie',is,'Willy','Claes',?]).
sentence('0034',['Wie',was,'Emiliano','Zapata',?]).
sentence('0035',['Wie',is,'Antonio','Matarrese',?]).
sentence('0036',['Wie',is,'Uffe','Elleman-Jensen',?]).
sentence('0037',['In',welke,haven,begon,de,veerboot,'Estonia',aan,zijn,laatste,reis,?]).
sentence('0038',['Welk',computervirus,werd,door,de,'Amerikaanse','National','Computer','Security','Association',als,loos,alarm,bestempeld,?]).
sentence('0039',['Welk',symbool,wordt,sinds,'1473',gebruikt,als,kenmerk,voor,de,'Schotse',pond,?]).
sentence('0040',['Wat',is,'Aum','Shinrinkyo',?]).
sentence('0041',['Wat',is,'Shell',?]).
sentence('0042',['Welke',genmutatie,verantwoordelijk,voor,borstkanker,werd,als,eerste,ontdekt,?]).
sentence('0043',['Welk',enzym,maakt,koolstofdioxyde,en,ethanol,uit,suiker,?]).
sentence('0044',['Wie',is,'Simon','Wiesenthal',?]).
sentence('0045',['Wie',is,'Kim','Il','Sung',?]).
sentence('0046',['Wie',is,'Yoko','Ono',?]).
sentence('0047',['Wie',is,'Saddam','Hussein',?]).
sentence('0048',['Wat',is,'Artsen','Zonder','Grenzen',?]).
sentence('0049',['Wie',is,de,koning,van,'Noorwegen',?]).
sentence('0050',['Welke','Franse',president,opende,de,'Kanaaltunnel',?]).
sentence('0051',['Wie',is,de,weduwe,van,'John','Lennon',?]).
sentence('0052',['Welke','Britse',vorstin,woonde,de,opening,van,de,'Kanaaltunnel',bij,?]).
sentence('0053',['Met',wie,was,'Neferet',getrouwd,?]).
sentence('0054',['In',welke,provincie,ligt,'Atapuerca',?]).
sentence('0055',['Welk',land,grenst,aan,'Noord-Korea',?]).
sentence('0056',['In',welk,land,ligt,de,stad,'Aken',?]).
sentence('0057',['Waar',ligt,'Bonn',?]).
sentence('0058',['In',welk,land,ligt,'Tokyo',?]).
sentence('0059',['In',welk,land,ligt,'Pyongyang',?]).
sentence('0060',['Waar',staat,de,afkorting,'RSI',voor,?]).
sentence('0061',['Welk',fruit,bevat,vitamine,'C',?]).
sentence('0062',['Wie',stierf,op,'8',juli,'1994',?]).
sentence('0063',['In',welk,land,vochten,de,'Tutsis',en,'Hutus',in,het,midden,van,de,jaren,negentig,?]).
sentence('0064',['Wie',is,'Umberto','Bossi',?]).
sentence('0065',['Uit',welk,land,komt,'Diego','Maradona',?]).
sentence('0066',['Wat',is,de,'PLO',?]).
sentence('0067',['Wie',is,de,adviseur,van,'Yasser','Arafat',?]).
sentence('0068',['Wie',regisseerde,de,film,'Pulp','Fiction',?]).
sentence('0069',['Wie',regisseerde,film,'Reservoir','Dogs',?]).
sentence('0070',['In',welke,serie,reed,'Mika','Salo',vier,jaar,lang,in,'Japan',?]).
sentence('0071',['Wat',is,de,hoofdstad,van,'Cyprus',?]).
sentence('0072',['Bij',welke,ziekte,wordt,'Clenbuterol',als,medicijn,gebruikt,?]).
sentence('0073',['In',welke,stad,ligt,het,beroemde,'Piazza',dei,'Miracoli',?]).
sentence('0074',['Waar',stierf,'Kurt','Cobain',?]).
sentence('0075',['Hoe',heet,de,president,van,'Servië',?]).
sentence('0076',['Wie',is,de,'secretaris-generaal',van,de,'VN',?]).
sentence('0077',['Hoe',heet,de,ruimtesonde,die,op,'25',januari,'1994',werd,gelanceerd,om,de,maan,in,kaart,te,brengen,?]).
sentence('0078',['Wie',werd,verkozen,tot,'Miss','Universe',in,'1994',?]).
sentence('0079',['Hoe',heet,de,raket,waarmee,de,ruimtesonde,'Clementine',werd,gelanceerd,?]).
sentence('0080',['Wat',is,de,'ILO',?]).
sentence('0081',['Wie',is,algemeen,directeur,van,de,'GGDO',?]).
sentence('0082',['Wat',is,'Medline',?]).
sentence('0083',['Waar',ligt,'Lillehammer',?]).
sentence('0084',['Welke',stad,organiseerde,de,'Olympische','Spelen',in,'1992',?]).
sentence('0085',['Waar',vormt,zich,ieder,jaar,een,gat,in,de,ozonlaag,tijdens,de,lente,?]).
sentence('0086',['Wat',is,de,'UNEP',?]).
sentence('0087',['Wat',gebeurde,er,op,'6',juni,'1944',?]).
sentence('0088',['Wat',is,de,'RRF',?]).
sentence('0089',['Wie',is,de,'Amerikaanse',minister,van,defensie,?]).
sentence('0090',['Wie',is,de,president,van,de,'Wereldbank',?]).
sentence('0091',['Wat',is,'Barings','Brothers',?]).
sentence('0092',['Hoe',oud,was,'Nick','Leeson',toen,hij,tot,gevangenisstraf,werd,veroordeeld,?]).
sentence('0093',['Hoeveel',leden,heeft,de,vakbond,'IG','Metall',?]).
sentence('0094',['Wat',is,'Eyal',?]).
sentence('0095',['Wie',is,de,'Nederlandse',minister,van,defensie,?]).
sentence('0096',['Wie',is,'Wim','Kok',?]).
sentence('0097',['Noem',een,'Nederlandse',minister,'.']).
sentence('0098',['Wie',was,de,'Nederlandse',koningin,in,'1995',?]).
sentence('0099',['Waar',is,het,instituut,voor,buitenlandse,betrekking,'Clingendael',gevestigd,?]).
sentence('0100',['Wat',was,het,'Manhattan','Project',?]).
sentence('0101',['Wat',is,de,'Covra','NV',?]).
sentence('0102',['Hoe',heet,de,'Europese','Gemeenschap',voor,'Atoomenergie',?]).
sentence('0103',['Noem',een,'Russische',minister,van,atoomenergie,'.']).
sentence('0104',['Wat',is,de,populaire,spelling,voor,het,'Engelse',weed,?]).
sentence('0105',['Wat',is,de,laatste,letter,in,het,'NATO-spellingsalfabet',?]).
sentence('0106',['Wie',was,'Edwin','Hubble',?]).
sentence('0107',['Wie',was,piloot,van,de,missie,die,de,astronomische,satelliet,',',de,'Hubble','Space','Telescope',',',repareerde,?]).
sentence('0108',['Hoe',heet,het,'Europese',ruimtevaartcentrum,in,'Noordwijk',?]).
sentence('0109',['Waar',is,'DLR',een,afkorting,voor,?]).
sentence('0110',['Wie',is,'Iqbal','Masih',?]).
sentence('0111',['Welk',land,is,hoofdsponsor,van,het,'ILO-programma',tegen,kinderarbeid,?]).
sentence('0112',['Hoe',heet,de,beweging,van,'Nobelprijswinnaars',tegen,kinderarbeid,in,ontwikkelingslanden,?]).
sentence('0113',['Waar',ligt,de,'Okavango-delta',?]).
sentence('0114',['Hoe',heet,de,'voedsel-',en,landbouworganisatie,van,de,'Verenigde','Naties',?]).
sentence('0115',['Wie',was,landbouwcommissaris,in,'1992',?]).
sentence('0116',['Noem',een,'Amerikaanse',seriemoordenaar,'.']).
sentence('0117',['Hoe',stierf,'Jimi','Hendrix',?]).
sentence('0118',['Hoe',stierf,'Olof','Palme',?]).
sentence('0119',['Hoe',stierf,'Yitzhak','Rabin',?]).
sentence('0120',['Noem',een,'Russische',componist,'.']).
sentence('0121',['Wie',is,'Boris','Jeltsin',?]).
sentence('0122',['Hoe',heet,het,'Russische',ruimtevaartstation,?]).
sentence('0123',['In',welk,land,ligt,'Moermansk',?]).
sentence('0124',['Wat',is,de,'Hermitage',?]).
sentence('0125',['Hoe',heet,de,koning,van,'Zweden',?]).
sentence('0126',['Wie',was,'Linnaeus',?]).
sentence('0127',['Wat',is,'Ikea',?]).
sentence('0128',['Wie',is,de,'Zweedse',mininster,van,milieu,?]).
sentence('0129',['Hoeveel',inwoners,heeft,'Estland',?]).
sentence('0130',['Waar',ligt,'Paldiski',?]).
sentence('0131',['Wat',is,de,hoofdstad,van,'Litouwen',?]).
sentence('0132',['Wanneer',is,'Henry','Purcell',geboren,?]).
sentence('0133',['Wat',is,'Henry','Purcells',beroemdste,compositie,?]).
sentence('0134',['Hoe',heet,het,'Britse',koninklijke,jacht,?]).
sentence('0135',['Wie',is,de,voorzitter,van,'Unilever',?]).
sentence('0136',['Welk',bedrijf,is,'Unilevers',grote,'Amerikaanse',concurrent,?]).
sentence('0137',['Wie',is,'Chun','Doo','Hwan',?]).
sentence('0138',['Wie',is,de,directeur,van,de,'Opera','Bastille',in,'1995',?]).
sentence('0139',['Noem',een,'Amerikaanse',effectenbank,'.']).
sentence('0140',['Wat',is,'Sumitomo',?]).
sentence('0141',['Wat',is,de,grootste,bank,ter,wereld,?]).
sentence('0142',['Wie',is,'Tsuneo','Wakai',?]).
sentence('0143',['Welke',organisatie,is,eigenaar,van,de,'Bank',of,'California',?]).
sentence('0144',['Wie',is,'Andy','Grove',?]).
sentence('0145',['Wie',is,'Brian',de,'Palma',?]).
sentence('0146',['Wie',was,de,vriendin,van,'Agassi',in,'1995',?]).
sentence('0147',['Wie',is,'Bruno','Trentin',?]).
sentence('0148',['Wie',is,'Joe','Slovo',?]).
sentence('0149',['Wie',is,de,burgemeester,van,'Moskou',in,'1994',?]).
sentence('0150',['Noem',een,'Amerikaanse',filosoof,'.']).
sentence('0151',['Wie',is,'Steve','Jobs',?]).
sentence('0152',['Welke','Kroatische',president,nam,deel,aan,de,vredesbesprekingen,in,'Dayton',?]).
sentence('0153',['Hoeveel',mensen,nemen,jaarlijks,deel,aan,de,'Daytona','Bike','Week',?]).
sentence('0154',['Wie',is,'Richard','Holbrooke',?]).
sentence('0155',['Hoe',oud,was,'Richard','Holbrooke',in,'1995',?]).
sentence('0156',['Hoeveel',medicinale,produkten,met,tijgeringrediënten,gingen,er,tussen,'1990',en,'1992',over,de,toonbank,?]).
sentence('0157',['Wanneer',opende,het,'Solomon','R.','Guggenheim','Museum',zijn,deuren,?]).
sentence('0158',['Welke',prijs,won,'Aung','San','Suu','Kyi',?]).
sentence('0159',['Wie',won,de,'Nobelprijs',voor,medicijnen,in,'1994',?]).
sentence('0160',['Wie',is,'Nick','Leeson',?]).
sentence('0161',['Hoe',heet,'Nick','Leeson\'s','Singaporese',advocaat,?]).
sentence('0162',['Hoe',heet,'Nick','Leeson\'s',vrouw,?]).
sentence('0163',['In',welke,stad,was,'Nick','Leeson',effectenhandelaar,van,'Barings',?]).
sentence('0164',['Hoe',heet,de,internationale,luchthaven,van,'Singapore',?]).
sentence('0165',['Wie',is,de,premier,van,'Singapore',?]).
sentence('0166',['Wie',is,'Johannes',van,'Damme',?]).
sentence('0167',['Wat',is,de,hoofdstad,van,'Timor',?]).
sentence('0168',['Van',welk,land,was,'Oost-Timor',een,kolonie,voordat,het,in,'1975',werd,geannexeerd,door,'Indonesië',?]).
sentence('0169',['Hoe',heet,de,chef,van,de,politie,van,'Oost-Timor',?]).
sentence('0170',['In',welk,jaar,werd,'Oost-Timor',door,'Indonesië',geannexeerd,?]).
sentence('0171',['Wat',is,de,'Fretilin',?]).
sentence('0172',['Waar',staat,'LTTE',voor,?]).
sentence('0173',['Welke',stad,is,het,bolwerk,van,de,'Tamil','Tijgers',?]).
sentence('0174',['Wie',is,'Vilupillai','Prabhakaran',?]).
sentence('0175',['Waar',ligt,'Halifax',?]).
sentence('0176',['Wat',is,de,'Halifax','Building','Society',?]).
sentence('0177',['Wat',is,de,'G7',?]).
sentence('0178',['Noem',een,'Noorse',schrijver,'.']).
sentence('0179',['Wie',schreef,'"','De',wereld,van,'Sofie','"',?]).
sentence('0180',['Uit',welk,land,komt,'Jostein','Gaarder',?]).
sentence('0181',['Wie',is,de,directeur,van,de,'Tour',de,'France',?]).
sentence('0182',['Wat',is,de,hoofdstad,van,'Peru',?]).
sentence('0183',['Wat',is,de,munteenheid,van,'Peru',?]).
sentence('0184',['Wie',is,de,president,van,'Peru',?]).
sentence('0185',['Welke',landen,zijn,'\'s',werelds,grootste,producenten,van,cocablaadjes,?]).
sentence('0186',['Welke',nationaliteit,heeft,'Mario','Vargas','Llosa',?]).
sentence('0187',['Hoeveel',bedraagt,de,schuldenlast,van,'Peru',?]).
sentence('0188',['Wie',is,'Manfred','Donike',?]).
sentence('0189',['Wanneer',stierf,'Manfred','Donike',?]).
sentence('0190',['Hoe',oud,was,'Manfred','Donike',toen,hij,stierf,?]).
sentence('0191',['Waar',ligt,'Sondrio',?]).
sentence('0192',['Hoe',hoog,is,de,'Nevado',del,'Huila',?]).
sentence('0193',['Wat',is,de,rijkste,club,van,'Nederland',?]).
sentence('0194',['Hoeveel',kinderen,zwerven,in,'Bogota',door,de,straten,?]).
sentence('0195',['Welke',vulkaan,barstte,uit,in,juni,'1991',?]).
sentence('0196',['Wat',was,de,snelheid,van,de,orkaan,'Roxanne',?]).
sentence('0197',['Hoe',lang,verbleef,'Alexei','Leonov',in,de,ruimte,?]).
sentence('0198',['Wat',is,de,'IAAF',?]).
sentence('0199',['Wie',leidde,het,'African','National','Congress',van,'1917',tot,'1924',?]).
sentence('0200',['Wie',was,de,'Italiaanse',minister,van,justitie,van,'1945',tot,'1946',?]).
