:- module(alpino_suite,[ sentence/2 ]).

:- hdrug_util:set_flag(application_type,qa).

sentence('0001-2300',['Door',welke,medicus,is,'Goethes','Faust',geïnspireerd,?]).
sentence('0002-2300',['Met',wie,sloot,het,personage,'Faust',een,weddenschap,?]).
sentence('0003-2300',['Waar',komt,de,duivel,beslag,op,leggen,?]).
sentence('0004-2300',['Met',welke,poëet,en,toneelschrijver,',',die,in,'1805',overleed,',',werkte,'Goethe',innig,samen,?]).
sentence('0005-2301',['Wat',is,'Porgy',and,'Bess',?]).
sentence('0006-2301',['Wie',componeerde,de,opera,?]).
sentence('0007-2301',['Wat',bepaalde,hij,in,zijn,testament,?]).
sentence('0008-2301',['In',welk,jaar,verscheen,de,gelijknamige,film,?]).
sentence('0009-2302',['Hoe',hoog,is,de,'Matterhorn',?]).
sentence('0010-2302',['Wie',beklom,de,berg,voor,het,eerst,?]).
sentence('0011-2302',['Welk','Zwitsers',dorp,ligt,aan,de,voet,van,de,berg,?]).
sentence('0012-2302',['Op',welke,hoogte,ligt,het,dorp,?]).
sentence('0013-2303',['Hoe',heet,de,vader,van,'Otus',en,'Ephialtes',?]).
sentence('0014-2303',['Welke',godin,werd,door,'Ephialtes',gekozen,?]).
sentence('0015-2303',['Waarin',veranderde,'Artemis',zichzelf,?]).
sentence('0016-2303',['Wie',doodde,'Otus',?]).
sentence('0017-2304',['Wie',was,'Piet','Mondriaan',?]).
sentence('0018-2304',['Waar',werd,hij,geboren,?]).
sentence('0019-2304',['Waar',sloot,hij,zich,in,'1893',bij,aan,?]).
sentence('0020-2304',['Hoe',oud,werd,hij,?]).
sentence('0021-2305',['Waar',werd,het,hoofd,van,het,neefje,van,'Youp',van,'\'t','Hek',in,gedrukt,?]).
sentence('0022-2305',['Bij',welke,vereniging,was,dat,?]).
sentence('0023-2305',['Hoeveel',columns,schreef,'Youp',van,'\'t','Hek',hierover,?]).
sentence('0024-2305',['Waar',is,de,vereniging,'"','GSC','Vindicat',atque,'Polit','"',gevestigd,?]).
sentence('0025-2306',['In',welk,jaar,werd,het,beeld,'"',de,'Venus',van,'Milo','"',gevonden,?]).
sentence('0026-2306',['Uit',hoeveel,delen,is,het,beeld,gemaakt,?]).
sentence('0027-2306',['Hoe',hoog,is,het,beeld,?]).
sentence('0028-2306',['Waar',komt,het,marmer,vandaan,',',waar,het,beeld,uit,is,vervaardigd,?]).
sentence('0029-2307',['Welk',bedrijf,gaf,als,eerste,aandelen,uit,?]).
sentence('0030-2307',['Uit',hoeveel,personen,bestond,het,bestuur,van,de,'VOC',?]).
sentence('0031-2307',['Hoeveel',schepen,is,de,'VOC',in,de,loop,der,jaren,kwijtgeraakt,?]).  % de --> der
sentence('0032-2307',['Welke',vergelijkbare,organisatie,werd,opgezet,voor,de,handel,met,het,'Westen',?]).
sentence('0033-2308',['Welke','Antilliaanse',schrijver,was,ook,actief,als,balletcriticus,?]).
sentence('0034-2308',['Wie',was,zijn,eerste,vrouw,?]).
sentence('0035-2308',['Wanneer',was,hij,gouverneur,van,de,'Nederlandse','Antillen',?]).
sentence('0036-2308',['Aan',de,gevolgen,van,welke,ziekte,overleed,hij,?]).
sentence('0037-2309',['Wie',is,'Pedro','Calderón',de,la,'Barca',?]).
sentence('0038-2309',['Waar',studeerde,hij,?]).
sentence('0039-2309',['Van',welk,genre,is,hij,de,grondlegger,?]).
sentence('0040-2309',['Wanneer',ontstond,dit,genre,?]).
sentence('0041-2310',['Hoe',oud,werd,de,bijbelse,figuur,'Enos',?]).
sentence('0042-2310',['Van',welke,boom,mag,'Adam',niets,eten,?]).
sentence('0043-2310',['Wie',is,de,moeder,van,'Jozef',?]).
sentence('0044-2310',['Hoe',lang,hebben,de,'Israëlieten',in,'Egypte',gewoond,?]).
sentence('0045-2311',['Wat',is,de,'Straat','Drake',?]).
sentence('0046-2311',['Welke',ontdekkingsreiziger,heeft,hem,ontdekt,?]).
sentence('0047-2311',['Welke',oceanen,verbindt,de,'Straat','Drake',?]).
sentence('0048-2311',['Welke',drie,continenten,liggen,aan,de,'Straat','Drake',?]).
sentence('0049-2312',['Met',welke,film,brak,'Carice',van,'Houten',door,?]).
sentence('0050-2312',['Welke',prijs,won,ze,voor,haar,rol,in,deze,film,?]).
sentence('0051-2312',['Voor',welke,andere,films,won,ze,dezelfde,prijs,?]).
sentence('0052-2313',['Wie',is,'Ernst','Heinkel',?]).
sentence('0053-2313',['Wanneer',is,hij,geboren,?]).
sentence('0054-2313',['In',welke,'Duitse',stad,stond,zijn,fabriek,?]).
sentence('0055-2313',['Wat',is,het,typenummer,van,het,eerste,vliegtuig,met,een,raketmotor,?]).
sentence('0056-2314',['Wie',was,de,grondlegger,van,de,'Vulcan-maatschappij',?]).
sentence('0057-2314',['Wie',is,de,oorspronkelijke,bedenker,van,'Star','Trek',?]).
sentence('0058-2314',['Op',welk,schip,speelden,de,originele,serie,en,de,animatieserie,zich,af,?]).
sentence('0059-2315',['Uit',hoeveel,spellen,bestaat,de,'Command',&,'Conquer',serie,?]).
sentence('0060-2315',['Wanneer',is,het,uitbreidingspakket,van,'"','Command',&,'Conquer',:,'Generals','"',uitgebracht,?]).
sentence('0061-2315',['Door',welke,studio,is,de,'Command',&,'Conquer',serie,gemaakt,?]).
sentence('0062-2316',['Hoe',noemt,men,een,bestuurder,van,een,keizerlijke,burcht,?]).
sentence('0063-2316',['Waar',is,deze,functie,ontstaan,?]).
sentence('0064-2316',['Wanneer',ontstond,deze,graafschap,?]).
sentence('0065-2317',['Wat',is,het,hoogste,punt,van,'België',?]).
sentence('0066-2317',['Hoe',hoog,is,dit,punt,?]).
sentence('0067-2317',['In',welk,natuurgebied,ligt,dit,punt,?]).
sentence('0068-2318',['In',welke,stad,is,'Rita','Pavone',geboren,?]).
sentence('0069-2318',['Wat',zijn,de,voornamen,van,haar,twee,zonen,?]).
sentence('0070-2318',['Uit',welk,land,komt,de,zangeres,die,recent,een,hit,had,met,'Pavones','"','Arrivederci','Hans','"',?]).  % een hit had het --> een hit had met
sentence('0071-2319',['Waar',is,de,linkerhand,van,'Kapitein','Haak',door,vervangen,?]).
sentence('0072-2319',['Waar',komen,de,personages,'Jan',',','Wendy',en,'Michiel',uit,de,film,'Peter','Pan',vandaan,?]).
sentence('0073-2320',['Welke',band,bracht,het,album,'The','X','Factor',uit,in,'1995',?]).
sentence('0074-2320',['Wie',speelde,de,drums,op,dat,album,?]).
sentence('0075-2321',['Hoeveel',korpsen,telde,het,'Leger',des,'Heils',in,'Nederland',in,'1995',?]).
sentence('0076-2321',['Van',welke,organisatie,werd,het,'Leger',des,'Heils',in,dat,jaar,lid,?]).
sentence('0077-2322',['Wat',is,de,'Mark','VII',?]).
sentence('0078-2322',['Welk',bedrijf,heeft,de,tank,ontwikkeld,?]).
sentence('0079-2323',['Hoeveel',inwoners,telt,de,'Italiaanse',gemeente,'La','Salle',?]).
sentence('0080-2323',['Aan',welke,gemeenten,grenst,deze,gemeente,?]).
sentence('0081-2324',['Door',zijn,verbeteringen,aan,welke,uitvinding,werd,'Antoni',van,'Leeuwenhoek',het,meest,bekend,?]).
sentence('0082-2324',['Wanneer',werd,hij,gedoopt,?]).
sentence('0083-2325',['Door',welk,land,wordt,'Vietnam',begrensd,in,het,noordwesten,?]).
sentence('0084-2325',['Wanneer',wordt,de,verdeling,van,'Vietnam',in,'Noord-Vietnam',en,'Zuid-Vietnam',officieel,vastgelegd,?]).
sentence('0085-2326',['Waar',bevindt,zich,de,'Zimmertoren',?]).
sentence('0086-2326',['Wanneer',werd,de,toren,ingehuldigd,?]).
sentence('0087-2327',['Welke',drie,brede,waterwegen,moet,de,'Rijksweg','16',passeren,?]).
sentence('0088-2327',['Tussen',welke,plaatsen,loopt,de,'Rijksweg','16',?]).
sentence('0089-2328',['Welke',structuur,ontstaat,door,samentrekking,van,chromatine,?]).
sentence('0090-2328',['Waaruit',is,deze,structuur,opgebouwd,?]).
sentence('0091-2329',['Wie',is,'Mitchell','Feigenbaum',?]).
sentence('0092-2329',['Welke',constante,is,naar,hem,vernoemd,?]).
sentence('0093-2330',['Wat',is,een,relikwie,?]).
sentence('0094-2331',['In',welke,band,begon,'Wally','Tax',als,zanger,?]).
sentence('0095-2331',['Hoe',oud,was,hij,toen,?]).
sentence('0096-2332',['Aan',welke,universiteit,promoveerde,'Linnaeus',in,'1735',?]).
sentence('0097-2333',['Wanneer',is,het,'Moederdag',in,'België',?]).
sentence('0098-2334',['Van',welk,type,voertuig,is,'Ponny',een,merk,?]).
sentence('0099-2335',['Welke',bestuursvorm,is,gebaseerd,op,het,menselijke,gelijkheidsideaal,?]).
sentence('0100-2336',['Wat',is,'Scientology',?]).
sentence('0101-2337',['Waarmee',kan,een,onregelmatige,hartslag,of,hartrimtestoornis,vaak,verholpen,worden,?]).
sentence('0102-2338',['Wat',is,het,voetbalelftal,van,de,'Verenigde','Arabische','Emiraten',?]).
sentence('0103-2339',['Uit',welk,land,was,'Anton','Dreesmann',oorspronkelijk,afkomstig,?]).
sentence('0104-2340',['Wat',is,een,obool,?]).
sentence('0105-2341',['Wat',is,de,'Rooms-Katholieke','Kerk',?]).
sentence('0106-2342',['Hoeveel',asteroïden,zijn,er,bekend,?]).
sentence('0107-2343',['Hoe',heet,de,'Nederlandse',stichting,voor,het,bevorderen,van,de,bekendheid,van,fado,?]).
sentence('0108-2344',['Welke',bieren,zijn,erkend,als,trappistenbier,?]).
sentence('0109-2345',['Wie',produceert,het,softwareplatform,'Steam',?]).
sentence('0110-2346',['Hoe',noemt,men,een,salade,van,aardappelblokjes,',',rundvlees,',',appel,',',augurk,en,soms,ui,?]).
sentence('0111-2347',['Welk',object,verloor,de,hertog,van,'Alva',op,'1',april,volgens,een,bekend,ezelsbruggetje,?]).
sentence('0112-2348',['Wat',publiceerde,'Albert','Einstein',in,'1905',?]).
sentence('0113-2348',['Wat',publiceerde,hij,later,',',in,'1916',?]).
sentence('0114-2349',['Wie',heeft,de,lijm,uitgevonden,die,gebruikt,werd,voor,de,beroemde,'Post-it',notes,?]).
sentence('0115-2350',['Welke',private,'equity-investeringsmaatschappij',wordt,in,de,documentaire,'Fahrenheit','9/11',ter,discussie,gesteld,?]).
sentence('0116-2351',['Wat',is,net,als,een,poesta,',',een,pampa,en,een,savanne,',',een,graslandschap,?]).
sentence('0117-2352',['Waar',wordt,een,dwangbuis,ook,nog,gebruikt,',',buiten,de,psychiatrie,en,de,'SM',?]).
sentence('0118-2353',['Wie',waren,de,leermeesters,van,'Noam','Chomsky',?]).
sentence('0119-2354',['Wanneer',begint,de,zomertijd,in,'Nederland',?]).
sentence('0120-2355',['In',welke,'Amerikaanse',stad,groeide,'King','Camp','Gillette',op,?]).
sentence('0121-2356',['Hoe',hoog,kan,ruige,zegge,worden,?]).
sentence('0122-2357',['Wat',was,in,'2004',de,elorating,van,de,'Nederlandse',schaker,'Erik','Hoeksema',?]).
sentence('0123-2357',['Van',wie,nam,'Hoeksema',het,wereldrecord,denksimultaan,over,?]).
sentence('0124-2358',['In',welke,periode,was,'Marcus','Aurelius',keizer,van,'Rome',?]).
sentence('0125-2358',['Wanneer',werd,hij,geboren,?]).
sentence('0126-2359',['Hoe',heet,de,burgemeester,van,'Parijs',?]).
sentence('0127-2360',['Wat',is,de,afstand,tussen,het,'S-Bahnstation','Charlottenburg',in,'Berlijn',en,het,nabijgelegen,metrostation,'Wilmersdorfer','Straße',?]).
sentence('0128-2361',['Wie',was,de,beste,voetballer,van,de,wereld,in,'1992',?]).
sentence('0129-2362',['Hoeveel',dwergen,zaten,er,in,'Walt','Disneys',eerste,lange,animatiefilm,uit,'1937',?]).
sentence('0130-2363',['Wat',is,'Past','Reality','Integration',?]).
sentence('0131-2364',['In',welk,jaar,werden,de,laatste,'Video','2000-recorders',geproduceerd,?]).
sentence('0132-2365',['In',welke,jaren,werd,een,verfilming,van,'Agatha','Christie\'s',toneelstuk,'Witness',for,the,'Prosecution',uitgebracht,?]).
sentence('0133-2366',['Wat',is,de,'Partij',voor,de,'Vrijheid',?]).
sentence('0134-2367',['Op',welke,afstand,van,de,aarde,staat,de,dichtstbijzijnde,ster,?]).
sentence('0135-2368',['Wat',is,de,allerhardste,soort,bindweefsel,?]).
sentence('0136-2369',['Welk','Europees',land,kent,geen,zomertijd,?]).
sentence('0137-2370',['Wat',is,de,'Voyager','1',?]).
sentence('0138-2371',['Hoe',heet,is,de,kern,van,de,planeet,'Saturnus',?]).
sentence('0139-2372',['Welk',erts,werd,in,'1919',bij,het,plaatsje,'Moengo',gevonden,?]).
sentence('0140-2373',['Uit',welke,vier,provincies,bestond,'Zuid-Afrika',tot,'1994',?]).
sentence('0141-2374',['Hoeveel',procent,lag,het,gemiddelde,besteedbaar,inkomen,van,alleenstaande,bejaarde,'AOW\'ers',boven,de,'netto-AOW',in,'1992',?]).
sentence('0142-2375',['Hoeveel',bladzijden,telde,het,'FBI-dossier',over,de,'Amerikaanse',dirigent,'Leonard','Bernstein',?]).
sentence('0143-2376',['Wat',zijn,provinciale,landschappen,?]).
sentence('0144-2377',['Wat',kocht,'Joseph','Goebbels',van,'Hugo','Eckener',voor,'2.2',miljoen,mark,?]).
sentence('0145-2378',['Wie',was,'Jona',?]).
sentence('0146-2379',['Wanneer',ontsloeg,de,'Zimbabwaanse','Standard','Chartered','Bank',ongeveer,'5000',mensen,?]).
sentence('0147-2380',['Hoeveel',zetels,had,de,'Eerste','Kamer',der,'Staten-Generaal',tot,'1956',?]).
sentence('0148-2381',['Van',welk,materiaal,zal,het,laagste,gedeelte,van,het,'Nationaal','Centrum',voor,'Wetenschap',en,'Techniek',worden,gemaakt,?]).
sentence('0149-2382',['Waarvoor',moest,het,oude,stationsgebouw,van,'Den','Bosch',wijken,?]).
sentence('0150-2383',['Hoe',lang,kan,een,'Argentijnse','zee-engel',worden,?]).
sentence('0151-2384',['Uit',welke,periode,zijn,fossielen,van,de,'Lemniscomys',zebra,gevonden,?]).
sentence('0152-2385',['Hoeveel',inwoners,had,de,'Franse',gemeente,'Rahling',in,'2005',?]).
sentence('0153-2386',['Waarmee',wordt,de,mouw,van,een,mannenoverhemd,zonder,vaste,knoop,dichtgemaakt,?]).
sentence('0154-2387',['Wat',is,de,'Wii',?]).
sentence('0155-2388',['Welke',bank,weigerde,ooit,mee,te,werken,aan,de,overname,van,'Chrysler',door,'Tracinda',?]).
sentence('0156-2389',['Hoe',heet,een,instrument,voor,het,bestuderen,van,objecten,die,te,klein,zijn,om,goed,met,het,blote,oog,te,zien,?]).
sentence('0157-2390',['Wat',is,de,totale,buislengte,van,een,contrafagot,?]).
sentence('0158-2391',['Wat',is,de,oorspronkelijke,betekenis,van,spam,?]).
sentence('0159-2392',['Aan',welk,type,boom,groeien,kokosnoten,?]).
sentence('0160-2393',['Hoe',heet,de,grootste,'Belgische','GSM-operator',?]).
sentence('0161-2394',['Wat',betekent,reboelje,in,het,'Fries',?]).
sentence('0162-2395',['Wanneer',werd,het,nummer,'"','Tutti',frutti,'"',van,'Little','Richard',uitgebracht,?]).
sentence('0163-2396',['Wat',is,een,'Soera',?]).
sentence('0164-2397',['Welk',blad,is,door,'Stefan','Maul',opgericht,?]).
sentence('0165-2398',['Welke',installatie,bootste,het,menselijk,spijsverteringsstelsel,na,?]).
sentence('0166-2399',['Wie',ontdekte,de,drug,'LSD',?]).
sentence('0167-2400',['Van',welke,organisatie,was,het,schip,de,'Rainbow','Warrior',het,vlaggenschip,?]).
sentence('0168-2401',['Hoeveel',bruggen,waren,er,in,het,wiskundige,vraagstuk,dat,voor,het,eerst,werd,opgelost,door,'Leonhard','Euler',?]).
sentence('0169-2402',['Na',hoeveel,generaties,krijg,je,een,goede,tong,en,smaak,?]).
sentence('0170-2403',['Wat',is,de,oppervlakte,van,het,land,'Suriname',?]).
sentence('0171-2404',['Wie',toonde,aan,dat,curare,een,verslappend,effect,heeft,op,de,ademhalingsspieren,?]).
sentence('0172-2405',['Wat',is,'2','Unlimited',?]).
sentence('0173-2406',['Wie',was,'Bölthorn',in,de,'Noordse',mythologie,?]).
sentence('0174-2407',['Welke',woning,is,bestand,tegen,'mortier-aanvallen',en,is,onzichtbaar,voor,infrarood,detectoren,?]).
sentence('0175-2408',['Wat',is,het,libertarisme,?]).
sentence('0176-2409',['Hoeveel',kinderen,had,'Johan','George',van,'Saksen-Eisenach',?]).
sentence('0177-2410',['Hoe',heet,een,serie,van,afbeeldingen,die,een,verhaal,vormen,?]).
sentence('0178-2411',['Wie',kreeg,in,'1977',de,'Nobelprijs',voor,scheikunde,?]).
sentence('0179-2412',['Hoeveel',talen,worden,er,officieel,in,'Zuid-Afrika',gesproken,?]).
sentence('0180-2413',['Welke','Italiaanse',luchtvaartmaatschappij,boekte,in,'1993',een,verlies,van,'390',miljoen,gulden,?]).
sentence('0181-2414',['Wat',was,op,'1',januari,'2004',het,wereldrecord,op,de,'1000',meter,shorttrack,schaatsen,?]).
sentence('0182-2415',['Wat',is,de,naam,van,het,'Reddingsmuseum',in,'Den','Helder',?]).
sentence('0183-2416',['Hoe',heet,de,overkoepelende,organisatie,van,joodse,gemeenten,van,'orthodox-joodse',signatuur,in,'Nederland',?]).
sentence('0184-2417',['In',welk,jaar,vertrok,'Jean-François','De','Sart',naar,'RSC','Anderlecht',?]).
sentence('0185-2418',['Hoeveel',inwoners,heeft,'Noorwegen',?]).
sentence('0186-2419',['Wat',is,een,ander,woord,voor,gelijkspel,?]).
sentence('0187-2420',['Waarom',valt,motregen,langzamer,naar,beneden,dan,gewone,regen,?]).
sentence('0188-2421',['Wat',is,'DNA',?]).
sentence('0189-2422',['Hoeveel',mensen,werden,er,jaarlijks,aan,de,'Azteekse',zonnegod,'Tonatiuh',geofferd,?]).
sentence('0190-2423',['Waar',neemt,'Ben','Cramer',in,'2000',aan,deel,?]).
sentence('0191-2424',['Hoeveel',meter,bedraagt,een,'Engelse',mijl,?]).
sentence('0192-2425',['Wat',is,het,zeekadettenmat,?]).
sentence('0193-2426',['Hoeveel',soorten,glimwormen,zijn,er,ongeveer,?]).
sentence('0194-2427',['Wat',is,de,naam,van,het,'Engelse',graafschap,dat,het,dichtst,bij,het,'Europese',vasteland,ligt,?]).
sentence('0195-2428',['Wie',was,de,eerste,persoon,naar,wie,werd,verwezen,met,'"',horse,whisperer,'"',?]).
sentence('0196-2429',['Ligt',het,hart,in,de,romp,meer,links,of,meer,rechts,?]).
sentence('0197-2430',['Hoe',lang,is,'Rob','Bruintjes',?]).
sentence('0198-2431',['Van',welke,familie,van,de,slangen,zijn,alle,soorten,giftig,?]).
sentence('0199-2432',['Wat',is,de,naam,van,het,geologische,tijdvak,dat,'10.000',jaar,geleden,begon,?]).
sentence('0200-2433',['Uit',hoeveel,gemeenten,bestaat,'Samtgemeinde','Brookmerland',?]).



sentence('nl2en0001-44',['Welke',nationaliteit,had,'Jacques','Offenbach',?]).
sentence('nl2en0002-44',['In',welke,stad,is,hij,geboren,?]).
sentence('nl2en0003-44',['Welk',instrument,bespeelde,hij,?]).
sentence('nl2en0004-44',['Met',welke,pianisten,heeft,hij,samengewerkt,?]).
sentence('nl2en0005-53_2',['Wat',was,het,beroep,van,'Charles','Wakefield','Cadman',?]).
sentence('nl2en0006-53_2',['Welk',orkest,heeft,hij,opgericht,?]).
sentence('nl2en0007-53_2',['Hoeveel',liedjes,heeft,hij,geschreven,?]).
sentence('nl2en0008-53_2',['Voor',welke,films,heeft,hij,muziek,geschreven,?]).
sentence('nl2en0009-21',['Welke',componist,schreef,'"','Pacific','231','"',?]).
sentence('nl2en0010-21',['Wat',wordt,erin,geïmiteerd,?]).
sentence('nl2en0011-24',['Wat',is,de,naam,van,het,meest,bekende,werk,van,'Jeremiah','Clarke',?]).
sentence('nl2en0012-24',['Hoe',kwam,hij,om,het,leven,?]).
sentence('nl2en0013-31',['Wat',is,het,beroep,van,'Richard','Clayderman',?]).
sentence('nl2en0014-31',['Hoeveel',liedjes,heeft,hij,opgenomen,?]).
sentence('nl2en0015-31',['Hoeveel',exemplaren,zijn,er,verkocht,van,het,nummer,'"','Ballade',pour,'Adeline','"',?]).
sentence('nl2en0016-34',['In',welk,jaar,werd,'Emerson','Lake',&,'Palmer',gevormd,?]).
sentence('nl2en0017-34',['Welke',afkorting,wordt,voor,de,groep,gebruikt,?]).
sentence('nl2en0018-34',['Noem',twee,instrumenten,die,door,'Emerson',worden,bespeeld,'.']).
sentence('nl2en0019-40',['Wie',heeft,het,album,'"','Songs',in,'A','Minor','"',uitgebracht,?]).
sentence('nl2en0020-40',['Hoeveel',exemplaren,werden,op,de,eerste,dag,verkocht,?]).
sentence('nl2en0021-43',['Wat',is,de,echte,naam,van,'"','Common','"',?]).
sentence('nl2en0022-43',['Op',welke,dag,is,zijn,eerste,album,uitgebracht,?]).
sentence('nl2en0023-46',['Wie',was,'Charlotte','Mew',?]).
sentence('nl2en0024-47',['Waar','Alexandre','Dumas',père,begraven,tot,'30',november,'2002',?]).
sentence('nl2en0025-47',['Waar',werd,hij,herbegraven,op,'30',november,'2002',?]).
sentence('nl2en0026-50',['Geef',een,citaat,van,'Alfred','Tennyson','.']).
sentence('nl2en0027-52',['In',welke,stad,groeide,'W.H.','Auden',op,?]).
sentence('nl2en0028-52',['Welke',positie,aan,de,universiteit,van,'Oxford',bekleedde,hij,van,'1956',tot,'1961',?]).  % bekleede -> bekleedde
sentence('nl2en0029-55',['Wat',is,de,'Hegeliaanse',filosofie,?]).
sentence('nl2en0030-56',['In',welk,jaar,verscheen,de,film,'Remains',of,the,'Day',?]).
sentence('nl2en0031-56',['Wie',speelde,de,rol,van,'Mr.','Stevens',in,de,film,?]).
sentence('nl2en0032-56',['Wie',schreef,de,muziek,voor,de,film,?]).
sentence('nl2en0033-56',['Wie',schreef,het,boek,waarop,de,film,is,gebaseerd,?]).
sentence('nl2en0034-3',['Welke',twee,'studio\'s',brachten,de,film,'Angela\'s','Ashes',uit,?]).
sentence('nl2en0035-3',['In',welke,'Ierse',stad,speelt,de,film,zich,af,?]).
sentence('nl2en0036-44',['Noem',een,van,de,bedrijven,die,de,film,'Evelyn',coproduceerden,'.']).  % produceerde -> produceerden
sentence('nl2en0037-45',['Welke',film,wordt,beschreven,als,de,'35e',beste,'Britse',film,allertijden,?]).
sentence('nl2en0038-45',['Waarop',rijden,de,'Rockers',in,de,film,?]).
sentence('nl2en0039-48',['Wiens',stem,komt,voor,in,de,film,'Dragonheart',?]).
sentence('nl2en0040-49',['Noem',drie,'Ierse',architecten]).
sentence('nl2en0041-51',['Geef',een,voorbeeld,van,een,gebouw,in,'Sydney',ontworpen,door,'Norman','Foster','.']).
sentence('nl2en0042-52',['Welke',architect,ontwierp,het,nieuwe,'Britse',parlementsgebouw,nadat,het,'1834',was,vernietigd,in,een,brand,?]).
sentence('nl2en0043-54',['Wat',is,'Poundbury',?]).
sentence('nl2en0044-54',['Welke',architect,heeft,het,ontworpen,?]).
sentence('nl2en0045-54',['Van',wie,is,de,grond,van,de,stad,?]).
sentence('nl2en0046-54',['Welke','Engelse',prins,is,bij,de,stad,betrokken,?]).
sentence('nl2en0047-58',['Hoeveel',kerken,in,'Londen',zijn,door,'Christopher','Wren',ontworpen,?]).
sentence('nl2en0048-59',['Welk','Londens',plein,werd,op,aanvraag,van,de,graaf,van,'Bedford',ontworpen,door,'Inigo','Jones',?]).
sentence('nl2en0049-1_5',['Wat',is,'Telugu',?]).
sentence('nl2en0050-1_5',['Hoeveel',moedertaalsprekers,kent,het,?]).
sentence('nl2en0051-4',['Hoe',heette,het,eerste,boek,geschreven,in,'Esperanto',?]).
sentence('nl2en0052-4',['Wanneer',werd,dit,boek,uitgegeven,?]).
sentence('nl2en0053-4',['Aan',welke,universiteit,wordt,onderwezen,in,'Esperanto',?]).
sentence('nl2en0054-4',['Hoeveel',werkwoordsvervoegingen,worden,in,'Esperanto',gebruikt,?]).
sentence('nl2en0055-7',['Welke','Franse',organisatie,ziet,toe,op,het,correct,gebruik,van,de,'Franse',taal,?]).
sentence('nl2en0056-7',['Hoeveel',leden,heeft,zij,?]).
sentence('nl2en0057-12',['Wat',betekent,'"',bungo,'"',in,het,'Japans',?]).
sentence('nl2en0058-14_1',['Wat',waren,de,vier,oorsponkelijke,officiele,talen,van,het,'Pools-Litouwse','Gemenebest']).
sentence('nl2en0059-15',['Wat',is,astronomie,?]).
sentence('nl2en0060-16',['Wat',is,geomorfologie,?]).
sentence('nl2en0061-17_2',['Wie',schreef,het,eerste,computerprogramma,voor,annotatie,van,genomen,?]).
sentence('nl2en0062-17',['In',welk,jaar,schreef,'Mathieu','Orfila',zijn,'"','Traité',des,poisons,'"',?]).
sentence('nl2en0063-19',['Wanneer',was,de,recapitulatietheorie,van,'Ernst','Haeckel',algemeen,geaccepteerd,?]).
sentence('nl2en0064-20',['Geef',een,andere,naam,voor,fylogenetische,groepen,'.']).
sentence('nl2en0065-21',['Noem',drie,personen,die,kansspelen,hebben,geanalyseerd,'.']).
sentence('nl2en0066-22',['Wanneer',is,'Joseph','Fourier',geboren,?]).
sentence('nl2en0067-24',['Waar',is,'Joseph','Fourier',geboren,?]).
sentence('nl2en0068-25',['Wie',bedacht,de,term,'"',ethnography,of,speaking,'"',in,de,zestiger,jaren,?]).
sentence('nl2en0069-26',['Waar',werd,'Martin','Heidegger',hoogleraar,filosofie,?]).
sentence('nl2en0070-28_8',['Waar',is,'Jacques','Derrida',geboren,?]).
sentence('nl2en0071-28_8',['Wanneer',gaf,hij,de,lezing,'"','Structure',',','Sign',',',and,'Play',in,the,'Discourse',of,the,'Human','Sciences','"',aan,de,'Johns','Hopkinsuniversiteit',?]).
sentence('nl2en0072-30',['Hoe',oud,was,'Nietzsche',toen,hij,hoogleraar,werd,aan,de,universiteit,van,'Basel',?]).  % toe hij -> toen hij
sentence('nl2en0073-30',['Hoe',oud,was,hij,toen,hij,'"','Ecce','Homo','"',schreef,?]).
sentence('nl2en0074-32',['Van',welke,politieke,partij,is,de,'Ier','Bertie','Ahern',?]).
sentence('nl2en0075-34',['Wanneer',is,de,'Ierse',politicus,'Willie','O\'Dea',geboren,?]).
sentence('nl2en0076-35',['Waar',is,de,'Ierse',politicus,'Willie','O\'Dea',geboren,?]).
sentence('nl2en0077-36',['Van',welke,politieke,partij,is,'Tony','Blair',?]).
sentence('nl2en0078-37',['Op',welke,school,heeft,'William','Hague',gezeten,?]).
sentence('nl2en0079-43',['Hoe',groot,was,het,gedeelte,van,de,twinstigste,eeuw,waarin,de,'Britse',conservatieve,partij,aan,de,macht,was,?]).
sentence('nl2en0080-44',['In',welk,jaar,is,de,'Ierse',partij,'"','Progressive','Democrats','"',opgericht,?]).
sentence('nl2en0081-44',['Hoeveel',zetels,won,zij,bij,de,algemene,verkiezingen,van,'1987',?]).
sentence('nl2en0082-27',['Wanneer',werden,de,eerste,tenniskampioenschappen,in,'Wimbledon',gehouden,?]).
sentence('nl2en0083-28',['Hoeveel','Jeu',de,'Paumevelden',zijn,er,?]).
sentence('nl2en0084-29',['Hoe',heet,de,stick,die,wordt,gebruikt,in,de,'Ierse',sport,hurling,?]).
sentence('nl2en0085-31',['Welk',dier,berijden,polospelers,?]).  % Wel -> Welk
sentence('nl2en0086-33_8',['Welk',vervoermiddel,wordt,gebruikt,in,de,sport,motorcross,?]).
sentence('nl2en0087-34_7',['Hoeveel',zijspanwereldkampioenschappen,won,'Steve','Webster',tussen,'1987',en,'2004',?]).
sentence('nl2en0088-35_4',['Wat',is,bij,het,roeien,een,skiff,?]).
sentence('nl2en0089-36',['Over',welke,afstand,gaat,de,kortste,hordenrace,bij,de,mannen,?]).
sentence('nl2en0090-37',['Hoe',lang,is,de,langste,hordenrace,?]).
sentence('nl2en0091-38',['In',welke,landen,vinden,ijszeilraces,plaats,?]).  %ijzeil -> ijszeil
sentence('nl2en0092-39',['Hoe',breed,is,een,zogenaamd,'"','Dutch','"',jacht,bij,het,ijszeilen,?]).
sentence('nl2en0093-40',['Welke',afstand,wordt,afgelegd,in,een,marathon,?]).
sentence('nl2en0094-42',['Welke',afstand,wordt,afgelegd,bij,een,hamsterrace,?]).
sentence('nl2en0095-43_5',['Wat',is,loopsnelheid,?]).
sentence('nl2en0096-44',['Met',welk,voorwerp,wordt,er,gegooid,in,het,spel,petanque,?]).
sentence('nl2en0097-45',['Wie',is,'Barry','McGuigan',?]).
sentence('nl2en0098-46',['Wie',is,'Steve','Redgrave',?]).
sentence('nl2en0099-47_0',['Welke',country,club,bezit,'Nigel','Mansell',?]).
sentence('nl2en0100-48_3',['Wie',is,'Murray','Walker',?]).
sentence('nl2en0101-49_6',['In',welk,jaar,won,'James','Hunt',het,wereldkampioenschap,'Formule','1',?]).
sentence('nl2en0102-50_9',['In',welk,jaar,werd,'John','Curry',wereldkampioen,kunstschaatsen,?]).
sentence('nl2en0103-51',['Wat',is,een,'Chevrolet','Sprint',?]).
sentence('nl2en0104-52_3',['Wat',is,een,'Bolwell','Nagari',?]).
sentence('nl2en0105-53_3',['Waar',is,de,'Britse',autofabrikant,'Morgan',gevestigd,?]).
sentence('nl2en0106-55',['Hoeveel','Panther','Rio-auto\'s',zijn,er,gebouwd,?]).
sentence('nl2en0107-54',['Hoeveel',wielen,had,de,'F-4-wagen',van,de,'Britse',autofabrikant,'Morgan',?]).
sentence('nl2en0108-56_9',['Waar',werd,de,'Volkswagen','Polo','Playa',gebouwd,?]).
sentence('nl2en0109-57_9',['Welke','Britse',autofabrikaant,maakte,de,'Vauxhall','Chevette',?]).
sentence('nl2en0110-58',['Wat',is,een,kwets,?]).
sentence('nl2en0111-59',['Wat',is,een,loquat,?]).
sentence('nl2en0112-0',['Wanneer',ontdekte,men,dat,de,cichoreiwortel,inuline,bevat,?]).
sentence('nl2en0113-1',['Hoe',hoog,kan,een,avocadoboom,worden,?]).
sentence('nl2en0114-2',['Noem',een,plant,die,gebruikt,wordt,voor,het,verkrijgen,van,suiker,'.']).
sentence('nl2en0115-3',['Welke',ziekte,kan,worden,genezen,met,knoflook,?]).
sentence('nl2en0116-4',['Hoe',lang,is,de,'Engelse',snelweg,'M56',?]).
sentence('nl2en0117-6_2',['Hoe',heet,de,'Engelse',snelweg,rondom,'Manchester',?]).
sentence('nl2en0118-8_0',['In',welk,jaar,is,de,'Romeinse',stad,'Exeter',gevormd,?]).
sentence('nl2en0119-8',['Welke',gravin,liet,in,de,dertiende,eeuw,een,dam,aanleggen,in,de,rivier,'Exe',?]).
sentence('nl2en0120-10',['Waar',ontspringt,de,rivier,'Deben',in,'Suffolk',?]).
sentence('nl2en0121-11',['Hoe',lang,is,de,'Koningin','Elizabeth','II-brug',?]).
sentence('nl2en0122-13_3',['Hoeveel',staal,is,gebruikt,bij,het,bouwen,van,de,'Forth-Rail-brug',?]).
sentence('nl2en0123-14_9',['Wat',is,de,hoofdstad,van,'Namibië',?]).
sentence('nl2en0124-15',['Wat',is,de,oppervlakte,van,'Frankrijk',zonder,de,overzeese,departementen,?]).
sentence('nl2en0125-16_2',['Hoe',heet,de,hoofdstad,van,'Letland',?]).
sentence('nl2en0126-17',['Waar',zetelt,de,regering,van,'Maleisië',?]).
sentence('nl2en0127-18',['Wat',is,het,grootste,warenhuis,van,het,'Verenigd','Koninkrijk',?]).
sentence('nl2en0128-19',['Wie',plaatste,in,'1964',een,klok,boven,de,ingang,van,'Fortnum',&,'Mason',?]).  % oven -> boven
sentence('nl2en0129-19',['Waar',staat,de,winkel,bekend,om,?]).
sentence('nl2en0130-45',['Wat',is,de,'Xbox',?]).
sentence('nl2en0131-45',['Welke',gamepad,werd,door,het,blad,'Game','Informer',uitgeroepen,tot,'Blunder',van,het,'Jaar',?]).
sentence('nl2en0132-42',['Welk',bedrijf,produceert,de,spelcomputer,'Wii',?]).
sentence('nl2en0133-42',['Wie',heeft,de,spelcomputer,ontworpen,?]).
sentence('nl2en0134-42',['Noem',één,van,de,typen,media,die,kan,worden,gelezen,door,de,computer,'.']).
sentence('nl2en0135-47',['Wat',is,een,'MP3-speler',?]).
sentence('nl2en0136-7_9',['Hoeveel',inwoners,telt,'Huddersfield',?]).
sentence('nl2en0137-48',['Wat',is,een,'Livery','Company',?]).
sentence('nl2en0138-49',['Wie',zijn,de,'Salesianen',van,'Don','Bosco',?]).
sentence('nl2en0139-50',['Wat',is,de,'CAMRA',?]).
sentence('nl2en0140-52_3',['Wat',voor,een,soort,organisatie,is,de,'Royal','Yachting','Association',?]).
sentence('nl2en0141-53_1',['Wie',was,'Bruce','Lee',?]).
sentence('nl2en0142-53',['Wat',is,de,bijnaam,van,'Ian','Thorpe',?]).
sentence('nl2en0143-53',['Hoe',zwaar,was,hij,bij,zijn,geboorte,?]).
sentence('nl2en0144-56',['Waar',is,de,'IAAF',gezeteld,?]).
sentence('nl2en0145-57',['Waarvoor',staat,de,afkorting,'CORGI',?]).
sentence('nl2en0146-57',['Aan',welke,overheidsinstantie,moet,de,'CORGI',verantwoordelijkheid,afleggen,?]).
sentence('nl2en0147-59',['Welke','Duitse',band,bracht,een,album,uit,dat,alleen,beschikbaar,is,op,een,'USB-stick',?]).
sentence('nl2en0148-0',['Wat',was,de,codenaam,van,de,'Nintendo','DS',?]).
sentence('nl2en0149-0',['Hoe',heet,het,nieuwe,model,dat,uitkwam,in,'2006',?]).
sentence('nl2en0150-3_8',['Hoe',groot,was,de,verhoging,van,de,accijns,op,sigaretten,in,'Californië',op,'1',januari,'1994',?]).
sentence('nl2en0151-4',['Wat',is,het,beroep,van,'Art','Shell',?]).
sentence('nl2en0152-6',['Noem',één,van,de,tracks,van,het,album,'"','MoJazz','Christmas','Album','"',van,pianist,'Eric','Reed','.']).
sentence('nl2en0153-8_2',['Voor',welk,bedrijf,werkt,'Dick','Mason',?]).
sentence('nl2en0154-8',['Wat',is,het,beroep,van,'Jerry','Hickman',?]).
sentence('nl2en0155-9',['Hoeveel',inwoners,heeft,het,plaatsje,'Starbuck',in,'Minnesota',?]).
sentence('nl2en0156-10',['Hoeveel',personen,moeten,in,een,auto,op,de,carpoolstrook,langs,de,'Santa','Monica','Freeway',zitten,?]).
sentence('nl2en0157-14',['Wat',laten,de,modellen,zien,op,de,jaarlijkse,'Damas',de,'Caridad','Bal','Masque',?]).
sentence('nl2en0158-15',['Hoe',lang,is,'Matt','Steffe',?]).
sentence('nl2en0159-17_7',['Welke',studio,bracht,de,film,'The','Toxic','Avenger',uit,?]).
sentence('nl2en0160-18_4',['Welk',instrument,bespeelt,'Betty','Bryant',?]).
sentence('nl2en0161-19_6',['Welke','Amerikaanse',organisatie,startte,'Operation','Pothole',?]).
sentence('nl2en0162-24',['Wat',zijn,de,inschrijfkosten,voor,de,'Area','Code','Games',in,'Blair','Field',?]).
sentence('nl2en0163-26',['Wie',heeft,de,'tv-serie','Brady','Bunch',bedacht,?]).
sentence('nl2en0164-27',['Van',welk,team,was,'Tom','Gullikson',in,september,'1994',aanvoerder,?]).
sentence('nl2en0165-28',['Hoe',groot,is,de,winkel,van,'House',of,'Fabrics',in,'Simi','Valley']).
sentence('nl2en0166-29',['Voor',welk,bedrijf,werkt,'Neil','Sweig',?]).
sentence('nl2en0167-30',['Hoe',lang,is,'Jerod','Ward',?]).
sentence('nl2en0168-31',['Noem',een,vis,die,bij,de,'Revillagigedo-eilanden',kan,worden,gevangen,'.']).
sentence('nl2en0169-32',['Waar',vond,de,kunsttentoonstelling,'Brand','XXIV',plaats,?]).
sentence('nl2en0170-49_1',['Wat',is,aquavit,?]).
sentence('nl2en0171-50',['Wat',is,'Disneyficatie',?]).
sentence('nl2en0172-51',['Wie',is,'Richard','D.','Farman',?]).
sentence('nl2en0173-52',['Wie',is,'James','L.','Armstrong',?]).
sentence('nl2en0174-53',['Noem',drie,films,die,werden,gepresenteerd,op,het,zesde,filmfestival,van,'Palm','Springs','.']).
sentence('nl2en0175-2',['Welke',drank,wordt,ook,wel,'"',levenswater,'"',genoemd,?]).
sentence('nl2en0176-3',['Wie',is,directeur,corporate,services,van,de,'HOWDENgroep',?]).
sentence('nl2en0177-5',['Wat',voor,soort,dier,is,'Letsbeonestaboutit',?]).
sentence('nl2en0178-6',['Wie',was,staatssecretaris,van,'Schotland',in,'1995',?]).
sentence('nl2en0179-7',['Wat',werd,door,'Jill','Vandebrand',ontworpen,?]).
sentence('nl2en0180-9',['Wanneer',is,de,'Bath','Press','Group',opgericht,?]).
sentence('nl2en0181-9',['Hoeveel',boeken,geeft,zij,per,jaar,uit,?]).
sentence('nl2en0182-11',['Hoeveel',liedjes,telt,de,revue,'Closer',than,'Ever',?]).
sentence('nl2en0183-12',['Wie',schreef,de,muziek,voor,de,liedjes,in,de,revue,'Closer',than,'Ever',?]).
sentence('nl2en0184-13',['Hoeveel',rondes,worden,er,per,jaar,gespeeld,op,de,golfbaan,'Collingtree','Park',bij,'Northampton',?]).
sentence('nl2en0185-14',['Hoeveel',spelers,namen,deel,aan,het,open,golftoernooi,van,'Andalusië',op,de,'Islantilla',club,in,'1995',?]).
sentence('nl2en0186-15',['Wanneer',ontving,'Bob','Steward',zijn,diploma,van,de,'Glasgow','School',of,'Art',?]).
sentence('nl2en0187-16',['In',welk,jaar,zal,het,'Brunswick','City','Hotel',in,'Glasgow',worden,geopend,?]).
sentence('nl2en0188-18_4',['In',welk,jaar,is,het,bedrijf,'In','Video',van,'David','McWhinnie',opgericht,?]).
sentence('nl2en0189-19',['Wanneer',ontving,'William','McIntosh','Millar',de,'OBE',?]).
sentence('nl2en0190-20',['Waar',was,'David','S.','Forsyth',bibliothecaris,?]).
sentence('nl2en0191-21',['Waar',woont,'Muriel','Herkes',?]).
sentence('nl2en0192-22',['Waar',vond,de,conferentie,van,de,'Schotse','Labourpartij',plaats,in,'1995',?]).
sentence('nl2en0193-23',['Wie',is,de,directeur,van,de,racebanen,van,'Uttoxeter',en,'Newcastle',?]).
sentence('nl2en0194-24',['Welke',rang,had,'Gerry','Purnell',op,de,'HMS','Indefatigable',in,'1945',?]).
sentence('nl2en0195-25',['Wie',is,'Tim','Fawcett',?]).
sentence('nl2en0196-26',['Waarvoor',staat,de,afkorting,'NFUS',?]).
sentence('nl2en0197-28',['Wat',voor,soort,organisatie,is,'Camelot',?]).
sentence('nl2en0198-29',['Noem',de,boeken,die,geschreven,zijn,door,'Nicholas','Ind.']).
sentence('nl2en0199-18',['In',welke,opera,van,'Puccini',zit,een,viola,'d\'amore',?]).
sentence('nl2en0200-22',['Hoeveel',spelers,nemen,deel,aan,singlestennis,?]).




sentence('nl2es0001-9',['Wat',is,orichalcum,?]).
sentence('nl2es0002-12',['Wie',was,'Edgar','P.','Jacobs',?]).
sentence('nl2es0003-12',['In',welk,jaar,leerde,hij,'Hergé',kennen,?]).
sentence('nl2es0004-12',['In',welk,jaar,verscheen,het,eerste,album,van,'Blake',en,'Mortimer',?]).
sentence('nl2es0005-15',['Waar',werd,tijdens,kerst,'1995',naar,verwezen,met,'"','El','Gordo','"',?]).
sentence('nl2es0006-15',['Wat',was,de,prijs,in,dat,jaar,?]).
sentence('nl2es0007-17',['Wie',was,'Eleanor','Roosevelt',?]).
sentence('nl2es0008-17',['In',welk,jaar,trouwde,zij,met,'Franklin','Delano','Roosevelt',?]).
sentence('nl2es0009-19',['Waar',leeft,de,'Mohavestam',?]).
sentence('nl2es0010-19',['Wie',waren,hun,vijanden,?]).
sentence('nl2es0011-21',['Op',welke,leeftijd,overleed,'Wallace','Rowling',?]).
sentence('nl2es0012-21',['Van',welk,land,was,hij,'minister-president',?]).
sentence('nl2es0013-23',['Wie',schreef,de,encycliek,'"','Evangelium','Vitae','"',?]).
sentence('nl2es0014-23',['Hoeveel',encyclieken,schreef,hij,?]).
sentence('nl2es0015-25',['In',welk,sterrebeeld,staat,'Deneb',?]).
sentence('nl2es0016-25',['Wat',is,de,afstand,tussen,de,ster,en,de,aarde,?]).
sentence('nl2es0017-26',['Uit',welke,eilanden,bestaan,de,'Pelagische','Eilanden',?]).
sentence('nl2es0018-26',['Hoe',heet,het,grootste,eiland,?]).
sentence('nl2es0019-28',['In',welke,stad,is,'Karel',de,'Grote',begraven,?]).
sentence('nl2es0020-28',['Wanneer',is,hij,overleden,?]).
sentence('nl2es0021-28',['Welke',stad,veroverde,hij,in,'778',?]).
sentence('nl2es0022-31',['Wie',was,'Saul','Bass',?]).
sentence('nl2es0023-31',['Wie',was,zijn,leraar,?]).
sentence('nl2es0024-33',['Wie',ontwerp,het,'Guggenheimmuseum',in,'New','York',?]).
sentence('nl2es0025-33',['En',wie,ontwierp,die,van,'Bilbao',?]).
sentence('nl2es0026-34',['Van',welke,planeet,komt,'Superlópez',?]).
sentence('nl2es0027-34',['Wie',zijn,zijn,vijanden,?]).
sentence('nl2es0028-37',['Wie',hebben,'Magnum','Photos',opgericht,?]).
sentence('nl2es0029-37',['In',welk,jaar,vond,dat,plaats,?]).
sentence('nl2es0030-38',['Wanneer',was,de,slag,bij,'Brunete',?]).
sentence('nl2es0031-38',['Waar',werd,'Gerda','Taros',artikel,over,de,slag,gepubliceerd,?]).
sentence('nl2es0032-38',['Naar',welk,ziekenhuis,werd,zij,na,haar,ongeluk,gebracht,?]).
sentence('nl2es0033-42',['Wie',spelen,de,belangrijkste,rollen,in,de,film,'Beetlejuice',?]).
sentence('nl2es0034-42',['Wie',van,hen,speelt,de,hoofdrol,?]).
sentence('nl2es0035-44',['Wat',is,een,wierookvat,?]).
sentence('nl2es0036-44',['Hoe',heet,die,van,de,kathedraal,van,'Santiago',de,'Compostela',?]).
sentence('nl2es0037-44',['Hoe',zwaar,is,hij,?]).
sentence('nl2es0038-47_8',['Wie',schreef,'"','De',vernuftige,edelman,'Don','Quichot',van,'La','Mancha','"',?]).
sentence('nl2es0039-47_8',['Wat',waren,de,reuzen,tegen,wie,hij,vocht,?]).
sentence('nl2es0040-48',['Wat',was,'ODESSA',?]).
sentence('nl2es0041-48',['Wie',was,'ODESSAs',leider,in,'Spanje',?]).
sentence('nl2es0042-50',['Wie',werd,door,'Otto','Skorzeny',gered,?]).
sentence('nl2es0043-50',['Hoeveel',zweefvliegtuigen,werden,daarbij,gebruikt,?]).
sentence('nl2es0044-50',['Waar',vond,het,proces,tegen,hem,plaats,?]).
sentence('nl2es0045-50',['Wie',hielp,hem,te,ontsnappen,?]).
sentence('nl2es0046-57_1',['Hoeveel',mensen,werden,gedood,in,het,'Bloedbad',van,'Katyn',?]).
sentence('nl2es0047-57_1',['Hoeveel',overlevenden,waren,er,?]).
sentence('nl2es0048-57_1',['Welk',land,was,verantwoordelijk,?]).
sentence('nl2es0049-59',['Wat',was,'Hideki','Tojo',voor,de,aanval,op,'Pearl','Harbor',?]).
sentence('nl2es0050-59',['Op',welke,dag,werd,hij,opgehangen,?]).
sentence('nl2es0051-1',['Wat',is,het,'Verdrag',van,'Londen',?]).
sentence('nl2es0052-1',['Op',welke,dag,werd,het,gesloten,?]).
sentence('nl2es0053-3_3',['Waar',wordt,'Mirandees',gesproken,?]).
sentence('nl2es0054-3_3',['Welke',organisatie,bevordert,het,gebruik,van,de,taal,?]).
sentence('nl2es0055-4',['Welke',taifa,heeft,het,paleis,'La','Aljafería',gebouwd,?]).
sentence('nl2es0056-4',['Welke',organisatie,heeft,er,tegenwoordig,haar,hoofdkantoor,?]).
sentence('nl2es0057-6',['Welk',museum,zit,er,in,het,'Paleis',van,'Castril',?]).
sentence('nl2es0058-6',['In',welk,jaar,is,het,gebouwd,?]).
sentence('nl2es0059-6',['Wie',heeft,de,gevel,gemaakt,?]).
sentence('nl2es0060-8',['In',welk,land,is,'Sparta',?]).
sentence('nl2es0061-8',['In',welk,departement,ligt,het,?]).
sentence('nl2es0062-8',['Tegen',wie,vocht,zij,in,de,'Slag',bij,'Thermopylae',?]).
sentence('nl2es0063-8',['Hoeveel',soldaten,namen,er,volgens,'Herodotus',deel,aan,de,slag,?]).
sentence('nl2es0064-11',['Waar',moet,je,de,tanden,voor,de,tandenfee,achterlaten,?]).
sentence('nl2es0065-11',['Wie',heeft,de,tandenfee,bedacht,?]).
sentence('nl2es0066-12',['In',welk,land,is,het,'Kasteel',van,'Colditz',?]).
sentence('nl2es0067-12',['In',welke,deelstaat,is,het,kasteel,?]).
sentence('nl2es0068-12',['Wie',ontsnapte,als,eerste,van,het,kasteel,?]).
sentence('nl2es0069-14',['Wat',was,de,'Pour',le,'Mérite',?]).
sentence('nl2es0070-14',['In',welk,jaar,ontving,de,'Rode','Baron',de,onderscheiding,?]).
sentence('nl2es0071-16',['Waar',staan,de,brouwerijen,van,'Cristal',?]).
sentence('nl2es0072-16',['Hoeveel',bier,produceren,ze,per,maand,?]).
sentence('nl2es0073-18',['Wie',schreef,'"','2001',:,'A','Space','Odyssey','"',?]).
sentence('nl2es0074-18',['Wie',maakte,de,gelijknamige,film,?]).
sentence('nl2es0075-18',['In',welk,jaar,is,hij,gemaakt,?]).
sentence('nl2es0076-21_7',['Welk',vervoersmiddel,werd,gebruikt,in,de,'Kon-Tiki-expeditie',?]).
sentence('nl2es0077-21_7',['Hoeveel',mensen,zaten,erop,?]).
sentence('nl2es0078-22',['In',welke,provincie,ligt,'Catoira',?]).
sentence('nl2es0079-22',['In',welke,maand,vieren,zij,het,'Vikingfestival',?]).
sentence('nl2es0080-23',['Wat',heeft,'Samuel','Morse',uitgevonden,?]).
sentence('nl2es0081-23',['Hoe',lang,was,de,eerste,telegraafverbinding,?]).
sentence('nl2es0082-25',['Van',wie,zijn,de,postcodes,in,'Spanje',?]).
sentence('nl2es0083-25',['Hoeveel',cijfers,bevatten,de,'Spaanse',postcodes,?]).
sentence('nl2es0084-25',['Welke',stad,heeft,postcode,'28046',?]).
sentence('nl2es0085-27',['Welke',opmaaktaal,is,bedacht,door,'Donald','Knuth',?]).
sentence('nl2es0086-27',['Hoe',spreek,je,het,uit,?]).
sentence('nl2es0087-36_3',['Wat',is,schroot,?]).
sentence('nl2es0088-36_3',['Wat',wordt,ervan,gemaakt,?]).
sentence('nl2es0089-37',['Hoe',heet,het,architectuurboek,van,'Leone','Battista','Alberti',?]).
sentence('nl2es0090-37',['En',hoe,heet,zijn,boek,over,beeldhouwkunst,?]).
sentence('nl2es0091-39_4',['In',welke,stad,ligt,het,hoofdkwartier,van,'Chinas','Oostelijke','Vloot',?]).
sentence('nl2es0092-39_4',['Hoe',ver,ligt,deze,stad,van,'Chinas',hoofdstad,?]).
sentence('nl2es0093-39_4',['Hoeveel',inwoners,had,de,stad,in,'2002',?]).
sentence('nl2es0094-28',['Hoe',lang,is,de,'M-40',?]).
sentence('nl2es0095-28',['Hoeveel',kostte,het,laatste,stuk,?]).
sentence('nl2es0096-40',['Wanneer',werd,het,verdrag,van,'Maastricht',getekend,?]).
sentence('nl2es0097-40',['Op',welke,dag,trad,het,verdrag,in,werking,?]).
sentence('nl2es0098-42',['Welk',instrument,speelde,'Keith','Moon',?]).
sentence('nl2es0099-42',['Hoe',oud,was,hij,toen,hij,stierf,?]).
sentence('nl2es0100-42',['In',welke,band,speelde,hij,?]).
sentence('nl2es0101-45',['Hoeveel',dagen,was,'Luis','Roldán',op,de,vlucht,voor,de,politie,?]).
sentence('nl2es0102-45',['Hoeveel',borg,moest,zijn,vrouw,betalen,?]).
sentence('nl2es0103-46',['Hoe',heet,de,hoofdstad,van,'Ierland']).
sentence('nl2es0104-47',['Wie',was,de,regisseur,van,'"','North',by,'Northwest','"',?]).
sentence('nl2es0105-47',['Hoe',oud,was,hij,toen,hij,stierf,?]).
sentence('nl2es0106-49',['Wat',is,de,munteenheid,van,'China',?]).
sentence('nl2es0107-50',['Hoe',heet,de,luchtvaartmaatschappij,van,'Niki','Lauda',?]).
sentence('nl2es0108-50',['In',welke,stad,staat,de,'Brandenburger','Poort',?]).
sentence('nl2es0109-51',['Hoe',heet,de,hoofdstad,van,'Canada',?]).
sentence('nl2es0110-52',['Welke','Nobelprijs',won,'Willy','Brandt',?]).
sentence('nl2es0111-53',['Welke','Nobelprijs',won,'Kenzaburo','Oe',?]).
sentence('nl2es0112-54',['Welk',team,werd,voetbalkampioen,van,'Spanje',in,het,seizoen,'1994-1995',?]).
sentence('nl2es0113-55',['Wat',is,de,geboortedatum,van,'Yasser','Arafat',?]).
sentence('nl2es0114-56',['In',welk,team,begon,de,'Formule-I-carrière',van,'Ayrton','Senna',?]).
sentence('nl2es0115-57',['Hoe',hoog,is,de,'Eiffeltoren',?]).
sentence('nl2es0116-58',['Wie',hebben,de,komeet,'Shoemaker-Levy','9',ontdekt,?]).
% sentence('nl2es0117-1',['Who',played,the,main,roles,in,the,movie,'"','Color',of,'Night','"',?]).
sentence('nl2es0118-59',['Wat',is,de,belangrijkste,stof,in,aspirine,?]).
sentence('nl2es0119-0',['Wie',was,de,eerste,'Amerikaanse',president,die,'China',bezocht,?]).
sentence('nl2es0120-2',['Waar',werd,'Bender','Bending','Rodríguez',gebouwd,?]).
sentence('nl2es0121-2',['Hoe',heten,de,ouders,van,'Luke','Skywalker',?]).
sentence('nl2es0122-3',['Welke',militaire,eenheden,leidde,'Rommel',?]).
sentence('nl2es0123-4',['Welk',bedrijf,gebruikte,'Bibendum',als,mascotte,?]).
sentence('nl2es0124-5',['Hoeveel',kelders,heeft,de,'Picassotoren',?]).
sentence('nl2es0125-6_4',['Waar',heeft,'Rachel','Weisz',literatuur,gestudeerd,?]).
sentence('nl2es0126-6',['Wat',was,de,codenaam,van,de,'Landing',in,'Normandië',?]).
sentence('nl2es0127-7',['Wie',was,de,'Amerikaanse',president,tijdens,de,aanval,op,'Pearl','Harbor',?]).
sentence('nl2es0128-8',['In',welk,land,begon,de,griepepidemie,van,'1918',?]).
sentence('nl2es0129-9',['Welke',terroristische,groep,pleegde,een,aanslag,tijdens,de,'Olympische','Spelen',van,'München',?]).
sentence('nl2es0130-10',['Wat',was,de,capaciteit,van,het,'Estadio','Santiago','Bernabéu',in,de,jaren,tachtig,?]).
sentence('nl2es0131-29',['Wat',is,een,adobe,?]).
sentence('nl2es0132-11',['Hoeveel','auto\'s',werden,op,de,wegen,van,'Madrid',verwacht,in,het,lange,weekend,'"','Puente',del,'Pilar','"',?]).
sentence('nl2es0133-30_1',['Wat',is,vexillologie,?]).
sentence('nl2es0134-30',['Wat',was,de,naam,van,de,geheime,politie,van,de,'Sovjetunie',tijdens,het,bewind,van,'Stalin',?]).
sentence('nl2es0135-31',['Welke',landen,nemen,deel,in,het,'TACIS-programma',?]).
sentence('nl2es0136-32',['Wat',is,ruwijzer,?]).
sentence('nl2es0137-33',['Wat',is,een,pilum,?]).
sentence('nl2es0138-34_7',['Hoeveel',jaar,wist,'"','Toto','"','Riina',uit,de,handen,van,de,politie,te,blijven,?]).
sentence('nl2es0139-34',['Hoeveel',gestolen,'auto\'s',werden,door,de,'Italiaanse','"','Guardia',de,'Finanzas','"',in,'1994',teruggevonden,?]).
sentence('nl2es0140-35',['Hoeveel',mensen,werden,gearresteerd,in,de,operatie,'Spartacus',?]).
sentence('nl2es0141-36',['Hoeveel',mensen,werden,door,blikseminslagen,gedood,in,'1955',?]).
sentence('nl2es0142-37',['Hoeveel',werd,in,'1994',betaald,voor,de,'Codex','Leicester',?]).
sentence('nl2es0143-38',['Hoeveel',dagen,zat,'Donatella','Di','Rosa',in,de,gevangenis,?]).
sentence('nl2es0144-39',['Wat',werd,in,'1995',door,de,'Spaanse',expeditie,bij,'Gebel','Barkal',ontdekt,?]).
sentence('nl2es0145-41',['Hoe',heette,het,vliegtuig,waarmee,paus,'Johannes','Paulus','II',in,'1995',door,de,'Verenigde','Staten',reisde,?]).
sentence('nl2es0146-41',['Welk',instrument,bespeelde,'Niccolò','Paganini',?]).
sentence('nl2es0147-42',['Wie',leidde,de,'Russische',afdeling,van,de,'CIA',van,'1983',tot,'1985',?]).
sentence('nl2es0148-43',['Wie',zijn,de,drie,wijzen,uit,het,oosten,?]).
sentence('nl2es0149-44',['Welk',circus,trad,in,'1995',op,tijdens,het,jazzfestival,van,'Montréal',?]).
sentence('nl2es0150-45',['Welke',record,pakte,'Rominger',in,'1994',af,van,'Induráin',?]).
sentence('nl2es0151-46_2',['Op',welke,afstand,won,'David','Meca',een,gouden,medaille,op,het,wereldkampioenschap,in,'Montreal',?]).
sentence('nl2es0152-46',['Wie',was,de,president,van,de,'Verenigde','Staten',tijdens,de,'Cubacrisis',?]).
sentence('nl2es0153-47',['Wat',werd,in,'1911',uit,het,'Louvre',gestolen,?]).
sentence('nl2es0154-48',['Wie',pleegde,een,aanslag,in,'Sarajevo',op,'28',juni,'1914',?]).
sentence('nl2es0155-49',['Welke','Amerikaanse',wet,verbood,het,drinken,van,alcohol,van,'1920',tot,'1933',?]).
sentence('nl2es0156-52_2',['Welke',stad,werd,door,'Jeanne','d\'Arc',bevrijd,?]).
sentence('nl2es0157-52',['Waar',bevond,'Santiago','Ramón',y,'Cajal',zich,in,'1874',?]).
sentence('nl2es0158-55',['Waarop',verwierf,'Guglielmo','Marconi',in,'1897',een,patent,?]).
sentence('nl2es0159-56',['In',welk,sterrenstelsel,bevindt,de,planeet,'Mongo',zich,?]).
sentence('nl2es0160-57',['Wie',is,de,keeper,van,het,'Spaanse',basketbalteam,?]).
sentence('nl2es0161-58_1',['Wat',is,een,uitsteker,?]).
sentence('nl2es0162-59',['Wie',bespeelt,bij,'Guns','N\'','Roses',de,viool,?]).
sentence('nl2es0163-0',['Welke',bus,stopt,bij,de,planeet,'Venus',?]).
sentence('nl2es0164-1',['Hoeveel',inwoners,heeft,'Mars',?]).
sentence('nl2es0165-1',['Wat',kost,een,toegangskaartje,voor,'The','House',of,'Blues',?]).
sentence('nl2es0166-2_9',['Waar',kan,ik,een,schilderij,van,'Renoir',kopen,?]).
sentence('nl2es0167-2',['Waar',is,de,'Tannhauserpoort',?]).
sentence('nl2es0168-3_6',['In',welke,'Spaanse',krant,verschijnt,'Casper',en,'Hobbes',?]).
sentence('nl2es0169-3',['Wie',is,'Rick','Deckard',?]).
sentence('nl2es0170-3',['Wat',zijn,replicants,?]).
sentence('nl2es0171-5_3',['Wat',is,de,'Kwomintang',?]).
sentence('nl2es0172-5',['Wat',is,'Opel',?]).
sentence('nl2es0173-6',['Wat',zijn,houtpellets,?]).
sentence('nl2es0174-7',['Wie',was,'Chiang','Kai-shek',?]).
sentence('nl2es0175-8_0',['Wie',was,'Rafael','Azcona',?]).
sentence('nl2es0176-9',['Wat',is,'Polaroid',?]).
sentence('nl2es0177-10',['Wat',zijn,de,kleuren,van,de,vier,ruiters,van,de,'Apocalyps',?]).
sentence('nl2es0178-11',['Welke','Europese',landen,bleven,neutraal,tijdens,de,'Tweede','Wereldoorlog',?]).
sentence('nl2es0179-12',['Wat',zijn,de,departementen,van,'Kreta',?]).
sentence('nl2es0180-13',['Welke',steden,liggen,in,de,'Algarve',?]).
sentence('nl2es0181-14',['Wie',zijn,de,leden,van,de,'Spaanse','Koninklijke',familie,?]).
sentence('nl2es0182-15',['Welke',landen,nemen,deel,in,de,'Europese','Zuidelijke','Sterrenwacht',?]).
sentence('nl2es0183-16',['Hoeveel','politieauto\'s',zou,'Barcelona',moeten,hebben,volgens,het,plan,van,'Belloch',?]).
sentence('nl2es0184-16',['En',hoeveel,zou,'Madrid',er,moeten,hebben,?]).
sentence('nl2es0185-18',['Geef',voorbeelden,van,woestijnen,die,in,de,regenschaduw,liggen,'.']).
sentence('nl2es0186-18',['In',wat,voor,een,auto,rijdt,inspecteur,'Columbo',?]).
sentence('nl2es0187-19',['Wat',werd,door,'Schuyler','Skaats','Wheeler',uitgevonden,?]).
sentence('nl2es0188-20',['Waarmee',heeft,'Lee','Harvey','Oswald','Kennedy',vermoord,?]).
sentence('nl2es0189-21',['Welke',misdaden,zou,'Alan','García',hebben,gepleegd,tussen,'1985',en,'1990',?]).
sentence('nl2es0190-22',['Hoeveel',vogelsoorten,leven,er,rondom,de,'Laguna',de,'Gallocanta',?]).
sentence('nl2es0191-23',['In',welk,seizoen,voor,'1994',ontmoette,'Barcelona','Milan',in,de,'Europese',competitie,voor,landskampioenen,?]).
sentence('nl2es0192-24',['Uit',hoeveel,paarden,bestaat,een,quadriga,?]).
sentence('nl2es0193-25',['Hoeveel',deelnemers,had,'The','Grand','National',van,'1839',?]).
sentence('nl2es0194-26',['Door',welk,zwaard,werd,de,gladius,vervangen,?]).
sentence('nl2es0195-27',['Welke',film,beleefde,zijn,première,tijdens,de,slotceremonie,van,het,'London','Film','Festival','1994',?]).
sentence('nl2es0196-28',['Welke',film,won,de,oscar,voor,de,beste,film,in,'1993',?]).
sentence('nl2es0197-29',['In',welke,episode,van,'"','The','Simpsons','"',wint,'Homer',de,'Pulitzerprijs',?]).
sentence('nl2es0198-29',['Met',welk,werk,won,'John','Updike',de,prijs,in,'1991',?]).
sentence('nl2es0199-39',['Wat',is,het,voedsel,van,de,dennenprocessierups,?]).
sentence('nl2es0200-40',['Hoe',lang,leeft,de,monarchvlinder,als,vlinder,?]).
