:- module(alpino_suite,[ sentence/2 ]).

:- hdrug_util:set_flag(application_type,qa).

sentence(1,['Wanneer',vond,de,'Duitse',hereniging,plaats,?]).
sentence(2,['Wie',is,bestuursvoorzitter,van,'Fiat',?]).
sentence(3,['Wie',stelde,een,embargo,in,tegen,'Irak',?]).
sentence(4,['In',welk,land,ligt,'Bosnië',?]).
sentence(5,['Wat',is,de,afkorting,voor,'gekke-koeienziekte',?]).
sentence(6,['Wat',betekent,de,afkorting,'EEG',?]).
sentence(7,['Waar',staat,de,afkorting,'DNA',voor,?]).
sentence(8,['Wie',heeft,de,'Berlijnse','Muur',gebouwd,?]).
sentence(9,['Wie',is,de,president,van,'Italië',?]).
sentence(10,['Welke',bevolkingsgroepen,voerden,oorlog,in,'Rwanda',?]).
sentence(11,['Wie',is,de,president,van,de,'Verenigde','Staten',?]).
sentence(12,['Wat',is,de,hoofdstad,van,'Zuid-Afrika',?]).
sentence(13,['Hoe',heet,de,nationale,luchtvaartmaatschappij,van,'Zwitserland',?]).
sentence(14,['Wanneer',is,de,'EEG',opgericht,?]).
sentence(15,['Wanneer',werd,het,'Verdrag',van,'Rome',getekend,?]).
sentence(16,['Wanneer',werd,de,'Europese','Akte',getekend,?]).
sentence(17,['Wanner',werd,het,'Verdrag',van,'Maastricht',getekend,?]).
sentence(18,['Welk','Europees',land,heeft,de,hoogste,alcoholconsumptie,?]).
sentence(19,['Hoeveel',inwoners,heeft,'Zweden',?]).
sentence(20,['Hoeveel',inwoners,heeft,'Berlijn',?]).
sentence(21,['Hoeveel',kost,een,'XTC',pil,?]).
sentence(22,['Hoe',heet,de,'Nederlandse',premier,?]).
sentence(23,['Hoeveel','Joodse',inwoners,heeft,'Israel',?]).
sentence(24,['Hoeveel',inwoners,heeft,'Irak',?]).
sentence(25,['Hoeveel',lidstaten,heeft,de,'Verenigde','Naties',?]).
sentence(26,['Wanneer',stelde,de,'Verenigde','Naties',een,embargo,in,tegen,'Irak',?]).
sentence(27,['Hoeveel',inwoners,heeft,'Tsjetsjenië',?]).
sentence(29,['Wie',is,de,leider,van,'Bosnië',?]).
sentence(30,['Hoeveel',is,een,yuan,waard,in,dollars,?]).
sentence(31,['Hoeveel',kantons,zijn,er,in,'Zwitserland',?]).
sentence(32,['Wanneer',werd,de,doodstraf,afgeschaft,in,'Frankrijk',?]).
sentence(33,['Wanneer',trad,de,wet,op,de,computercriminaliteit,in,werking,?]).
sentence(34,['Wie',is,de,president,van,'Frankrijk',?]).
sentence(35,['Hoe',lang,is,'Kim','Il','Sung',aan,de,macht,geweest,in,'Noord-Korea',?]).
sentence(36,['Hoe',heet,de,zoon,van,'Kim','Il','Sung',?]).
sentence(37,['Wat',is,de,hoofdstad,van,'Noord-Korea',?]).
sentence(38,['Hoeveel',politieke,gevangenen,zijn,er,in,'Noord-Korea',?]).
sentence(39,['Wie',is,er,aan,de,macht,in,'Pyongyang',?]).
sentence(40,['Hoeveel',inwoners,telt,'Moskou',?]).
sentence(41,['Op',welke,datum,trad,het,'Verdrag',van,'Maastricht',in,werking,?]).
sentence(42,['In',welk,jaar,besloot,'Noorwegen',middels,een,referendum,om,niet,toe,te,treden,tot,de,'Europese','Gemeenschap',?]).
sentence(43,['Wie',is,de,president,van,'Joegoslavië',?]).
sentence(44,['In',welk,land,in,'Afrika',is,een,nieuwe,grondwet,aangenomen,?]).
sentence(45,['Wat',is,de,uitslag,van,de,wedstrijd,'Italië-Noorwegen',tijdens,de,'WK',?]).
sentence(46,['Wanneer',is,de,republiek,'Zuid-Afrika',gesticht,?]).
sentence(47,['Wie',is,de,oprichter,van,de,'Orde',van,de,'Zonnetempel',?]).
sentence(48,['Hoe',oud,was,'Joseph',di,'Mambro',toen,hij,stierf,?]).
sentence(49,['Wat',is,de,afstand,tussen,de,zon,en,de,aarde,?]).
sentence(50,['Hoe',groot,is,de,wereldbevolking,?]).
sentence(51,['Hoeveel',landen,nemen,deel,aan,de,'Internationale','Conferentie',over,'Bevolking',en,'Ontwikkeling',?]).
sentence(52,['In',welke,stad,werd,de,'Internationale','Conferentie',over,'Bevolking',en,'Ontwikkeling',gehouden,?]).
sentence(53,['In',welk,jaar,trad,'Spanje',toe,tot,de,'Europese','Gemeenschap',?]).
sentence(54,['Wie',is,de,voorzitter,van,het,'Europese','Parlement',?]).
sentence(55,['Wie',is,de,'Duitse',bondspresident,?]).
sentence(56,['Wie',is,het,staatshoofd,van,'Australië',?]).
sentence(57,['Wanneer',is,de,'GATT',opgericht,?]).
sentence(58,['Waar',staat,'GATT',voor,?]).
sentence(59,['Wie',is,de,'Italiaanse',minister,van,buitenlandse,zaken,?]).
sentence(60,['Hoe',lang,was,de,'Berlijnse','Muur',?]).
sentence(61,['Wanneer',kwam,'Jeltsin',aan,de,macht,?]).
sentence(62,['Wat',is,de,'Chinese',munt,?]).
sentence(63,['Wie',is,de,president,van,'Rusland',?]).
sentence(64,['Welk',team,is,'Europees',kampioen,basketbal,?]).
sentence(65,['Wat',is,de,uitslag,van,de,finale,van,het,'Europese',kampioenschap,basketbal,?]).
sentence(66,['Wie',is,de,president,van,'Noord-Korea',?]).
sentence(67,['Hoeveel',lidstaten,telt,de,'Europese','Unie',?]).
sentence(68,['Hoeveel',inwoners,telt,'Azië',?]).
sentence(69,['Hoeveel',inwoners,heeft,'Sydney',?]).
sentence(70,['Hoeveel',inwoners,heeft,'Noord-Korea',?]).
sentence(71,['Waaruit',wordt,methaan,gewonnen,?]).
sentence(72,['Waar',vond,de,bijeenkomst,van,de,'G7-landen',plaats,?]).
sentence(73,['Waaruit',wordt,tolueen,gewonnen,?]).
sentence(74,['Hoeveel',motoren,heeft,een,vliegtuig,?]).
sentence(75,['Waardoor',worden,de,meeste,verkeersongevallen,veroorzaakt,?]).
sentence(76,['Welk',land,is,de,grootste,'olie-producent',ter,wereld,?]).
sentence(77,['Hoeveel',slachtoffers,worden,er,per,jaar,door,landmijnen,veroorzaakt,?]).
sentence(78,['Welk',land,heeft,het,hoogste,geboortecijfer,in,'Europa',?]).
sentence(79,['Wanneer',werd,de,'Berlijnse','Muur',gebouwd,?]).
sentence(80,['Waar',explodeerde,de,eerste,atoombom,?]).
sentence(81,['Wat',is,de,hoofdstad,van,'Canada',?]).
sentence(82,['In',welke,'Amerikaanse',staat,ligt,'San','Francisco',?]).
sentence(83,['In',welke,'Europese',stad,bevindt,zich,de,'Eiffeltoren',?]).
sentence(84,['Hoeveel',kinderen,heeft,'Silvio','Berlusconi',?]).
sentence(85,['Wie',tekenden,het,verdrag,van,'Lateranen',?]).
sentence(86,['Waar',ligt,'Vaticaanstad',?]).
sentence(87,['Wat',is,de,hoofdstad,van,'Rusland',?]).
sentence(88,['Hoe',heet,de,'Russische',munt,?]).
sentence(89,['Waar',ligt,'Haïti',?]).
sentence(90,['Wanneer',explodeerde,de,eerste,atoombom,?]).
sentence(91,['Wie',organiseerde,de,bouw,van,de,'Sint','Pieter',?]).
sentence(92,['Waarmee',zwaaiden,de,'Apollo',astronauten,op,de,maan,in,'1969',?]).
sentence(93,['Welke',prijs,hebben,'Weinberg',',','Salam',en,'Glashow',gewonnen,?]).
sentence(94,['Welk',land,is,de,grootste,exporteur,van,olijfolie,in,'Europa',?]).
sentence(95,['Hoeveel',kost,een,liter,olijfolie,ongeveer,?]).
sentence(96,['Hoe',lang,is,de,kustlijn,van,'Italië',in,kilometers,?]).
sentence(97,['In',welke,maand,vond,de,scheepsramp,met,de,'Estonia',plaats,?]).
sentence(98,['Hoeveel',slachtoffers,waren,er,bij,de,scheepsramp,met,de,'Estonia',?]).
sentence(99,['In',welke,oceaan,zonk,de,'Titanic',?]).
sentence(100,['Welke',zee,is,in,de,buurt,van,'Stockholm',?]).
sentence(101,['Uit',welke,haven,vertrok,de,veerboot,'"','Estonia','"',?]).
sentence(102,['Hoeveel',mensen,werden,gered,bij,de,ramp,met,de,veerboot,'"','Estonia','"',?]).
sentence(103,['Welke',veerboot,zonk,ten,zuidoosten,van,het,eiland,'Utö',?]).
sentence(104,['Waar',is,'Adolf','Hitler',geboren,?]).
sentence(105,['Welke','Amerikaanse',generaal,was,opperbevelhebber,van,de,geallieerden,in,'1943',?]).
sentence(106,['Hoeveel',inwoners,heeft,'Rusland',?]).
sentence(107,['Wie',is,de,'Duitse',minister,van,economische,zaken,?]).
sentence(108,['Wat',is,de,hoofdstad,van,'Haïti',?]).
sentence(109,['Hoeveel','Spaanse',blauwhelmen,overleden,in,'Bosnië',?]).
sentence(110,['Welk',beroep,heeft,'Renzo','Piano',?]).
sentence(111,['Waar',werd,een,grote,voorraad,methaan,ontdekt,?]).
sentence(112,['In',welk,land,ligt,het,gebied,van,de,'Grote','Meren',?]).
sentence(113,['Hoe',lang,duurt,het,om,een,'Duitse',herder,te,trainen,?]).
sentence(114,['Wiens',bijnaam,was,de,'"',woestijnvos,'"',?]).
sentence(115,['Wat',is,de,afkorting,voor,de,vakbond,van,'Zwitserse',spoorwegmedewerkers,?]).
sentence(116,['Van',welk,land,is,'Jeltsin',president,?]).
sentence(117,['Waar',staat,de,afkorting,'VN',voor,?]).
sentence(118,['Wat',is,de,voornaam,van,'Milosevic',?]).
sentence(119,['In',welk,jaar,viel,de,'Berlijnse','Muur',?]).
sentence(120,['Wanneer',begon,de,'Franse','Revolutie',?]).
sentence(121,['Wat',is,de,hoofdstad,van,'Ierland',?]).
sentence(122,['Wat',is,de,heilige,stad,voor,joden,',',christenen,en,moslims,?]).
sentence(123,['Wie',is,de,'Noorse',bondscoach,?]).
sentence(124,['Hoeveel',heeft,de,'Eurotunnel',gekost,?]).
sentence(125,['Wat',is,de,lengte,van,de,'Eurotunnel',?]).
sentence(126,['Hoeveel',mensen,werden,doodgeschoten,in,de,'Fosse','Ardeatine',?]).
sentence(127,['Welke',film,won,de,'Gouden','Leeuw',?]).
sentence(128,['Aan',wie,zijn,de,'Gouden','Leeuw',oeuvreprijzen,toegekend,?]).
sentence(129,['Hoeveel',planeten,zijn,er,in,het,zonnestelsel,?]).
sentence(130,['Wat',is,de,temperatuur,op,de,oppervlakte,van,de,zon,?]).
sentence(131,['Hoe',heet,de,eerste,man,op,de,maan,?]).
sentence(132,['Wanneer',is,de,'Gewapende','Islamitische','Groep',opgericht,?]).
sentence(133,['Hoeveel',werknemers,heeft,'Air','France',?]).
sentence(134,['Hoeveel',inwoners,heeft,'Algiers',?]).
sentence(135,['Algiers',is,de,hoofdstad,van,welk,land,?]).
sentence(136,['Welke',voetbalploeg,is,kampioen,van,'Italië',?]).
sentence(137,['Wie',is,de,voorzitter,van,de,voetbalploeg,'Roma',?]).
sentence(138,['In',welke,stad,is,het,'Delle','Alpi-stadion',?]).
sentence(139,['Hoe',heet,de,'Franse',premier,?]).
sentence(140,['Bij',welke,politieke,partij,hoort,'Silvio','Berlusconi',?]).
sentence(141,['Bij',welke,politieke,partij,hoort,'Fassino',?]).
sentence(142,['Wie',is,de,vrouw,van,'John','Lennon',?]).
sentence(143,['Aan',wie,werd,'Coppa','Volpi',voor,de,beste,mannelijke,hoofdrol,toegekend,?]).
sentence(144,['In',welke,maand,werd,de,'Eurotunnel',in,gebruik,genomen,?]).
sentence(145,['Hoeveel',soorten,haaien,zijn,er,?]).
sentence(146,['Hoeveel',voetbalteams,doen,mee,aan,het,'Italiaanse',kampioenschap,?]).
sentence(147,['Hoe',heet,de,'Italiaanse',premier,?]).
sentence(148,['Hoe',heet,het,nooit,gepubliceerde,nummer,van,'John','Lennon',dat,door,'Paul','McCartney',',','George','Harrison',en,'Ringo','Starr',is,opgenomen,?]).
sentence(149,['Wie',heeft,de,'Beatles',opgericht,?]).
sentence(150,['Wie',is,de,bekendste,internationale,terrorist,?]).
sentence(151,['In',welke,stad,is,de,'Brandenburger','Tor',?]).
sentence(152,['Welke','Franse',premier,pleegde,zelfmoord,in,de,jaren,'90',?]).
sentence(153,['Wat',is,de,'Turkmeense',hoofdstad,?]).
sentence(154,['In',welke,stad,werd,de,'Internationale','Conferentie',over,'Bevolking',en,'Ontwikkeling',gehouden,?]).
sentence(155,['Hoe',groot,is,het,gebied,dat,door,de,bosbranden,bij,'Sydney',werd,verwoest,?]).
sentence(156,['Hoeveel',landen,nemen,deel,in,de,'Europese','Economische','Ruimte',?]).
sentence(157,['Waar',staat,de,afkorting,'WTO',voor,?]).
sentence(158,['Voor',welke,theorie,is,de,'Nobelprijs',voor,de,'Economie',toegekend,?]).
sentence(159,['Waar',is,de,'Estonia',gezonken,?]).
sentence(160,['In',welk,jaar,zonk,de,'"','Mar','Egeo','"',?]).
sentence(161,['Welk',land,pleegde,een,invasie,in,'Haïti',?]).
sentence(162,['Welk',fenomeen,in,de,'Stille','Oceaan',beïnvloedt,het,wereldklimaat,?]).
sentence(163,['Wie',won,de,'Ronde',van,'Frankrijk',?]).
sentence(164,['Wanneer',begon,het,embargo,tegen,'Irak',?]).
sentence(165,['Welke','Russische',president,gaf,opdracht,tot,de,interventie,in,'Tsjetsjenië',?]).
sentence(166,['Waar',is,'Chiapas',?]).
sentence(167,['In',welke,stad,vond,de,finale,van,het,'WK',voetbal,plaats,?]).
sentence(168,['Hoeveel',doelpunten,vielen,er,tijdens,de,finale,van,het,'WK',voetbal,?]).
sentence(169,['Hoe',heet,de,'Chinese',munteenheid,?]).
sentence(170,['In',welk,deel,van,'Rusland',is,een,oliepijpleiding,gebroken,?]).
sentence(171,['Welke',kracht,had,de,aardbeving,waardoor,het,noorden,van,'Japan',werd,getroffen,?]).
sentence(172,['Welke','Noordkoreaanse',president,overleed,op,'82-jarige',leeftijd,?]).
sentence(173,['Waar',vond,de,'G7-top',plaats,?]).
sentence(174,['Op',welke,dag,was,de,opening,van,de,'Eurotunnel',?]).
sentence(175,['Hoeveel',doden,vielen,er,in,de,rechtbank,van,'Euskirchen',?]).
sentence(176,['Waar',ligt,'Euskirchen',?]).
sentence(177,['Bij',welk,festival,wordt,de,'"','Gouden','Leeuw','"',uitgereikt,?]).
sentence(178,['Waar',staat,de,afkorting,'IRA',voor,?]).
sentence(179,['Bij',welke,groep,hoorde,'John','Lennon',?]).
sentence(180,['Welk',land,ontving,hulp,tijdens,'"','Operatie','Turquoise','"',?]).
sentence(181,['In',welk,land,werd,het,'"','Plan','Real','"',ter,bestrijding,van,de,inflatie,uitgevoerd,?]).
sentence(182,['Wat',is,de,technische,naam,voor,'"','gekke-koeienziekte','"',?]).
sentence(183,['Uit',welk,land,komt,de,makelaar,'Schneider',?]).
sentence(184,['Welk',land,pleegde,een,invasie,in,'Koeweit',in,'1990',?]).
sentence(185,['Onder',welke,naam,is,het,'EFA-project',ook,wel,bekend,?]).
sentence(186,['Welke','Nobelprijs',kreeg,'Solzjenitsyn',?]).
sentence(187,['Hoe',heet,de,broer,van,'Mika','Kaurismaki',?]).
sentence(188,['Wie',is,de,'Italiaanse',premier,?]).
sentence(189,['In',welke,stad,werden,de,'Olympische','Winterspelen',gehouden,?]).
sentence(191,['Waar',werd,'Kazem','Radjavi',vermoord,?]).
sentence(192,['Wat',is,de,hoofdstad,van,'Iran',?]).
sentence(193,['Welke',prijs,won,de,film,'"','Pulp','Fiction','"',van,regisseur,'Quentin','Tarantino',tijdens,het,'Filmfestival',van,'Cannes',?]).
sentence(194,['Uit',welk,land,kwam,de,communistische,leider,'Najibullah',?]).
sentence(195,['Welke',functie,bekleedde,'Rabbani',toen,de,burgeroorlog,uitbrak,in,'Afghanistan',in,'1992',?]).
sentence(196,['Hoeveel',mensen,hadden,het,recht,om,te,stemmen,voor,een,nieuw,'Europees','Parlement',',',in,de,'EU',?]).
sentence(197,['Wie',was,de,eerste,'Europese',commissaris,uit,'Finland',?]).
sentence(198,['Uit',welk,land,komt,'Edouard','Balladur',?]).
sentence(200,['Hoe',vaak,is,de,'Braziliaanse',coureur,'Ayrton','Senna','Formule',wereldkampioen,in,de,'Formule','1',geweest,?]).
sentence(201,['Hoe',heette,de,zanger,en,leider,van,'Nirvana',?]).
sentence(202,['Wie',is,de,voorzitter,van,de,'Europese','Commissie',?]).
sentence(203,['In',welk,jaar,was,de,val,van,de,'Berlijnse','Muur',?]).
sentence(204,['Hoe',vaak,is,men,in,'Brazilië',van,munteenheid,veranderd,?]).
sentence(205,['In',welke,stad,is,het,'Europese','Parlement',?]).
sentence(206,['Op',welke,plaats,eindigde,'Italië',tijdens,het,wereldkampioenschap,voetbal,?]).
sentence(207,['Hoeveel','Europese',landen,nemen,deel,in,de,'G7',?]).
sentence(208,['Waar',staat,de,afkorting,'ETA',voor,?]).
sentence(209,['Wie',is,de,premier,van,'Spanje',?]).
sentence(210,['Wanneer',werd,het,ruimtestation,'MIR',in,een,baan,om,de,aarde,gebracht,?]).
sentence(211,['Op',welke,dag,van,het,jaar,wordt,de,'Spaanse','Grondwet',gevierd,?]).
sentence(212,['Wie',won,'Wimbledon',?]).
sentence(213,['Welk',land,veroverde,de,'Davis','Cup',?]).
sentence(214,['In',welk,merk,babyvoedsel,werden,pesticiden,gevonden,?]).
sentence(215,['Welk',team,won,het,'NBA',kampioenschap,?]).
sentence(216,['Welk',land,trok,zijn,troepen,terug,uit,'Bosnië',?]).
sentence(217,['Wie',won,de,'Final','Four',?]).
sentence(218,['Wat',is,de,hoogste,berg,van,de,'Alpen',?]).
sentence(220,['Welke','Russische',president,woonde,de,'G7-top',in,'Napels',bij,?]).
sentence(221,['Op',welke,datum,vond,het,'Noorse',referendum,over,toetreding,tot,de,'EU',plaats,?]).
sentence(222,['Welke',twee,etnische,groepen,zijn,in,conflict,in,'Rwanda',?]).
sentence(223,['Tegen',welk,schip,botste,de,olietanker,'"','New','World','"',?]).
sentence(224,['Waar',vond,het,ongeluk,met,de,olietanker,'"','Mar','Egeo','"',plaats,?]).
sentence(225,['Onder',welke,vlag,voer,de,olietanker,'"','Egeïsche','Zee','"',?]).
sentence(226,['Hoeveel',olie,werd,gelekt,bij,het,ongeluk,met,de,olietanker,'"','Egeïsche','Zee','"',?]).
sentence(227,['Wat',was,de,geschatte,schade,door,het,ongeluk,met,de,'"','Egeïsche','Zee','"',?]).
sentence(228,['Wie',vergoedde,de,schade,door,het,ongeval,met,de,olietanker,'"','Egeïsche','Zee','"',?]).
sentence(229,['Wie',was,de,officier,van,justitie,in,de,rechtszaak,om,het,ongeluk,met,de,'"','Egeïsche','Zee','"',?]).
sentence(230,['Wat',is,de,afkorting,voor,het,'Wereld','Natuur','Fonds',?]).
sentence(231,['Hoeveel',landen,zijn,lid,van,de,'Internationale','Walvisvaart','Commissie',?]).
sentence(232,['Boven',welk,werelddeel,werd,een,gat,in,de,ozonlaag,ontdekt,?]).
sentence(233,['Waar',vond,de,algemene,vergadering,van,de,'Internationale','Walvisvaart','Commissie',plaats,?]).
sentence(234,['In',welk,jaar,vond,de,oprichting,van,de,'Wereldbank',plaats,?]).
sentence(235,['In',welk,jaar,vond,de,oprichting,van,het,'Internationale','Monetaire','Fonds',plaats,?]).
sentence(236,['Hoeveel',leeden,heeft,het,'IMF',?]).
sentence(237,['Wie',is,de,president,van,'Peru',?]).
sentence(238,['Bij',welke,conferentie,werden,de,'Wereldbank',en,het,'IMF',opgericht,?]).
sentence(239,['Wat',is,de,'Vietnamese',munt,?]).
sentence(240,['Wie',is,de,bedenker,van,de,'Brady-overeenkomst',?]).
sentence(241,['Welke',rol,vervulde,'Brady',bij,het,'Amerikaanse',ministerie,van,financiën,?]).
sentence(242,['Welk',bedrijf,is,door,'Nicholas','Brady',opgericht,?]).
sentence(243,['Welke','Peruaanse',president,werd,beschuldigd,van,omkomping,in,het,toekennen,van,een,spoorwegbouwcontract,?]).
sentence(244,['Welke','Franse','ex-minister',werd,tot,een,gevangenisstraf,veroordeeld,wegens,corruptie,?]).
sentence(245,['Op',welke,datum,trad,'Vicente','Albero',',',de,'Spaanse',minister,van,landbouw,',',af,?]).
sentence(246,['Op',welke,datum,nam,het,'Spaanse',parlement,een,wet,ter,bestrijding,van,corruptie,aan,?]).
sentence(247,['Tegen',welke,premier,is,een,onderzoek,naar,corruptie,ingesteld,?]).
sentence(248,['Op',welke,datum,werd,tegen,'Silvio','Berlusconi',een,onderzoek,ingesteld,op,verdenking,van,medeplichtigheid,aan,corruptie,?]).
sentence(249,['Op',welke,datum,stapte,de,onderzoeksrechter,van,'Milaan',',','Antonio','Di','Pietro',',',uit,de,rechterlijke,macht,?]).
sentence(250,['Met',welke,'Franse',kernonderzeeër,had,een,ongeluk,plaats,?]).
sentence(251,['Hoeveel',opvarenden,kwamen,om,het,leven,aan,boord,van,de,onderzeeër,'"','Emeraud','"',?]).
sentence(252,['Wanneer',vond,de,ramp,in,'Tsjernobyl',plaats,?]).
sentence(253,['In',hoeveel,landen,werd,de,voormalige,'Sovjet-Unie',verdeeld,?]).
sentence(254,['Hoeveel',mensen,zullen,sterven,als,een,gevolg,van,'Tsjernobyl',?]).
sentence(255,['Welk',deel,van,de,wereldbevolking,pleegt,zelfmoord,?]).
sentence(256,['Hoe',hoog,is,de,'Mount','Everest',?]).
sentence(257,['Waar',staat,'PLO',voor,?]).
sentence(258,['Hoeveel',landen,woonden,de,'"','MED','21','"',conferentie,bij,?]).
sentence(259,['Wie',is,de,voorzitter,van,de,'Palestijnse','Nationale','Autoriteit',?]).
sentence(260,['Wanneer',is,de,intifada,uitgebroken,?]).
sentence(261,['Welk','Brits',bedrijf,neemt,deel,uit,van,'Airbus',?]).
sentence(262,['Hoeveel',mensen,kwamen,om,bij,het,verongelukken,van,een,'Airbus',bij,de,luchthaven,van,'Nagoya',?]).
sentence(263,['Hoeveel',mensen,telt,de,wereldbevolking,?]).
sentence(264,['Wanneer',is,de,'Socialistische','Internationale',opgericht,?]).
sentence(265,['Welke','Nobelprijs',werd,uitgereikt,aan,'Willy','Brandt',?]).
sentence(266,['Waar',vonden,de,'Olympische','Spelen',in,'1996',plaats,?]).
sentence(267,['Uit',welk,land,is,'Piet','Mondriaan',afkomstig,?]).
sentence(268,['In',welke,stad,is,het,'Prado','Museum',?]).
sentence(269,['Hoeveel',werd,betaald,voor,'"','Huilende','Vrouw','"',',',een,gravure,van,de,'Spaanse',schilder,'Pablo','Picasso',?]).
sentence(270,['In',welke,stad,is,'"','Broadway','"',?]).
sentence(271,['Wat',was,de,volledige,naam,van,de,'Joegoslavische',president,'"','Tito','"',?]).
sentence(272,['Wat',is,de,hoofdstad,van,'Kroatië',?]).
sentence(273,['Hoeveel',inwoners,telt,'België',?]).
sentence(274,['Welk',land,heeft,de,hoogste,alcoholconsumptie,?]).
sentence(275,['In',welk,land,ligt,'Tegucigalpa',?]).
sentence(276,['Wie',is,de,componist,van,'"','Het','Zwanenmeer','"',?]).
sentence(277,['Wanneer',werd,de,eerste,'Nobelprijs',uitgereikt,?]).
sentence(278,['Wie',was,president,van,de,'Verenigde','Staten',tijdens,de,'Tweede','Wereldoorlog',?]).
sentence(279,['Wanneer',viel,het,voormalige,'Joegoslavië',uiteen,?]).
sentence(280,['Hoe',lang,duurt,een,zwangerschap,bij,mensen,?]).
sentence(281,['Welke',groep,organiseert,de,opstand,in,'Chiapas',?]).
sentence(282,['In',welke,maand,bloeien,de,amandelbomen,?]).
sentence(283,['Waar',in,'Argentinië',was,er,een,uitbraak,van,cholera,?]).
sentence(284,['Van',welk,fruit,wordt,wijn,gemaakt,?]).
sentence(285,['Hoeveel',kilometer,kan,de,'Monarch',koningsvlinder,afleggen,?]).
sentence(286,['Wie',is,de,uitvinder,van,de,radio,?]).
sentence(287,['Wanneer',is,de,berlijnse,'Muur',gebouwd,?]).
sentence(288,['Wat',is,het,wereldrecord,hoogspringen,voor,dames,?]).
sentence(289,['Hoe',ver,is,het,'Iberisch',schiereiland,van,'Afrika',?]).
sentence(290,['Wie',is,de,componist,van,het,'"','Concierto','d\'Aranjuez','"',?]).
sentence(291,['Welke',representatieve,gebouwen,worden,er,in,het,moderne,'Berlijn',gebouwd,?]).
sentence(292,['Hoe',heet,de,beroemde,wet,ter,bevordering,van,het,gebruik,van,de,'Franse',taal,?]).
sentence(293,['Welke','EU',landen,kregen,een,reductie,van,hun,kabeljauwquota,in,de,recente,onderhandelingen,?]).
sentence(294,['In',welke,stad,ligt,de,woonwijk,'"','Yordan','"',?]).
sentence(295,['Hoeveel',alcohol,gebruikt,men,gemiddeld,per,persoon,in,'Spanje',?]).
sentence(296,['Wat',is,'IBM\'s',jaaromzet,?]).
sentence(297,['In',welk,jaar,won,'Octavio','Paz',de,'Nobelprijs',?]).
sentence(298,['Hoeveel',zal,het,onderhoud,van,het,'Internationale','Ruimtestation',jaarlijks,kosten,?]).
sentence(299,['Hoeveel',inkomsten,worden,gederfd,door,'software-piraterij',?]).
sentence(300,['Waar',staat,de,afkorting,'BSA',voor,?]).
sentence(301,['Wie',is,de,leider,van,'Sinn','Fein',?]).
sentence(302,['Hoeveel',kinderen,heeft,'Anthony','Quinn',?]).
sentence(303,['Waar',ligt,het,'Timan','Pechora',bassin,?]).
sentence(304,['Noem',een,'Japanse',stad,die,door,een,aardbeving,is,getroffen,'.']).
sentence(305,['Wanneer',is,'Frank','Rijkaard',geboren,?]).
sentence(306,['Waar',ligt,'Requena',?]).
sentence(307,['Wie',zijn,de,'"','McLibel','2','"',?]).
sentence(308,['Hoeveel',mensen,verdronken,toen,de,veerboot,'Estonia',kapseisde,en,zonk,?]).
sentence(309,['Waar',staat,'OCA',voor,?]).
sentence(310,['Hoeveel',kunstvoorwerpen,worden,jaarlijks,gestolen,in,'Europa',?]).
sentence(311,['Hoe',oud,is,'Brian','Eno',?]).
sentence(312,['Hoeveel',is,tien,peso,waard,?]).
sentence(313,['Wie',is,de,leider,van,de,'Bosnische','Serviërs',?]).
sentence(314,['Van',welke,voetbalclub,is,'Jesus','Gil',y,'Gil',voorzitter,?]).
sentence(315,['Noem',een,film,waarin,'Audrey','Hepburn',de,hoofdrol,speelde,'.']).
sentence(316,['Hoe',heet,de,opvolger,van,de,'GATT',?]).
sentence(317,['Hoeveel',inwoners,telt,'Shanghai',?]).
sentence(318,['Welke',oliemaatschappij,is,eigenaar,van,de,'Brent','Spar',?]).
sentence(319,['Wie',is,de,oprichter,van,de,'Chippendale-stripteaseshow',?]).
sentence(320,['Noem',een,eigenschap,van,ammoniakgas,'.']).
sentence(321,['Waar',ligt,het,'Belgische','Eynaten',?]).
sentence(322,['Hoe',kwam,'Ayrton','Senna',om,het,leven,?]).
sentence(323,['Wie',was,de,eerste,president,van,'Indonesië',?]).
sentence(324,['Wat',is,de,'Argentijnse',naam,voor,de,'Falklands',?]).
sentence(325,['Wie',is,de,schrijver,van,'Star','Trek',?]).
sentence(326,['Noem',een,aidsremmend,middel,'.']).
sentence(327,['Hoe',vaak,in,zijn,leven,moet,een,moslim,de,pelgrimstocht,naar,'Mekka',maken,?]).
sentence(328,['Wanneer',werd,'Ierland',opgedeeld,?]).
sentence(329,['Hoeveel',passagiers,moesten,het,schip,verlaten,nadat,op,de,'Regent','Star',brand,was,uitgebroken,?]).
sentence(330,['Wie',is,de,geestelijke,vader,van,'Doctor','Snuggles',?]).
sentence(331,['Wanneer',kreeg,'Rusland',een,nieuwe,grondwet,?]).
sentence(332,['Welke','Britse',premier,bezocht,'Zuid-Afrika',in,'1960',?]).
sentence(333,['Noem',een,medicijn,tegen,malaria,'.']).
sentence(334,['Wie',is,de,leider,van,de,'Nation',of,'Islam',?]).
sentence(335,['Wie',vermoordden,de,'Colombiaanse',voetballer,'Andres','Escobar',?]).
sentence(336,['Welke','Britse',staatsburger,kreeg,'50',zweepslagen,toegediend,in,'Quatar',?]).
sentence(337,['Hoe',heet,de,'Israelische',binnenlandse,veiligheidsdienst,?]).
sentence(338,['Wie',zijn,de,leiders,van,de,'Orde',van,de,'Zonnetempel',?]).
sentence(339,['Op',welke,leeftijd,overleed,'Thomas','\'','Tip','\'','O\'Neill',?]).
sentence(340,['Wie',is,ooit,de,'Mussolini',van,de,media,genoemd,?]).
sentence(341,['Welk',land,legaliseerde,in,'1994',de,videorecorder,?]).
sentence(342,['Hoe',luidt,de,voornaam,van,de,vrouw,van,'Nelson','Mandela',?]).
sentence(343,['Hoe',hoog,is,de,top,van,de,'Alto','Cruz',de,la,'Demanda',?]).
sentence(344,['Hoe',oud,is,het,'Bolshoi','Theater',?]).
sentence(345,['Wanneer',heersten,de,'Fransen',in,'Vietnam',?]).
sentence(346,['Hoe',heet,de,directeur,van,de,'CIA',?]).
sentence(347,['Wanneer',leefde,'Piet','Mondriaan',?]).
sentence(348,['Wanneer',begon,de,'Europese','Economische',en,'Monetaire','Unie','(','EMU',')',?]).
sentence(349,['Welk',deel,van,de,wereldhandel,in,cocaïne,wordt,gecontroleerd,door,het,kartel,van,'Cali',?]).
sentence(350,['Hoe',hoog,is,de,'Matterhorn',?]).
sentence(351,['Hoeveel',mensen,overleefden,het,vernietigingskamp,'Auschwitz',?]).
sentence(352,['Bij',welk,metrostation,in,'Tokio',vond,een,aanslag,met,het,gifgas,sarin,plaats,?]).
sentence(353,['Voor',hoeveel,doden,wordt,de,'Rode','Khmer',verantwoordelijk,gehouden,?]).
sentence(354,['Noem',een,journalist,die,door,de,'Gewapende','Islamitische','Groep','(','GIA',')',is,vermoord,'.']).
sentence(355,['Welk',bedrijf,heeft,de,autoproducent,'Rover',overgenomen,?]).
sentence(356,['Noem',een,land,of,regio,waar,het,'Ebola-virus',is,aangetroffen,'.']).
sentence(357,['In',welk,jaar,werd,het,testen,van,biologische,en,giftige,wapens,verboden,?]).
sentence(358,['Welke',tennisspeler,wordt,wel,de,'"','Big','Mac','"',genoemd,?]).
sentence(359,['Noem',een,eiland,in,de,'Oostelijke','Sporaden','.']).
sentence(360,['Waar',ligt,'Basra',?]).
sentence(361,['Waar',staat,'RSA',voor,?]).
sentence(362,['Hoe',begon,'Diana','Ross',haar,professionele,carriere,?]).
sentence(363,['Wanneer',werden,patrouillevliegtuigen,van,het,type,'Nimrod',in,dienst,genomen,?]).
sentence(364,['Hoeveel',eilanden,heeft,'Indonesië',?]).
sentence(365,['Welke','ETA-terroriste',heeft,de,bijnaam,'"','De','Tijgerin','"',?]).
sentence(366,['Hoe',kwam,'Frederick','West',om,het,leven,?]).
sentence(367,['Wat',is,het,rijkste,land,ter,wereld,?]).
sentence(368,['Wanneer',overleed,'Mao','Zedong',?]).
sentence(369,['Hoeveel',inwoners,telt,'Uttar','Pradesh',?]).
sentence(370,['Wat',was,de,oorzaak,van,een,brand,in,een,bioscoop,in,de,'Chinese',stad,'Karamay',?]).
sentence(371,['Wat',is,de,naam,van,'Richard','Branson\'s',cola,?]).
sentence(372,['In',welk,land,worden,'buzkashi-wedstrijden',gehouden,?]).
sentence(373,['Wanneer',werd,'Malta',onafhankelijk,?]).
sentence(374,['In',de,'Floating','Point','Unit',van,welke,chip,werd,een,fout,ontdekt,?]).
sentence(375,['Welke','Nobelprijs',ontving,'Kenzaburo','Oe',de,'Nobelprijs',?]).
sentence(376,['Welke','Iraakse',nucleair,deskundige,verdween,in,de,'Griekse',hoofdstad,'Athene',?]).
sentence(377,['Wat',is,de,latijnse,naam,van,de,'Arabische',oryx,?]).
sentence(378,['Wie',is,de,president,van,'Zuid-Korea',?]).
sentence(379,['Hoeveel','pagina\'s',telt,'Albert','Einsteins',oudste,manuscript,over,de,relativiteitstheorie,?]).
sentence(380,['Wie',produceert,de,'\'','Smart-Car','\'',?]).
sentence(381,['Hoeveel',bedraagt,het,staatspensioen,in,'Zuid-Afrika',?]).
sentence(382,['Wat',is,de,hoofdstad,van,'Maleisië',?]).
sentence(383,['Wat',is,de,afkorting,voor,'"',polyethylene,terephthalate,'"',?]).
sentence(384,['Welk',land,wordt,ook,wel,'"','De','Lage','Landen','"',genoemd,?]).
sentence(385,['Waar',bevindt,zich,de,'Klaagmuur',?]).
sentence(386,['Wat',is,het,serienummer,van,de,'Steinway-vleugel',van,de,pianist,'Vladimir','Horowitz',?]).
sentence(387,['Hoe',groot,is,het,risico,op,een,hartinfarct,in,'Noordeuropese',landen,?]).
sentence(388,['Noem',een,film,van,'Spike','Lee','.']).
sentence(389,['Hoeveel',politieke,partijen,deden,mee,aan,de,eerste,gemeenteraadsverkiezingen,in,'Zuid-Afrika',?]).
sentence(390,['Wat',veroorzaakt,wiegedood,?]).
sentence(391,['In',welk,jaar,was,de,'Wereldtentoonstelling',in,'Brussel',?]).
sentence(392,['Wie',is,de,'Hongaarse',premier,?]).
sentence(393,['Hoe',heet,het,besturingssysteem,van,'Sun',?]).
sentence(394,['Wat',wordt,wel,de,grootste,show,ter,wereld,genoemd,?]).
sentence(395,['In',welke,'Londense',wijk,staat,het,'British','Museum',?]).
sentence(396,['In',welk,land,kreeg,de,voormalige,'Haïtiaanse',dictator,'Prosper','Avril',politiek,asiel,?]).
sentence(397,['Wat',is,de,'SAS-lijfspreuk',?]).
sentence(398,['Wanneer',werd,'Dzjochar','Doedajev',geboren,?]).
sentence(399,['Wat',is,de,echte,naam,van,'Snoop','Doggy','Dogg',?]).
sentence(400,['Waar',werd,de,graftombe,ontdekt,van,de,'Maya-keizer','Kinich','Ah','Pop',?]).
sentence(401,['Wat',is,de,officiele,taal,van,'Indonesie',?]).
sentence(402,['Wanneer',was,de,militaire,dictatuur,in,'Argentini',?]).
sentence(403,['Voor',welk,radiostation,werkt,'Howard','Stern',?]).
sentence(404,['Hoeveel',geregistreerde,'aids-patienten',telt,'Denemarken',?]).
sentence(405,['Wanneer',werd,'Walt','Disney',geboren,?]).
sentence(406,['Waar',ligt,de,vulkaan,'Popocatepetl',?]).
sentence(407,['Wanneer',leefde,'Pablo','Neruda',?]).
sentence(408,['Welke',filantroop,van,'Hongaarse',afkomst,staat,bekend,om,zijn,succesvolle,financiële,speculaties,?]).
sentence(409,['Waar',groeide,'Paul','Weller',op,?]).
sentence(410,['Wie',was,de,leider,van,de,'Angolese',guerrillabeweging,'UNITA',?]).
sentence(411,['Wat',is,de,geboortedatum,van,'Andre','Agassi',?]).
sentence(412,['Noem',een,oprichter,van,'Apple','.']).
sentence(413,['Wie',is,de,leider,van,de,'Japanse','Aum','Shinrikyo-sekte',?]).
sentence(414,['Wanneer',zal,'China','Hongkong',overnemen,?]).
sentence(415,['Wie',regisseerde,'"','North',by,'Northwest','"',?]).
sentence(416,['Hoe',oud,is,'Nick','Leeson',?]).
sentence(417,['Hoe',lang,is,de,'Fiat','500',?]).
sentence(418,['Welk',land,trad,als,dertiende,lidstaat,tot,de,'Europese','Unie',toe,?]).
sentence(419,['In',welk,land,heeft,de,'Bengalese',schrijfster,'Taslima','Nasrin',asiel,gevraagd,?]).
sentence(420,['Hoe',heet,'Nikki','Laudas',eigen,luchtvaartmaatschappij,?]).
sentence(421,['Hoeveel',inwoners,telt,'Aruba',?]).
sentence(422,['Wat',is,de,op,drie,na,grootste,bank,in,'Venezuela',?]).
sentence(423,['Wat',is,de,grootste,automatiseringsbeurs,ter,wereld,?]).
sentence(424,['Hoe',stierf,'Charles','Bukowski',?]).
sentence(425,['Wanneer',werd,de,republiek,uitgeroepen,in,'IJsland',?]).
sentence(426,['Welke',nationaliteit,heeft,de,golfer,'Seve','Ballesteros',?]).
sentence(427,['Wat',was,de,echte,naam,van,'Moeder','Teresa',?]).
sentence(428,['Welke','Amerikaanse',fysicus,stelde,het,bestaan,van,quarks,voor,?]).
sentence(429,['Noem',een,product,dat,in,'China',wordt,nagemaakt,'.']).
sentence(430,['Wanneer',overleed,'Marilyn','Monroe',?]).
sentence(431,['Hoeveel',verslaafden,aan,harddrugs,heeft,'Nederland',?]).
sentence(432,['Wanneer',vonden,de,'Olympische','Spelen',in,'Moskou',plaats,?]).
sentence(433,['Welke',munteenheid,heeft,men,in,'Rusland',?]).
sentence(434,['Hoe',vaak,is,'Ajax',kampioen,van,'Nederland',geweest,?]).
sentence(435,['Wie',is,de,grote,liefde,van,prins,'Charles',?]).
sentence(436,['Hoeveel',kernproeven,heeft,'Frankrijk',sinds,'1960',genomen,?]).
sentence(437,['Wat',is,laquado,?]).
sentence(438,['Hoe',lang,bestaat,de,'America\'s','Cup',',',het,meest,prestigieuze,zeilevenement,?]).
sentence(439,['Met',welke,andere,film,deelde,'The','Piano',van,'Jane','Campion',de,'Gouden','Palm',op,het,filmfestival,van,'Cannes',?]).
sentence(440,['Welke',taal,spreken,de,'Berbers',?]).
sentence(441,['Hoe',heet,de,maatschappij,die,de,spoortunnel,onder,het,'Kanaal',exploiteert,?]).
sentence(442,['Wie',was,chief,executive,officer,van,'IBM',van,'1956',tot,'1971',?]).
sentence(443,['Welke','Amerikaanse',wiskundige,bewees,de,'Stelling',van,'Fermat',?]).
sentence(444,['Hoe',heet,de,voormalige,'Albanese',geheime,dienst,?]).
sentence(445,['Welke',tennisspeelster,werd,op,'30',april,'1993',met,een,mes,in,de,rug,gestoken,?]).
sentence(446,['In',welk,land,kreeg,'Mengistu','Haile','Mariam',',',de,afgezette,'Ethiopische',dictator,',',politiek,asiel,?]).
sentence(447,['Wat',is,de,'Amserikaanse',staat,met,de,strengste,milieuwetten,?]).
sentence(448,['Hoeveel',militairen,heeft,'Noord-Korea',?]).
sentence(449,['Hoe',diep,is,'Challenger','Deep',',',het,diepste,punt,van,de,aarde,?]).
sentence(450,['Wie',is,'directeur-generaal',van,de,'IAEA',?]).
