:- module(alpino_suite,[ sentence/2 ]).

:- hdrug_util:set_flag(application_type,ovis).

sentence(1,[<@>,half,negen]).
sentence(2,[nee]).
sentence(3,[ik,wou,van,groningen,naar,utrecht]).
sentence(4,[om,tien,uur]).
sentence(5,[graag]).
sentence(6,['\'s',morgens]).
sentence(7,[ja]).
sentence(8,[nee,hoeft,niet]).
sentence(9,[maastricht]).
sentence(10,[nee,'\'s',avonds]).
sentence(11,[ik,wil,om,zeven,uur,'\'s',avonds,aankomen,nee,zes,uur,'\'s',avonds]).
sentence(12,[laat,u,maar]).
sentence(13,[<@>,niet,noodzakelijk,om,achttien,uur,maar,wel,op,achttien,april]).
sentence(14,[ja]).
sentence(15,[om,acht,uur,'\'s',ochtends]).
sentence(16,[ja]).
sentence(17,[nee]).
sentence(18,[utrecht,naar,naarden,bussum]).
sentence(19,[vrijdag,tien,april]).
sentence(20,[donderdag,tien,april]).
sentence(21,[zes,uur]).
sentence(22,[ja]).
sentence(23,[nee]).
sentence(24,[terug]).
sentence(25,[ja]).
sentence(26,[ik,wil,niet,op,vrijdag,reizen,ik,wil,op,donderdag,reizen]).
sentence(27,[nee,dank,u,wel]).
sentence(28,[nee,ik,wil,zondag,vertrekken]).
sentence(29,[vanaf,station,nijmegen]).
sentence(30,[dat,klopt]).
sentence(31,[ik,wil,van,gramsbergen,naar,driebergen,zeist]).
sentence(32,[dat,klopt,ja]).
sentence(33,[morgenmiddag,om,twee,uur]).
sentence(34,[ja]).
sentence(35,[ja]).
sentence(36,[vandaag]).
sentence(37,[ja]).
sentence(38,[ja,een,latere]).
sentence(39,[van,utrecht,centraal,naar,enschede]).
sentence(40,[van,vlissingen,naar,roosendaal]).
sentence(41,[nee]).
sentence(42,[ik,wil,helemaal,niet,naar,delft,vertrekken]).
sentence(43,[twaalf,uur]).
sentence(44,[ik,wil,om,middelburg,naar,deventer]).
sentence(45,[op,vrijdag]).
sentence(46,[<@>,vrijdag]).
sentence(47,[veertien,dertig]).
sentence(48,[ja,nee]).
sentence(49,[nee,dank,je]).
sentence(50,[nee,dank,u]).
sentence(51,[om,tien,uur]).
sentence(52,[nee]).
sentence(53,[van,utrecht,naar,den,bosch]).
sentence(54,['<@m>',overmorgen,om,twee,uur]).
sentence(55,[om]).
sentence(56,[twaalf,uur]).
sentence(57,[nee]).
sentence(58,[<@>,om,tien,uur]).
sentence(59,[ik,wil,om,tweeentwintig,uur,vertrekken,ja]).
sentence(60,[nee,hoor,dank,u,wel]).
sentence(61,[om,drie,uur]).
sentence(62,[inderdaad]).
sentence(63,[ik,wil,van,utrecht,cs,naar,geldermalsen]).
sentence(64,[vandaag,vandaag,is,het,vrijdag]).
sentence(65,[ja]).
sentence(66,[<@>,ongeveer,drie,uur]).
sentence(67,[nee,eerder]).
sentence(68,[om,vijftien,uur]).
sentence(69,[nee]).
sentence(70,[utrecht,naar,almere,cs]).
sentence(71,[vandaag]).
sentence(72,[nee,dank,u]).
sentence(73,[wel,graag]).
sentence(74,[graag]).
sentence(75,[nee,dank,u,wel]).
sentence(76,[dit,<@>,dit,was,het,helemaal]).
sentence(77,[zeven,uur]).
sentence(78,[nee]).
sentence(79,[van,rotterdam,wilgenplas,naar,haarlem]).
sentence(80,[ja]).
sentence(81,[driebergen,zeist]).
sentence(82,[om,twee,uur]).
sentence(83,[ja]).
sentence(84,[ja]).
sentence(85,[graag]).
sentence(86,[stop,overnieuw]).
sentence(87,[van,alphen,aan,den,rijn,naar,aalten]).
sentence(88,[ik,wil,opnieuw,beginnen]).
sentence(89,[ja]).
sentence(90,[elf,uur]).
sentence(91,[nee,nee,nee,nee]).
sentence(92,[ik,wil,naar,krabbendijke,zegt,ze,net]).
sentence(93,[ja]).
sentence(94,[ik,wil,zo,spoedig,mogelijk,van,ede,naar,amersfoort]).
sentence(95,[nee,op,vrijdag,elf,april]).
sentence(96,[ja,dat,is,goed]).
sentence(97,[nee,dat,hoeft,niet,nee]).
sentence(98,[<@>,morgen]).
sentence(99,[om,zeventien,uur,eenentwintig]).
sentence(100,[<@>,ik,beeindig,dit,gesprek]).
sentence(101,[dertien,uur,dertig,of,te,wel,half,twee]).
sentence(102,[nee]).
sentence(103,[nee,dank,u]).
sentence(104,[ja]).
sentence(105,[zaterdag]).
sentence(106,[ja]).
sentence(107,[ja]).
sentence(108,[ook,fout]).
sentence(109,[hoe,laat,in,de,middag,ik,wil,'\'s',morgens,vertrekken]).
sentence(110,[om,twee,uur,'\'s',middags]).
sentence(111,[<@>,ja,twaalf,april]).
sentence(112,[naar]).
sentence(113,[van,vlissingen,naar,groningen]).
sentence(114,[delft]).
sentence(115,[van,delft,naar,groningen]).
sentence(116,[op,zaterdag]).
sentence(117,[om,tien,uur,wil,ik,vertrekken]).
sentence(118,[ja]).
sentence(119,[op,zaterdag]).
sentence(120,[negen,uur]).
sentence(121,[nee]).
sentence(122,[<@>,ja]).
sentence(123,[delft,naar,arnhem,via,groningen]).
sentence(124,[naarden]).
sentence(125,[ja]).
sentence(126,[nee,hoor,hoeft,niet]).
sentence(127,[tien,voor,half,acht]).
sentence(128,[harlingen,naar,delfzijl]).
sentence(129,[zaterdag]).
sentence(130,[nee]).
sentence(131,[ik,wil,om,ongeveer,negen,uur,'\'s',ochtends,aankomen]).
sentence(132,[wat,zeg,je]).
sentence(133,[nee]).
sentence(134,[ja]).
sentence(135,[nee,dat,hoeft,niet]).
sentence(136,[woensdag]).
sentence(137,[nee,ik,wil,om,zes,uur,dertig,vertrekken]).
sentence(138,[zes,uur,dertig]).
sentence(139,[ja,ik,wil,om,zes,uur,dertig,vertrekken]).
sentence(140,[ik,wil,woensdag,zestien,april,reizen]).
sentence(141,[woensdag]).
sentence(142,[ja]).
sentence(143,[nee]).
sentence(144,[nee,dat,wil,ik,niet]).
sentence(145,[ik,wilde,graag,weten,op,vijf,mei]).
sentence(146,[ja]).
sentence(147,[amsterdam,naar,naarden]).
sentence(148,[nee,hoor,ik,heb,het,wel,verstaan]).
sentence(149,[woensdag]).
sentence(150,[half,één]).
sentence(151,[ja]).
sentence(152,[nee]).
sentence(153,[vandaag]).
sentence(154,[nee,donderdag]).
sentence(155,[van,amsterdam,naar,rotterdam]).
sentence(156,[vrijdag]).
sentence(157,[vertrek,om,half,acht,'\'s',morgens]).
sentence(158,[nee,dank,u]).
sentence(159,[van,hilversum,naar,weert]).
sentence(160,[om,negen,uur]).
sentence(161,[ja,ik,wil,vertrekken,om,zestien,uur]).
sentence(162,[nee]).
sentence(163,[half,vijf,aankomen]).
sentence(164,[half,vijf,vanmiddag,aankomen]).
sentence(165,[morgen]).
sentence(166,[ik,wil,graag,van,nijmegen,naar,blerick]).
sentence(167,[ik,wil,van,den,haag,naar,amsterdam,overmorgen]).
sentence(168,[ja,graag]).
sentence(169,[achttien,uur,dertig]).
sentence(170,[ja]).
sentence(171,[nee,wel,de,tweede,wil,ik,horen]).
sentence(172,[ik,wil,naar,zeist,toe,aanstaande,maandag]).
sentence(173,[nee,hoor,dat,hoeft,niet]).
sentence(174,[nee,om,acht,uur,'\'s',avonds]).
sentence(175,[nee]).
sentence(176,[van,zoetermeer,naar,groningen]).
sentence(177,[<@>,de,dag,na,overmorgen]).
sentence(178,[om,zeventien,uur,eenentwintig]).
sentence(179,[nee]).
sentence(180,[ja]).
sentence(181,[ja]).
sentence(182,[ik,wil,van,workum,naar,beesd]).
sentence(183,[ja]).
sentence(184,[van,oeteldonk,naar,schragenveen]).
sentence(185,[van,rotterdam,naar,den,haag]).
sentence(186,[vandaag]).
sentence(187,[nee,'\'s',avonds]).
sentence(188,[ja]).
sentence(189,[van,vught,naar,coevorden]).
sentence(190,[ja]).
sentence(191,[nee,hoor]).
sentence(192,[brummen]).
sentence(193,[van,brummen,naar,arnhem]).
sentence(194,[ja]).
sentence(195,[vandaag]).
sentence(196,[nee]).
sentence(197,[ja,ik,wil,om,zeven,uur,'\'s',middags,aankomen]).
sentence(198,[nee]).
sentence(199,[dertig,april]).
sentence(200,[nee,zes,uur]).
sentence(201,[nee]).
sentence(202,[almere,centraal]).
sentence(203,[van,amsterdam,naar,haarlem]).
sentence(204,[van,amsterdam,centraal,naar,houten]).
sentence(205,[om,kwart,over,negen]).
sentence(206,[ja]).
sentence(207,[nee]).
sentence(208,[<@>,vandaag]).
sentence(209,[om,vijf,voor,half,twaalf]).
sentence(210,[nee]).
sentence(211,['<@m>',even,denken,daar,moet,ik,eigenlijk,eventjes,over,nadenken,hoe,ik,dat,eigenlijk,eventjes,even,kijk,eens,nou,laten,we,zeggen,<@>,dertig,april]).
sentence(212,[nee,ik,zei,dat,ik,op,dertig,april,wil,reizen,dertig,april]).
sentence(213,[van,zandvoort,aan,zee]).
sentence(214,[maastricht,limburg]).
sentence(215,[zandvoort,aan,zee]).
sentence(216,[correct]).
sentence(217,[apeldoorn]).
sentence(218,[van,apeldoorn,naar,amsterdam,centraal]).
sentence(219,[op,woensdag,zestien,april]).
sentence(220,[<@>,na,negen,uur,de,eerste,trein]).
sentence(221,[nee]).
sentence(222,[<@>,van,amsterdam,centraal,naar,nederhorst,ten,berg]).
sentence(223,[op,maandag,veertien,april]).
sentence(224,[ja,ja]).
sentence(225,[ja]).
sentence(226,[<@>,tussen,negen,en,tien,uur]).
sentence(227,[inderdaad]).
sentence(228,[<@>,amsterdam,centraal]).
sentence(229,[sorry,wat,zei,je]).
sentence(230,[om,negen,uur,ongeveer]).
sentence(231,[<@>,woensdag]).
sentence(232,[ja,op,geen,enkele,dag]).
sentence(233,[ja,dat,wil,ik,niet]).
sentence(234,[nee]).
sentence(235,[<@>,zoetermeer,buytenwegh]).
sentence(236,[van,zoetermeer,buytenwegh,naar,utrecht,centraal]).
sentence(237,[zoetermeer,buytenwegh]).
sentence(238,[van,zoetermeer,buytenwegh]).
sentence(239,[ja]).
sentence(240,[tien,uur]).
sentence(241,[naar]).
sentence(242,[nee,ik,wil,niet,naar,'\'s',hertogenbosch,ik,wil,naar,maastricht]).
sentence(243,[ik,wil,van]).
sentence(244,[nee,sorry,om]).
sentence(245,[nee,om,zeven,uur]).
sentence(246,[ik,van,amsterdam,rai]).
sentence(247,[spanje]).
sentence(248,[oosterbeek,arnhem,velperpoort]).
sentence(249,[vijf,mei]).
sentence(250,[nee]).
sentence(251,[aankomen,in,bunnik,om,tien,uur]).
sentence(252,[ja]).
sentence(253,[ja]).
sentence(254,[ja]).
sentence(255,[jawel]).
sentence(256,['<@m>',<@>,twaalf,uur]).
sentence(257,[ja]).
sentence(258,[ja]).
sentence(259,[ja]).
sentence(260,[ja]).
sentence(261,[ik,wil,niet,naar,nieuw,vennep]).
sentence(262,[ik,wil,niet,naar,nieuwerkerk]).
sentence(263,[utrecht,cs]).
sentence(264,[om,vijf,uur]).
sentence(265,[nee]).
sentence(266,[zondag]).
sentence(267,[amsterdam]).
sentence(268,[nee,zondag,dertien,april]).
sentence(269,[naar,amsterdam,centraal]).
sentence(270,[ja]).
sentence(271,[nee]).
sentence(272,[nee]).
sentence(273,[maandag]).
sentence(274,[ja]).
sentence(275,[maassluis,naar,schiphol]).
sentence(276,[maassluis,naar,schiphol]).
sentence(277,[maandag]).
sentence(278,[nee]).
sentence(279,[maassluis,naar,schiphol]).
sentence(280,[maassluis,naar,schiphol]).
sentence(281,[ja]).
sentence(282,[ik,wil,helemaal,niet,om,twaalf,uur,reizen]).
sentence(283,[van,amsterdam,naar,enschede]).
sentence(284,[amsterdam,naar,enschede]).
sentence(285,[twee,uur,'\'s',middags]).
sentence(286,[twee,uur]).
sentence(287,[ja]).
sentence(288,[om,tien,uur,'\'s',ochtends]).
sentence(289,[klopt,inderdaad,ja]).
sentence(290,[nee]).
sentence(291,[van,koog,bloemwijk,naar,zoetermeer,de,leyens]).
sentence(292,[van,leiden,naar,amsterdam]).
sentence(293,[nee,ik,wil,niet,van,nijkerk,ik,wil,van,leiden]).
sentence(294,[nee,dat,is,niet,nodig]).
sentence(295,[ja,ik,wil,graag,ik,wil,niet,naar,maarn,maar,naar,naar,muiden]).
sentence(296,['<@m>',gisteren]).
sentence(297,[ja]).
sentence(298,[van,amsterdam,naar,haarlem]).
sentence(299,[op,zondag]).
sentence(300,[ja]).
sentence(301,[dinsdag,vijftien,april]).
sentence(302,[ja]).
sentence(303,[heel,graag]).
sentence(304,[nee]).
sentence(305,[op,donderdag,zeventien,april]).
sentence(306,[vier,uur]).
sentence(307,[van,utrecht,naar,amsterdam]).
sentence(308,[vandaag]).
sentence(309,[van,utrecht,naar,amsterdam,vandaag,om,twaalf,uur]).
sentence(310,[ja,graag]).
sentence(311,[zaterdag]).
sentence(312,[van,assen,naar,utrecht]).
sentence(313,[<@>,op,zaterdag]).
sentence(314,[nee,hoor]).
sentence(315,[nee,ik,wil,vanuit,amsterdam,muiderpoort,reizen]).
sentence(316,[van,amsterdam,muiderpoort,naar,vlaardingen,west]).
sentence(317,[ik,heb,het,niet,over,donderdag,zeven,april,ik,heb,het,over,zaterdag,twaalf,april]).
sentence(318,[amsterdam,bijlmer]).
sentence(319,[nee]).
sentence(320,[nee]).
sentence(321,[ik,wil,van,haarlem,naar,driebergen,zeist]).
sentence(322,[<@>,nee,dat,hoeft,niet]).
sentence(323,[twee,uur,'\'s',middags]).
sentence(324,[ja]).
sentence(325,[dat,is,juist]).
sentence(326,[purmerend]).
sentence(327,[purmerend]).
sentence(328,[ja]).
sentence(329,[ik,wil,op,dinsdag,van,arnhem,naar,weert,reizen,de,aankomsttijd,in,weert,is,ongeveer,twaalf,uur,vijfenveertig]).
sentence(330,[amsterdam,zuid]).
sentence(331,[tien,uur]).
sentence(332,[nee]).
sentence(333,[nee]).
sentence(334,[van,amsterdam,lelylaan,naar,den,haag,nieuw,oost,indie]).
sentence(335,[nee]).
sentence(336,[nee]).
sentence(337,[ik,wil,van,maarssen,naar,geleen]).
sentence(338,[negen,uur]).
sentence(339,['<@m>',volgende,week,vrijdag,om,een,uur,of,zeven,uur,'\'s',avonds]).
sentence(340,[ja,het,is,helemaal,goed]).
sentence(341,[nee,om,acht,uur,'\'s',avonds]).
sentence(342,[santpoort,noord,naar,amsterdam,sloterdijk]).
sentence(343,[nee,ik,wil,niet,op,zondag,twintig,april,ik,wil,vandaag,reizen]).
sentence(344,[nee,om,tien,uur,'\'s',morgens]).
sentence(345,[neen,nee,nee,nee,hoor,het,is,genoeg,zo,dank,u,wel]).
sentence(346,[nee,niet,negen,februari,nee,hoor,<@>,u,mag,wat,mij,betreft,de,verbinding,wel,verbreken]).
sentence(347,[van,utrecht,naar,arnhem]).
sentence(348,[vandaag]).
sentence(349,[dat,klopt]).
sentence(350,[ja]).
sentence(351,[woensdag]).
sentence(352,[twaalf,uur]).
sentence(353,[nee]).
sentence(354,[van,utrecht,naar,nee,van,amsterdam,naar,utrecht]).
sentence(355,[utrecht]).
sentence(356,[<@>,morgen]).
sentence(357,[nee]).
sentence(358,[ja,hoor]).
sentence(359,[dertig,april]).
sentence(360,[ja,'\'s',morgens,half,tien]).
sentence(361,[half,tien,'\'s',morgens]).
sentence(362,[om,negen,uur,dertig,'\'s',ochtends]).
sentence(363,[zeventien,uur]).
sentence(364,[ja]).
sentence(365,[ja]).
sentence(366,[amsterdam]).
sentence(367,[van,arnhem,naar,weert]).
sentence(368,[op,dinsdag,tweeentwintig,april,wil,ik,van,arnhem,naar,weert,reizen,aankomsttijd,in,weert,om,ongeveer,twaalf,uur,vijfenveertig]).
sentence(369,[neen,wil,dinsdag,tweeentwintig,april,van,arnhem,naar,weert,reizen,aankomsttijd,twaalf,uur,vijfenveertig,in,weert]).
sentence(370,[ik,wil,dinsdag,tweeentwintig,april,van,arnhem,naar,weert,reizen,aankomst,in,weert,om,ongeveer,twaalf,uur,vijfenveertig]).
sentence(371,[ik,wilde,van,arnhem,naar,weert,reizen]).
sentence(372,[ik,wilde,van,arnhem,naar,weert,reizen]).
sentence(373,[ik,wil,van,arnhem,naar,weert,reizen]).
sentence(374,[ik,wil,van,arnhem,naar,weert,reizen]).
sentence(375,[van,arnhem,naar,weert]).
sentence(376,[op,dinsdag,tweeentwintig,april,wil,ik,reizen,van,arnhem,naar,weert,aankomsttijd,twaalf,uur,vijfenveertig,'\'s',middags]).
sentence(377,[op,dinsdag,tweeentwintig,april,wil,ik,van,arnhem,naar,weert,reizen]).
sentence(378,[ja]).
sentence(379,[nee,ik,wil,van,arnhem,naar,weert,reizen]).
sentence(380,[ja]).
sentence(381,[nee]).
sentence(382,[nee]).
sentence(383,[ja]).
sentence(384,[zesentwintig,mei]).
sentence(385,[één,uur,'\'s',middags]).
sentence(386,[ja]).
sentence(387,[amsterdam,maastricht]).
sentence(388,[ja]).
sentence(389,[nee]).
sentence(390,[jawel]).
sentence(391,[ja]).
sentence(392,[nee,dank,u]).
sentence(393,[van,amsterdam,naar,hoorn]).
sentence(394,[nee]).
sentence(395,[van,wehl,naar,doetinchem]).
sentence(396,[didam]).
sentence(397,[ja]).
sentence(398,[ja]).
sentence(399,[nee]).
sentence(400,[ja]).
sentence(401,[nee]).
sentence(402,[maandag]).
sentence(403,[nee]).
sentence(404,[dinsdag]).
sentence(405,[<@>,ja]).
sentence(406,[nee,nee,nee,naar,lelystad]).
sentence(407,[ja,dat,klopt]).
sentence(408,[dat,klopt]).
sentence(409,[van,amsterdam,naar,hoorn]).
sentence(410,[ik,wil,eigenlijk,zondagochtend,om,drie,uur,vertrekken]).
sentence(411,[nee,ik,wil,van,de,nacht,<@>,op,van,zaterdag,op,zondag,om,een,uur,of,drie,vertrekken]).
sentence(412,[zondag]).
sentence(413,[drie,uur,'\'s',nachts]).
sentence(414,[ja,ik,wil,niet,vertrekken]).
sentence(415,[dat,is,correct]).
sentence(416,[morgen]).
sentence(417,[om,tien,uur]).
sentence(418,[ja]).
sentence(419,[ja]).
sentence(420,[weesp]).
sentence(421,[morgen]).
sentence(422,[ja]).
sentence(423,[amsterdam]).
sentence(424,[van,purmerend,overwhere,naar,schiphol]).
sentence(425,[veertien,april]).
sentence(426,[<@>,dinsdag]).
sentence(427,[nee]).
sentence(428,[nee]).
sentence(429,[nee]).
sentence(430,[ja,vanuit,leeuwarden]).
sentence(431,[amsterdam]).
sentence(432,[vandaag]).
sentence(433,[nee]).
sentence(434,[amsterdam,centraal,naar,heerlen]).
sentence(435,[drie,uur]).
sentence(436,[nee]).
sentence(437,[veenendaal,de,klomp]).
sentence(438,[van,veenendaal,de,klomp,naar,utrecht]).
sentence(439,[twintig,uur]).
sentence(440,[nee]).
sentence(441,[vijf,uur,twintig]).
sentence(442,[vijf,uur,twintig,'\'s',ochtends]).
sentence(443,['\'s',ochtends,om,zes,uur,vijf]).
sentence(444,[van,amsterdam,naar,utrecht]).
sentence(445,[ja,dat,klopt]).
sentence(446,[ik,wil,aanstaande,vrijdag,van,eindhoven,naar,groningen,en,dan,wil,ik,om,vier,uur,aankomen]).
sentence(447,[ja]).
sentence(448,[van,amersfoort,naar,utrecht]).
sentence(449,[nee]).
sentence(450,[amsterdam,rotterdam]).
sentence(451,[twintig,april]).
sentence(452,[ja]).
sentence(453,[van,rotterdam,zuid,naar,utrecht,centraal]).
sentence(454,[kwart,over,zes,'\'s',ochtends]).
sentence(455,[nee]).
sentence(456,[geen]).
sentence(457,[zondag]).
sentence(458,[rotterdam]).
sentence(459,[ja]).
sentence(460,[nee]).
sentence(461,[nee]).
sentence(462,[van,spanbroek,naar,alkmaar]).
sentence(463,[nee]).
sentence(464,[nee]).
sentence(465,[negen,uur]).
sentence(466,[ja]).
sentence(467,[wat,zegt,u]).
sentence(468,[doe,maar]).
sentence(469,[nee]).
sentence(470,[zes,uur,dertig]).
sentence(471,[ja]).
sentence(472,[om,drie,uur]).
sentence(473,[ja]).
sentence(474,[nee,dank,u]).
sentence(475,[zestien,april]).
sentence(476,[nee]).
sentence(477,[nee,dank,u]).
sentence(478,[zondag]).
sentence(479,[ja]).
sentence(480,[van,cuyk,naar,maastricht]).
sentence(481,[ja]).
sentence(482,[van,heerhugowaard,naar,amsterdam]).
sentence(483,[ja]).
sentence(484,[ik,wil,overmorgen,van,groningen,naar,amsterdam]).
sentence(485,[nee]).
sentence(486,[nee,vanuit,amsterdam]).
sentence(487,[overmorgen,en,ik,wil,'\'s',avonds,om,tien,uur,aankomen]).
sentence(488,[van,amsterdam,naar,rotterdam]).
sentence(489,[ja]).
sentence(490,[nee]).
sentence(491,[nee]).
sentence(492,[nee]).
sentence(493,[pardon,ik,wil,van,amsterdam,naar,tilburg]).
sentence(494,[op,vrijdag]).
sentence(495,[van,utrecht,naar,nijkerk]).
sentence(496,[dank,u,wel]).
sentence(497,[ik,wil,van,enschede,van,enschede,<@>,om,half,twaalf]).
sentence(498,[<@>,ja,natuurlijk,krijg,ik,dat]).
sentence(499,[nee]).
sentence(500,[om,tien,uur,aankomen]).
