:- module(alpino_suite,[ sentence/2 ]).

:- hdrug_util:set_flag(application_type,ovis).

sentence(501,[nee]).
sentence(502,[half,negen]).
sentence(503,[van,enschede,naar,amsterdam]).
sentence(504,[zetten]).
sentence(505,[nee]).
sentence(506,['\'s',gravenhage]).
sentence(507,[den,haag,hollands,spoor]).
sentence(508,[van,hoogeveen,naar,heerenveen]).
sentence(509,[ja]).
sentence(510,[zes,uur,'\'s',morgens]).
sentence(511,[herhalen]).
sentence(512,[nee,naar,utrecht]).
sentence(513,[ja]).
sentence(514,[van,maastricht,naar,eindhoven]).
sentence(515,[<@>,vandaag]).
sentence(516,[nee,dank,u]).
sentence(517,[amsterdam,brussel]).
sentence(518,[nee]).
sentence(519,[den,haag,moerwijk]).
sentence(520,[nee,ik,wil,naar,voorhout,reizen]).
sentence(521,[nee]).
sentence(522,[voorhout,naar,utrecht]).
sentence(523,[vandaag,naar,utrecht,centraal,de,uithof,azu]).
sentence(524,[nee]).
sentence(525,[nee]).
sentence(526,['<@m>',op,maandag,maar,ik,wil,graag,naar,venlo]).
sentence(527,[om,half,acht]).
sentence(528,[twee,uur]).
sentence(529,[van,eindhoven,naar,amsterdam]).
sentence(530,[nee]).
sentence(531,[ik,wil,van,rijssen,naar,emmen]).
sentence(532,[ja,precies]).
sentence(533,['<@m>',elf,uur]).
sentence(534,[nee,ik,woon,in,rijssen]).
sentence(535,[naar,rijssen]).
sentence(536,[<@>,van,rijswijk,naar,eindhoven]).
sentence(537,[heerlen,naar,amsterdam]).
sentence(538,[vandaag]).
sentence(539,[ik,wil,<@>,aanstaande,zondag,vanaf,rotterdam,naar,leeuwarden,reizen,en,ik,moet,daar,'\'s',middags,om,vijf,uur,aankomen]).
sentence(540,[ja]).
sentence(541,[nee,dank,u]).
sentence(542,[van,utrecht,naar,putten]).
sentence(543,[<@>,nee,maar,ik,wil,niet,overstappen]).
sentence(544,[vandaag]).
sentence(545,[ja,inderdaad]).
sentence(546,[nee,hoor,dank,u,wel]).
sentence(547,[ja]).
sentence(548,[ik,wil,om,half,één,in,heerlen,aankomen]).
sentence(549,[nee,ik,wil,om,twaalf,uur,dertig,'\'s',middags,aankomen]).
sentence(550,[nee]).
sentence(551,[amsterdam,amstel,roermond]).
sentence(552,[ja]).
sentence(553,[nee]).
sentence(554,[<@>,op,zondag]).
sentence(555,[nee]).
sentence(556,[ja]).
sentence(557,[acht,uur]).
sentence(558,[nee]).
sentence(559,[nee]).
sentence(560,[nee]).
sentence(561,[ik,wil,morgen,zo,snel,mogelijk,van,amersfoort,naar,soestduinen]).
sentence(562,[twaalf,uur]).
sentence(563,[zestien,april]).
sentence(564,[nee]).
sentence(565,[zeventien,april]).
sentence(566,[acht,uur]).
sentence(567,[ja]).
sentence(568,[nee]).
sentence(569,[ja,ik,wil,graag,morgenmiddag,van,enschede,naar,rotterdam,en,ik,moet,daar,om,twee,uur,'\'s',middags,aankomen]).
sentence(570,[tien,uur]).
sentence(571,[ja]).
sentence(572,[ja]).
sentence(573,[ja]).
sentence(574,[van,eindhoven,naar,delft]).
sentence(575,[vrijdag]).
sentence(576,[nee]).
sentence(577,[ja]).
sentence(578,[nee]).
sentence(579,[nee]).
sentence(580,[vijftien,uur]).
sentence(581,[correct]).
sentence(582,[nee,om,<@>,drieentwintig,uur]).
sentence(583,[<@>,om,tien,uur,in,ochtend,op,eenentwintig,april]).
sentence(584,[eenentwintig,april]).
sentence(585,[nee]).
sentence(586,[ja,een,verbinding,na,tien,uur,veertien]).
sentence(587,[nee,ik,zei,van,heemstede,aerdenhout,naar,leiden]).
sentence(588,[naar,osnabruck]).
sentence(589,[vandaag]).
sentence(590,[van,roermond,naar,amsterdam]).
sentence(591,[vandaag]).
sentence(592,[elf,uur]).
sentence(593,[neen]).
sentence(594,[<@>,op,maandag]).
sentence(595,[vrijdag]).
sentence(596,[van,hoorn,naar,utrecht]).
sentence(597,[van,hoorn,naar,utrecht]).
sentence(598,[op,dinsdag]).
sentence(599,[zes,uur,'\'s',ochtends]).
sentence(600,[neen]).
sentence(601,[dinsdag]).
sentence(602,[ja]).
sentence(603,[van,hoorn,naar,maarssen]).
sentence(604,[nee,zes,uur,vijftig,'\'s',ochtends]).
sentence(605,[van,arnhem,naar,middelburg]).
sentence(606,[nee]).
sentence(607,[van,enschede,naar,amsterdam]).
sentence(608,[van,enschede,naar,amsterdam]).
sentence(609,[ik,wil,naar,amsterdam,centraal,station,vanmiddag]).
sentence(610,[vijf,uur]).
sentence(611,[ik,wil,van,nijmegen,naar,maastricht]).
sentence(612,[ja]).
sentence(613,[<@>,vandaag]).
sentence(614,[<@>,vier,uur]).
sentence(615,[van,enschede,naar,utrecht]).
sentence(616,[zondag]).
sentence(617,[nee,op,zondag]).
sentence(618,[<@>,zaterdag]).
sentence(619,[<@>,van,den,haag,hollands,spoor,naar,leiden]).
sentence(620,[<@>,half,tien]).
sentence(621,[nee]).
sentence(622,[ja]).
sentence(623,[<@>,ja]).
sentence(624,[<@>,half,vier]).
sentence(625,[zaterdag]).
sentence(626,[om,veertien,uur,aankomen]).
sentence(627,[nee]).
sentence(628,[van,<@>,delft,cs,naar,<@>,den,haag,cs]).
sentence(629,[ja]).
sentence(630,[ja]).
sentence(631,[van,amsterdam,naar,rotterdam]).
sentence(632,[<@>,doe,maar,op,zondag]).
sentence(633,[nee]).
sentence(634,[twaalf,uur,'\'s',morgens]).
sentence(635,[ja]).
sentence(636,[ja]).
sentence(637,[nee]).
sentence(638,[ja]).
sentence(639,[nee]).
sentence(640,[ja]).
sentence(641,[om,twee,uur]).
sentence(642,[van,vierlingsbeek,naar,utrecht]).
sentence(643,[nee,dank,je,wel]).
sentence(644,[nee,dank,u,wel]).
sentence(645,[ik,wil,reizen,van,utrecht,naar,amsterdam]).
sentence(646,[ongeveer,half,zeven]).
sentence(647,['\'s',avonds]).
sentence(648,[ja]).
sentence(649,[nee,dank,u]).
sentence(650,[op,zondag]).
sentence(651,[nee,dank,u,wel]).
sentence(652,[jawel]).
sentence(653,[ik,wil,van,utrecht,naar,amsterdam]).
sentence(654,[ja]).
sentence(655,[op,woensdag]).
sentence(656,[ik,wil,om,één,uur,in,heerlen,aankomen]).
sentence(657,[nee]).
sentence(658,[nee]).
sentence(659,[van,amsterdam,naar,den,haag]).
sentence(660,[dinsdag]).
sentence(661,[ja]).
sentence(662,[ik,wil,naar,purmerend,reizen]).
sentence(663,[ja]).
sentence(664,[van,utrecht,naar,soestduinen]).
sentence(665,[<@>,twaalf,uur]).
sentence(666,[amsterdam,maastricht]).
sentence(667,[ja]).
sentence(668,[ja]).
sentence(669,[van,bilthoven,naar,leidschendam]).
sentence(670,[zestien,april]).
sentence(671,[vertrek,acht,uur,'\'s',ochtends]).
sentence(672,[zestien,april]).
sentence(673,[morgen]).
sentence(674,[nee]).
sentence(675,[op,woensdag]).
sentence(676,[nee]).
sentence(677,[van,vleuten,naar,utrecht]).
sentence(678,[nee,dat,hoeft,niet]).
sentence(679,[ja]).
sentence(680,[breda,naar,antwerpen]).
sentence(681,[amsterdam,wtc]).
sentence(682,[van,breda,naar,amsterdam,wtc]).
sentence(683,[ik,wil,van,breda,naar,amsterdam,wtc,reizen]).
sentence(684,[zondag,twintig,april]).
sentence(685,[ja]).
sentence(686,[nee]).
sentence(687,[ook,niet]).
sentence(688,[vandaag]).
sentence(689,[nee,om,één,uur]).
sentence(690,[nee,hoor]).
sentence(691,[volgende,week,zaterdag]).
sentence(692,[om,drie,uur,'\'s',ochtends]).
sentence(693,[nee,ik,wil,naar,borne]).
sentence(694,[nee]).
sentence(695,[nee]).
sentence(696,['<@m>']).
sentence(697,[ja]).
sentence(698,[nee]).
sentence(699,[nee]).
sentence(700,[amsterdam,soest]).
sentence(701,[ja]).
sentence(702,[nee]).
sentence(703,[nee]).
sentence(704,[van,veenendaal,de,klomp,naar,utrecht]).
sentence(705,[nee,dank,u]).
sentence(706,[vandaag]).
sentence(707,[ja]).
sentence(708,[nee]).
sentence(709,[van,amersfoort,naar,best]).
sentence(710,[kwart,voor,tien,'\'s',avonds]).
sentence(711,[nee]).
sentence(712,[van,amersfoort,naar,best]).
sentence(713,[nee]).
sentence(714,[ja]).
sentence(715,[ik,wil,om,vier,uur,aankomen]).
sentence(716,[ja]).
sentence(717,[ja]).
sentence(718,[nee]).
sentence(719,[ik,wil,van,soest,zuid,naar,maastricht]).
sentence(720,[<@>,amsterdam,lelystad,naar,nijmegen,centraal]).
sentence(721,[van,den,haag,naar,<@>,leidschendam]).
sentence(722,[ja]).
sentence(723,[nee]).
sentence(724,[van,utrecht,centraal,station,naar,soestduinen]).
sentence(725,[morgen]).
sentence(726,[ik,wil,morgenochtend,om,half,negen,van,utrecht,naar,soestduinen]).
sentence(727,[ik,wil,van,rotterdam,naar,groningen,reizen,en,ik,moet,daar,zaterdag,om,twee,uur,'\'s',middags,aankomen]).
sentence(728,[<@>,'\'s',morgens,om,half,acht]).
sentence(729,[dat,klopt]).
sentence(730,[nee,dank,u]).
sentence(731,[amsterdam]).
sentence(732,[nee,om,elf,uur,'\'s',avonds]).
sentence(733,[ja]).
sentence(734,[nee]).
sentence(735,[vierentwintighonderd,uur]).
sentence(736,[<@>]).
sentence(737,[vandaag]).
sentence(738,[ja]).
sentence(739,[<@>,vanaf,half,één]).
sentence(740,[ja]).
sentence(741,[ja]).
sentence(742,[dertien,uur]).
sentence(743,[ja]).
sentence(744,[nee]).
sentence(745,[ja]).
sentence(746,[ja]).
sentence(747,[op,woensdag]).
sentence(748,[dat,is,juist]).
sentence(749,[inderdaad]).
sentence(750,[ja]).
sentence(751,[nee]).
sentence(752,[om,elf,uur,'\'s',avonds]).
sentence(753,[ja,doet,u,dat]).
sentence(754,[om,drieentwintig,uur]).
sentence(755,[ja,dat,zou,ik,graag,willen,reizen]).
sentence(756,[nee,dat,hoeft,niet]).
sentence(757,[nee,dank,u]).
sentence(758,[ja]).
sentence(759,[ja,herhalen]).
sentence(760,[nee]).
sentence(761,[vanuit,eindhoven,naar,hoogezand]).
sentence(762,[ja]).
sentence(763,[yes]).
sentence(764,[naar,amersfoort]).
sentence(765,[donderdag]).
sentence(766,[<@>,dinsdag,tweeentwintig,april]).
sentence(767,[ja,dat,wil,ik]).
sentence(768,[van,sevenum,naar,naar,bijlmer]).
sentence(769,[van,sevenum,naar,bijlmer]).
sentence(770,[drieentwintig,uur]).
sentence(771,[nee]).
sentence(772,[nee]).
sentence(773,[ja]).
sentence(774,[ja]).
sentence(775,[twaalf,uur]).
sentence(776,[ja]).
sentence(777,[ja]).
sentence(778,[hoogeveen,middelburg]).
sentence(779,[elf,uur]).
sentence(780,[nou,klopt,er,helemaal,niets,meer,van]).
sentence(781,[heerenveen,zeist]).
sentence(782,[nee]).
sentence(783,[om,<@>,één,uur,in,de,namiddag]).
sentence(784,[van,utrecht,cs,naar,almere,cs]).
sentence(785,[nee]).
sentence(786,[nee,ik,wil,van,apeldoorn,naar,boskoop]).
sentence(787,[ja]).
sentence(788,[nee]).
sentence(789,[twee,uur,'\'s',nachts]).
sentence(790,[van,holten,naar,markelo]).
sentence(791,[ik,wil,reizen,van,holten,naar,deventer]).
sentence(792,[ja]).
sentence(793,[nee,om,vijf,uur]).
sentence(794,[ja]).
sentence(795,[van,rijswijk,naar,eindhoven]).
sentence(796,[nee]).
sentence(797,[hoera]).
sentence(798,[nee]).
sentence(799,[woensdag]).
sentence(800,[nee]).
sentence(801,[morgen]).
sentence(802,[ik,wil,om,half,negen,in,rijswijk,zijn]).
sentence(803,[nee,naar,rijswijk]).
sentence(804,[half,acht]).
sentence(805,[ik,wil,ook,nog,terug]).
sentence(806,[van,rijswijk,naar,amsterdam,centraal]).
sentence(807,[<@>,elf,dertig]).
sentence(808,[ik,wil,graag,de,volgende,verbinding]).
sentence(809,[nee,ik,wil,verder,geen,reisadvies,dank,u,voor,de,inlichtingen]).
sentence(810,[om,kwart,over,zeven,'\'s',ochtends]).
sentence(811,[ja]).
sentence(812,[nee,dank,u]).
sentence(813,[ja]).
sentence(814,[vanuit,station,soest,zuid,naar,station,maastricht]).
sentence(815,['<@m>','\'s',morgens,om,zes,uur]).
sentence(816,[nee]).
sentence(817,[ik,wil,op,vier,mei,naar,amsterdam]).
sentence(818,[vanuit,voorburg,naar,hengelo]).
sentence(819,[nee,naar,hengelo]).
sentence(820,[op,dertig,april]).
sentence(821,[voorburg,groningen,morgen,om,tien,uur,aankomen]).
sentence(822,[ja]).
sentence(823,[nee,vanuit,den,haag,centraal,overmorgen,om,drie,uur,'\'s',middags,vertrekken]).
sentence(824,[nee,om,drie,uur,'\'s',middags]).
sentence(825,[om,drie,uur]).
sentence(826,[<@>,van,den,haag,mariahoeve,naar,schiphol]).
sentence(827,[nee]).
sentence(828,[nee]).
sentence(829,[nee]).
sentence(830,[ja]).
sentence(831,[alexanderpolder,naar,groningen]).
sentence(832,[fout]).
sentence(833,[fout]).
sentence(834,[eerste,pinksterdag]).
sentence(835,[amsterdam,lelylaan,nijmegen]).
sentence(836,[ja]).
sentence(837,[<@>,woensdag]).
sentence(838,[ik,wil,om,twaalf,uur,aankomen,in,heerlen]).
sentence(839,[vandaag]).
sentence(840,[<@>,zeventienhonderd,uur]).
sentence(841,[nee,dank,u]).
sentence(842,[op,eenentwintig,april]).
sentence(843,[nee]).
sentence(844,[nee]).
sentence(845,[ja]).
sentence(846,[ik,wil,reizen,van,amsterdam,amstel,naar,echt]).
sentence(847,[ik,wil,vanuit,amsterdam,amstel,naar,echt,reizen]).
sentence(848,[nee,dank,u]).
sentence(849,[nee,dank,u]).
sentence(850,[nee]).
sentence(851,[nee]).
sentence(852,[ja]).
sentence(853,[dinsdag]).
sentence(854,[nee,dank,u,wel]).
sentence(855,[woensdag]).
sentence(856,[van,utrecht,naar,amersfoort]).
sentence(857,[ja]).
sentence(858,[elf,uur,'\'s',avonds]).
sentence(859,[ja,dat,klopt]).
sentence(860,[amsterdam,parijs]).
sentence(861,[amsterdam,brussel]).
sentence(862,[ik,wil,van,boskoop,naar,waddinxveen]).
sentence(863,[nee,ja]).
sentence(864,[neen]).
sentence(865,[zeven,uur,'\'s',avonds]).
sentence(866,[ja]).
sentence(867,[nee]).
sentence(868,[dinsdag,tweeentwintig,april]).
sentence(869,[nee]).
sentence(870,[ja]).
sentence(871,[ik,wil,om,half,drie,uur,aankomen]).
sentence(872,[ik,wil,om,half,vier,in,amersfoort,aankomen]).
sentence(873,[ja,een,kleintje]).
sentence(874,[steenwijk,naar,utrecht]).
sentence(875,[op,zondag]).
sentence(876,['<@m>',den,haag,naar,amsterdam]).
sentence(877,[ik,wil,volgende,week,vrijdag,naar,groningen]).
sentence(878,[nou,vroeg]).
sentence(879,[voor,zevenen]).
sentence(880,[nee,laat,maar]).
sentence(881,[nee]).
sentence(882,[nee]).
sentence(883,[ja]).
sentence(884,[ja]).
sentence(885,[nee]).
sentence(886,[om,<@>,twaalf,uur]).
sentence(887,[ja]).
sentence(888,[om,acht,uur]).
sentence(889,[nee,van,<@>,maastricht,naar,nijmegen]).
sentence(890,[ja,graag]).
sentence(891,[ik,moet,aanstaande,woensdag,om,twee,uur,'\'s',middags,in,amsterdam,aankomen,en,ik,vertrek,vanaf,enschede]).
sentence(892,[nee,ik,wil,vanuit,enschede,naar,amsterdam,centraal,reizen,en,ik,moet,daar,volgende,week,woensdag,om,drie,uur,'\'s',middags,aankomen]).
sentence(893,[ik,moet,morgenochtend,van,nijmegen,naar,schiphol,ik,wil,ongeveer,om,elf,uur,aankomen]).
sentence(894,[van,nijmegen,naar,schiphol]).
sentence(895,[volgende,week,zaterdag]).
sentence(896,[ik,wil,om,<@>,drie,uur,'\'s',middags,aankomen]).
sentence(897,[zaterdag]).
sentence(898,[om,twee,uur,'\'s',middags]).
sentence(899,[ja]).
sentence(900,[ja]).
sentence(901,[nee,dank,u]).
sentence(902,[ja]).
sentence(903,[nee,dank,u]).
sentence(904,[om,zes,uur]).
sentence(905,[om,nul,zes,uur]).
sentence(906,[nee]).
sentence(907,[ja]).
sentence(908,[nee]).
sentence(909,[dat,is,goed]).
sentence(910,[ja,dat,is,goed]).
sentence(911,[boskoop]).
sentence(912,[boskoop]).
sentence(913,[<@>,van,rotterdam,naar,delft]).
sentence(914,[om,drie,uur]).
sentence(915,[nee]).
sentence(916,[nee]).
sentence(917,[ik,wil,vanavond,in,utrecht,aankomen,vanuit,naarden,bussum]).
sentence(918,[ik,wil,vanavond,van,naarden,bussum,naar,enschede]).
sentence(919,['<@m>',om,acht,uur,vertrekken]).
sentence(920,[nee]).
sentence(921,[ja,graag]).
sentence(922,[ja]).
sentence(923,[nee,om,kwart,voor,tien,aankomen,'\'s',ochtends]).
sentence(924,[ja]).
sentence(925,[nee,hoor]).
sentence(926,[ja,voorburg,amsterdam]).
sentence(927,[<@>,van,rotterdam,naar,zwaagwesteinde]).
sentence(928,[nee,dank,u]).
sentence(929,[nee,van,leiden,naar,leeuwarden]).
sentence(930,[nee]).
sentence(931,[nee]).
sentence(932,[half,zeven]).
sentence(933,[nee]).
sentence(934,[van,amstelveen,naar,hoorn]).
sentence(935,[nee]).
sentence(936,[ja]).
sentence(937,[nee]).
sentence(938,[nee,hoeft,niet]).
sentence(939,[nee]).
sentence(940,[om,twee,uur]).
sentence(941,[woensdag,zestien,april]).
sentence(942,[ik,woon,al,in,haarlem,ik,hoef,niet,te,reizen]).
sentence(943,[<@>,ik,wil,om,twaalf,uur,ongeveer,in,arnhem,zijn]).
sentence(944,[om,vier,uur]).
sentence(945,[nee,dank,u]).
sentence(946,[nee,dank,je]).
sentence(947,[dat,klopt,is,correct]).
sentence(948,[nee,dank,u,wel]).
sentence(949,[van,amsterdam,amstel,naar,oss,west]).
sentence(950,[ja]).
sentence(951,[van,oss,west,naar,amsterdam,amstel]).
sentence(952,[elf,uur]).
sentence(953,[elf,uur]).
sentence(954,[van,best,naar,roodeschool]).
sentence(955,[om,negen,uur]).
sentence(956,[ik,wil,van,enschede,naar,groningen,reizen]).
sentence(957,[nee,dank,u]).
sentence(958,[<@>,nee]).
sentence(959,[van,delft,naar,amsterdam]).
sentence(960,[nee]).
sentence(961,[om,tien,uur,nee,sorry,om,twaalf,uur,vertrekken]).
sentence(962,[nee,vanuit,grouw,irnsum]).
sentence(963,[ja]).
sentence(964,[ja]).
sentence(965,[nee,ik,wil,niet,vanaf,ede,wageningen,reizen]).
sentence(966,[<@>,ik,wil,om,zeven,uur,aankomen]).
sentence(967,[ja]).
sentence(968,[nee,dank,u]).
sentence(969,[ja,graag]).
sentence(970,[om,twee,uur,'\'s',middags]).
sentence(971,[van,den,haag,moerwijk,den,haag,centraal]).
sentence(972,[den,haag,moerwijk]).
sentence(973,[den,haag,moerwijk]).
sentence(974,[nee]).
sentence(975,[nee]).
sentence(976,[ja,van,enschede,naar,deventer,aanstaande,zondag,om,vier,uur]).
sentence(977,[ik,wil,van,<@>,station,soest,zuid]).
sentence(978,['<@m>',nee,dank,u,ik,heb,genoeg,zo]).
sentence(979,[veenendaal,de,klomp,naar,apeldoorn]).
sentence(980,[<@>,<@>,morgen]).
sentence(981,[ja]).
sentence(982,[veenendaal,de,klomp,naar,apeldoorn]).
sentence(983,[ja]).
sentence(984,[nee]).
sentence(985,[woensdag]).
sentence(986,[dertien,honderd,uur]).
sentence(987,[ja]).
sentence(988,[wilt,u,herhalen,of,ik,de,verbinding,moet,herhalen]).
sentence(989,[van,delft,naar,rotterdam]).
sentence(990,[tussen,zeven,en,acht,uur]).
sentence(991,[nee]).
sentence(992,[ja]).
sentence(993,[amsterdam,amstel,naar,utrecht]).
sentence(994,[tussen,tien,en,elf,uur]).
sentence(995,[ik,wil,op,woensdag,naar,rotterdam,reizen]).
sentence(996,[nee,ik,wil,morgen,van,tiel,naar,nijmegen,vertrekken]).
sentence(997,[van,den,haag,naar,schiphol]).
sentence(998,[om,zeven,uur]).
sentence(999,[ja]).
sentence(1000,[nee]).
