#!/usr/bin/perl
# © Gertjan van Noord, 1998.
# mailto:vannoord@let.rug.nl
# DONE: noew ensures the final file contains at least one sentence

use Getopt::Std;

getopts('m:p:o:uz');

$opt_p ||= 5000;
$opt_m ||= 1000;
$opt_o ||= "output";

if ($opt_u){
    %seen=();
}

if ($opt_z) {
    $filesuffix = "";
    $cmdprefix = "|cat >"
} else {
    $filesuffix = ".gz";
    $cmdprefix = "|gzip >"
}

$closed=1;
$part=1;
while (<>) {
  if (/^[%]/) {
    if ($closed) {
       $ofile = sprintf "%s_part%05d.sents$filesuffix",$opt_o,$part;
       open(OUTPUT,"$cmdprefix$ofile") || die "cannot write to $ofile: $!\n";
       $part++;
       $counter=0;
       $closed=0;
    }
    print OUTPUT $_;
    next;
  }
  if ($opt_u){
      if ($seen{$_}) {
	  next;
      }
      else {
	  $seen{$_}++;
      }
  }

  $counter++;
  @words=split;
  if (@words < $opt_m) {
    if ($closed) {
       $ofile = sprintf "%s_part%05d.sents$filesuffix",$opt_o,$part;
       open(OUTPUT,"$cmdprefix$ofile") || die "cannot write to $ofile: $!\n";
       $part++;
       $counter=0;
       $closed=0;
    }
    print OUTPUT "$_";
  }
  if ($counter >= $opt_p) {
    close OUTPUT;
    $closed=1;
  }
}
