#!/usr/bin/perl
# © Gertjan van Noord, 1998.
# mailto:vannoord@let.rug.nl

use File::Basename;

%counter=();
$current_file="no_identifier";
$parcounter=0;
$sentcounter=0;
while (<> )  {
    chomp;
    if (/^%% FILE /) {
	$file=$'; #';
	($current_file,undef,undef) = fileparse($file,'\..*');
	$parcounter=0;
	$sentcounter=0;
	if ($counter{$current_file}) {
	    $counter{$current_file}++;
	} else {
	    $counter{$current_file}=1;
	    close OUTPUT;
	    open(OUTPUT,">$current_file.sents") || die "cannot write to $current_file.sents: $!\n";
	}
    } elsif (/^%% PAR/) {
	$parcounter++;
	$sentcounter=0;
    } else {
	$sentcounter++;
	print OUTPUT $current_file . "-" . $counter{$current_file} . "-" . $parcounter . "-" . 
	    $sentcounter . "|$_\n";
    }
}

