#!/usr/bin/perl
# © Gertjan van Noord, 1998.
# mailto:vannoord@let.rug.nl

use Getopt::Std;

getopts('m:p:o:uz');

$opt_p ||= 5000;
$opt_m ||= 1000;
$opt_o ||= "output";

if ($opt_u){
    %seen=();
}

if ($opt_z) {
    $filesuffix = "";
    $cmdprefix = "|cat >"
} else {
    $filesuffix = ".gz";
    $cmdprefix = "|gzip >"
}

$ofile = $opt_o."_part00001.sents$filesuffix";
open(OUTPUT,"$cmdprefix$ofile") || 
  die "cannot write to $ofile: $!\n";
$part=2;
$counter=0;
while (<> )  {
  if (/^[%]/) {
    print OUTPUT $_;
    next;
  }
  if ($opt_u){
      if ($seen{$_}) {
	  next;
      }
      else {
	  $seen{$_}++;
      }
  }

  $counter++;
  @words=split;
  if (@words < $opt_m) {
    print OUTPUT "$_";
  }
  if ($counter >= $opt_p) {
    $counter=0;
    close OUTPUT;
    $ofile = sprintf "%s_part%05d.sents$filesuffix",$opt_o,$part;
    open(OUTPUT,"$cmdprefix$ofile") || 
      die "cannot write to $ofile: $!\n";
    $part++;
  }
}
