.TH Alpino 1
.SH NAME
ALPINO
.SH SYNOPSIS
.B Alpino [Options]

.SH DESCRIPTION

Alpino is a wide coverage parser for Dutch. 

.SH SEE ALSO

the on-line documentation http://www.let.rug.nl/~vannoord/alp/Alpino/

.SH COPYRIGHT
Copyright \(co 2000-2006 by Gertjan van Noord / RuG / NWO.

.SH AUTHOR
Gertjan van Noord, vannoord@let.rug.nl
